### ISSUE TITLE
Case indentation error

### ISSUE THREAD

**Issue by tobiasBora** [haskell/haskell-mode#1000]
Hello,

First thank you for your work. I have a problem with haskell-indentation-mode: when I do
```
"fact n =<RET>case n of<RET>1 -> 0<RET>n -> n * fact (n-1)"
```

I have
```
fact n =
  case n of
  0 -> 1
  _ -> n * fact (n - 1)
```
while I would like to have
```
fact n =
  case n of
    0 -> 1
    _ -> n * fact (n - 1)
```
Do you have any solution ?

Thank you for you work !

**Comment by gracjan** [comment]
You can press TAB just when in the line after 'case'.

But I agree we should fix this inconvenience.

**Comment by tobiasBora** [comment]
When I do so the TAB doesn't do anything... I just stay on the same position, and if I manually add space and then press TAB it comes back to it's initial position...

**Comment by gracjan** [comment]
It seems to be more broken than I thought... Sorry about that.

Are you able to add a test case that documents the failing behaviour in
tests/haskell-indentation-tests.el?
