### ISSUE TITLE
Implement nice font-lock for LiquidHaskell

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1005]
Implement nice font-lock for LiquidHaskell

**Comment by gridaphobe** [comment]
This would indeed be nice! We have a (possibly outdated) syntax highlighter for vim.

https://github.com/ucsd-progsys/liquid-types.vim/blob/master/haskell.vim#L224-L234

I don't know how portable vim-style highlighters are to emacs font-lock, but it might be a start.

**Comment by gracjan** [comment]
Thanks. As usual we are waiting on a volunteer. @gridaphobe, maybe you will try?

**Comment by alanz** [comment]
I think as a start just highlighting the whole comment delimited by `{-@` and `@-}` in a different font would help, never mind the innards of it.

**Comment by gracjan** [comment]
True. We have code to colorize `{-# ... #-}` so this could be used to colorize `{-@ ... @-}`. The biggest problem is not solved though: we have to pick the color! Let the bikeshedding begin :)

**Comment by gracjan** [comment]
@alanz: Done! Looks already pretty nice!

We can think about deeper annotation highlight later.
