### ISSUE TITLE
Illegal token: )

### ISSUE THREAD

**Issue by KenetJervet** [haskell/haskell-mode#1006]
```haskell
module Jason.Core (
  JData(..),
  stringify
) where

import Data.List
```

With the cursor at the end of the import statement, pressing Enter fails with "Illegal token: )"
Placing the cursor at a trailing new line works though

**Comment by gracjan** [comment]
Can you check newest version? This issue was fixed during current month, if you update you should be good.

**Comment by KenetJervet** [comment]
Cool. That fixed it. Thank you!
