### ISSUE TITLE
hsc2hs support

### ISSUE THREAD

**Issue by unhammer** [haskell/haskell-mode#1012]
On doing `haskell-process-load-file` on a file that ends in .hsc, would it be possible to run `hsc2hs` on it first and load the resulting .hs (instead of the .hsc)?

**Comment by unhammer** [comment]
Perhaps something like

    (defun haskell--process-hsc2hs-load ()
      "Run hsc2hs and load the resulting file (unless hsc2hs failed)."
      (let* ((hwin (get-buffer-window (current-buffer)))
             (hs (replace-regexp-in-string "\\.hsc\\'" ".hs" (buffer-file-name)))
             (cbuf (compilation-start (format "hsc2hs %s" (buffer-file-name))
                                      nil
                                      (lambda (_) "*hsc2hs*")))
             (proc (get-buffer-process cbuf)))
        (while (eq (process-status proc) 'run) ; TODO: is there no built-in way to wait on a process?
          (sit-for 0.5))
        (when (equal 0 (process-exit-status proc))
          (select-window (get-buffer-window cbuf))
          (bury-buffer)
          (select-window hwin)
          (haskell-process-file-loadish (haskell--file-name-to-load-string hs)
                                      nil
                                      (current-buffer)))))
    
    ;;;###autoload
    (defun haskell-process-load-file ()
      "Load the current buffer file."
      (interactive)
      (save-buffer)
      (haskell-interactive-mode-reset-error (haskell-session))
      (if (equal "hsc" (file-name-extension (buffer-file-name)))
          (haskell--process-hsc2hs-load)
        (haskell-process-file-loadish (haskell--file-name-to-load-string (buffer-file-name))
                                      nil
                                      (current-buffer))))

**Comment by gracjan** [comment]
Hmm, interesting functionality.

Instead of waiting in a loop it would be better to convert the code to callback style. There is a way to trigger a callback when a process has ended, see here [`set-process-sentinel`](http://www.gnu.org/software/emacs/manual/html_node/elisp/Sentinels.html#index-set_002dprocess_002dsentinel).

Note that we will need some unit tests before this functionality is accepted. See [[Writing tests]] for more details.

**Comment by gracjan** [comment]
@unhammer, can you turn this into proper PR? Thanks.

**Comment by unhammer** [comment]
I actually wanted it to be a blocking wait when I was using hsc2hs, but I suppose if it's a long-running compilation people will want async. I'll make a PR with callbacks, just a sec …

**Comment by unhammer** [comment]
See https://github.com/haskell/haskell-mode/pull/1238

**Comment by gracjan** [comment]
Closing due to low interest.
