### ISSUE TITLE
Broken indentation in Emacs 24.5

### ISSUE THREAD

**Issue by jstolarek** [haskell/haskell-mode#1013]
I recently updated my Emacs installation to version 24.5.1 and discovered that in haskell mode upon entering a new line indentation behaves in an unexpected and unintuitive way. In these examples below `X` shows where the point is set upon pressing Enter at the end of previous line and `Y` shows where it used to be set before upgrading Emacs:

```haskell
module Foo where
Y   X
```

```haskell
foo :: Bool
Y      X
```

```haskell
data A = A

Y      X
```
```haskell
instance Foo a where
    bar A A = A
    Y       X
```
Using haskell-mode just became extremely annoying :| I am using haskell-mode from melpa, version 20151202.34 (ie. today's build).

**Comment by jstolarek** [comment]
Oh, and this behaviour happens consistently on two different machines. Both have Emacs 24.5.1 compiled from sources, haskell-mode from melpa and [this configuration file](https://github.com/jstolarek/scripts/blob/0a79361b663bff84c756b2cd23720c9b05035f48/emacs/.emacs).

**Comment by gracjan** [comment]
Remove this line:

(add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
restart. It should help.

**Comment by jstolarek** [comment]
Indeed, that changes indentation behaviour, but it does not restore previous, correct behaviour. For example, indentation of case alternatives does not work in a reasonable way. Also, if I have:

```haskell
foo :: Bool
X
```
where `X` represents mark, I would expect that pressing TAB will insert `foo`. But after commenting out that configuration line it doesn't.

So I would say that what you've given me is a workaround that restores reasonable indentation behaviour at the price of loosing functionality. Thank you for that, but it is not the final solution I am looking for.

**Comment by gracjan** [comment]
It seems we should reopen #208.

**Comment by jstolarek** [comment]
Closed means fixed?

**Comment by gracjan** [comment]
You seem to have found a way to make indentation work so I guess this part is fixed.

There is the unimplemented feature of `haskell-indentation-mode` that is present in `haskell-indent-mode` that is symbol completion.

You are the second person requesting that and I'm not sure if this is an expected feature or not. Anyway we will need a volunteer to implement it.

**Comment by gracjan** [comment]
Anyway submitted as separate issue #1027.

**Comment by jstolarek** [comment]
> You seem to have found a way to make indentation work so I guess this part is fixed.

No, I have not been able to restore previous functionality in a reasonable way, ie. after disabling indentation the problem went away but so did useful functionality. So in no way is my problem solved :( Perhaps this is a duplicate of #208 (as you've pointed out), but in such case please re-open #208.

> You are the second person requesting that and I'm not sure if this is an expected feature or not.

I believe I am not requesting any new feature. Completing function name has been present in haskell-mode since I started using it ~3 years ago.

**Comment by gracjan** [comment]
Opened as #1027.

**Comment by jstolarek** [comment]
Ok, clearly there is something I don't understand here. From reading #1027 I understand that so far I have been using `haskell-indent`. After updating Emacs to 24.5 behaviour of `haskell-indent` is broken and I was forced to turn it off (obviously, losing its functionality). #1027 mentions something about `haskell-indentation`. Is `haskell-indentation` a replacement of `haskell-indent`? Is `haskell-indent` deprecated or unmaintained and should not be used?

**Comment by gracjan** [comment]
Your understanding is about correct. `haskell-indentation` is next attempt at indentation mode after `haskell-indent`. So far `haskell-indentation` code has been proved to be more readable and maintanable, at least compared to `haskell-indent`. Although `haskell-indent` is not deprecated I think it will be a problem to find a brave soul to fix issues with that indetation mode. Currently all the effort goes into `haskell-indentation`.

**Comment by jstolarek** [comment]
Now it makes sense. Thanks. I'll switch to `haskell-indentation` and hope someone implements #1027

**Comment by PierreR** [comment]
Wouldn't be clearer to remove `haskell-indent` completely ? It is not maintained and broken. What's the point keeping it knowing there is no contributor out there to work on it.

I personally would vote for a single indentation scheme that works well (instead of 3 broken option).

The way I understand it is that the initial creator/contributor of `haskell-indent` is gone without caring for the transition. So it is fair to say `haskell-indent` is dead IMHO.

**Comment by gracjan** [comment]
@PierreR: We are slowly getting there. It is time to reduce the number from three to two by removing `haskell-simple-ident` in #958.
