### ISSUE TITLE
Tags not being generated on save

### ISSUE THREAD

**Issue by sumitsahrawat** [haskell/haskell-mode#1022]
From the discussion here: serras/emacs-haskell-tutorial#39

**Comment by gracjan** [comment]
@sumitsahrawat: How about pulling the content of that tutorial into our official documentation:

http://haskell.github.io/haskell-mode/manual/latest/

Source is in `docs/haskell-mode.texi`. Texi is super easy to get going and is Emacs standard.

And our documentation is autogenerated, so no need to do it manually.

**Comment by sumitsahrawat** [comment]
> @sumitsahrawat: How about pulling the content of that tutorial into our official documentation:

Only @serras can decide that. Thanks for the offer.

I think he will agree, as he was looking for people to maintain it.

> Texi is super easy to get going and is Emacs standard.

Yup, I've seen books being written in texi, and it would be a good opportunity to learn a thing or two about it.

**Comment by serras** [comment]
I am OK with it, and willing to help a bit if needed :)

**Comment by gracjan** [comment]
If TAGS were generated directly there would not be a need for current session. Issue #964 describes this and I'm closing this one as a duplicate of #964.

**Comment by sumitsahrawat** [comment]
I completely forgot about the discussion that took place here. I'll try and find some time to add the documentation as suggested.
