### ISSUE TITLE
Add an easy way to navigate back after `haskell-mode-jump-to-def-or-tag`

### ISSUE THREAD

**Issue by martinvlk** [haskell/haskell-mode#1026]
Hi, this is a feature request to implement an easy way to go back when I jump to a definition or tag using M-.

In emacs this is usually bound to M-, so it would make sense to make it so for haskell-mode too.

Many Thanks

**Comment by bergey** [comment]
`pop-tag-mark` navigates back on my machine.  It's bound to `M-*` for me, which I think is an emacs default.

**Comment by gracjan** [comment]
This should be documented and maybe end up as a menu item.

Meanwhile the issue itself seems resolved so closing.
