### ISSUE TITLE
Regression quasi-quotes are not highlighted anymore

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1041]
That's it. Previously text beween `[foo|` and `|]` was highlighted just like string, but now it's not. In some cases highlighting “breaks” entirely at this point and the rest of document after quasi-quote is not highlighted at all. This regression is relatively new, I think it's less than a week old.

**Comment by gracjan** [comment]
Can you add an example here?

**Comment by mrkkrp** [comment]
Sure. Here is some nonsense that demonstrates the problem:

```
module Main where

main :: IO ()
main = setMsg MsgSuccess [shamlet|
this text is not highlighted
|]
```

**Comment by gracjan** [comment]
Try to use some HTML inside the quasiquote:

```
main = setMsg MsgSuccess [shamlet|this text is <bold>bold</bold> and <italic>italic</italic>|]
```

**Comment by gracjan** [comment]
But I agree font locking could be more pronouced here.

**Comment by mrkkrp** [comment]
Why HTML inside should change anything? I do have a tag (without closing one, because it's Hamlet template) inside in my real code, but it's not highlighted there as well. Simpliest case would be to highlight everywhing between the pipes. Previously it worked (I think).

**Comment by gracjan** [comment]
Now it should be more visible and should not break.
