### ISSUE TITLE
Font lock Role annotations

### ISSUE THREAD

**Issue by mrBliss** [haskell/haskell-mode#1057]
I just noticed #1056 and realised that [Role annotations] are also not properly font locked.

[Role annotations]: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/roles.html#role-annotations

Some examples that demonstrate that GitHub's syntax highlighting has the same problem :smiley::

```haskell
{-# LANGUAGE RoleAnnotations #-}

type role Ptr representational
data Ptr a = Ptr Addr#

type role Foo nominal representational phantom
data Foo a b c = Foo a b
```
The `role` keyword must only be highlighted after `type`, analogous to `family`. But what about `phantom`, `representational`, and `nominal`? They are also special keywords in this particular context, but specifying a regex for this seems nontrivial.

**Comment by gracjan** [comment]
@mrBliss: Are you able to write a (failing) test case? Usually when a test case is there somebody comes along and fixes the issue.

**Comment by gracjan** [comment]
We can easily keywordize `role`. The specifiers seem to be more of a problem, we may look at this later.
