### ISSUE TITLE
haskell-mode-stylish-buffer is called in haskell-mode-after-save-handler

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1074]
Why AFTER save? Why not BEFORE?

Also `haskell-mode-after-save-handler` is pretty creepy as it conflicts with any other after save hook functions.

**Comment by bergey** [comment]
Ick.  That is bizarre.  a37fa715f3335544994da3b39fb1fe9d6da9fc2b seems to be the relevant commit, but it doesn't explain *why*.  That predates b5e8f40a181369e6949d64f34b42e74c12261780, which makes `haskell-mode-stylish-buffer` use a temporary file.  I think I understand why if the sequence was

- save
- `stylish-haskell`
- `revert-buffer`

.hat would make more sense in the `after-save-hook`.

Anyhow, I think it would make sense to:
- stop suppressing the save hooks
- remove `basic-save-buffer`
- move `haskell-mode-stylish-buffer` to `before-save-handler`

And test as best we can.

**Comment by gracjan** [comment]
@bergey: Good investigation! I think we should strive to get this code into expected shape, so into before save hook.

**Comment by gracjan** [comment]
Fixing this one will also fix #256 and #788.

**Comment by gracjan** [comment]
@bergey: Can you take this on you?

**Comment by gracjan** [comment]
ping?

**Comment by bergey** [comment]
@gracjan Can you reopen this per discussion in #1137

**Comment by WraithM** [comment]
This issue can be closed.
