### ISSUE TITLE
M-j does not work in block comments

### ISSUE THREAD

**Issue by jstolarek** [haskell/haskell-mode#1078]
Assume I have:

```haskell
-- my comment|
```
where `|` represents cursor position. Pressing `M-j` should continue the comment in the next line (currently affected by #981):

```haskel
-- my comment
-- |
```
That doesn't work with block comments. Assume I have:

```haskell
{-
  my comment|
-}
```
Pressing `M-j` gives:
```haskell
{-
  my comment-}
{-|
-}
```
The correct result is:
```haskell
{-
  my comment
  |
-}
```

**Comment by gracjan** [comment]
Documentation says:

> `(indent-new-comment-line &optional SOFT)`
>
> This command is intended for styles where you write a comment per line, starting a new comment (and terminating it if necessary) on each line. If you want to continue one comment across several lines, use `M-x newline-and-indent`.

So it seem we are doing things according to the documentation, although I agree that it does not make much sense.

**Comment by jstolarek** [comment]
Related: #393

**Comment by gracjan** [comment]
Same as #225.
