### ISSUE TITLE
Add `indentation` label to relevant tickets

### ISSUE THREAD

**Issue by jstolarek** [haskell/haskell-mode#1085]
I noticed there is an `indentation` label created to label reported issues. These issues should be labelled with it: #1084, #1081, #1080, #1079, #1065, #1046, #1034, #1032, #1027 (?), #981, #952, #951 (not sure if worth fixing in light of #1065), #813, #721, #719

**Comment by gracjan** [comment]
Done, thanks.

**Comment by jstolarek** [comment]
New indentation tickets: #1086,  #1091, #1101

**Comment by gracjan** [comment]
Added, thanks.
