### ISSUE TITLE
[Discussion] Make haskell-indentation external, editor agnostic project 

### ISSUE THREAD

**Issue by arybczak** [haskell/haskell-mode#1086]
Hey,

I've recently realized that even though haskell-indentation has seen a lot of improvements recently and is quite pleasant to use, there are two fundamental problems:
1) It's emacs specific, so it doesn't benefit anyone who is not an emacs user.
2) It's written in elisp, which creates high entry barrier for newcomers who would want to contribute.

Both of these severely reduce the pool of people who would be willing to improve the state of the project. Therefore I wonder if we could benefit from porting haskell-indentation to other language (Haskell seems to be the obvious choice here) and making it an external application so that editors can just pass the code and receive a list of possible indentations to use.

Any thoughts?

**Comment by geraldus** [comment]
I had some similar thoughts, however, Emacs provide a way to package authors control various aspects of Emacs behaviour such an indentation, pairs, completions via special variables, e.g. `indent-line-function`, `completion-at-point-function` and etc.  Surely, if you design some major mode you could rely on Emacs default behaviour, but if there is a way to customize this stuff why not to do this?

One thing I can say for sure we can not depend on any external tool, *haskell-mode** should be self-sufficient.

There is very promising Haskell IDE Engine project and if indentation stuff will be added to it, we could use HIE to handle indentation, but even in this case it should be optional and it would be great to provide some fallback. I think future of HIE is still unclear for now, it may or may not become tool number one for any kind of Haskell workflow. Even if we remove indentation logic from **haskell-mode** we should have some handy customizations.

One last point, when I started contributing to **haskell-mode** I had 0 experience in Elisp, but it was super easy to learn it.  I think what we really need is greater number of active people involved in process, I think there are many things we can improve and simplify and make **haskell-mode** more qualitative and outstanding.

**Comment by gracjan** [comment]
@arybczak: Possible and doable although a lot of work.

Note also that indentation has a couple of unintuitive requirements:
- has to work for invalid haskell code (basically any stream of bytes)
- has to support haskell, haskell+cpp, literate haskell, hsc, all future versions of haskell, etc
- has to not fail if source code has git conflict markers
- there are things like hsx, layers on top of haskell
- there is already rich and growing set of quasi quote languages (sql, yesod, etc)

There are projects like [structured-haskell-mode](https://github.com/chrisdone/structured-haskell-mode) and [ghc-exactprint](https://github.com/alanz/ghc-exactprint), but those work only with syntactically correct Haskell source files.

**Comment by arybczak** [comment]
@geraldus 

> Surely, if you design some major mode you could rely on Emacs default behaviour, but if there is a way to customize this stuff why not to do this?

Can you provide an example of limitation arising from having indentation helper as external application? My understanding is that if you treat the helper as referentially transparent function, i.e. you pass a config and a fragment of Haskell code and you get a list of indentation points, you're good. A conversion from haskell-mode config to helper config would be needed, but that is not a problem.

> One thing I can say for sure we can not depend on any external tool, haskell-mode should be self-sufficient.
That is a noble goal, but it creates unnecessary duplication of work. How many editor developers had (and will have) to do the same thing over and over again to get indentation in Haskell to somehow work?

I've looked at HIE, but I don't think there are currently any efforts to solve this specific problems so far.

@gracjan 

Yes, these requirements make it quite challenging as this prevents us from reusing any existing parser library like haskell-src-exts, unless one makes it return partial syntax tree in case of errors and also contain information about indentation of the source code.

Quasi-quoters are a whole issue altogether, but this could possibly be solved e.g. by custom plugins written by their authors or something.

Ultimately the same set of issues applies no matter if the development of indentation-mode continues in Elisp for Emacs only or as the external, editor agnostic application, but I would think that the probability of these problems getting solved is much higher in case of the latter.

**Comment by geraldus** [comment]
@arybczak if such helper indentation application will support *all* possible platforms suitable for Haskell+Emacs workflow I guess this won't be an issue.

**Comment by gracjan** [comment]
I guess the following holds true:

- external indentation tool is not going to happen under Haskell Mode umbrella due to lack of manpower
- if such tool appears we will be eager to support it

I'll close this ticket. Please reopen if you have such a tool running :)
