### ISSUE TITLE
Support indentation for Utrecht style (prefixed) commas

### ISSUE THREAD

**Issue by bergmark** [haskell/haskell-mode#1091]
Below, `X` marks where the caret ends up when i press RET and where I would like different behavior (marked by `Y`). These examples are only for cases where the position of a new comma is obvious by looking on the previous line.

For all of these I think the most flexible solution would be to indent to the position of the previous comma since that would allow me to insert a comma and a space for a new item, or to close the listing

Pragmas:
```haskell
{-# LANGUAGE
    Arrows
  , FlexibleContexts<RET>
X

=>

{-# LANGUAGE
    Arrows
  , FlexibleContexts<RET>
  Y
```

Exports:

```haskell
module Foo
  ( foo
  , bar<RET>
    X

=>

module Foo
  ( foo
  , bar<RET>
  Y
```

Expressions:

```haskell
bar = [ baz
      , bax<RET>
        X

=>

bar = [ baz
      , bax<RET>
      Y

```

Deriving:

```haskell

data Foo = Foo
  deriving
    ( Bar
    , Baz<RET>
      X

=>

data Foo = Foo
  deriving
    ( Bar
    , Baz<RET>
      Y
```

**Comment by gracjan** [comment]
Insert `comma`, press `TAB`.

We can talk about electric commas.

**Comment by geraldus** [comment]
@gracjan I always have to do this when work with records, and I find it's quite tedious (:

**Comment by gracjan** [comment]
Well, we can talk about electric commas :)

**Comment by gracjan** [comment]
Note #1133. @bergmark, I do not know how much time do you have, but would be great if you took a look at #1133 yourself. What do you think?

**Comment by fice-t** [comment]
@gracjan Was this recently fixed? It seems that it offers an appropriate indent position now for everything listed in the issue except for the pragma (which doesn't indent at all for me).

**Comment by gracjan** [comment]
I used to work for as long as I remember. This functionality was already present in `hi2`.

I keep this open because LANGUAGE pragma does not indent. At this time we treat language pragma just like every other comment, we just do not do any indentation inside of it.

**Comment by gracjan** [comment]
In general we support comma-first lists, the missing part is to support LANGUAGE pragma indentation, noted in separate issue #1312.
