### ISSUE TITLE
haskell-indentation misbehaves for comments

### ISSUE THREAD

**Issue by jstolarek** [haskell/haskell-mode#1101]
Say I have:
```haskell
data F -- bla blaX
```
where `X` is current cursor position. I would expect that pressing `M-j` will align comment on the new line with comment on the previous line, but it doesn't:
```haskell
data F -- bla bla
     -- X
```
Pressing `TAB` cycles only between that indentation and no indentation at all. Expected result:
```haskell
data F -- bla bla
       -- X
```

**Comment by gracjan** [comment]
Already reported as #1034. So closing as duplicate.

**Comment by gracjan** [comment]
BTW, was this comment handling working in `haskell-indent`?

**Comment by jstolarek** [comment]
> was this comment handling working in `haskell-indent`?

Yes. `haskell-indentation` is really lacking in basic features compared to `haskell-indent`.

**Comment by gracjan** [comment]
This is interesting. General knowledge was that `haskell-indentation` is improved version of `haskell-indent` and then it itself was improved in `hi2` iteration. Then `hi2` was renamed to `haskell-indentation` and merged back to `haskell-mode`.

`haskell-indent` code is rather hard to modify, uses short uninformative identifiers, uses decision tables, etc. I do not know if we are able to work on `haskell-indent`.

**Comment by jstolarek** [comment]
I understand that sometimes it's just easier to throw away old code and rewrite it from scratch. But at the moment it seems that in terms of usability `haskell-indentation` is still not fully developed and that there is not enough manpower to fix the reported issues (ie. they are not worked on actively). So perhaps it would be a possible to put some minimal effort into maintaining `haskell-indent` until `haskell-indentation` really catches up?

**Comment by jstolarek** [comment]
Oh, I just noticed #1104

**Comment by gracjan** [comment]
Our effort is already spread super thin and you can feel that. Spreading it even thinner would create even more misery as there is now.
