### ISSUE TITLE
haskell-process-path-* now allowed to be lists

### ISSUE THREAD

**Issue by mikesperber** [haskell/haskell-mode#1112]
The customize specs for haskell-process-path-ghci & friends say they can be lists of strings. But the code actually only works with strings.

(I want to use `("nix-shell" "--run" "ghci")`.)

**Comment by gracjan** [comment]
Thanks for the report. This should not be hard to fix. Can you help?

**Comment by mikesperber** [comment]
I'd be happy to - I assume you mean actually handling lists, right? (Rather than outlawing them at the `defcustom`.)

**Comment by gracjan** [comment]
Yes, handling lists.

**Comment by gracjan** [comment]
Hi @mikesperber, I noticed that docstrings for `haskell-process-path-ghci` and friend are confusing now. Can you help and write better description?

(While you are at it a section about those does not exist in `doc/haskell-mode.texi`. Can you add it there?)
