### ISSUE TITLE
haskell-font-lock-symbols no longer works

### ISSUE THREAD

**Issue by patrickt** [haskell/haskell-mode#1120]
As of 20160128.2207, setting `haskell-font-lock-symbols` to `t` does not display characters' Unicode equivalents.

I am running Emacs 25.0, compiled myself from HEAD.

This feature still works as expected on MELPA stable.

**Comment by gracjan** [comment]
Can you quit and start Emacs again?

**Comment by patrickt** [comment]
@gracjan Tried it; no luck.

**Comment by gracjan** [comment]
Unicode prettification in haskell mode is very fragile.

The true solution will be to use `prettify-symbols-mode` from Emacs 25, when it is released.

Temporary solution is embedded in #1050 . When that is merged this one will be also solved.

**Comment by gracjan** [comment]
Should work again now.
