### ISSUE TITLE
Research Wisent/Semantic

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1122]
@kuribas: Thanks for the tip about [Wisent](https://www.gnu.org/software/emacs/manual/html_node/wisent/index.html). So far this looks really good.

From a short research it seems that we can write a pretty easy and forgiving parser that will be able to parse layout vs non-layout and type vs expressions.

As experiment I'll try to implement #899.

**Comment by gracjan** [comment]
If I understand correctly iterative parsers (as they are called in wisent) can be very useful in Haskell thanks to offside rule, basically if something is indented more than initial line it can be reparsed separatelly. Nice!

**Comment by gracjan** [comment]
Some results:

Wisent/Semantic is great, at least on paper, haven't run anything yet. Although documentation (for programming) is scarce, the source is pretty decent and there are examples.

Semantic has some magic to first parse the buffer in full, then reparse only parts that have changed. Default idle reparse time is 1 min (60 sec), that is too much. Reparse trigger key is `C-c , ,`. To see how it works use provided mode for C/C++, `semantic-mode`.

Wisent can be used on its own but then efficient reparsing goes away.

Semantic stores all the info in overlays. There can be nested overlays. There are functions to query this 'overlay database'.

Wisent calls lexer and there are ways to do a lexer hack, just like in C++.

Steps:

1. Connect `haskell-lexeme` lexer to wisent.
2. Implement new 'block lexeme', delimited by indentation, triggered by one of layout keywords.
3. Implement type parser triggered by `::`
4. For font lock use `font-lock-unfontify-region-function` subverting this whole regexp mechanism.
5. Add composition to `font-lock-unfontify-region-function` as this seems to be the only way to get dot composition right.

**Comment by kuribas** [comment]
We could trigger reparse when the user presses TAB or ENTER.  Maybe have a hook to show which region is *dirty* when the buffer changes, then test if the region is dirty before triggering idle reparse.

**Comment by gracjan** [comment]
@kuribas, can you prepare, well, anything? I have problems getting started with semantic. What is the general architecture to get anything running?

**Comment by kuribas** [comment]
I think the best is to start from the existing examples, and modify them for our needs.  There is a simple calc example in the docs.  For haskell we'll need a tokenizer (which we already have right?).  The output format of the tokenizer is described in the manual.  I suggest to use two tokenizers, one for "raw" tokens, and the other with a layout stack, and which generates (implicit) layout tokens.  The layout stack should be an external variable, so it can be popped from the parser when necessary, using the error rule (like in ghc).  We could start with (both) tokenizers, which shouldn't be hard since we already have them.

**Comment by gracjan** [comment]
Current tokenizer can be adapted to Wisent interface.

**Comment by gracjan** [comment]
More results:

1. To define what is top level use `define-mode-local-override semantic-tag-boundary-p`.
2. To define how tags are structured inside use `define-mode-local-override semantic-tag-components`.

Overall good source of ideas is in [grammar.el](https://sourceforge.net/p/cedet/git/ci/master/tree/lisp/cedet/semantic/grammar.el) and [grammar.wy](https://sourceforge.net/p/cedet/git/ci/master/tree/lisp/cedet/semantic/grammar.wy) directly in cedet source code.

**Comment by gracjan** [comment]
Pushing this further:

1. Semantic first tokenizes a region, then run Wisent, so usual lexer hack will not work.
2. Reparsing code is very ad hoc and looks like a buggy hack. It might mostly work.
3. Reparsing needs a specialized function that will take a change and produce a region that needs to be reparsed. This is fragile again.

If reparse regions are selected in a principled way then there might be a principled way to generate those from change information.

**Comment by gracjan** [comment]
Further lessons:

1. I'm still not sure how reparsing works. Luckily this can be left as exercise for next generation parser.
2. Haskell grammar is horribly complicated. It took me 2 weeks to understand patterns.
3. I was advised to use a testing framework while developing grammar. It seems we have to create a framework as there is nothing out of the box present out there.

**Comment by gracjan** [comment]
After initial bumps I have the feeling I can have control over this and create a workable Haskell grammar in finite time. Then we can see what to do with this later.

**Comment by gracjan** [comment]
I looked at parser source files in GHC itself:

- [Lexer.x](https://github.com/ghc/ghc/blob/master/compiler/parser/Lexer.x)
- [Parser.y](https://github.com/ghc/ghc/blob/master/compiler/parser/Parser.y)

Boy, those are complicated. I do not really see how those could be used to generate Wisent grammars. Moreover as the requirements are substantially different I have the feeling that we might not want to do automatic conversion.

On the other hand there is a lot of knowledge coded there and we will have to discover most of it again. Not fun and never ending work.

**Comment by gracjan** [comment]
On top of that we may be able to implement incremental with Semantic (although at this point I do not know how). Semantic does not require any additional dependencies and that is a great feature.

**Comment by gracjan** [comment]
Haskell2010 has about 80 syntactic definitions, lets add 20 for non-Haskell2010 features plus 20 that are technical necessity for Wisent, that gives us 120 rules. Manageable.

[Context-Free Syntax](https://www.haskell.org/onlinereport/syntax-iso.html#sect9.5)

**Comment by gracjan** [comment]
Currently `haskell-indentation` has a recursive descent parser that takes into account that a special token `end-tokens` can appear at any place and end parsing on the spot. Whenever indentation examines `current-token` it has to explicitly handle `end-tokens``. Note that we do not know if it always does it, but we had fixed bugs when it did not. Indentation makes decision about indentation places on the spot, uses something called `following-token` and bails out of parsing to top level using `(throw 'end-parse nil)`.

Anyway, how to simulate all of this with bison-like parser?

Looks like any rule with more than one token would need to have also $EOI handled somehow in there. I've never seen anything like this.

**Comment by gracjan** [comment]
Haskell grammar is just too large to rewrite it in Semantic, at least unless a volunteer comes.
