### ISSUE TITLE
Indenting data types seems broken and not configurable

### ISSUE THREAD

**Issue by karljs** [haskell/haskell-mode#1125]
I realize there is a lot going on with indentation right now, but this seemed like a pretty extreme case of something simple not working at all.  I looked through the other issues, too, and didn't spot anything.  Here's the scenario.  Start defining a new data type:

    data Foo = Bar

Newline, pipe character, indent, now gives:

    data Foo = Bar
      | Baz

And repeated tab presses do nothing to indent this further.  I want to align the pipe character with the equals character, as is common when not using GADTs.

If I already have two or more lines in the data type definition, then adding more after that seems to work just fine.  Thinking maybe this was just a new default, I looked through the customization options, but didn't see one that corresponds to this.

**Comment by gracjan** [comment]
Thanks for the report. Can you add a test case in `tests/haskell-indentation-tests.el`?

**Comment by karljs** [comment]
Should be no problem.  I'll take a look when I have some more spare minutes.

**Comment by gracjan** [comment]
Great!

**Comment by gracjan** [comment]
@karljs: How do you indent this fragment:

```haskell
data User = User
  { userName :: String }
          | Admin
  { adminName :: String }
```

?

**Comment by karljs** [comment]
I wouldn't claim to have the definitive answer to this, but I would probably do the following.

```
data User = User { userName :: String
                 , ...}
          | Admin { adminName :: String
                  , ...}
```

This also seems to work fine for me currently.

**Comment by gracjan** [comment]
Thanks. We try to reconcile two styles of indentation to reduce a bit of complexity. Hence the question.
