### ISSUE TITLE
Implement electric comma, semicolon, etc

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1133]
`haskell-indentation` reacts to a couple of characters, most notably comma and semicolonbut also other chars.

Implement function that can be used in `post-command-hook` that will:
- [ ] check if there is exactly one character on the line
- [ ] check if there is only one indentation position returned from `haskell-indentation-find-indentations`
- [ ] do the indentation if both are true
- [ ] connect this function to `,;` and `)}]`

More info:
http://www.gnu.org/software/emacs/manual/html_node/ccmode/Electric-Keys.html

**Comment by bch29** [comment]
This function does the job, but unfortunately I'm not familiar enough with emacs to know how to hook it into electirc keys:

```elisp
(defun haskell-try-auto-indent ()
  (if (and
       (= 1 (length (s-trim (current-line))))
       (= 1 (length (haskell-indentation-find-indentations))))
      (haskell-indentation-indent-line)))
```

**Comment by gracjan** [comment]
`cc-mode` knows how to do electric keys. Can you look there?

**Comment by gracjan** [comment]
This is great find: https://github.com/haskell/haskell-mode/pull/1175#issuecomment-187692908 .

**Comment by fice-t** [comment]
I don't believe that we should put this in `post-command-hook` (as far as I can tell, `cc-mode` doesn't use that approach either). I'm unsure about using `electric-indent-mode` but it does make the code shorter. The following should work:

```haskell
(defun haskell-electric-keys (char)
  "Indent after typing CHAR when:
1) There is no other character on the current line.
2) There is only one possible indentation position.
3) The variable `haskell-use-electric-keys' is either t or, if it's a list, CHAR is in it."
  (and (if (listp haskell-use-electric-keys)
           (memq char haskell-use-electric-keys)
         haskell-use-electric-keys)
       (string-empty-p (string-trim-left (thing-at-point 'line t)))
       (= 1 (length (save-excursion
                      (move-to-column (haskell-indentation-current-indentation))
                      (haskell-indentation-find-indentations))))))

(defcustom haskell-use-electric-keys t
  "If t, various special keys will be 'electric' when `electric-indent-mode` is turned on. 
If a list, only the special characters present in the list will be 'electric'."
  :group 'haskell-indentation
  :type '(choice boolean (repeat character)))

(setq-local electric-indent-chars (string-to-list ",;=|)}]"))
(setq-local electric-indent-functions #'haskell-electric-keys)
```
We'd have to turn off `electric-indent-inhibit` of course.

**Comment by fice-t** [comment]
Actually, looking a bit more closely, the above won't cut it. I thought that `electric-indent-functions` would only be called after typing one of `electric-indent-chars`. Apparently `electric-indent-functions` gets called after *every* character typed, and if one of the functions returns true *or* the character typed was in `electric-indent-chars` then it indents.

So now I'm really against using `electric-indent` for this, as it runs the check after every `self-insert`, which is unnecessary. I changed the above to a version that actually works, but I don't like it.

**Comment by geraldus** [comment]
@fice-t very nice!  Will you send a pull request for this?

**Comment by fice-t** [comment]
I could, but I don't think it's a good way to go about it. Wouldn't just defining the electric functions as needed be a better solution since nothing meaningful would be added to `post-self-insert-hook`?
(`cc-mode` does this, though in their case they need to do it as the electric keys have different behaviour). 

I have a solution for it that I can post later, which is slightly more involved. Instead it only checks after the special characters are typed, and not after every `self-insert-command` like the above does.

I think the slight increase in complexity would be worth it since @gracjan was talking about performance recently. It probably doesn't really matter either way though, so it's up to you two.

**Comment by geraldus** [comment]
@fice-t maybe customizing `electric-indent-chars` should be sufficient if we'll implement `haskell-mode-electric-indent` function and add it `electric-indent-hook`?

**Comment by fice-t** [comment]
Unless I misunderstand, that was my previous approach -- `electric-indent-functions` would be called after every `self-insert-command`, and typing characters in `electric-indent-chars` would unconditionally re-indent, which is not what we want.

**Comment by geraldus** [comment]
@fice-t I can't remember have you tried to implement some function which should decide what to do in your previous approach?

_Sorry, I have weak mind today, all this indentation stuff is still messy in my head.  I'm more inclined in direction to provide just semantic indentation support but not aesthetic (as was recently discussed in #1178) leaving this to third party packages.  For now I'm confused a bit and I can't give good advices because of lacking experience with electric indentation in other modes, and it requires some time to research all of this._

**Comment by fice-t** [comment]
Yeah, the problem is that `electric-indent` (to my understanding) will indent automatically if at least one of these is true:

1) A function in `electric-indent-functions` returns true
2) The character typed is in `electric-indent-chars`

So we can't just add special characters to `electric-indent-chars` because then when typing these characters it will pretty much always indent (it doesn't go through `electric-indent-functions`).

Which means that `electric-indent-functions` is called after every character typed, which as it's short-circuited doesn't mean the end of the world, but it's not something that I'd say is very good.

**Comment by geraldus** [comment]
Ah, so, due to Haskell have indentation related syntax the real solution would be not to customize `electric-indent-chars` but rather implement `haskell-mode-electric-indent` function, wouldn't it?

**Comment by fice-t** [comment]
Yeah, I think so. The below does just that:

```elisp

(defun haskell-electric-command (char)
  (let ((only-char? (string-empty-p (string-trim-left (thing-at-point 'line t))))
        (electric? (if (listp haskell-use-electric-keys)
                            (memq char haskell-use-electric-keys)
                          haskell-use-electric-keys)))
    (insert char)
    (when (and only-char?
               electric?
               (= 1 (length (save-excursion
                              (move-to-column (haskell-indentation-current-indentation))
                              (haskell-indentation-find-indentations)))))
      (indent-according-to-mode))))

(defcustom haskell-use-electric-keys t
  "If t, various special keys will be 'electric'. If a list, only the
special characters present in the list will be 'electric'."
  :group 'haskell-indentation
  :type '(choice boolean (repeat character)))

(defmacro define-haskell-electric-keys (names)
  `(progn
     ,@(cl-loop for (name . char) in names
                for func-name = (intern (concat "haskell-electric-" name))
                collect `(defun ,func-name ()
                           ,(format "Automatically indent when typing '%c' when:
1) There is no other character on the current line.
2) There is only one possible indentation position.
3) The variable `haskell-use-electric-keys' is either t or, if it's a list, '%c' is in it."
                                    char
                                    char)
                           (interactive)
                           (haskell-electric-command ,char))
                into functions
                collect `(define-key haskell-mode-map
                           ,(char-to-string char) #',func-name)
                into define-keys
                finally (return (append functions define-keys)))))

(define-haskell-electric-keys (("comma" . ?,) ("semicolon" . ?\;)
                               ("equals" . ?=) ("pipe" . ?|)
                               ("end-paren" . ?\)) ("end-brace" . ?})
                               ("end-bracket" . ?\])))
```

`haskell-electric-command` is basically the same as the above except it handles the input of the character as well.

`define-haskell-electric-keys` is a macro that both creates the `defun`s for the electric keys and their keybindings. So it will create `haskell-electric-comma` and in `haskell-mode-map` bind it to `,`, and so on.

**Comment by fice-t** [comment]
@gracjan @geraldus Do you prefer one of the above solutions? It's been a month, but I think both solutions worked.

Basically:
* `electric-indent-function` approach: shorter code, but perhaps too much overhead
* Approach right above: a bit of a mess, but better at runtime

**Comment by geraldus** [comment]
@fice-t hi, I need some time to overview both again, I will be able to do this in few days.  However, here is some quick thoughts.  Short and concise code is always better long messy one.  If you have messy but effective code please just spent some little time to make it cleaner a bit (e.g. splitting into small chunks) to make it easier to follow the idea.  In practice only messy code need to be refactored, and this is what we are doing with existing functionality most of the time.

**Comment by fice-t** [comment]
Yeah, you're right. I guess since the list of electric keys doesn't really change much then a special macro doesn't need to be made. I made the macro since I didn't feel like writing essentially the same defun/define-key for each key, but the following would be more clear (it's basically what the macro expands to):

```elisp
(defun haskell-electric-comma nil "Automatically indent when typing ',' when:
1) There is no other character on the current line.
2) There is only one possible indentation position.
3) The variable `haskell-use-electric-keys' is either t or, if it's a list, ',' is in it."
       (interactive) (haskell-electric-command ?,))
(defun haskell-electric-semicolon nil "Automatically indent when typing ';' when:
1) There is no other character on the current line.
2) There is only one possible indentation position.
3) The variable `haskell-use-electric-keys' is either t or, if it's a list, ';' is in it."
       (interactive) (haskell-electric-command ?\;))
...etc
(define-key haskell-mode-map "," (function haskell-electric-comma))
(define-key haskell-mode-map ";" (function haskell-electric-semicolon))
(define-key haskell-mode-map "=" (function haskell-electric-equals))
...etc
```

**Comment by fice-t** [comment]
@geraldus I've found a way that's shorter and closer to how `cc-mode` does it:

```elisp
(defcustom haskell-use-electric-keys t
  "If t, various special keys will be 'electric'. If a list, only the
special characters present in the list will be 'electric'."
  :group 'haskell-indentation
  :type '(choice boolean (repeat character)))


(defun haskell-electric-command (arg)
  "Calls `self-insert-command' to insert the character typed
and indents when all of the following are true:

1) There is no other character on the current line.
2) There is only one possible indentation position.
3) The variable `haskell-use-electric-keys' is either t 
   or, if it's a list, the character typed is in it."
  (interactive "*p")
  (let* ((col (haskell-indentation-current-indentation))
         (empty-line? (eq (+ col (line-beginning-position))
                          (line-end-position))))
    (self-insert-command arg)
    (when (and empty-line?
               (> arg 0)
               (if (consp haskell-use-electric-keys)
                   (memq (char-before) haskell-use-electric-keys)
                 haskell-use-electric-keys)
               (= 1 (length (save-excursion
                              (move-to-column col)
                              (haskell-indentation-find-indentations)))))
      (indent-according-to-mode))))

(dolist (key (string-to-list ",;=|)}]"))
  (define-key haskell-mode-map (string key) #'haskell-electric-command))
```

Now they share the same command, but that should be alright.

**Comment by geraldus** [comment]
@gracjan any thoughts?

@fice-t I think space insertion is not needed (someone may prefer to omit spaces).  Thank you for your efforts!

**Comment by gracjan** [comment]
Hmm, my thoughts:

- it should work with `electric-indent-mode`, specifically we do not want another `defcustom` variable
- list of chars should contain only self delimiting characters, so `",;)}]"`. others cannot be there because those may form longer operators like `||` or `==` and we do not want to be getting in the way 
- I like that this is one function

There is a way to use `electric-indent-function` efficiently. In the body of `haskell-electric-indent-function` you can check just recently inserted character by `(char-before)` and that should be efficient enough.

**Comment by fice-t** [comment]
I'm not sure what's wrong with the defcustom variable. I could understand if I was injecting something new deep into the indentation parser, but this is a simple variable that would allow people to select which operators are electric easily. The variable could always just have a default value of `electric-indent-mode`, like `cc-mode` does with its `c-electric-flag`.

Considering we'd have to turn turn off `electric-indent-inhibit` if we put this into `electric-indent-functions`, I don't think it's a good idea. Again, `cc-mode` doesn't even do this. As for efficiency, I suppose it wouldn't really matter either way. 
Though I think it'd be nice to be able to use this feature without using `electric-indent-mode` (like in `cc-mode`), especially as many configs (e.g. spacemacs) turn the mode off anyway.

**Comment by gracjan** [comment]
@fice-t, lets do this your way.

Please fix a couple of things in the code:

- [ ] s/haskell-use-electric-keys/haskell-indentation-electric-flag/g
- [ ] haskell-use-electric-keys should be just a bool, set of characters should be hardcoded
- [ ] keys should be bound directly in `haskell-indentation-mode-map`
- [ ] the character does not have to be the only on the line, it is enough if it is first
- [ ] none of this logic should be active in strings, comments or quasiquotes

And thanks for thorough discussion.
