### ISSUE TITLE
Consider font-lock faces for identifiers based on identifier origin

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1141]
Consider different faces for identifier:
1. Local identifiers (arguments, patterns, `where` or `let` clauses).
2. Same module identifiers.
3. Imported identifiers.

With #1122 font-lock should have necessary information available in Semantic layers.

This idea is based on a similar concept presented at the end of [Making Semantic Highlighting Useful](https://medium.com/@brianwill/making-semantic-highlighting-useful-9aeac92411df#.4czo17nq5) blog post.

**Comment by geraldus** [comment]
Wow, this will be super cool!

**Comment by gracjan** [comment]
Lack of semantic parser renders this impossible, unless a Haskell parser backend is used also. Anyway looks too big.
