### ISSUE TITLE
Reconsider word breaks for haskell-cabal-mode

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1146]
One thing I dislike in `haskell-cabal-mode` that functions such
* `left-word`
* `right-word`
* `backward-kill-word`

and etc. do not considering point `.` as word break char, for example 
```cabal
  exposed-modules:  Internal.Type
```
if I place point at beginning of exposed module name `Internal.Type` and invoke `right-word` it moves point to line end, while I expect that point should go to beginning of "Type" (like in `haskell-mode`).  Now if I invoke `backward-kill-word` it will delete whole module name, while I expect it will leave "Internal." part untouched.

**Comment by mrBliss** [comment]
That annoys me too! I found the cause of this and will post a pull request shortly.

**Comment by bergey** [comment]
Agreed.  Can we treat hyphens as punctuation too, given how we use them in package names?
