### ISSUE TITLE
Case sensitive completions in haskell-cabal-mode

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1147]
I know we have some auto-completion customizations for `haskell-mode`.  Could we make completions case sensitive by default in `haskell-cabal-mode` too?

**Comment by gracjan** [comment]
We have `dabbrev` customizations in `haskell-mode`. We can have same in `haskell-cabal-mode`. Can you create a PR?

**Comment by geraldus** [comment]
I tried to play with `dabbrev-case-fold-search`, `dabbrev-case-distinction`, and `dabbrev-case-replace` variables, but didn't understand how this stuff works (reading docs does not helped also).  It seems that all time I get same candidates, I'm with `company-mode` and not sure how it gets completion candidates: there are a bunch of backends listed in `company-backends`, and `completion-at-point-functions` is set to `tag-completion-at-point-function`.  Another weird thing: when I type `as` company shows me a lot completions, where I can find completely irrelevant things like `askell`, `askell2010`, `askcreated` and a lot of other wrong candidates.

**Step 1**.  
I have following global `company-backends` value
```el
(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```
> This variable is safe as a file local variable if its value
  satisfies the predicate ‘company-safe-backends-p’.

Should we restrict `company-backends` only to single grouped backend `'(company-capf company-dabbrev-code company-etags company-dabbrev company-files)` locally in haskell source files and cabal files?

**Comment by geraldus** [comment]
Hmm… Something wrong with `company-dabbrev` backend https://github.com/company-mode/company-mode/issues/474

**Comment by gracjan** [comment]
Use <kbd>M-/</kbd>.

**Comment by gracjan** [comment]
Looks like this is company issue.
