### ISSUE TITLE
haskell-forward-sexp should signal scan-error at the end of list like forward-sexp

### ISSUE THREAD

**Issue by cruegge** [haskell/haskell-mode#1148]
Emacs' own `forward-sexp` does not jump out of balanced expressions. Instead, it signals a `scan-error`. This behaviour is used by functions like `up-list` to determine the end of the expression. `haskell-forward-sexp`, on the other hand, jumps out of the expression without error. While this behaviour is probably more intuitive from the user perspective, it breaks at least one other useful navigation function.

I assume that implementing the proper behaviour for arbitrary Haskell expressions would be way to complex, but maybe it would be possible to simply signal an error when looking at a closing paren/bracket/brace, thus retaining the most common use-case for `up-list`, i.e. jumping out of sexp-like lists. Another option might be to just rebind `forward-sexp` instead of setting `forward-sexp-function` to a function that does not behave properly.

**Comment by gracjan** [comment]
Agreed. @cruegge: can you add a failing test case for this?

**Comment by cruegge** [comment]
Never did this, but I think I'll figure it out. Might take a while.

**Comment by gracjan** [comment]
Please put those tests in this file: https://github.com/haskell/haskell-mode/blob/master/tests/haskell-mode-tests.el

**Comment by gracjan** [comment]
Fixed  by #1151.
