### ISSUE TITLE
Indentation level is missing for `deriving` keyword

### ISSUE THREAD

**Issue by issue-dispenser** [haskell/haskell-mode#1154]
As defined [here](http://hackage.haskell.org/package/base-4.8.2.0/docs/src/GHC.Base.html#Maybe):
```haskell
data  Maybe a  =  Nothing | Just a
  deriving (Eq, Ord)
```

There's no indentation level that will result in the deriving being 2 spaces. It'll only do this:
```haskell
data  Maybe a  =  Nothing | Just a
               deriving (Eq, Ord)
```

**Comment by gracjan** [comment]
Can you add a test case for this?

**Comment by issue-dispenser** [comment]
Is the hindent test 55a correct behaviour? From what I can tell, it seems like deriving on a new line should be indented like `where` is instead of aligned to an equals.

**Comment by gracjan** [comment]
Looks good to me, can you also add tests covering #1046?

**Comment by gracjan** [comment]
Note that `deriving` can be on its own line, too:

```hs
deriving instance XYZ a b
```
