### ISSUE TITLE
Stylish haskell doesn't work in haskell-mode any more

### ISSUE THREAD

**Issue by Mikolaj** [haskell/haskell-mode#116]
Others can't reproduce this, so it may be due to my emacs version (GNU Emacs 23.3.1, Ubuntu 12.04.1 LTS) or the cruft in my emacs configuration:

https://github.com/Mikolaj/mydotflies/blob/master/.emacs

Perhaps somebody else has a similar problem?

I can run stylish-haskell all right from command line, but it does not seem to have any effect anymore from haskell-mode. The commit that causes the behaviour is the last of the series that fixed many problems of stylish-haskell in haskell-mode

https://github.com/haskell/haskell-mode/commit/11b531cb2f55a32f646721b761b7d76b9f36855e

With this commit, it apparently saves some extra stuff when I change and save the file:

```
Saving file /mikolaj/r/LambdaHack/Game/LambdaHack/Kind.hs...
Wrote /mikolaj/r/LambdaHack/Game/LambdaHack/Kind.hs [2 times]
Tags generated.
```

but the file is not affected apart of my original change. 
For comparison, when I set

```
'(haskell-stylish-on-save nil)
```

I'm getting

```
Saving file /mikolaj/r/LambdaHack/Game/LambdaHack/Kind.hs...
Wrote /mikolaj/r/LambdaHack/Game/LambdaHack/Kind.hs
(No changes need to be saved)
Tags generated.
```

**Comment by nrolland** [comment]
there is still a weird issue, as when haskell-stylish-on-save is enabled, the TAGS file supposed to be coming from haskell-tags-on-save is not actually generated

**Comment by ivan-m** [comment]
@nrolland maybe open a new issue for this as this one is labelled as being closed?

**Comment by Mikolaj** [comment]
> there is still a weird issue, as when haskell-stylish-on-save is enabled, the TAGS file supposed to be coming from haskell-tags-on-save is not actually generated

I can't reproduce that with GNU Emacs 24.3.1 and haskell-mode from 2013-11-09 21:44:26 (doh, am I lazy with updating!).

**Comment by gracjan** [comment]
@nrolland: Thanks for reporting. We will need a reproducible case to debug this.

Also a new open issue would be a good idea so that new information is not lost.

**Comment by nrolland** [comment]
@gracjan I ma not sure what is the best way to have a reproducible case. 

@Mikolaj : are you sure the file is actually generated ? I have the emacs display that tags have been generated but no file appears.
Very oddly enough, when calling directly M-x haskell-process-generate-tags, the file does get generated. FWIW, I tried to trace the calls down to  haskell-process.el : (defun haskell-process-send-string (process string) but  I dont see any difference in the string being sent when triggered on save VS manually invoked, which is puzzling...


":!cd /Users/nrolland/notes/utrecht/lab22/ && find . -name '*.hs' -print0 -or -name '*.lhs' -print0 -or -name '*.hsc' -print0 | xargs -0 hasktags -e -x
"

":!cd /Users/nrolland/notes/utrecht/lab22/ && find . -name '*.hs' -print0 -or -name '*.lhs' -print0 -or -name '*.hsc' -print0 | xargs -0 hasktags -e -x
"

invoking that command from cabal real does generate the tags.

**Comment by Mikolaj** [comment]
@nrolland: yes, the TAGS are automatically generated for me (but note I no longer have access to the old configuration from the time I reported the bug and with the new setup I see no erroneous behariouv). Cheers!
