### ISSUE TITLE
Support non-interactive completions

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1171]
Let's:

+ [x] hardcode completion candidates for keywords
+ [x] introduce `haskell-completion-at-point` (language, pragma name, options, extensions, keywords) in `haskell-completions.el`
+ [x] add it to `completion-at-point-functions` in `haskell-mode.el`

For interactive part:
+ [x] rename `haskell-completions-sync-completions-at-point` to `haskell-sync-repl-completion-at-point`
+ [x] use `haskell-completion-at-point` internally
+ [x] replace `haskell-completions-at-point-function` in `completion-at-point-functions` with  `haskell-sync-repl-completions-at-point`

I'd prefer a bit longer names: `haskell-completion-completion-at-point` and `haskell-completions-sync-repl-completions-at-point`.

Docs:
+ take a look at docs, and make necessary changes and clarifications.
  + [x] find out if section 4.2.5 is relevant (#1182)
  + [x] find out contextual-space usage (#1182)
  + [x] update section 4.3:
    + [x] mention non-interactive completions
    + [x] mention keyword completions
    + [x] mention requirement of active process (session associated to buffer)

Related #215 #1169 #1184

**Comment by geraldus** [comment]
@gracjan can you take care about section 4.3 of manual?

**Comment by gracjan** [comment]
Okay. Maybe not that soon, but yes...

**Comment by geraldus** [comment]
Cool, then I can proceed with some other stuff.
