### ISSUE TITLE
Feature request: guess project from path and save somewhere

### ISSUE THREAD

**Issue by Mikolaj** [haskell/haskell-mode#118]
A feature request (unless it's bug that only affects me): I'd like to avoid answering questions for each of the dozens of files in my project whether I like the file to be included in the current project. I suppose this can be guessed from the path or the cabal file. Alternatively or in addition, this information could be saved somewhere for future session, e.g, in the desktop file, if that makes sense.

**Comment by gracjan** [comment]
This issue has not seen activity for a very long time. Is this still something we should be concerned about?

**Comment by Mikolaj** [comment]
Oh, I'm sorry, it's long ago fixed. thank you!
