### ISSUE TITLE
Enable jump to tag without activating a session

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1180]
I only activate session when I need to use REPL. Why jumping to a tag cannot work without this? `hasktags` gererates TAGS file, just read it and jump? No?

**Comment by gracjan** [comment]
Misarchitecture. Haskell mode checks if session exists so that it can use it to jump to definitions better. Checking if sessions exists has this side effect of starting a session. Somebody needs to fix this.
