### ISSUE TITLE
Paredit M-s no longer works after upgrade to 13.18

### ISSUE THREAD

**Issue by ozataman** [haskell/haskell-mode#1183]
Apologies if this is a known issue - a quick search for "paredit" did not reveal any issues.

Just upgraded via the package manager to 13.18 and my paredit in Haskell files started acting strangely. Most notably, I can no longer get rid of parentheses from within them using M-s.

Example: 

I want `(map go m)` to become `map go m`. I used to be able to put cursor on, say, "go" and hit M-s and the parentheses would disappear.

Now, I get the following error: `up-list: Scan error: "Unbalanced parentheses", 9464, 9464`

The positions always refer to some large value that feels like it's after the current module. I've tested even with a single line module and had the same issue.

**Comment by bergey** [comment]
Short term fixes include using `sp-splice-sexp` (from `smartparens`) or setting `(setq forward-sexp-function nil)` in Haskell buffers.  The latter may break other things, I'm not sure.

I haven't figured out what `haskell-forward-sexp` is doing wrong.

**Comment by ozataman** [comment]
@bergey Thanks for the tip on smartparens - looks pretty good so far!

**Comment by geraldus** [comment]
@bergey any chances you will have a time to find real issue and fix it?

**Comment by bergey** [comment]
@geraldus That seems unlikely, I'm afraid.  Not any time soon, certainly.

**Comment by gracjan** [comment]
This issue was fixed by #759.

@ozataman: for now either use workaround provided by @bergey or use the git version of haskell-mode.
