### ISSUE TITLE
Extend non-interactive completions for identifiers from TAGS

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1184]
+ [x] make `hasktags` to work in non-interactive mode too
+ [x] combine TAGS completions with haskell-completions in non-interactive mode
+ [x] bring some light about this in docs
+ [x] interactive mode should override completion functions hook (as it does now)

Look like we can improve static completions to provide identifier and module name completions too making use of tags.

I need some time to do a basic research on this topic.

_Moved documentation notes to #702_

**Comment by geraldus** [comment]
The best way I can think of is to steal this code from company mode
https://github.com/company-mode/company-mode/blob/250ca1c395c6f05b733abce69a2d928b6cd31618/company-etags.el#L62-L84

**Comment by geraldus** [comment]
Ok, let's not complicate things!  I have a better solution.  Default value of `completion-at-point-functions` is `(tags-completion-at-point-function)`, so let's
+ in `haskell-mode` set `completion-at-point-functions` to 
```el
(haskell-completions-completion-at-point tags-completion-at-point-function)
```
+ in `haskell-interactive-mode` set `completion-at-point-functions` to
```el
(haskell-completions-sync-repl-completion-at-point)
```
This should give tags completions in static mode without even without any completion backend.  `company-mode` automatically re-uses `haskell-completions-completion-at-point` by default.  For interactive completions with company I would mention making `company-backends` list buffer-local for haskell buffers and prepending it with following grouped backend:
```el
(company-capf company-dabbrev-code)
```
This adds dabbrev completion candidates to REPL completions, which is quite handy.

**Comment by gracjan** [comment]
Good idea.

**Comment by geraldus** [comment]
> Good idea.

Ahh… Tags are generated only when session is present, so basically this won't work well: user must to generate tags manually and visit it manually.  Some features of Haskell Mode require minimal project information, and I often think about such functionality.  I think we should discuss this.

**Comment by gracjan** [comment]
See #964.

**Comment by geraldus** [comment]
@gracjan aha.  I though about some very simple `.cabal` file lookup in static mode (just for tags generation, enabled extensions and modules related to current file); though it looks very simple I guess the complexity is hidden underneath, for example cashing issues and etc.

**Comment by geraldus** [comment]
I'm closing this
