### ISSUE TITLE
haskell-mode and delete-trailing-whitespace delete content of buffer on save

### ISSUE THREAD

**Issue by vlatkoB** [haskell/haskell-mode#1188]
This is one very, very strange bug.
Happens on  GNU Emacs `25.0.50.2` (x86_64-pc-linux-gnu, GTK+ Version 3.10.8), Mint,
but not on     GNU Emacs `24.5.1` (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6), Arch

I tested to get most minimal example and here it is.
- Create empty .emacs.d/
- Put init.el:
````elisp
(package-initialize)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
````

- Create .emacs.d/elpa dir and copy just haskell-mode in
  (notice haskell-mode is not even `required` in init.el?)
- Create a .hs file with this content in `external editor`
````
....
....redirect 
....
..where
..
````

- Replace all dots with space in `external editor`
- Open file in emacs
- Make a change and save the file
7.  In buffer you see just
````
    redirect
````
`where` is gone.

This can happen in the middle of the file, at the end.... 
Not all content is deleted. Few lines here, few lines there.

Can anyone test and reproduce this?

**Comment by gracjan** [comment]
Related #395.

**Comment by vlatkoB** [comment]
Are you sure? I think this started to happen few months ago. But occasionally, so I didn't investigate.
I can't believe no one has noticed this before.

**Comment by fice-t** [comment]
Works in Emacs `25.0.92.1` -- you can try it [here](https://lists.gnu.org/archive/html/emacs-devel/2016-03/msg00024.html).

**Comment by geraldus** [comment]
> Works as expected (only trailing whitespace deleted) in Emacs `25.0.92.1` -- you can try it [here](https://lists.gnu.org/archive/html/emacs-devel/2016-03/msg00024.html).

Also works for me in Emacs `25.0.91.1`

**Comment by vlatkoB** [comment]
Thanks, I'll upgrade.

**Comment by vlatkoB** [comment]
Works fine on Emacs `25.1.50.2`.

**Comment by gracjan** [comment]
Nice to hear!
