### ISSUE TITLE
Indentation is broken for quasiquotation with quote symbols

### ISSUE THREAD

**Issue by neongreen** [haskell/haskell-mode#1189]
~~~
foo = do
  let bar = [text|"some text"|]
  button "Cancel" $ do
                _
~~~

After pressing Enter after `do`, the cursor is at the position marked with `_`, which is rather wrong.

This doesn't happen when:

  * quasiquotation isn't present
  * or `"Cancel"` is removed
  * or quotes around `"some text"` are removed

**Comment by gracjan** [comment]
Thanks for the report. Can you add a test case in `tests/haskell-indentation-tests.el`?

**Comment by neongreen** [comment]
Sure.

**Comment by neongreen** [comment]
@gracjan: Could you help me a bit?

`haskell-indentation-skip-token` has this code:

~~~ elisp
            ;; QuasiQuotes, with help of propertize buffer and string delimeters
            (looking-at "\\s\"\\S\"*\\s\"")
~~~

When the point is here, `\s"` treats `|` as a quote character:

~~~
     v
[text|foo "bar"|]
~~~

~~~
> (looking-at "\\s\"")
t
~~~

And when it's inside the quote, it doesn't treat `|` as a quote character anymore but it treats `"` as a quote character:

~~~
          v
[text|foo "bar"|]
~~~

~~~
> (looking-at "\\s\"")
t
~~~

(Moreover, `|` isn't treated as a quote-character outside of the quasiquotation context.)

So my guess is that thanks to this `haskell-indentation-skip-token` treats the string between `|` and `"` as a single token, which is incorrect. I have several ideas about how this could be fixed, but it's hard for me to choose because I don't understand how the meaning of `\s"` can change dynamically:

  * If meaning of `\s"` doesn't change *while* regexp consumes the string, I could make it so that `\s"` matches `|` but doesn't match `"` (when the point is after `[text`) and so `\s"\S"*\s"` wouldn't stop at the `"` in the quasiquote. (Where can it be changed, tho?)

  * If meaning of `\s"` can change while regexp consumes the string, I could write something like `\(\s"\) ???* \1` (I don't know how to say “any character that isn't the same as the quote character matched previously”, tho).

  * Can we somehow check whether we're at the beginning of a quasiquote and then write a regexp that would match `|`s explicitly without the `\s"` shenanigans? (But then I don't know how to write such a regexp, because it needs to detect `|]` and Emacs regexps don't have lookahead.)

  * Maybe `\s$` (paired delimiters) could help?

**Comment by neongreen** [comment]
Also, what exactly is `haskell-indentation-peek-token` supposed to do? Its idea of “token” seems to be different from `haskell-indentation-skip-token`'s:

~~~
     v
[text|foo "bar"|]
~~~

~~~
> (haskell-indentation-peek-token)
"|"

> (haskell-indentation-skip-token)

           v
[text|foo "bar"|]
~~~

**Comment by gracjan** [comment]
Character properties are added in `haskell-syntax-propertize`. It sets 'generic string delimeter' property on the first and last `|` in quasiquote.

But then I would not rely on this and I'm not sure why peek-token does this. It should just match `"` and `[xxx|` and `|]` and that's it.
