### ISSUE TITLE
Write a script for generation some hard-coded stuff

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1194]
Write script(s) to generate:
for Haskell Doc mode
+ [ ] a list of Prelude identifiers (`ghc -e ':bro Prelude'`)

for Haskell Completions package
+ [ ] a list of supported extensions (`ghc --supported-extensions`) 
+ [ ] a list of supported GHC options (`ghc --show-options`)

+ [ ] collect all this stuff in some elisp file
+ [ ] `haskell-doc-prelude-types`, `haskell-ghc-supported-extensions`, `haskell-ghc-supported-options` should be bound to generated lists
+ regenerate this lists once new GHC released

Caveats:
+ data declarations should be excluded from `:bro Prelude` output
+ class functions in `:bro Prelude` output lack of class constraints in type signature, so it should be modified, the easiest method to get valid type signatures would be run `:type` command for all class functions.

**Comment by gracjan** [comment]
Fixed in #1334.
