### ISSUE TITLE
Automatic ghci-ng/ghci-8.0 support for :set +c

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1200]
Support for `:complete` command requires `:set +c` in the beginning of a ghci session. We should support this out of the box:

1. Issue `:set +c` unconditionally for every GHCi session started.
2. Look for response, if there was an error mark session as incapable of `:complete`.
3. Use this marker to either issue `:complete` commands of not.
4. Remove from documentation mentions of `:set +c` in `.ghci` file. Those are rude :)

**Comment by geraldus** [comment]
@gracjan `:complete` forks fine in GHC 7.10+ without `+c`!  But  `:type-at` does not

**Comment by gracjan** [comment]
Aha. Anyway I would do `+c` by default.

**Comment by geraldus** [comment]
I have this in my `~/.ghci` for ages :D

**Comment by gracjan** [comment]
We have this is documentation and that irks me. It should JustWork (tm).
