### ISSUE TITLE
Error: (void-function haskell--rx-let)

### ISSUE THREAD

**Issue by PierreR** [haskell/haskell-mode#1209]
I have just updated `haskell-mode` to `20160314.416` from elpa  and I have got the following error:
```
Error: (void-function haskell--rx-let)
```
It is probably due to a recent commit because if I use `20160309.237` the error disappears and I can use `haskell-mode` again.

PS: using `spacemacs with NixOS 15.09`

**Comment by nomicflux** [comment]
Same issue, using `spacemacs` on `Kali 2.0` (which I believe uses packages from `Debian "jessie"`), as well as on `Windows 10`.

**Comment by gracjan** [comment]
Already fixes with 86b6ffd148451e313b7cacaafd614d1a49ee3c98

**Comment by nomicflux** [comment]
Made the same change in haskell-c2hs.el, removing `;;;###autoload` in front of `c2hs-font-lock-keywords `; still getting `(void-function haskell--rx-let)` when loading Emacs, rendering haskell-mode unusable.

**Comment by gracjan** [comment]
You needs also run `rm haskell-mode-autoloads.el` and `make haskell-mode-autoloads.el`

**Comment by nomicflux** [comment]
Perfect - that worked.
