### ISSUE TITLE
Require at least Emacs 24.3 or properly support Emacs 24.1 and Emacs 24.2

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1218]
Currently `haskell-mode` claims compatibility with Emacs 24.1, this is not true.

Note that our test suite runs properly on both Emacs 24.1 and Emacs 24.2.

Support for Emacs 24.1/2 faces compilation warnings/errors:
- `eval-after-load` signals `"Error: Attempt to modify read-only object"`
- there are issues with `cl` package: function 'cl-find-if' from cl package called at runtime
- `setq-local` is absent

Fixable, but requires work.

So we have to decide and commit to one of the following:
1. Officially support Emacs 24.3 and greater.
2. Officially support Emacs 24.1/2 and add Travis tests for those.

Release dates for Emacs versions:
- Emacs 24.1: June 10, 2012
- Emacs 24.2: August 27, 2012
- Emacs 24.3: March 11, 2013
- Emacs 24.4: October 20, 2014
- Emacs 24.5: April 10, 2015

Ubuntu LTS 14.04 has Emacs 24.3 installed.

**Comment by gracjan** [comment]
Note: since c2hs we are using `setq-local` and nobody reported issues about it. This means people aren't using Emacs 23.2 or less.

**Comment by fice-t** [comment]
I happened to try the latest version out on 24.1 and it turns out Haskell Interactive mode doesn't work:
```
Haskell Debugger entered--Lisp error: (wrong-type-argument stringp #[257 "\300\301\302!\"\207" [cl-find-if #[257 "\304\305\306\307
	#,\207" [start string regexp inhibit-changing-match-data ".\\.cabal\\'" nil t string-match] 5 "
```
I'd imagine being backwards compatible for a 3 year old version is good enough.

**Comment by gracjan** [comment]
@fice-t: This particular error might be there because your Emacs 24.1 used compiled versions of elc from Emacs 24.3.

**Comment by fice-t** [comment]
I don't believe so; I sandboxed the 24.1 version off. I found the .elc file responsible `haskell-customize.elc` and indeed it says `;;; in Emacs version 24.1.1`.
Does it work on your copy of 24.1?

**Comment by gracjan** [comment]
Okay, @fice-t, can you alter those places where we say we are Emacs 24 or 24.1 compatible and put 24.3 in there? Thanks.

**Comment by fice-t** [comment]
I could do that later. Should there be a new corresponding stable release with this?

**Comment by fice-t** [comment]
Couple questions:

1. Should `haskell-mode` error when on 24.1 and 24.2? Or perhaps just give a warning for those two versions as some parts work?

2. Should the `cl-lib` in the `tests/compat` directory be removed?

**Comment by fice-t** [comment]
@gracjan The work is basically done -- just need confirmation on the above.

**Comment by gracjan** [comment]
1. Error.
2. Remove `cl-lib`.

Rationale about 1: we either support things or we don't. If somebody wants to use haskell-mode with old versions they can always use one of old versions of haskell-mode.
