### ISSUE TITLE
haskell-mode-contextual-space binding on the wiki is preventing space insertion

### ISSUE THREAD

**Issue by mmaz** [haskell/haskell-mode#1222]
Hi, I upgraded haskell-mode today (this was my output from Cask):

```
haskell-mode 20160211.110 -> 20160315.1454
```
My `init.el` includes [the wiki settings](https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-Setup). After upgrading I tried to edit the following line in a `diagrams` file:

`hsep 0.1 (...)`

and I wanted to make the following modification:

`vsep 0.1 [hsep 0.1 ..., ...]`

but when I moved my cursor to the beginning of `hsep` and began typing:

```
vsep|hsep 0.1
    ^
```

I then found myself unable to press SPC to insert a space after `vsep`:

``` 
command-execute: Symbol's function definition is void: haskell-mode-contextual-space
```

Was `haskell-mode-contextual-space` removed from master? Removing the following in my `init.el` fixed the issue for me:
`;;(define-key haskell-mode-map (kbd "SPC") 'haskell-mode-contextual-space)`

Thanks!

**Comment by geraldus** [comment]
Hi @mmaz ,  yes it was removed in #1191 . Initially I tended to deprecate this function, but then we decided to remove this silently.  Please tell us does these changes broken your workflow?  Was `haskell-mode-contextual-space` really useful for you?

**Comment by geraldus** [comment]
Sorry for confusion, I've removed `haskell-mode-contextual-space` from manual, but did not noticed that we have it in Wiki too, GitHub search do not shows me wiki pages.

**Comment by geraldus** [comment]
@gracjan how we can make wiki to be consistent with manual in automatically?

**Comment by mmaz** [comment]
@geraldus Thanks for the response - the change won't break my workflow. I haven't personally used `haskell-mode-contextual-space` for anything; I only copied + pasted the binding in my `init.el` config from the wiki long ago when I first configured `haskell-mode`

**Comment by geraldus** [comment]
Thank you for feedback.  I've removed this from Wiki.

**Comment by nrolland** [comment]
Is there a way to display a deprecation warning when this happens ? got stung with this

**Comment by gracjan** [comment]
We try to get under control what is public and what is private interface. Currently this is very loosely defined, hence issues like this. Sorry about that, we try to get better.

**Comment by nrolland** [comment]
that's ok, dont be sorry it's not really a pb. but it can be surprising when it breaks down. maybe leaving the symbol there and output a message is possible..

**Comment by gracjan** [comment]
Usually we do what you say.
