### ISSUE TITLE
Define `haskell-project.el`

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1229]
I sense the need to define what a Haskell project is. Currently we have at least three different competing definitions:

1. A bunch of source files that are rooted in the same directory. This is discovered by counting number of dots in `module A.B.C where`.
2. A cabal project discovered by finding nearest `.cabal` file by going up the directory hierarchy. Then `.cabal` is parsed and some things are taken into account, other are not.
3. A stack project discovered by finding nearest `stack.yml` file by going up the directory hierarchy. We generally do not do much about this yet.

All of this is a lot of guessing without much thought put into it. Note that complexity increases very fast while going down the list. For example cabal project can have different targets and different flags. It requires dependency install and configure step. A stack is even more complex as a stack project may be an umbrella for multiple cabal projects or a stack project may stand on its own without cabal at all.

Overall the situation is messy. History adds additional problems because Haskell programmers are used to opening a Haskell source file and expect that all will be magically inferred from there. With the current situation this creates a lot of sorrow and disappointment.

Tasks:

1. Create a workable definition of a project that has certain properties like a root directory.
2. Define what types of projects we support.
3. Define what properties each type of project needs to operate.
4. Make different parts of `haskell-mode` use these properties.

Note that quite some of this work is already done in `haskell-interactive-mode`, hopefully `haskell-project.el` will end up being a refactoring and extraction from `haskell-interactive-mode.el`, `haskell-cabal.el` and `haskell-mode.el`.

**Comment by gracjan** [comment]
There is a thing called [`projectile`](https://github.com/bbatsov/projectile). It defines a project as a directory with a special file, like `.git` or `.projectile`. It can find project root itself.

We could make `haskell-project` depend on `projectile` or optionally depend. And it already has a bit of Haskell support: https://github.com/bbatsov/projectile/blob/master/projectile.el#L282

**Comment by gracjan** [comment]
Projectile has `projectile-project-compilation-cmd` and `projectile-project-run-cmd` bound to nice keys. `haskell-mode` could automatically provide those depending on selected project type `stack` vs `cabal` vs `ghci`.

**Comment by ivan-m** [comment]
> a stack project may stand on its own without cabal at all.

I thought a Stack-based project still needed `.cabal` files, with the `stack.yml` file just providing some extra metadata regarding dependency versions.  Or do you mean it doesn't need cabal-the-executable?

**Comment by gracjan** [comment]
I mean they are working on stack that does not require cabal at all.

**Comment by gracjan** [comment]
It seems it is good enough to identify a project by its root directory.

Each source code file could implicitly belong to an open project based on relative paths. If a source file is outside of any open projects then there is a need to open a project.

New project needs its root dir, everything else can be initialized from defaults. If there is a need to change there should be a way to edit project settings. Looks like a pretty big edit view.

There is `.dir-locals.el` file that can have its variables.
