### ISSUE TITLE
Don't ask to 'create new project' with the same name

### ISSUE THREAD

**Issue by lightquake** [haskell/haskell-mode#124]
I keep getting prompted to create a new project or load an existing one for each file in my project, since it doesn't 'guess' that it should just use the existing one with the same name.

**Comment by jaseemabid** [comment]
Haskell mode is asking too many questions before it starts a repl. The project does have a .cabal file. I'm using the `haskell-process-load-file` function bound to C-c C-l to start the repl. 

1. It asks for project name
2. Cabal directory
3. Build target 
4. Current directory

How do I configure haskell mode to ask no questions at all ? 

    GNU Emacs 25.0.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2015-05-19 on lcy01-07
    haskell-mode version 13.15-git (/home/j/.emacs.d/elpa/haskell-mode-20150729.316/)
