### ISSUE TITLE
Error message when hitting space bar

### ISSUE THREAD

**Issue by cokleisli** [haskell/haskell-mode#1242]
I'm running GNU Emacs version 24.5.1 and the following version of haskell-mode:

`haskell-mode       20160330.629  installed             A Haskell editing mode`

I'm getting the following error when hitting the space bar in the editor:

Symbol's function definition is void: haskell-mode-contextual-space

**Comment by fosskers** [comment]
They removed that function, see #1182 .

The error goes away if you remove the binding to `SPC` in your `.emacs`.

**Comment by cokleisli** [comment]
Cool - I removed it from my `.emacs` - all is good again. Cheers.

**Comment by fosskers** [comment]
Mind you, pressing `SPC` after `import` no longer opens up the import completor. That completion hasn't worked for me for a while, so I guess there's no harm done. Do you know a good alternative for import completion?

**Comment by geraldus** [comment]
@fosskers you don't use interactive Haskell mode, do you?

**Comment by fosskers** [comment]
As far as I know I do. My emacs bottom bar says `(Haskell Interactive FlyC Helm)`, and I have `(add-hook 'haskell-mode-hook 'interactive-haskell-mode)` in my `.emacs`.

**Comment by geraldus** [comment]
In this case if you will load your file into REPL <kbd>C-c C-l</kbd> Emacs will be able to autocomplete module name.  This is not the same as contextual menu, but very close to that.  I'm using company mode for completion and have stylish haskell enabled, I type `import ` then company mode helps me with module names and finally stylish haskell aligns them.

**Comment by fosskers** [comment]
No, it doesn't do that anymore, even with a REPL open in emacs (that is my usual workflow). Maybe I'll try company.

**Comment by fosskers** [comment]
...my god, it's amazing. How haven't I been using this the whole time?

**Comment by gracjan** [comment]
Hmm, it is even documented with beautiful animated gifs: http://haskell.github.io/haskell-mode/manual/latest/Editing-Haskell-Code.html#Completion-support
