### ISSUE TITLE
Remove usage of (require 'cl)

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1246]
Supposedly `cl-lib` is the way to go, so change those:

```
$ grep -Hn "require 'cl)" *.el
haskell-cabal.el:37:;;   (with-no-warnings (require 'cl))
haskell-doc.el:303:(eval-when-compile (require 'cl))
```

**Comment by fice-t** [comment]
From what I can tell, the only `cl` function used in `haskell-doc` is `lexical-let`, which when using lexical binding is useless.

**Comment by gracjan** [comment]
@fice-t: Can you fix those two places?
