### ISSUE TITLE
Highlighting of data types is broken

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1249]
Now it somehow uses `font-lock-function-name-face` or something visually similar instead of `font-lock-type-face`.

**Comment by mrkkrp** [comment]
Now highlighting does not quite work and indentation is still not working for me (even that bare minimum that used to work). I'm beginning to think that `haskell-mode` is just getting worse and worse. Perhaps soon it will be completely unusable. You publish monthly reports with some words in them, but I'm not going to be excited about that when most basic functionality suffers such degradation. Can you at least perform some *manual* testing before pushing?

----

I hate to be negative, but the dynamic of `haskell-mode` development scares me.

**Comment by mrkkrp** [comment]
![shit0](https://cloud.githubusercontent.com/assets/8165792/14277760/db98a1f4-fb4e-11e5-8eb8-14a54633ef9d.png)

↑ Here, every capitalized word should be orange, now they are highlighted seemingly randomly. Can we have proper highlighting back?

**Comment by geraldus** [comment]
I think that idea (to distinguish module names, type constructors, value constructors, and _maybe_ class names from each other) is good and reasonable itself.

**Comment by mrkkrp** [comment]
Well, *maybe*. But now we've got a lot of *different* things that are colored the same way (identifiers and type-level things for example). I find this harder to read.

**Comment by geraldus** [comment]
I agree the algorithm should be fixed.  Coloured code is a matter of choice, there are people who find monochrome code is much readable.

**Comment by gracjan** [comment]
Types are colored using `haskell-type-face`. Place change it to the color of your liking.

**Comment by mrkkrp** [comment]
Why not use standard `font-lock` collection of faces that are defined in all color themes nicely? Do you expect me to tune this stuff myself? I set up a theme and then open a Haskell source and it should look OK, just like in every other mode (what a nightmare would it be if every major mode used its own collection of faces when there is a conventional set of `font-lock-` ones?). No? Quasi-quotes also look strange (not highlighted at all, it seems).

No issue that I reported here has been fixed properly and note that all this stuff generally worked well in the past. Maybe we didn't have indentation enabled out-of-box, but it worked much better in simplest cases. Now it does not work and I'm doing all indentation manually or with special editing commands I wrote myself. In addition to this, you say I'm going to have troubles and custom arrangements even with basic highlighting?

**Comment by mrkkrp** [comment]
![shit2](https://cloud.githubusercontent.com/assets/8165792/14281316/8993a598-fb62-11e5-9c52-c19f9081fd4e.png)

↑ I'm just trying to understand how to work with this without feeling like I'm messing with something absolutely broken.

**Comment by ivan-m** [comment]
I think QuasiQuotes are done by trying to font-lock according to a mode by assuming that the quasiquoter used is the same as the name of a mode.  I think if a mode isn't found though that it should just default to being the same as a String.

**Comment by gracjan** [comment]
@mrkkrp: I see only three issues reported by you and not closed #870, #1180 and this one.

QuasiQuotes are colorized like the respective mode. There is a bug when colorization gets in the way, it is tracked by tests case here: https://github.com/haskell/haskell-mode/blob/master/tests/haskell-font-lock-tests.el#L378

`haskell-type-face` has wrong default `font-lock-function-name-face`, should be `font-lock-type-face` and I suppose this is the real bug you are talking about here.

Please discuss indentation in #1178.

**Comment by mrkkrp** [comment]
“QuasiQuotes are colorized like the respective mode” — cool, but I've got a mode for hamlet templates and it doesn't seem to work here.

**Comment by gracjan** [comment]
How is it called?

**Comment by mrkkrp** [comment]
I'm using this: https://github.com/CodyReichert/shakespeare-mode, is there another one?

**Comment by gracjan** [comment]
Can you add it in `haskell-font-lock-quasi-quote-modes` in place of `("shamlet" . xml-mode)` so basically `("shamlet" . shakespeare-mode)` and see if this is any good? If it is we will change the default.

**Comment by mrkkrp** [comment]
Tried pushing `("shamlet" . shakespeare-mode)` as well as `("shamlet" . shakespeare-hamlet-mode)`. Something is different in every case but I cannot say that proper highlighting from that mode is applied.
