### ISSUE TITLE
Indentation (and newline-and-indent) super slow

### ISSUE THREAD

**Issue by benma** [haskell/haskell-mode#125]
Hi there

I have a major issue with indentation in this mode. For any medium-sized code file, hitting [TAB] or [RET] takes a second or even more to complete, which unfortunately makes this feature completely useless. I revert to manually indent because it takes too long to cycle the indentations to pick the correct one.

What could be going wrong? I ran the latest haskell-mode with no other packages interfering.

Thanks!

**Comment by gracjan** [comment]
We have just merged new, improved version of `haskell-indentation` that hopefully is faster in cases like this one. Therefore I'm closing this issue.

Should you experience problems with new `haskell-indentation` do not hessitate to open new issues.
