### ISSUE TITLE
Regression: dots (functional composition) are not highlighted as operators anymore

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1255]
Here we go:

![bad-dot](https://cloud.githubusercontent.com/assets/8165792/14290078/d3787fa6-fb87-11e5-9a2f-e8adee9887ce.png)

**Comment by geraldus** [comment]
Hmm... I have not seen before that composition was highlighted properly.  If I'm not mistaken there is related issue already.

**Comment by gracjan** [comment]
Good catch...

**Comment by mrkkrp** [comment]
@geraldus, I'm quite sure that they were highlighted correctly in the past. I remember seeing little blue dots all the day…
