### ISSUE TITLE
Auto add packages to cabal deps omits comma in some cases

### ISSUE THREAD

**Issue by shanemikel** [haskell/haskell-mode#1257]
When adding dependencies, I've noticed that if I have
`build-depends: something`
and haskell-mode tries to add `something-else`, I get
```
build-depends: something 
                something-else
```
but, if there is   
```
build-depends: something
            , something-else
```

and haskell-mode wants to add another, it properly inserts the comma

**Comment by geraldus** [comment]
Good catch

**Comment by gracjan** [comment]
@shanemikel: Can you add a unit test in our test suite?
