### ISSUE TITLE
Debugging the system (haskell tooling) environment

### ISSUE THREAD

**Issue by shanemikel** [haskell/haskell-mode#1258]
I'm using stack-ghci as my haskell-processtype.  Is there a way, as with ghc-debug in ghc.el, to see what paths haskell-mode is using for the haskell-process?

**Comment by geraldus** [comment]
Try to look at `*Haskell Process Log*` buffer.  I believe there you can find executed command .

**Comment by shanemikel** [comment]
I see the commands that are executed in the repl itself, but not the command to start it.

**Comment by geraldus** [comment]
Indeed, there is no path in log.

**Comment by shanemikel** [comment]
I brought this up, because it's pretty hard at the moment to get the environment quite right (for any haskell development tool-stack).  Disclaimer:  There may be certain issues here that, as a user here, I can safely ignore, but I've mentioned them all, because there's no mention of that in the documentation.

Some users might use a combination of cabal projects and stack/cabal projects...
When I recently started to use haskell-mode, I intended to use ghc-mod, but I was confused about whether or not this project relies on the ghc-mod emacs scripts, and if it does, how the versions of the ghc-mod emacs scripts are tied to ghc-mod versions.  This was frustrating enough I just started using interactive mode.

Something to confuse the matter even more, for ghc-mod there's the question of whether to install it in your project sandboxes, or once on your PATH.  There's a stack issue that hopes to reconcile the feature of enabling multiple ghc versions with tools like ghc-mod, that don't really require being built and installed for each project, but only for each compiler version.
commercialhaskell/stack#1796

Ideally, these hurdles wouldn't amount to the cartesian product of the set of haskell users and the set of haskell emacs plugins.  Is this something I should expect to be solved once-and-for-all by stack-ide?

**Comment by gracjan** [comment]
Yes, I confirm that the situation is horrible. We are working to untangle this mess on our end, ghc-mod is also progressing and then there is haskell-ide-engine. Hopefully we can get to a state where things aren't that confusing as they are now.

Any help appreciated. I think the immediate low hanging fruit is to improve logging and error handling in all the cases so that there is at least user is informed if and why something does not work.

The next step is to define concept of a 'project'.

Any help appreciated.

**Comment by gracjan** [comment]
`*haskell-process-log*` has these lines:

```
("Starting inferior GHCi process ghci ..." "haskell" nil "ghci" "-ferror-spans")
("Starting inferior GHCi process ghcix ..." "haskell" nil "ghcix" "-ferror-spans")
```

This should be enough to debug issues with `haskell-interactive-mode`.
