### ISSUE TITLE
Break point highlighting

### ISSUE THREAD

**Issue by ExternalReality** [haskell/haskell-mode#127]
This is more of a feature request than an issue. If this is not the place to put feature requests than please refer me to that place where I can.

As a user, when I use the GHCi debugger in haskell-mode and I add a break point I would like haskell-mode to jump to and highlight the break point when the debugger stops at that break point in any open buffer that contains the relevant source.

**Comment by gracjan** [comment]
@ExternalReality: Hej, good idea!

I think we will need help from to get this implemented. For example can you please research how can emacs know on which line in source code did the debugger hit a breakpoint?

**Comment by gracjan** [comment]
There does not seem to be enough interest in pushing this forward. Let HIE save us here.
