### ISSUE TITLE
Focus issues when ghc process dies

### ISSUE THREAD

**Issue by anakreontas** [haskell/haskell-mode#1272]
When ghc process dies mode line queries if it should restart the process. The focus however is not on mode line. If I try to switch to another window ,C x - o, the query in mode line interferes but still it does not get focus and I can't answer if it should restart the process. There is also a message error:
Error running timer `haskell-doc-mode-print-current-symbol-info': (wrong-type-argument stringp nil)

How to reproduce:
1. Open a haskell file and load it into ghci
2. Open a terminal and kill ghc (killall -9 ghc)
3. Switch to emacs and try to move to another line or window (C n, C x - o)

**Comment by geraldus** [comment]
If I'm not mistaken, you do not need to change buffer, when you see prompt just press <kbd>y</kbd> (or other suggested key).  Personally I dislike the way Haskell mode prompts user currently, this is not obvious that you can answer without focus on mini-buffer and I always miss such prompts, changing buffer or pressing other keys canceling prompt.  Overall this is not very user friendly.

**Comment by anakreontas** [comment]
Thanks, didn't know that

**Comment by gracjan** [comment]
Reference #1170 which is supposed to get rid of the prompts and have better usability. When somebody finds time to implement those...
