### ISSUE TITLE
Fix indentation in haskell-interactive-mode-multi-line

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1278]
There is this magic: https://github.com/haskell/haskell-mode/blob/be9044b2e633b9342a68f762d07e82fe9ababf5f/haskell-interactive-mode.el#L254

This means that by using <kbd>C-j</kbd> one can have multiline command like this:

```
λ> let x = 1
       y = 3
```

it will be wrapped in `:{` and `}:` and send to GHCi like this:

```
:{
let x = 1
       y = 3
:}
```

Note that this is not documented and does not really work due to misaligned indentation.

Tasks:

- [ ] make it respect indentation
- [ ] document that by using <kbd>C-j</kbd> one can get multilne working

**Comment by geraldus** [comment]
It looks like inconsistency to me.

**Comment by gracjan** [comment]
Is this really fixed by #1341?

**Comment by fice-t** [comment]
Do you have an example that doesn't work? It works for me.

**Comment by gracjan** [comment]
Are we talking about the same functionality?

**Comment by fice-t** [comment]
Isn't this about properly wrapping an expression in `:{` and `:}`? That's part of the PR. So the example

```
λ> let x = 1
       y = 3
```
Should work now.
