### ISSUE TITLE
Add a non-package install instructions

### ISSUE THREAD

**Issue by rusimody** [haskell/haskell-mode#1280]
ATM when I try package-install haskell-mode it finds no such;  only finds haskell-emacs

Packages in emacs are sufficiently broken for enough people
Please put the 'old-fashioned' or manual procedure also.

IOW something of the form
1. Put this in load-path
2. Put this in your init
3. You will need this set <... > of packages pre-installed

Update: Install via git worked

**Comment by gracjan** [comment]
We aren't able to maintain and take responsibility for many ways of installing. Melpa and git is enough.
