### ISSUE TITLE
What's the difference between `inf-haskell` and `interactive-haskell`?

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1284]
The difference is completely unclear to me and anybody else.

If there were deficiencies (which?) in `inf-haskell` why weren't those fixed and completely new mode was created?

Is there a way to converge them?

**Comment by gracjan** [comment]
There is intero now, hopefully it will subsume all other options.

**Comment by alanz** [comment]
The main thing about `inf-haskell` is it gives you an inferior ghci session, similar to a standard ghci session, whereas `interactive-haskell` does all sorts of other weird stuff, and obscures the ghci session

**Comment by geraldus** [comment]
> and obscures the ghci session

Well, I use interactive REPL some times ;D

**Comment by alanz** [comment]
That was just my view. I know `inf-haskell-mode`, and ghci. I tried the other once or twice but never took the time to learn it, and got frustrated each time.

**Comment by gracjan** [comment]
It is a shame that we do not have a single well working interactive mode, having more than one confuses everybody, mostly newcomers.

**Comment by geraldus** [comment]
@gracjan we need re-engineer some parts of Haskell mode in terms of Emacs' minor and major modes I suppose.  For example, interactive mode could be a minor mode, which have a session attached to it (or two, one for internal jobs and other for direct user interaction).  So it will be possible to have a set of commands which works nice in static mode and if minor interactive mode is enabled use it.

Sadly, I have no time now.
