### ISSUE TITLE
Syntax highlighting in SQL quasi-quoter is broken

### ISSUE THREAD

**Issue by bgamari** [haskell/haskell-mode#1289]
Consider this program,
```
sql = [sql| SELECT f1, f2 FROM aTable |]
xml = [xml| <html><body id="hi">hello</body></html> |]
```
I have ` ("sql" . sql-mode))` in `haskell-font-lock-quasi-quote-modes` yet the body of the quoter gets no syntax highlighting whatsoever. If I past the body into a new buffer and enter `sql-mode` manually it is highlighted as one would expect, so presumably it works as expected. The `xml` quote is also highlighted as one would expect, so quasi-quoting highlighting isn't generally broken. It seems to be particular to SQL.

**Comment by bgamari** [comment]
It seems that `javascript-mode` may be affected as well.

**Comment by gracjan** [comment]
Can you run `make check` and see if it goes through? We have a test for `sql-mode` so it should fail if there is something wrong.

**Comment by bgamari** [comment]
Indeed updating `emacs` seemed to help.
