### ISSUE TITLE
font-lock for certain list comprehensions is broken

### ISSUE THREAD

**Issue by purcell** [haskell/haskell-mode#1292]
The following is wrongly interpreted as a quasi-quote:

```haskell
module Foo where
process = [k|(k,v) <- M.toAscList counts, odd v]
```
whereas this is fine:
```haskell
module Foo where
process = [k |(k,v) <- M.toAscList counts, odd v]
```
(note the space before the `|`)

![screen shot 2016-04-17 at 22 38 21](https://cloud.githubusercontent.com/assets/5636/14586470/210d04ee-04ed-11e6-8faa-94ca893a1421.PNG)

**Comment by geraldus** [comment]
@purcell hi Steve!  This is a known issue, please see details here #1185.

**Comment by gracjan** [comment]
@purcell: If you have better idea than the one given by bgamari  in https://github.com/haskell/haskell-mode/issues/1185#issuecomment-192706169 then we can try to implement it.

**Comment by purcell** [comment]
Cool, I'll close this as a duplicate -- sorry for the noise.
