### ISSUE TITLE
REPL can't find test suite

### ISSUE THREAD

**Issue by fosskers** [haskell/haskell-mode#1295]
I'm having some fairly consistent trouble with `haskell-session-change-target`. Given a test suite as defined:

```
test-suite aur-test
  type:                exitcode-stdio-1.0

  build-depends:       aur
                     , base >=4.8 && <4.9
                     , tasty >= 0.11 && < 0.12
                     , tasty-hunit >= 0.9.2 && < 0.10

  hs-source-dirs:      tests
  main-is:             Test.hs
  default-language:    Haskell2010
```

Even after using `haskell-session-change-target` and reloading, the process dies claiming:

```
The following target packages were not found: aur-test
```

Note that `stack` has no trouble running these tests from the command line. Thoughts?

**Comment by sheyll** [comment]
I have the same issue

**Comment by ivan-m** [comment]
Yes, that's how stack wants it, whereas using cabal-install you don't need the prefix.
