### ISSUE TITLE
`stack ghci` invokes all subprojects listed in `stack.yaml`

### ISSUE THREAD

**Issue by fosskers** [haskell/haskell-mode#1296]
I discovered this when attempting to `haskell-process-load-file` (C-c C-l) in a subproject. My project has a single `stack.yaml` at top-level, with three subprojects, all with their own `.cabal`. Now, in one of those `.cabal` I defined `default-extensions: NoImplicitPrelude` for convenience. To my surprise, when I tried to `C-c C-l` in one of the other subprojects, the compiler complained of missing symbols, as if `NoImplicitPrelude` were defined there as well.

Checking the `*haskell-process-log*`, I found:

```
("Starting inferior stack GHCi process using stack" "aur" nil "stack" "ghci" "--ghc-options=-ferror-spans")
...
There are issues with this project which may prevent GHCi from working properly.

   -XNoImplicitPrelude will be used, but GHCi will likely fail to build things which depend on the implicit prelude.

   It is specified for:

       aura:exe:aura

   But not for: 

       arel:exe:arel aur:lib
...
```

which is what one sees when they invoke `stack ghci` manually from the command line in such a project. However, `haskell-mode` goes on to just load _all_ the subprojects and their settings, even though I intended to only be working with one of them:

```
Configuring GHCi with the following packages: arel, aur, aura
```

Note that none of this happens on the command line if you are explicit about the subproject from the get-go: `stack ghci aur`.

This tells me that `haskell-mode` isn't invoking `stack ghci` correctly.

**Comment by gracjan** [comment]
`haskell-mode` runs `ghci` as:

    stack ghci

you seem to want:

    stack ghci aur

**Comment by fosskers** [comment]
Precisely. If run as `stack ghci <name-of-subproject-here>` we would avoid the settings-pollution bug that we're seeing.

The `name-of-subproject` should be an available symbol at `ghci` invocation time, as the REPL buffer's name is always that of the subproject.

**Comment by mgsloan** [comment]
`stack ghci` takes all the same target syntax as `stack build`, including directories (all packages contained in the dir are built).  So, you could also do `stack ghci path/to/my-pkg/`.  This will likely be easier, if haskell-mode knows the cabal file associated with the hs file you're starting ghci for

**Comment by fosskers** [comment]
`haskell-mode` does know the local cabal file, as well as the top-level stack file. Since I have:

```
packages:
  - aura/
  - aur/
  - arel/
```
listed in my `stack.yaml`, it shouldn't have trouble finding only the subproject I'm trying to invoke the REPL for.

**Comment by mgsloan** [comment]
Right, the issue is that `haskell-mode` probably won't know the cabal package name.  It will know its directory, though.

**Comment by fosskers** [comment]
I think it does know the cabal package name. Anecdote tells me at much, at least.
