### ISSUE TITLE
Flymake produce temp file without cleaning it up

### ISSUE THREAD

**Issue by ArthurTu** [haskell/haskell-mode#130]
If I edit a file named a.hs, it takes a long time to start haskell mode. And a file named a_flymake.hs is created on that directory without asking me. It stands there even after i closed a.hs.

I do not have ghc installed in my host os. So haskell-program-name is not set in my .emacs. Check if this is related to the bug. 

However, i want to use emacs to edit haskell files with hilight and indent features. 

I think codes about flymake should be written into a function instead of being a default feature. If somebody want to enable it, just that to the haskell-mode-hook.

I have to dive into haskell-mode.el and comment the last few lines to disable flymake. That is embarrassing and dirty.

**Comment by gracjan** [comment]
Lets agree to use `flycheck` instead of `flymake`, `flycheck` is better at handling temporary files.

**Comment by terlar** [comment]
Perhaps this could be revisited with the new and improved flymake version.

**Comment by carlosdagos** [comment]
As far as I can see, `flycheck` never made it? `:(`

**Comment by codygman** [comment]
I don't think it did @carlosdagos, but it seems the temp file junk endlessly created by default is [fixed by this code](https://github.com/haskell/haskell-mode/blob/bbdbc0e9231f49a45ce787ebfb3f2b019615bf61/haskell-mode.el#L1053).
