### ISSUE TITLE
stack: no such file

### ISSUE THREAD

**Issue by julien-truffaut** [haskell/haskell-mode#1300]
Hi, I am trying to use haskell-mode with stack but I am getting the following error when I run `M-x haskell-process-load-file`: Searching for program: no such file or directory, stack

I have the following config:
```
(req-package haskell-mode
  :config (progn
    (define-key haskell-mode-map (kbd "C-c C-l") 'haskell-process-load-file)
    (add-hook 'haskell-mode-hook 'haskell-doc-mode)
    (add-hook 'haskell-mode-hook 'haskell-indentation-mode)
    (add-hook 'haskell-mode-hook 'interactive-haskell-mode)
    (add-hook 'haskell-mode-hook 'haskell-decl-scan-mode)
    (add-hook 'haskell-mode-hook (lambda ()
				   (electric-indent-local-mode -1)))
    (setq haskell-process-type 'stack-ghci)
    (setq haskell-process-path-ghci "stack")
    (setq haskell-process-args-ghci '("ghci"))

    (setq haskell-process-suggest-remove-import-lines t)
    (setq haskell-process-auto-import-loaded-modules t)
    (setq haskell-process-log nil)
    (setq haskell-stylish-on-save t)))
```

I have `stack` on my path and I was using spacemacs previously which could find `stack ghci`.

**Comment by gracjan** [comment]
https://github.com/haskell/haskell-mode/wiki/PATH

**Comment by julien-truffaut** [comment]
Thanks for the link, I added `/usr/local/bin` where is `stack` but I still get the same error.

For reference:
```
(getenv "PATH") ==> "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

which stack  ==> /usr/local/bin/stack
```

**Comment by fice-t** [comment]
Can you get a backtrace? Set `debug-on-error` and try the command again.

**Comment by syohex** [comment]
You need to set not only `PATH` environment variable but also `exec-path` variable.
And please check `M-: (executable-find "stack")` too.

See also
- http://ergoemacs.org/emacs/emacs_env_var_paths.html
- https://www.emacswiki.org/emacs/ExecPath

**Comment by julien-truffaut** [comment]
Thanks! It worked once I added it to `exec-path`.
