### ISSUE TITLE
pop-tag-mark doesn't return if haskell-mode-find-def succeeds

### ISSUE THREAD

**Issue by henrylaxen** [haskell/haskell-mode#1311]
When I am in haskell-mode, and type M-. to find the source of the definition under point, and the definition under point is in a different file, I get the following error message in the \*Messages\* buffer:

error: "Marker points into wrong buffer", #\<marker at 15335 in Snaplet.hs\<Games>>

```
(defun haskell-mode-jump-to-def-or-tag (&optional _next-p)
  ;; FIXME NEXT-P arg is not used
  "Jump to the definition.
Jump to definition of identifier at point by consulting GHCi, or
tag table as fallback.

Remember: If GHCi is busy doing something, this will delay, but
it will always be accurate, in contrast to tags, which always
work but are not always accurate.
If the definition or tag is found, the location from which you jumped
will be pushed onto `xref--marker-ring', so you can return to that
position with `xref-pop-marker-stack'."
  (interactive "P")
  (let ((initial-loc (point-marker))
        (loc (haskell-mode-find-def (haskell-ident-at-point))))
    (if loc
        (haskell-mode-handle-generic-loc loc)
      (call-interactively 'haskell-mode-tag-find))
    (unless (equal initial-loc (point-marker))
      (save-excursion
        (goto-char initial-loc)
        (xref-push-marker-stack)))))

```

This behaviour does NOT occur if haskell-mode-find-def fails and haskell-mode-tag-find is called and succeeds.  I instrumented haskell-mode-jump-to-def-or-tag and found that the error happens at the (goto-char initial-loc) line in the code, hence the (xref-push-marker-stack) line isn't executed.  However if haskell-mode-tag-find succeeds, the the previous location is indeed pushed (inside of haskell-mode-tag-find somewhere) so M-* (pop-tag-mark) works correctly.  I hope this is helpful.
Best wishes,
Henry Laxen

**Comment by fice-t** [comment]
There should be a `(set-buffer (marker-buffer initial-loc))` above the `goto-char`.

@gracjan 25.1's `xref-push-marker-stack` allows for an optional marker argument which would mean there's no need for the `save-excursion` + `goto-char`:
```elisp
(defun xref-push-marker-stack (&optional m)
  "Add point M (defaults to `point-marker') to the marker stack."
  (ring-insert xref--marker-ring (or m (point-marker))))
```

Also, if `haskell-mode-tag-find` already pushes a marker, then should the `unless` block run after it?

**Comment by gracjan** [comment]
There was something fishy with `xref-push-marker-stack` in Emacs 25-snapshot, that is was it looks so strange.

Yes, it should be fixed.

**Comment by fice-t** [comment]
@henrylaxen Should be fixed now. Please report back if something's still wrong.

**Comment by gracjan** [comment]
@fice-t, we will fix it again if this happens. Would be great to have a test case for this.
