### ISSUE TITLE
Pattern synonyms are highlighted as definitions

### ISSUE THREAD

**Issue by taktoa** [haskell/haskell-mode#1313]
It seems to me that every instance of the token `pattern` in the attached code sample should be highlighted with the keyword face (i.e.: the same face as `module`, `class`, `where`, etc.).

The main objection to this kind of fix is that people could want to name a function `pattern` when the extension is disabled. However, the `proc` keyword has similar problems but is currently being syntax-highlighted regardless of the presence of the relevant language pragma. I guess `proc` *is* technically in the Haskell 2010 Report so it's Official Haskell whereas -XPatternSynonyms is merely GHC Haskell, but I think that doesn't hold much water given the popularity of GHC extensions.

```haskell
{-# LANGUAGE GADTs           #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE UnicodeSyntax   #-}
{-# LANGUAGE ViewPatterns    #-}

-- Pattern synonyms can be exported
module Main (pattern A1) where

data Foo = Foo
data Bar where Bar :: (Show a) => a -> Bar

-- Basic usage of unidirectional and bidirectional pattern synonyms
pattern A1 <- Foo
pattern A2 = Foo

-- Patterns can have type signatures
-- These type signatures have up to two contexts
-- (these are called CProv and CReq for proven and required constraints resp.)
pattern B1 :: (Show a) => (Show a) => a -> Bar
pattern B1 x <- Bar x
pattern B2 :: (Show a) => (Show a) => a -> Bar
pattern B2 x =  Bar x

-- If CProv is empty, it can be omitted.
pattern C1 :: (Show a) => a -> Bar
pattern C1 x <- Bar x
pattern C2 :: (Show a) => a -> Bar
pattern C2 x =  Bar x

-- If CProv is not empty but CReq is, it's denoted like so:
pattern D1 :: (Show a) => () => a -> Bar
pattern D1 x <- Bar x
pattern D2 :: (Show a) => () => a -> Bar
pattern D2 x =  Bar x

-- Explicitly-bidirectional pattern synonym
pattern Succ n <- (subtract 1 -> n) where Succ n = n + 1

-- With -XUnicodeSyntax, ← can be used for a unidirectional synonym definition
pattern Baz ← Foo

-- For comparison, a function definition:
foo :: Int -> Int
foo x = x + 5

main :: IO ()
main = return ()
```

**Comment by gracjan** [comment]
Although `proc` is a keyword everywhere (when enabled), `pattern` is a keyword only in some contexts. That mean `haskell-font-lock` would need to track the context to know if the `pattern` it is looking at is a keyword or is it a normal identifier.

We had similar issue with `family` but then the context for `family` is really easy: just the keyword before it. For `pattern` this is more complicated.

Anyway: the proper way to kick this is off is to write tests, so basically take your examples and turn them into ert tests in https://github.com/haskell/haskell-mode/blob/master/tests/haskell-font-lock-tests.el#L534.

Thanks.

**Comment by gracjan** [comment]
@taktoa: Can you create some tests that 1) use pattern in keyword position 2) use pattern in non-keyword position?

Mark them as failing with `:expected-result :failed` and then we will wait on somebody that will fix it.

**Comment by taktoa** [comment]
Sure, I'm dealing with final exams up until this coming Monday but after that I have two free weeks in which I can write some test cases. I'll reference this issue in the pull request.

**Comment by gracjan** [comment]
Great. Good luck on exams.

**Comment by gracjan** [comment]
@taktoa, how did the exems go?

**Comment by taktoa** [comment]
Oh, sorry, just noticed this. I am currently moderately busy, I may be able to get around to this soon but my "two free weeks" have been eaten up (unexpected family emergency) and I have an internship starting on Monday. Hopefully I can find some time to write a test case somewhere in there but I can't promise anything. Exams went pretty well though.

**Comment by taktoa** [comment]
I just remembered that I have a 12 hour train ride on Sunday, so I'll try to get it done then. I took a look at some of the existing test cases and it seems like it'll be fairly easy to write.
