### ISSUE TITLE
Emacs 25+, scan-sexp with standard syntax table causes infloop in syntax propertize

### ISSUE THREAD

**Issue by npostavs** [haskell/haskell-mode#1315]
This is a minimal example reduced from capitaomorte/yasnippet#687.

In a git checkout of lates `master` (5d583145736e9d4cf2a16613a4ae82009f3f791b) `emacs -Q -L . -l haskell-autoloads -l synprop-bug.el` causes an infinite loop. After hitting `C-g`, `*Messages*` contains `Error during redisplay: (internal--syntax-propertize 6) signaled (quit)`. `synprop-bug.el` contains:

```elisp
(switch-to-buffer "hh")
(haskell-mode)
(erase-buffer)
(insert "{-# foo #-}")
(with-syntax-table (standard-syntax-table)
  (scan-sexps 5 1))
```

This doesn't happen in Emacs 24.5, so it *may* be a bug in Emacs.

**Comment by gracjan** [comment]
Hmm, even if `haskell-propertize` would not hang I do not see it producing correct result when `syntax-table` is not the one it expects.

Then I do not see why yasnippets try to use different syntax table than is defined in the buffer. What is the point of messing with syntax table?

**Comment by npostavs** [comment]
Because it's parsing yasnippet syntax, which is independent of the major mode's syntax. So it looks like the question is why does yasnippet's temporary syntax-table manipulation affect the syntax propertize function in Emacs 25, but not earlier? I will open an Emacs bug.

**Comment by gracjan** [comment]
Great. Thanks.

**Comment by npostavs** [comment]
The conclusion from the Emacs bug discussion is that it's expected behaviour, I will fix this in yasnippet (capitaomorte/yasnippet#695)

**Comment by gracjan** [comment]
Good, thanks.
