### ISSUE TITLE
Unexpected character class of underscore

### ISSUE THREAD

**Issue by tobiasBora** [haskell/haskell-mode#1318]
Hello,

First thank you for your work. However I have a problem with the underscore: in (nearly) all major modes of emacs, '_' isn't seen as a classical letter. Like that when you have:

    my_variable_name

and when you do <code>M-x forward-word</code> or <code>M-x backward-kill-word</code>, you will jump/delete all the word. Usually in emacs mode when you do so you jump only "name". The above example should become:

     my_variable_

I tried to change the table like that:

    (modify-syntax-entry ?_ "-")

However this leads to another problem: Now in completion (<code>M-/</code>) <code>my_variable_name</code> is seen as three separate strings. So

    my_var

will expands into

    my_variable

instead of

    my_variable_name

In all emacs mode, <code>my_variable_name</code> is seen as a single string for expansion, but as separate words for moving/deleting, and I don't understand why haskell change this good practice.

Is there any reason to proceed like this ? Do you plan to come back to a more conventional approach ? If not, do you have solution for people like me that would like to keep the original behaviour ? 

Thank you,

TobiasBora.

**Comment by tobiasBora** [comment]
I found a workaround but it's not really practical:

    (add-hook 'haskell-mode-hook
          (lambda ()
	    (modify-syntax-entry ?_  "-" haskell-mode-syntax-table)
	    (setq dabbrev-abbrev-char-regexp "\\sw\\|\\s_")))

By the way if anyone knows how I could achieve to do Ctrl-Backspace with camelCase I'm interested in it.

**Comment by gracjan** [comment]
@tobiasBora: there you go, fixed.

**Comment by tobiasBora** [comment]
Thank you !

Le 14 mai 2016 08:42:11 GMT+02:00, Gracjan Polak <notifications@github.com> a écrit :
>@tobiasBora: there you go, fixed.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/haskell/haskell-mode/issues/1318#issuecomment-219204364

-- 
TobiasBora
