### ISSUE TITLE
What is the recommended way to unbind `;` in `haskell-indentation-mode-map`

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1320]
I have my own minor mode that binds `;`. `haskell-indentation` is very agressive in binding that key as well. I tried various methods, but only this allows to tame `;`:

```emacs-lisp
(defun mk-purge-that-nice-thing ()
  (define-key haskell-indentation-mode-map (kbd ";") nil))

(add-hook 'haskell-indentation-mode-hook #'mk-purge-that-nice-thing)
```

Variations like this do not work:

```
(eval-after-load 'haskell-mode
  '(setq-default haskell-indentation-mode-map (make-sparse-keymap)))
```

Is there some option to forbid `haskell-indentation-mode` bind anything?

**Comment by fice-t** [comment]
It's a bit surprising that just setting the map to nil or a blank keymap doesn't do what you want (though it makes sense). Even if it did, I think you'd have to `eval-after-load 'haskell-indentation` for it to work.

Try this:
 ```elisp
(with-eval-after-load 'haskell-indentation
  (setq minor-mode-map-alist (assq-delete-all 'haskell-indentation-mode minor-mode-map-alist)))
```

Just setting the variable to a blank keymap doesn't work at Emacs doesn't check that variable, but the keymap it usually points to (the one in that alist) for the keybindings.

**Comment by gracjan** [comment]
What is the problem with <kbd>;</kbd>?

**Comment by mrkkrp** [comment]
I bind it to other things.

**Comment by gracjan** [comment]
A semicolon? What other things? And how do you put a semicolon in?

**Comment by mrkkrp** [comment]
Do not underestimate weirdness of Emacs users :-D I use [Modalka](https://github.com/mrkkrp/modalka) for custom modal editing. When it's active, it binds <kbd>;</kbd>, it gets translated to <kbd>C-;</kbd>, which is in turn activates my custom function for correction of misspellings. Quite handy, especially on Dvorak keyboard where <kbd>;</kbd> does not occupy such prominent position on home row.

I know a person that uses QWERTY, and he binds <kbd>;</kbd> to work as <kbd>↵ Enter</kbd> if I remember correctly (makes sense, it's on home row). Emacs encourages this sort of thing, so I would be very careful binding things like <kbd>;</kbd>, unless it's custom non-editing environment like Magit or MU4E.

Binding <kbd>;</kbd> is not usually a problem because Modalka is a minor mode too and it usually takes precedence, but this time `haskell-indentation-mode` was very perisisent.

How do I put semicolon in? Well, when I need to *input* text, I switch off Modalka (in Vim terms go into insert mode) and I can type normally.

Furthermore, I use <kbd>Enter</kbd> to toggle the `modalka-mode` (instead of entering new line, I enter them as <kbd>RET m RET</kbd> typically), and I have a good number of keys in non-standard positions.

I can type all day long without even sign of strain in my hands or something. I think it's worth it.

**Comment by fice-t** [comment]
There's `minor-mode-overriding-map-alist` if you want your particular minor mode to override others. That and the above solution should work for everyone.

Though perhaps Haskell mode could put the indentation keybindings in `haskell-mode-map` instead of using minor modes? So instead of turning on/off individual keymaps it would modify the major mode map directly.

**Comment by gracjan** [comment]
@fice-t: Indentation keybindings stay in indentation.
