### ISSUE TITLE
haskell-interactive-mode uses a different syntax table 

### ISSUE THREAD

**Issue by fice-t** [haskell/haskell-mode#1323]
Currently `haskell-interactive-mode`'s syntax table is different than `haskell-mode`'s, which means that a lambda like this: `(\(a, b) -> a + b)` causes parentheses to be unbalanced as the `\(` escapes the open paren.

Should ``haskell-interactive-mode`` inherit the syntax table?

**Comment by gracjan** [comment]
`haskell-mode`'s syntax table works only paired up with `haskell-syntax-propertize` which is a complicated function. For example backslash is set to non-escaping but then it has to regain its escaping status when inside strings.

**Comment by fice-t** [comment]
> haskell-mode's syntax table works only paired up with haskell-syntax-propertize which is a complicated function.

Alright. There should be a subset of it that's suitable for the interactive mode, yes? For example:

```elisp
(mapc (lambda (x)
            (modify-syntax-entry x "." table))
          "!#$%&*+./:<=>?@^|~,;\\")
```
The above seems to work fine and solves the parenthesis problem.
> but then it has to regain its escaping status when inside strings.

What specifically does this do? Highlight the backslash?

**Comment by gracjan** [comment]
It makes string terminate properly:

    " \" "

the above would count of 1.5 strings as middle quote would not be escaped.

**Comment by fice-t** [comment]
Right, that makes sense.

Though in interactive mode, the strings aren't fontified (except for the output, which is unaffected), so I think the change would still be good for it.

**Comment by gracjan** [comment]
It will be less surprizing ot use same syntax table, so I've added this change.
