### ISSUE TITLE
haskell-doc messages obscured by "async" messages

### ISSUE THREAD

**Issue by swilde** [haskell/haskell-mode#1327]
With current haskell-mode the output of haskell-doc minor mode (as well as other output in the emacs echo area) is obscured by useless (at least to me) "async" messages when interactive-haskell-mode is started.  That is: the string "async" is printed to the echo area, thereby overwriting the actualy useful information ie. the output from doc mode...

To reproduce:
```
1. enable haskell-doc-mode
2. in any haskell file (with active haskell-mode) move the cursor on a known funtion (e.g. tail)
   → you should see the type of the function in the echo area (e.g. tail :: [a] -> [a])
3. now start interactive-haskell by C-c C-z
4. repeat step from 2.
   → this time the echo area shows "async" instead of the functions type
```

By bisecting I was able to track down the problem to commit 31426d720b2a40e607c6c95207b238af72158233 
reverting the changes made to haskell-doc.el there (that is: re-inserting the lexical-let) in the current master fixes the problem.  I currently don't see why, but maybe someone who understands the special magic taking place there can fix it without reintroducing the use of cl...

**Comment by swilde** [comment]
#1328 should do the trick, at least it fixes the issue for me.

**Comment by fice-t** [comment]
Crap, that was my bad. The issue isn't the lexical binding, but the return value of the function. It's just that I put the ending parenthesis in the wrong line which lead to the function returning the symbol `async` even when it's not async.
