### ISSUE TITLE
`haskell-guess-module-name` returns wrong results

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1338]
When package name starts with a capital letter maybe, for example if package name is `JuicyPixels-extra` then in module `Codec.Picture.Extra` it returns: `JuicyPixels-extra.Codec.Picture.Extra`. This is incorrect, the result should be `Codec.Picture.Extra`. I can reproduce this with [`JuicyPixels-repa`](https://github.com/TomMD/JuicyPixels-repa) (just clone the repo, go to src file and call `haskell-guess-module-name`) which follows the same naming scheme.

**Comment by gracjan** [comment]
Can you write a failing test case?

**Comment by fice-t** [comment]
Does the following work for you?

```elisp
(defun haskell-guess-module-name ()
  "Guess the current module name of the buffer."
  (interactive)
  (let* ((case-fold-search nil)
         (components (cl-loop for part
                              in (nreverse (split-string (file-name-sans-extension (buffer-file-name))
                                                         "/"))
                              while (string-match "^[[:upper:]][[:alpha:]]*$" part)
                              collect part)))
    (mapconcat #'identity (nreverse components) ".")))
```

**Comment by gracjan** [comment]
@fice-t, use regexps defined in `haskell-lexeme`.

**Comment by fice-t** [comment]
Makes sense. Though is `haskell-lexeme-modid` correct? As per the 2010 report:
`A module name (lexeme modid) is a sequence of one or more identifiers beginning with capital letters, separated by dots, with no intervening spaces.`

IIUC what is `haskell-lexeme-modid` should be `haskell-lexeme-codid` and the modid should be:
`modid 	→ 	{conid .} conid ` (also from 2010 report)

**Comment by gracjan** [comment]
@fice-t you are right that the name is wrong, what report calls modid is called haskell-lexeme-modid-opt-prefix in haskell-lexeme. Need cleanup there.
