### ISSUE TITLE
Consider bringing back "show indentation" feature

### ISSUE THREAD

**Issue by yupferris** [haskell/haskell-mode#1340]
Previously, haskell-mode had the ability to display the various indentation options for the current line by rendering underscores at the indentation positions. It looks like it was removed in this commit: https://github.com/haskell/haskell-mode/commit/9579efcdab415e0997f1843f1794bc3e90a92b7b

While I certainly don't disagree with disabling this feature by default, I'm a bit disappointed it was removed altogether. I thought this was a nice feature and very helpful to people who are new to haskell syntax.

If possible, I'd like to see this feature make its way back into haskell-mode, even if it's disabled by default. Thoughts?

**Comment by geraldus** [comment]
It was removed because of some conflicts with other package overlays.  Though it was not very useful I liked that underscores too.

**Comment by gracjan** [comment]
@yupferris, comment https://github.com/haskell/haskell-mode/pull/947#issuecomment-149000264 has reasoning why this move was made. If you have arguments countering what is presented there, or even better man-power to move indentation forward then we are all ears.

**Comment by gracjan** [comment]
Closing due to lack of manpower.
