### ISSUE TITLE
Function name with proceeding the underline sign is not highlighted.

### ISSUE THREAD

**Issue by vonavi** [haskell/haskell-mode#1342]
Here is a little example, where function name at the last line is not highlighted (its face is `default` instead of `haskell-definition-face`):
```hs
isEmpty :: [Int] -> Bool
isEmpty [] = True
isEmpty _  = False
```

Best regards,
Vladimir.

**Comment by fice-t** [comment]
@gracjan This is due to this commit ff846824f7904923e193e6303b5a3c74ed06d69f

Another issue that commit causes is that the function name gets font-locked too soon:

```haskell
is_empty$
```
When your cursor is where the $ is, then the `is_` is font-locked, but the `empty` is not.
