### ISSUE TITLE
font-lock mode hangs with unbalanced left-parenthesis in type signature near top of long file

### ISSUE THREAD

**Issue by ChrisKuklewicz** [haskell/haskell-mode#1344]
I am running Emacs (GNU Emacs 24.5.1 (i686-pc-mingw32)) on Windows, and haskell-mode 1.5

When I am in a big haskell file (1000 lines) and at the bottom of the file I can type a new line:

`foo :: (some text goes here`

This works well and performance appears fine.

But if I type that at the top of the file (just under the import statements for instances) then once I hit the left-parenthesis (which is unbalanced) the rate of response from Emacs drops to less than one character per second, often I have to wait for 10 to 20 seconds for any of "some text goes here" to appear in the buffer after the left parenthesis.

Note that this performance bug only occurs when the unbalanced left parenthesis is part of a type, not when it is part of a normal expression.

This is such a serious performance bug it essentially hangs Emacs.  I have to disable font-lock mode when editing many haskell files.

**Comment by ChrisKuklewicz** [comment]
Using profile-report in Emacs, it appears to blame haskell-syntax-propertize, but I have no practice at profiling elisp.

**Comment by gracjan** [comment]
Culprit is here: https://github.com/haskell/haskell-mode/blob/fa57f913443577569d8a14e28900a689094d6584/haskell-font-lock.el#L261

I guess we cannot rely on balanced parentheses in type declarations.

**Comment by ChrisKuklewicz** [comment]
Good to know where the 20 second delay comes from.  Quickly failing to balance and not updating highlighting should be okay.  Too bad there is no background thread for this sort of thing.

**Comment by gracjan** [comment]
I've found a better solution.

**Comment by ChrisKuklewicz** [comment]
Awesomely fast response, thanks!
