### ISSUE TITLE
Interactive-Haskell module name

### ISSUE THREAD

**Issue by Pitometsu** [haskell/haskell-mode#1351]
Can I show loaded module name in prompt of `Interactive-Haskell`?

**Comment by fice-t** [comment]
Currently it's possible to show the module name in `prompt2` but not `prompt`. It sends `set prompt "\\4"` to GHCi as a way to detect `prompt` later on, but you can set `prompt2` using `haskell-interactive-prompt2`. You can look at `haskell-process-send-startup` to see what the REPL is sent.

**Comment by Pitometsu** [comment]
@fice-t thank you for explanation a lot. I thins, it may be implemented in way that I describe here https://github.com/haskell/haskell-mode/issues/1353#issuecomment-223715621

***
So I close this one issue.
