### ISSUE TITLE
Shelling out to `which` for executable paths

### ISSUE THREAD

**Issue by ocramz** [haskell/haskell-mode#1358]
I need to switch GHC versions, and can't seem to find anywhere a menu that lets me set the path for `ghc` and related tools. I did use it once though, but I can't recall the incantation.

In general, wouldn't it be simpler if the mode called `which`, at least on Unix-based systems, for retrieving the system-wide path to commands such as `ghc`, `ghci`, `stack` etc. ?

Thank you

**Comment by chrisbarrett** [comment]
Perhaps surprisingly, `which` isn't portable across *nixes. haskell-mode uses Emacs' builtin functions for doing this, which will work correctly if you have Emacs' exec-path set correctly. Given that a go? :)

**Comment by gracjan** [comment]
Emacs finds executables by using `exec-path`. If what is executed goes via some shell then `PATH` environment variable gets its say where shell looks for other executables.

See #975. (I'm closing this one as dupe of #975).

**Comment by fice-t** [comment]
You also may want to look into the `haskell-process-path-` variables.

**Comment by ocramz** [comment]
@fice-t `exec-path` is the most robust way of doing. I don't have a way to assess which path variable takes priority, but `M-x customize-variable`ing  `exec-path` worked.
