### ISSUE TITLE
Font lock is unusably slow on GHC's DynFlags

### ISSUE THREAD

**Issue by bgamari** [haskell/haskell-mode#1360]
It seems that GHC's [`compiler/main/DynFlags.hs`](https://github.com/ghc/ghc/blob/master/compiler/main/DynFlags.hs) triggers some pathological case in the lexer, resulting in soul-crushing font-lock performance, with `emacs` chewing through the cycles of an entire core and taking nearly a second to redraw after a keystroke. The profile seems to suggest that the lexer is the culprit

```
- redisplay_internal (C function)                               23528  84%
 - jit-lock-function                                            23333  83%
  - jit-lock-fontify-now                                        23333  83%
   - jit-lock--run-functions                                    23333  83%
    - run-hook-wrapped                                          23329  83%
     - #<compiled 0x221e9c9>                                    23325  83%
      - font-lock-fontify-region                                23301  83%
       - font-lock-default-fontify-region                       23301  83%
        - font-lock-fontify-keywords-region                     23190  83%
         - #<lambda 0x2f67107>                                  22362  80%
          - let                                                 22362  80%
           - and                                                22362  80%
            - nth                                               19336  69%
             - syntax-ppss                                      19336  69%
              - syntax-propertize                               19256  69%
               - haskell-syntax-propertize                      19208  69%
                - save-excursion                                19208  69%
                 - let                                          19208  69%
                  - while                                       19192  68%
                   - let                                        19156  68%
                    - haskell-lexeme-looking-at-token              15769  56%
                     - let                                      14582  52%
                      - or                                      14530  52%
                       - and                                    14490  52%
                        - if                                     3826  13%
                         - let                                   3151  11%
                          + unwind-protect                         88   0%
                         + progn                                  631   2%
                        + let                                    1019   3%
                        + equal                                    88   0%
                     + while                                      359   1%
                      if                                         2887  10%
                    + cond                                        416   1%
                    syntax-ppss                                     4   0%
```

**Comment by gracjan** [comment]
Thanks, this is a very good example!

**Comment by gracjan** [comment]
I can't reproduce the issue with https://github.com/ghc/ghc/blob/bcb419a41754bbd883973c96d4b0bca4639e4f2d/compiler/main/DynFlags.hs

Haven't you been hit by already solved #1344?

**Comment by enolan** [comment]
I have this problem on Idris' AbsSyntaxTree.hs too. Maybe it's a problem with giant sum types or just long files. To reproduce, download [this](https://raw.githubusercontent.com/idris-lang/Idris-dev/master/src/Idris/AbsSyntaxTree.hs), open it in emacs and add some constructors to `Opt`. `Opt` starts at line 542 as of now. I have a similar profile to @bgamari's, with `haskell-lexeme-looking-at-token` seeming to be the culprit, but for some reason I don't see the let under it.

```
- redisplay_internal (C function)                                2868  67%
 - jit-lock-function                                             2816  66%
  - jit-lock-fontify-now                                         2812  66%
   - funcall                                                     2812  66%
    - #<compiled 0x2b28d03>                                      2796  66%
     - run-hook-with-args                                        2796  66%
      - font-lock-fontify-region                                 2792  66%
       - font-lock-default-fontify-region                        2792  66%
        - font-lock-fontify-keywords-region                      2792  66%
         - #<lambda 0x100a55fd875b7bd0>                          2776  65%
          - let                                                  2776  65%
           - and                                                 2776  65%
            - nth                                                2728  64%
             - syntax-ppss                                       2728  64%
              - syntax-propertize                                2656  62%
               - haskell-syntax-propertize                       2444  57%
                - haskell-lexeme-looking-at-token                1832  43%
                   syntax-after                                   108   2%
                 + funcall                                         36   0%
                   match-string-no-properties                      28   0%
                + haskell-lexeme-classify-by-first-char                120   2%
              + funcall                                            68   1%
         + eval                                                     8   0%
           rainbow-delimiters--propertize                           4   0%
      + goto-address-fontify-region                                 4   0%
      #<compiled 0x1acb9a7>                                        16   0%
 + eval                                                            52   1%
+ flycheck-handle-signal                                          818  19%
+ command-execute                                                 300   7%
- ...                                                             163   3%
 + company--preprocess-candidates                                 110   2%
   Automatic GC                                                    40   0%
 + sp--get-allowed-pair-list                                       13   0%
+ flycheck-perform-deferred-syntax-check                           32   0%
+ evil-escape-pre-command-hook                                     29   0%
+ timer-event-handler                                              12   0%
+ #<compiled 0x16b9073>                                             8   0%
```

**Comment by gracjan** [comment]
@enolan: Just checked and everything works fine with my setup. What version of Emacs do you have?

**Comment by bgamari** [comment]
@gracjan sorry for the latency; had visitors this week.

I believe I have also been hit by #1344 in the past, although this appears to be a different problem since the module in question is perfectly well-formed.

I am using emacs 25.0.92.1. I can also reproduce the issue (albeit to lesser degree) using the `AbsSyntaxTree` module from `idris`.

**Comment by enolan** [comment]
I'm using 24.5.1 with Spacemacs. If I get some time later I'll test with just the base Emacs setup.

**Comment by enolan** [comment]
I tested without Spacemacs and there wasn't any problem. Advice on narrowing it down?

**Comment by gracjan** [comment]
We can try to optimize `haskell-lexeme-looking-at-token` because there is some room for improvement there, but that would be work in the dark. Would be so much better to have a reproducible test case.

**Comment by gracjan** [comment]
Does anybody have more info about this one? I'm worried.

**Comment by bgamari** [comment]
Gracjan Polak <notifications@github.com> writes:

> Does anybody have more info about this one? I'm worried.
>
I'm afraid not; I also have noticed that the issue is significantly
worse when using the full Spacemacs suite. Unfortunately I've
not been able to isolate the culprit. It is on my list of things to look
into, however. Thanks for everything you do!

**Comment by gracjan** [comment]
I still haven't found the interaction that you guys are hitting.

What I discovered recently is that Emacs' regexps make it easy to hit backtracking behavior and I guess this results in quadratic regexp matching time.

Basically any use of `\\( .. \\| .. \\)*` (alternate with multiple) operator triggers backtracking. I've looked into this and we can go around the issue by looping in lisp instead as most of repetitions are on top level.

Still not sure if this is what you are guys hitting.

**Comment by bgamari** [comment]
I suspect what I am seeing is an interaction with another package,
although I haven't been able to pin down which. Unfortunately I am not a
terribly sophisticated Emacs user (coming from vim) and, worse, use
Spacemacs, so my understanding of the components involved isn't very
deep. I did manage to test with `emacs -q` and found that font-lock
performance was perfectly fine with the exact same `haskell-mode`
version used by spacemacs.
> Still not sure if this is what you are guys hitting.

It appears that Spacemacs enables a few minor modes (`yas`, `which-key`,
and `smart-parens`) yet even disabling all of these still results in
unusable font-lock performance while editing `DynFlags.hs` (each
keystroke taking more than a second to be reflected in the buffer).

Perhaps it's possible that `evil-escape-pre-command-hook` is simply
calling the font lock code more often than emacs does alone?

**Comment by gracjan** [comment]
@bgamari, @enolan: can I have your `.spacemacs` file? Which layers do you have enabled?

**Comment by bgamari** [comment]
@gracjan of course. See http://github.com/bgamari/spacemacs-config. To test,
```
$ mkdir ~/spacemacs
$ cd ~/spacemacs
$ HOME=$HOME/spacemacs
$ git clone git://github.com/syl20bnr/spacemacs .emacs.d
$ git clone git://github.com/bgamari/spacemacs-config .spacemacs.d
$ wget https://raw.githubusercontent.com/bgamari/ghc/master/compiler/main/DynFlags.hs
$ emacs DynFlags.hs 
```

**Comment by gracjan** [comment]
@bgamari: I managed to reproduce the problem.

**Comment by gracjan** [comment]
In plain Emacs `haskell-syntax-propertize` is called only for visible portion of the buffer. In Spacemacs it is called for the whole file at every keystroke. That is of course problematic.

**Comment by gracjan** [comment]
Solution: disable `hl-todo-mode`.

`hl-todo-mode` causes refresh of much more than the visible buffer to be propertized and this happens on every keystroke. For some reason `hl-todo-mode` also invalidated a perfectly valid properties that were already done.

**Comment by gracjan** [comment]
For as long as https://github.com/tarsius/hl-todo/issues/14 is not fixed add these lines to your `.spacemacs`:

```el
   ;; A list of packages and/or extensions that will not be install and loaded.
   dotspacemacs-excluded-packages '(hl-todo)
```

**Comment by bgamari** [comment]
Gracjan Polak <notifications@github.com> writes:

> Solution: disable `hl-todo-mode`.
>
Well spotted! Out of curiosity how did you deduce this? I don't recall
seeeing any signs of hl-todo in the profile.

**Comment by gracjan** [comment]
`haskell-syntax-propertize` was always called with `end` argument pointing to a line with a `TODO` or `FIXME` or `XXX`.
