### ISSUE TITLE
Unclosed string literal causes Emacs to freeze

### ISSUE THREAD

**Issue by kvelicka** [haskell/haskell-mode#1369]
#### Description
Emacs freezes (unresponsive, 100% CPU) when editing a particular Haskell file:
https://gist.github.com/kvelicka/217ae60620acec3990c448dfa8299c32

Note that the string literal on line 6 is missing the trailing double quote character. If this character is put back, the freeze no longer occurs.

I moved this issue here after initially submitting it to Spacemacs but later realising this is a haskell-mode bug. I have reproduced it on a fresh Xubuntu 16.04 VM and Emacs 25.1, as well as the spacemacs-generated information in the "System Info" section below.

#### Reproduction guide
- Start Emacs
- Open the above-mentined gist as a file with emacs
- Go to the end of line 7
- Press enter (i.e. insert a newline)

*Observed behaviour:*
Emacs freezes - becomes completely unresponsive and (presumably) goes into an infinite loop as CPU usage goes to 100% (of one core) and stays there seemingly indefinitely.

*Expected behaviour:*
A new line is inserted and cursor is placed in it

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t

**Comment by gracjan** [comment]
Hmm, I cannot reproduce this and I cannot trigger the infinite loop. I'm running MELPA version, same as git right now.

**Comment by kvelicka** [comment]
Hi, thank you for having a look at this! 

I have just re-checked, with success on the following VM:  
* Emacs 25.1.50
* haskell-mode 20160622.1433
* Xubuntu 16.04

and the following Windows machine:
* Emacs 24.3
* haskell-mode 20160622.1433
* Windows 7 SP3

The bug manifests itself if I try to insert a newline while the cursors is anywhere on the line line that reads `else return ()`. Is there any chance you (and/or anyone else interested) could attempt to reproduce this with a clean install of emacs/haskell-mode or something similar? I personally found the VM route the quickest.

Interestingly, the Windows machine's Emacs had previously been used with Emacs Prelude and when I tested using that setup (not sure about version numbers, could try and find out if needs be), the freeze did not occur. Therefore, it would seem that the issue is not universally reproducible but is definitely triggered on clean setups with most up-to-date versions of emacs and haskell-mode.

**Comment by gracjan** [comment]
Okay, I've reproduced the problem with simpler example:

```haskell
func = "unterminated
            where
```

Now somebody needs to add this to the test suite in `tests/haskell-indentation-tests.el`.

**Comment by kvelicka** [comment]
That's great news! Does that mean that his is an issue with the indentation part of haskell-mode? If so, I'll have a look at how to add tests to the suite, and with any luck, will add one for this case.

**Comment by gracjan** [comment]
Yes, indentation has its own tokenizer and this tokenizer likes only closed strings.

**Comment by gracjan** [comment]
@kvelicka: Did you have time to create the test?

**Comment by kvelicka** [comment]
I *should* be able to do it mid-next week, busy until then I'm afraid!

**Comment by gracjan** [comment]
@kvelicka, how is it going?

**Comment by kvelicka** [comment]
I'm hoping to add the test by Friday.
