### ISSUE TITLE
Autoindent sometimes indents too much

### ISSUE THREAD

**Issue by mcandre** [haskell/haskell-mode#137]
I sometimes have to comment out `(turn-on-haskell-indentation)` in my `.emacs`, as the current implementation sometimes indents too far deeply. This occurs at the first character of function signatures, for example, if the cursor is on the `f` in `fibber :: Int -> Int`:

    #!/usr/bin/env runhaskell

    fibber :: Int -> Int
    fibber 0 = 0
    fibber 1 = 1
    fibber n = fibber (n - 1) + fibber (n - 2)

    main :: IO ()
    main = print $ fibber 20

Then pressing Tab there results in:

    #!/usr/bin/env runhaskell

      fibber :: Int -> Int
    fibber 0 = 0
    fibber 1 = 1
    fibber n = fibber (n - 1) + fibber (n - 2)

    main :: IO ()
    main = print $ fibber 20

A similar error happens with the cursor beginning on the empty line between the shebang and the signature; pressing Tab results in improper indentation being inserted.

**Comment by gracjan** [comment]
We have just merged new version of `haskell-indentation` that should solve a lot of problems. I'm closing this particular issue, but do not hessitate to open new issue with specific report about new `haskell-indentation`.
