### ISSUE TITLE
Use `insert-file-contents` in `haskell-mode-stylish-buffer`

### ISSUE THREAD

**Issue by siddharthist** [haskell/haskell-mode#1370]
Looks like this function is duplicating some of the work done by [`save-excursion`](https://www.gnu.org/software/emacs/manual/html_node/eintr/append-save_002dexcursion.html). I'm new to programming with elisp, though so I might be wrong :smile: 

```elisp
(defun haskell-mode-stylish-buffer ()
  "Apply stylish-haskell to the current buffer."
  (interactive)
  (let ((column (current-column))
        (line (line-number-at-pos)))
    (haskell-mode-buffer-apply-command haskell-mode-stylish-haskell-path)
    (goto-char (point-min))
    (forward-line (1- line))
(goto-char (+ column (point)))))
```
 
https://github.com/haskell/haskell-mode/blob/bae8f14f31780f499d923dfac6d7a92893fc6862/haskell-commands.el#L785-L794

**Comment by geraldus** [comment]
Likely you're right!

**Comment by gracjan** [comment]
Not really, the point of this magic is that `haskell-mode-buffer-apply-command` replaces buffer contents so technically there is no place to return to. This function tries to get back to the same place as before.

I'm not sure how Emacs does it when revert buffer is called. Possibly that functionality could be used?

**Comment by siddharthist** [comment]
Well, save-excursion is defined in [`emacs-mirror/emacs/src/editfns.c` after around lin e975](https://github.com/emacs-mirror/emacs/blob/cfb3c61f1ffec9a6322407fdd228d5cc31c31ed0/src/editfns.c#L975), but I can't read C to understand what it does.

**Comment by WraithM** [comment]
Yeah, I've definitely noticed that the new stylish-haskell code kills some buffer state (eg. marks/location). Hopefully, this will fix that.

**Comment by WraithM** [comment]
Here's some discussion of using save-restriction and save-excursion together: https://www.gnu.org/software/emacs/manual/html_node/eintr/save_002drestriction.html

I'm trying this out now.

**Comment by WraithM** [comment]
I think that @siddharthist's code snippet has more or less the same effect as `save-excursion`. I'm gonna mess with it a bit more.

With the new stylish-haskell code, the buffer also centers on the cursor after stylish-haskell runs. It's very annoying. Adding `save-excursion` didn't help with that.

Also also, my `evil-mode` marks get killed after a stylish-haskell run.

**Comment by gracjan** [comment]
How about using `revert-buffer`?

https://www.gnu.org/software/emacs/manual/html_node/elisp/Reverting.html

**Comment by gracjan** [comment]
So the proper way is to use `insert-file-contents` because documentation says:

> If optional fifth argument REPLACE is non-nil, replace the current
> buffer contents (in the accessible portion) with the file contents.
> This is better than simply deleting and inserting the whole thing
> because (1) it preserves some marker positions and (2) it puts less data
> in the undo list.

That should be used here: https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L824

Note that we have framework to test this properly so whoever tackles this issue please create a test.
