### ISSUE TITLE
Stylish haskell asks too much when file edited outside of Emacs

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1374]
I see the following events:

1. Visit file `X.hs`.
2. Change something in the buffer.
3. Change `X.hs` outside of Emacs, now there are two incompatible changes.
4. <kbd>C-x C-s</kbd>.
5. `X.hs has changed since visited or saved.  Save anyway? (y or n)``, answer <kbd>y</kbd>.
6. `X.hs changed on disk; really edit the buffer? (y, n, r or C-h)`, answer <kbd>y</kbd>.
7. `Wrote X.hs`.

We should get rid of the second question in pt. 6.

**Comment by gracjan** [comment]
Interestingly this seems to be Emacs default behavior, when stylish-haskell is disabled it goes the same way.

**Comment by geraldus** [comment]
@gracjan also check if `auto-revert-mode` enabled.

**Comment by gracjan** [comment]
Hmm, this looks like completely normal Emacs behavior, even when stylish-haskell is not enabled. Leaving as it is.
