### ISSUE TITLE
Release a new version.

### ISSUE THREAD

**Issue by crocket** [haskell/haskell-mode#1387]
I am on melpa-stable, and I want to silence "visit tags table" dialogue.
The intrusive dialogue was silenced in #1234, but the fix is not available on melpa-stable, yet.

If you release a new version, I'll be able to receive the fix.

**Comment by gracjan** [comment]
Fixed in https://github.com/haskell/haskell-mode/commit/9eef80d1a16ac3b41b62b8d79ecbafa62e00c6c9.
