### ISSUE TITLE
Hangs when applying stylish-haskell

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#1389]
I've just upgraded stylish-haskell to 0.6.1.0, and it seems that now when haskell-mode tries to apply it it hangs (cursor spinning, etc.).  `C-g` stops it with the stylish-haskell output saved.

Is there anything more I can try and do to debug this?

**Comment by gracjan** [comment]
`stylish-haskell-0.5.14.1` is working correctly. I do not know what has changed.

**Comment by gracjan** [comment]
`stylish-haskell 0.6.1.0` works for me too. Do you have additional options in your configuration?

**Comment by gracjan** [comment]
@ivan-m: does this strill happen to you?

**Comment by ivan-m** [comment]
Sorry, I thought I had updated this; I found it was a conflict with some other setting of mine as I had updated haskell-mode around the same time.

Apologies for the noise.
