### ISSUE TITLE
Indentation broken

### ISSUE THREAD

**Issue by bitemyapp** [haskell/haskell-mode#1390]
I see this in messages when I try to manually enable Haskell indentation mode.

```
Haskell-Indentation mode disabled in current buffer
You can run the command ‘haskell-indentation-mode’ with M-x -indenta-m RET
```

The following configurations do not work:

```elisp
(require 'haskell-mode)
(require 'haskell-indentation)
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
```

```elisp
(require 'haskell-mode)
;; (require 'haskell-indentation) with or without
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
```

The following does, but it's not the indentation mode that gets most of the love:

```elisp
(require 'haskell-mode)
(add-hook 'haskell-mode-hook 'haskell-indent-mode)
```

This is what I get from MELPA stable: `haskell-mode-20160726.1027`

Broken here means that hitting the `<TAB>` key does nothing and return key doesn't start your line at the usual indent level. Attempting to load a haskell-indentation directly fails with weird, mangled error messages.

**Comment by gracjan** [comment]
It should work. All our tests are green.

**Comment by bitemyapp** [comment]
It's intermittent on my end :\

**Comment by fice-t** [comment]
Why are you trying to manually enable it? It's actually (supposed to) be enabled by default (hence the `Haskell-Indentation mode disabled in current buffer`). See the `(haskell-indentation-mode)` at the end of the `haskell-mode` function. Not sure if that's supposed to be there though.

Your configs work for me in `emacs -Q`. What's the output of `M-: haskell-indentation-mode` without doing anything after switching to `haskell-mode`?

**Comment by bitemyapp** [comment]
@fice-t only to debug. I have a hook for it.

Like I said, it's an intermittent issue, I don't have a repro right now.
