### ISSUE TITLE
"indent-new-comment-line" re-indents in haskell-mode

### ISSUE THREAD

**Issue by korayal** [haskell/haskell-mode#1396]
I thought this was a hindent-mode problem ( https://github.com/chrisdone/hindent/issues/192 ) but when I disable it, I still get the same result.

When I run the command M-j in a line comment, it creates a new comment line at the same level, but then it indents that new line again.

![image](https://cloud.githubusercontent.com/assets/313801/17546992/6b5aaa74-5eed-11e6-9388-21c267b6b14c.png)

So on the above picture when I press `M-j` when the cursor is at the second line, I get the behaviour at the third line.

**Comment by gracjan** [comment]
Thanks for the report, we know. Note #1034.
