### ISSUE TITLE
Indentation of non-parallel list comprehensions is wrong.

### ISSUE THREAD

**Issue by bremner** [haskell/haskell-mode#14]
forwarding http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=343248
Daniel Burrows writes:

  haskell-mode indents parallel list comprehensions (the GHC extension)
just fine, but it seems to have trouble with non-parallel ones.  For
instance, consider this code fragment:

```haskell
allCards :: CardUniverse -> [CardValue]
allCards (CardUniverse s free) = free ++ suited
    where suited = [cv | suit <- s,
                         (cv, _) <- elems (suitCards suit)]
```

  haskell-mode wants me to indent the last line to either the level of
"s" or the level of "cv" in the previous line; for instance:

```haskell
-- | Returns a list of all the cards in the universe; this will be a
-- set if the universe is well-formed.
allCards :: CardUniverse -> [CardValue]
allCards (CardUniverse s free) = free ++ suited
    where suited = [cv | suit <- s,
                    (cv, _) <- elems (suitCards suit)]
```

I verified that this behaviour still exists with 2.8.0 and `turn-on-haskell-indentation`

**Comment by LukeHoersten** [comment]
As Chris mentioned back in 2013, he was going to close this in a month. I confirmed hi2-mode still has this same behavior but the recommended indentation works correctly as this:

```haskell
allCards :: CardUniverse -> [CardValue]
allCards (CardUniverse s free) = free ++ suited
  where suited = [ cv | suit <- s
                      , (cv, _) <- elems (suitCards suit)
                      ]
```
