### ISSUE TITLE
Typo in Makefile

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-mode#1415]
diff --git a/Makefile b/Makefile
index 8ee6687..5a25b0b 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 #
 # Note: Due to MELPA distributing directly from github source version
-# needs to be embedded in files as is without proprocessing.
+# needs to be embedded in files as is without preprocessing.

**Comment by gracjan** [comment]
How about a pull request?
