### ISSUE TITLE
indent bug in haskell-indent.el

### ISSUE THREAD

**Issue by kosl90** [haskell/haskell-mode#142]
This bug annoyed me so much, if there is such a code fragment:

    main = do
      (fileName:_) <- getArgs
      writeFile fileName "content"

I cannot indent the writeFile line, emacs told me "Wrong type argument: arryp, nil". haskell-indentation.el works right, but I cannot use the cool thing that completes my function name when I press [TAB] below my function declaration.

I will appreciate that if you guys fix it.

**Comment by gracjan** [comment]
@kosl90, @ivan-m, @deftsp: Itried to reproduce your problem with current github version of haskell-mode and could not trigger described behavior. I'vre tried the code:

    main :: IO ()
    main = do
      (fileName:_) <- getArgs
      writeFile fileName "content"

I've used both `haskell-indent` and `haskell-indentation`. I could not trigger the error on any of the lines.

Can you check out if the problem described still exists?

**Comment by gracjan** [comment]
@chrisdone, @purcell, this seems to be fixed.
