### ISSUE TITLE
Indentation in export lists broken when exporting a module

### ISSUE THREAD

**Issue by neongreen** [haskell/haskell-mode#1422]
In this case, after pressing Enter at position `|`, cursor jumps to position `^`, as expected:

```
module Foo
(
  bar,|
  ^
```

However, if the exported item is a `module`, indentation disappears. This is wrong behavior:

```
module Foo
(
  module A,|
^
```

The bug doesn't appear if the paren is left on the first line:

```
module Foo (
  module A,|
  ^
```

**Comment by gracjan** [comment]
Nice catch! Can you write a test case? Thanks.

**Comment by gracjan** [comment]
What makes indentation mode confused is the open parenthesis on the first column. Indentation goes up to find a line that is not indented and starts from there, which in your report is the opening parenthesis. If the parenthesis is on the same line as module keyword or on following line but indented then confusion does not happen.

I think we should live with this.
