### ISSUE TITLE
Error: Unused lexical variable ‘move-point-in-windows’

### ISSUE THREAD

**Issue by aplanas** [haskell/haskell-mode#1428]
Compiling latest code from git (emacs and haskell-mode) as 24/09/2016:

    # make EMACS=/home/aplanas/bin/emacs
    EMACS check-emacs-version
    Using EMACS = /home/aplanas/bin/emacs, version = 25.2.50.1
    mkdir build-25.2.50.1
    EMACS build-25.2.50.1/haskell-menu.elc
    EMACS build-25.2.50.1/haskell-font-lock.elc
    EMACS build-25.2.50.1/haskell-complete-module.elc
    EMACS build-25.2.50.1/haskell-string.elc
    EMACS build-25.2.50.1/haskell-repl.elc
    EMACS build-25.2.50.1/inf-haskell.elc
    EMACS build-25.2.50.1/haskell-session.elc
    EMACS build-25.2.50.1/haskell-sandbox.elc
    EMACS build-25.2.50.1/haskell-process.elc

    In toplevel form:
    haskell-process.el:160:1:Error: Unused lexical variable ‘move-point-in-windows’
    make: *** [Makefile:69: build-25.2.50.1/haskell-process.elc] Error 1

**Comment by gracjan** [comment]
Hi, can you provide a PR? Should be easy to fix.

For added value can you add a testing in Travis/Appveyor for Emacs-25.2?

**Comment by gracjan** [comment]
Okay, somebody else fixed this particular issue. But no worriers, we have plenty of other issues to fix here and there!

**Comment by aplanas** [comment]
Thanks to @swilde and @gracjan!

I confirm that it works.
