### ISSUE TITLE
haskell-mode doesn't support indentation for ghcjs FFI.

### ISSUE THREAD

**Issue by crocket** [haskell/haskell-mode#1431]
``` haskell
foreign import javascript unsafe
  "$2[$1]" js_getProp :: S.JSString -> O.Object -> T.JSVal
```

I have to manually indent GHCJS FFI code in haskell-mode. It is tedious.
I conjecture that `javascript` keyword confuses haskell-mode.

**Comment by gracjan** [comment]
Can you add a unit test case?

**Comment by crocket** [comment]
Unfortunately, I don't know how to write emacs lisp, yet.
Also, I don't know what you specifically mean by a unit test case for GHCJS FFI.

**Comment by gracjan** [comment]
Unit test for indentation are in `tests/haskell-indentation-tests.el`.

**Comment by crocket** [comment]
I just read `tests/haskell-indentation-tests.el`. Since I don't know how to write emacs lisp and don't understand the internal mechanisms of haskell-mode, I was only confused.

**Comment by gracjan** [comment]
Interestingly, indentation seems to not support `foreign` declarations at all. Looks like a missing feature.

**Comment by crocket** [comment]
I think you'll find https://www.haskell.org/onlinereport/haskell2010/haskellch8.html#x15-1540008.4 helpful.

**Comment by crocket** [comment]
https://github.com/ghcjs/ghcjs/blob/master/doc/foreign-function-interface.md
