### ISSUE TITLE
Scroll to bottom option does not work

### ISSUE THREAD

**Issue by vshabanov** [haskell/haskell-mode#1438]
I have `Haskell Interactive Mode Scroll To Bottom` option disabled but cursor still goes to the end of current output.

You could try code like this (and you could change `putStrLn` to `putStr`):
`forM_ [1..10] $ \ i -> threadDelay 1000000 >> putStrLn (show i)`
if you move cursor up or left it will jump to the end next second.

**Comment by fice-t** [comment]
A couple functions were missing some `save-excursion`s. This should be fixed in #1441.

**Comment by vshabanov** [comment]
Thank you. But now when this option is disabled it never scrolls to bottom, even if cursor was at the bottom.

Is it possible to restore old haskell-mode behavior -- when cursor automatically goes to bottom if it was at the bottom before new output has arrived and does not move when it's not at the bottom?

It was very convenient since I get cursor at the λ> prompt and see output progress by default but can navigate output while program is working if I want.

**Comment by fice-t** [comment]
> Is it possible to restore old haskell-mode behavior -- when cursor automatically goes to bottom if it was at the bottom before new output has arrived and does not move when it's not at the bottom?

Was this really the old behaviour? Wasn't the absence of that behaviour the point of this issue?

Anyway, #1442 should do this for you.

**Comment by vshabanov** [comment]
Wow. That's great! I even think that you can make `haskell-interactive-mode-scroll-to-bottom` set to `nil` by default again since current behavior is much more reasonable than always scroll to bottom no matter where cursor is.

Yes, it was the old behavior but I mean really old `inf-haskell` mode. (I've updated from haskell-mode v2.4 recently ;)

**Comment by vshabanov** [comment]
Docs for `haskell-interactive-mode-scroll-to-bottom` says _Scroll to bottom in the REPL **always**_ so I thought -- OK, then with this option disabled it will scroll only when cursor is at the end of output.

But it scrolled in any case and then stopped to scroll in any case. And I just wanted old `inf-haskell` behavior. Here the confusion.

**Comment by fice-t** [comment]
Ah, I never really used `inf-haskell`.

> I even think that you can make haskell-interactive-mode-scroll-to-bottom set to nil by default again since current behavior is much more reasonable than always scroll to bottom no matter where cursor is.

I agree that it's better. @gracjan would you agree to changing the default?

**Comment by gracjan** [comment]
Can we get rid of the setting and just do the one single thing everybody wants?

**Comment by fice-t** [comment]
There might be someone who wants to scroll to the bottom whenever there's new input. 
This new behaviour seems good enough to remove the option if you want to, but since it's only used in 2 places I don't see the harm of keeping it either.

**Comment by gracjan** [comment]
I see more options as a burden on document writing in manual.

**Comment by fice-t** [comment]
Well, this option was never even documented in the manual at all!

#1442 now deletes the option.

**Comment by vshabanov** [comment]
I think it's perfect now. It's hard to imagine a use case when somebody wants to be interrupted and scrolled to bottom when he reads previous output.
