### ISSUE TITLE
installed from melpa-stable, but no haskell-mode-autoloads feature

### ISSUE THREAD

**Issue by kReoSo** [haskell/haskell-mode#1439]
I see there was a file 'haskell-mode-autoloads.el' in .emacs.d/elpa/haskell-mode-16.1, but I can't find (provide 'haskell-mode-autoloads) in that file. 

I just deleted haskell-mode, and installed it again, but it was the same. 

Just for curiosity, I have git-cloned and make haskell-mode, and there is indeed (provide 'haskell-mode-autoloads). 

Something's wrong with melpa-stable?

**Comment by syohex** [comment]
autoloads file(`haskell-mode-autoloads`) is generated by package.el. And it is loaded in `(package-initialize)`. So you need not to load it explicitly.

**Comment by gracjan** [comment]
@kReoSo: How do you install? Generation of autoloads is managed by the Emacs build in package manager (`package.el`).

**Comment by kReoSo** [comment]
Ok, that means, when you install from package.el, there is no need to load haskell-mode-autoloads explicitly, so the feature is not privided. right? 

Then problem solved. Thank you
