### ISSUE TITLE
ghci buffer has eval problem.

### ISSUE THREAD

**Issue by ccqpein** [haskell/haskell-mode#1446]
I write this code in *.hs file, and run ghci in emacs.

~~~haskell
climbS :: (Fractional a, Enum a, Num a, Integral a) => a -> a
climbS nn = sum [n | n <- [1..(div nn 2)]]
~~~

I put code below in ghci, and get the type of climbS

~~~haskell
λ> climbS 3
climbS 3 :: (Integral a, Fractional a) => a
~~~

but if I put expression directly, I get the return that I purposed get

~~~haskell
λ> let nn = 4 in sum [n | n <- [1..(div nn 2)]]
3
~~~

Then I quit emacs and enter ghci directly from shell, everything is fine. `climbS 3` works well and return 1.

**Comment by ivan-m** [comment]
I don't think you want the `Fractional` in there...

```haskell
Prelude> :i Fractional
class Num a => Fractional a where
  (/) :: a -> a -> a
  recip :: a -> a
  fromRational :: Rational -> a
        -- Defined in `GHC.Real'
instance Fractional Float -- Defined in `GHC.Float'
instance Fractional Double -- Defined in `GHC.Float'
```

No instance of `Integral` is an instance of `Fractional`, but your type signature (erroneously) requires both.

Since you don't specify a type when you did the `let` statement this isn't an issue.

**Comment by ccqpein** [comment]
You are right. The reason I use Fractional because there is another function in climbS. Whole code below

~~~haskell
permutations' :: (Fractional a, Enum a, Num a) => a -> a -> a
permutations' a b = let aa = a-b+1 in
  (product [aa..a])/ (product [1..b])

climbS :: (Fractional a, Enum a, Num a, Integral a) => a -> a
climbS nn = sum [(permutations' n (n + y))| n <- [1..(div nn 2)], let y = (nn - n * 2)]
~~~

`/` in permutations' need `Fractional`. 

I understand what is your meaning. You are right, I am trying find other ways to finish this.

**Comment by ivan-m** [comment]
You probably want `fromIntegral` in there somewhere.

Either way, this has nothing to do with haskell-mode.

**Comment by ccqpein** [comment]
Thank you! That's my mistake.
