### ISSUE TITLE
Is there a way to disable hints in mini buffer?

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1448]
Like when point is at `import` it shows:

```
import [qualified] modid [as modid] [impspec]
```

Or when it happens to think that it knows signature of some function, it can't wait but to show it in the minibuffer.

This always gets in the way of Flycheck or other stuff for me, is there a way to disable this for good?

**Comment by geraldus** [comment]
@mrkkrp  I think you are looking for this

![2016-11-04 23 56 49](https://cloud.githubusercontent.com/assets/744471/20018666/7a467216-a2ea-11e6-9be4-1c439b96f1f9.png)

**Comment by geraldus** [comment]
In case of

> import [qualified] modid [as modid] [impspec]

I guess you should turn off `show reserved` option.

**Comment by mrkkrp** [comment]
Ah I just need to avoid enabling `haskell-doc-mode` in the first place!
