### ISSUE TITLE
indentation breaks with do notation?

### ISSUE THREAD

**Issue by raould** [haskell/haskell-mode#1450]
Emacs haskell-mode installed last night using package-install from melpa. No idea what version or how to get it. I heard emacs? Blah. 

Ubuntu 16.04 lts 64 bit
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu) of 2016-04-17 on lgw01-04, modified by Debian

the first example program on
http://shakebuild.com/manual

seems to be impossible (for me anyway!) to get formatted properly via haskell-mode. :-) :-(

**Comment by kuribas** [comment]
Could you please tell what you were expecting, and what you got?   I tried that code it works just fine for me.

**Comment by gracjan** [comment]
Please reopen when there are more details available. I'm closing this now.
