### ISSUE TITLE
Stray character in haskell-mode.el

### ISSUE THREAD

**Issue by jkelleyy** [haskell/haskell-mode#1452]
There seems to be a stray character (0x0C) in haskell-mode.el, around line 990. This tripped Emacs up when it tried to generate autoload files. I'm not certain if this is the only file with this issue.

**Comment by gracjan** [comment]
0x0c is `form feed`. Should be treated like whitespace. Not that we actually want the character but it should not cause any issues if it is present.

How di you generate autoloads?

**Comment by gracjan** [comment]
Also there are more files using form feeds:

```
$ hexdump *.el | grep " 0c" | wc -l
      36
```

**Comment by jkelleyy** [comment]
Well this is weird, it seems to work when I do it manually now, even without removing the characters. For some reason installing it via gentoo still isn't building the autoload files, but I'm no longer as sure that it's not a gentoo bug.

**Comment by gracjan** [comment]
Use melpa. There is no need to use gentoo for emacs packages.

I have no clue what gentoo installs under 'haskell-mode' name, I'm pretty sure it is some super old unsupported version. Please do not do this.
