### ISSUE TITLE
haskell-process-wrapper-function is marked as risky as a file-local variable

### ISSUE THREAD

**Issue by TikhonJelvis** [haskell/haskell-mode#1457]
The `haskell-process-wrapper-function` variable is marked as risky, which gives a warning popup if you set it as a directory local variable—as suggested by its documentation:

> See Info Node `(emacs)Directory Variables' for a way to set this option on
a per-project basis.

Is this desired behavior? Emacs marks variables ending in `-function` as risky by default (which is probably sensible), but do we want to do something different for a variable we *expect* to be set locally?

**Comment by bezirg** [comment]
This fix seems to be gone in master. The variable is unsafe again , thus the issue is open

**Comment by bezirg** [comment]
Another way is to advise inside the docstring that people may add to their config `(put 'haskell-process-wrapper-function 'safe-local-variable #'functionp)` if they want to trust this variable
