### ISSUE TITLE
parse-partial-sexp wrongly tells being in list

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-mode#1459]
Not sure, if this is an haskell-mode or pure Emacs issue. With comments as shown below at top of buffer:

```
{- To explore this file: -}
-- asdf
```
---
Calling after comment `(parse-partial-sexp (point-min) (point))` results in
`(1 1 39 nil nil nil 0 nil nil (1) nil)`

pps thinks being inside a nesting list.

**Comment by gracjan** [comment]
Are you sure? This is what I get at the places:

```
{- To explore this file: (0 nil nil nil 1 nil 0 nil 1 nil)-}(0 nil nil nil nil nil 0 nil nil nil)
-- asdf(0 nil nil nil t nil 0 nil 29 nil)
(0 nil nil nil nil nil 0 nil nil nil)
```

Using `(insert (format "%S" (syntax-ppss)))`.

**Comment by andreas-roehler** [comment]
Seems a bug of GNU Emacs 26.0.50.1 (i686-pc-linux-gnu, GTK+ Version 3.14.5) of 2016-11-15
Does not exist at
GNU Emacs 25.1.90.1 (i686-pc-linux-gnu, GTK+ Version 3.14.5) of 2016-11-29

Thanks and sorry for the noise.

**Comment by gracjan** [comment]
Living on the edge, I see.
