### ISSUE TITLE
Have a menu entry for all commands

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-mode#1460]
Having a menu entry for all commands may provide some nice overview. Interested?

**Comment by gracjan** [comment]
Quick check:

```
$ grep "(interactive)" *.el | wc -l
     113
```

That is a bit of work. Is there a way to automate this and keep it up to date?

**Comment by andreas-roehler** [comment]
May use some stuff from here:
https://gitlab.com/python-mode-devs/python-mode/tree/master/devel
notably: python-components-create-menu.el

Should be possible to generalize these things.

**Comment by andreas-roehler** [comment]
Closed by mistake, wrong button.

**Comment by gracjan** [comment]
I see that you yourself are the brain behind https://gitlab.com/python-mode-devs/python-mode/blob/master/devel/python-components-create-menu.el

Is this a program that creates an elisp file? Why not generate menus dynamically instead of creating a source file to create menus?

**Comment by andreas-roehler** [comment]
...-create-menu.el wrote the menu-building-code which is inside python-mode.el,  wherefrom the menu is created than. It runs half-automated. But it's possible to push that a little bit further and create an menu.el at once - where from the menu might be loaded like the other stuff.

**Comment by gracjan** [comment]
I'm not against this, but I do not like the code-generation technique. I'm closing this one, as soon as somebody comes up with a PR then we can discuss.
