### ISSUE TITLE
Installation instructions pointing to wrong url of melpa

### ISSUE THREAD

**Issue by hithacker** [haskell/haskell-mode#1461]
In http://haskell.github.io/haskell-mode/manual/latest/Installation.html#Installation the step 2 says to INS a new archive with URL value `http://stable.melpa.org/packages` but if you do that it results in a Failed to download melpa-stable archive error when you restart your emacs and do package-refresh-contents. The correct url is the same but it ends with a slash `http://stable.melpa.org/packages/`. See https://github.com/melpa/melpa/issues/2139 for how someone was getting a same error and fixed it.

**Comment by gracjan** [comment]
Thanks, fixed
