### ISSUE TITLE
haskell-indentation-newline-and-indent honor block column

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-mode#1462]
foo = if xs == []
  
RET at EOL ends at second line column 2, but should match up with "if", col 6.

**Comment by kuribas** [comment]
type <RET> "then" <TAB>, "then" will allign with "if"

**Comment by kuribas** [comment]
no, there's just one TAB

**Comment by gracjan** [comment]
This is a feature discussed in https://github.com/haskell/haskell-mode/issues/366.
