### ISSUE TITLE
Consider changing default for `haskell-process-args-stack-ghci`

### ISSUE THREAD

**Issue by slpopejoy** [haskell/haskell-mode#1463]
Per intero, which defaults to adding `--no-build --no-load`, which speeds up repl startup tremendously. So far works great with my dev flow in just haskell-mode, so thought I'd suggest it. Happy to submit a PR if folks agree. The new default would be `--ghc-options=-ferror-spans --no-build --no-load`

**Comment by gracjan** [comment]
Looks right. Can we get a PR?
