### ISSUE TITLE
Erasing text segfaults Emacs

### ISSUE THREAD

**Issue by neongreen** [haskell/haskell-mode#1466]
Versions:
  * haskell-mode: 20161230.209 (in 20161101.751 it didn't happen)
  * Emacs: 25.1.1
  * OS: Arch Linux, x86_64

Steps to reproduce:

1. Create a new buffer

2. Paste this text:

```haskell
#define FOO(t) instance Bar where { foldMap = undefined; fold = undefined; sum = undefined; product = undefined; foldr = undefined; foldr' = undefined; foldl = undefined; elem = undefined; elem = undefined; elem = undefined;elem=undefined;elem=undefined;elem=undefined;elem=undefined;elem=undefined;@
#endif
```

3. Turn on haskell-mode

4. Place point after `@` (i.e. at the end of first line)

5. Press and hold Backspace

After a few seconds of erasing Emacs should segfault:

```
Fatal error 11: Segmentation fault
Backtrace:
emacs[0x507da9]
emacs[0x4ee96c]
emacs[0x50654e]
emacs[0x506773]
emacs[0x5067df]
/usr/lib/libpthread.so.0(+0x11080)[0x7f2fe517a080]
emacs[0x5370ac]
emacs[0x5347d6]
emacs[0x4a779b]
emacs[0x4ab96b]
emacs[0x443c60]
emacs[0x44e00e]
emacs[0x450762]
emacs[0x4643de]
emacs[0x46749e]
emacs[0x56053e]
emacs[0x454cdc]
emacs[0x4f8b7b]
emacs[0x4fb560]
emacs[0x4fd116]
emacs[0x5604b2]
emacs[0x4eedec]
emacs[0x560453]
emacs[0x4eeda9]
emacs[0x4f3537]
emacs[0x4f3878]
emacs[0x418a4e]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7f2fe4deb291]
emacs[0x4195da]
Segmentation fault (core dumped)
```

It also happens if you're quickly typing a string of `elem=undefined;`s instead of erasing it (almost always after `unde`). It doesn't happen when haskell-mode isn't turned on.

**Comment by gracjan** [comment]
Whatever happens lisp code should not crash Emacs. Have you tried to upgrade to 25.2?

**Comment by neongreen** [comment]
I'll upgrade to 25.2 when it comes out (unfortunately it's too much of a hassle to build Emacs from source) and report back.

**Comment by gracjan** [comment]
Report back if there are other issues.

**Comment by neongreen** [comment]
Upgrading to 25.2 indeed fixed this.
