### ISSUE TITLE
ghc-options is now called ghci-options

### ISSUE THREAD

**Issue by reactormonk** [haskell/haskell-mode#1476]
See https://www.reddit.com/r/haskell/comments/5kjwk7/spc_m_h_t_not_working_in_spacemacs_haskell_layer/ and https://github.com/syl20bnr/spacemacs/issues/4770#issuecomment-269240644

**Comment by gracjan** [comment]
This was fixed about a month ago already:

https://github.com/haskell/haskell-mode/blob/master/haskell-customize.el#L162
