### ISSUE TITLE
Tag navigation

### ISSUE THREAD

**Issue by chrissound** [haskell/haskell-mode#1479]
My knowledge of emacs is minimal, so please bear with me.

I'm using Spacemacs, and the Haskell functionality seems to work fine besides the ability to navigate source code. 

I'm not sure if this lies with haskell-mode, intereo, spacemacs - but any help would be appreciated - hopefully I'd be able update Spacemac's Haskell layer.

---

What do I need to install / configure to allow source code navigation functionality (jump to definition of a function)? Currently if try navigate to a function definition I get asked for a 'Visit tags table' file.

**Comment by ivan-m** [comment]
You may need to have a tool that generates TAGS files for you, like [hasktags](http://hackage.haskell.org/package/hasktags).

Alternative, try the imenu functionality instead; depending on which additional imenu libraries you bring in it can work for cross-project or just the one file.

**Comment by chrissound** [comment]
I see, well I've run into some issues with that too (https://github.com/MarcWeber/hasktags/issues/34), but will try resolve them then.

**Comment by chrissound** [comment]
Great so that issue has been resolved. 

Does anyone know how I can use hasktags to generate the tags to include dependencies from cabal / stack?

Currently just using `hasktags --ignore-close-implementation --etags .`, which generates tags for the source code under the current directory only.

**Comment by ivan-m** [comment]
You can enable `haskell-tags-on-save` to run `hasktags` for you.

I then have the following in my Emacs config (though I don't use it):

```elisp
;; Jump to the definition of the current symbol.
(define-key haskell-mode-map (kbd "M-.") 'haskell-mode-tag-find)
```

**Comment by chrissound** [comment]
So the tag generation works fine but it does not include generate 'tags' for dependencies (which I'm guessing are located somewhere within cabal / stack).

I've been able to work around that by having a  'sources' directory where I run `stack unpack scotty` for example.

**Comment by ivan-m** [comment]
I'm not sure if any tool supports generating `TAGS` files for all dependencies.

For `cabal`, the sources would be in `~/.cabal/packages/*/*/*/*.tar.gz`; for `stack` they're in (I think) `~/.stack/indices/*/packages/*/*/*.tar.gz` (this doesn't include any dependencies obtained via git AFAIK).

**Comment by chrissound** [comment]
Thanks for all the info!
