### ISSUE TITLE
haskell-mode-hook customizations are lost

### ISSUE THREAD

**Issue by Jehops** [haskell/haskell-mode#1480]
Customizations to the variable `haskell-mode-hook` are lost (reset to nil) after haskell-mode is first loaded.

1. Add, e.g., `'(haskell-mode-hook '(haskell-indent-mode interactive-haskell-mode intero-mode))` to `custom-set-variables`.
2. Restart Emacs.
3. `(find-file "something.hs")`
4. `(describe-variable 'haskell-mode-hook)` and its value will be nil.

**Comment by ivan-m** [comment]
How did you add it to `custom-set-variables`?

Do you have something changing where `custom-file` points to?

(This doesn't look like a haskell-mode issue, more a how-does-Emacs-work issue.)

**Comment by Jehops** [comment]
I just do `M-x customize-variable ...`.  There are others with the same issue.  http://emacs.stackexchange.com/questions/28967/haskell-mode-hook-is-nil

**Comment by ivan-m** [comment]
Just to make sure: you save it after setting it (and it appears in `custom-set-variables` in your `.emacs`)?

My approach is to define a new function and explicitly add it to the hook:

```elisp
(defun haskell-hook ()
  ...
)

(add-hook 'haskell-mode-hook 'haskell-hook)
```

**Comment by Jehops** [comment]
Ivan Lazar Miljenovic <notifications@github.com> writes:

> Just to make sure: you save it after setting it (and it appears in `custom-set-variables` in your `.emacs`)?

Yes.

> My approach is to define a new function and explicitly add it to the hook:

> ```elisp
> (defun haskell-hook ()
>   ...
> )

> (add-hook 'haskell-mode-hook 'haskell-hook)
> ```

Another workaround is to add `(setq haskell-mode-hook nil)` to the init file.

**Comment by phil-s** [comment]
> (This doesn't look like a haskell-mode issue, more a how-does-Emacs-work issue.)

It's both (which in practice means it's a `haskell-mode` bug).

Hook variable are not normally defined explicitly -- the mode creation macros define them, and `define-derived-mode` sets the value of the mode's hook variable to `nil`.

Here you evaluate `(defcustom haskell-mode-hook '(haskell-indentation-mode interactive-haskell-mode) ...)` *after* defining `haskell-mode`, which means that in a fresh installation of `haskell-mode` with no customization, the *intended* default value for this hook is never used (variable definitions never clobber pre-existing values for the variable being defined).

Simply evaluating `(defcustom haskell-mode-hook ...)` *before* `(define-derived-mode haskell-mode ...)` solves that problem, but introduces a different one: now docstring for the variable will be clobbered by the mode macro (again, these variables are not usually defined explicitly).

As such, a workable sequence is:

    (defcustom haskell-mode-hook '(haskell-indentation-mode interactive-haskell-mode)
      ;; This user option must be defined prior to `haskell-mode' to
      ;; prevent `define-derived-mode' setting its value to nil; however
      ;; the mode definition will clobber our docstring, so we will set
      ;; that after the mode has been defined.
      ...)

    (define-derived-mode haskell-mode prog-mode "Haskell"
      ...)

    ;; In order to provide a custom docstring for `haskell-mode-hook', we
    ;; must set it after `haskell-mode' is defined, as `define-derived-mode'
    ;; clobbers any existing docstring (see the user option definition for
    ;; why we define it first).
    (put 'haskell-mode-hook 'variable-documentation
         "List of functions to run after `haskell-mode' is enabled ....")
