### ISSUE TITLE
Haskell-mode not listed anywhere(including MELPA)

### ISSUE THREAD

**Issue by Red-Portal** [haskell/haskell-mode#1489]
![2016-12-15_19-52-32](https://cloud.githubusercontent.com/assets/18320033/23362349/bc38bc12-fd38-11e6-80bb-2eeef027f8c3.jpg)

Haskell-mode doesn't pop up

![2016-11-08_19-35-54](https://cloud.githubusercontent.com/assets/18320033/23362357/c0a9226e-fd38-11e6-8668-541d56acc359.jpg)

These are my currently connected package servers

**Comment by gracjan** [comment]
Interesting: https://melpa.org/#/haskell-mode

We have not changed anything recently. Can you double and tripple check your config?

**Comment by ivan-m** [comment]
Possible reason: do you already have `haskell-mode` installed? I'm not seeing other packages I have installed if I try and to `package-install`.

**Comment by Red-Portal** [comment]
I'll try again later! I'm currently using a manually downloaded git repo instead.

**Comment by Red-Portal** [comment]
https://github.com/Red-Portal/.emacs.d/blob/master/init.el

I've commented all code related to manually installed haskell-mode.
Haskell-mode is still not listing.

Anybody experienced this kindda thing?

**Comment by ivan-m** [comment]
Does it appear when you do `package-list-packages`?

**Comment by Red-Portal** [comment]
Yeah it does. Strange I swear I didn't see it there last time. Still doesn list on M-x Package-install though

**Comment by ivan-m** [comment]
In `package-list-packages`, did it indicate that it was installed or available?

Actually, I just tried doing `package-install` with a package I haven't installed (and one from the official "gnu" repository, not MELPA), and that didn't appear there either.  So I suspect this is an issue with package.el.

**Comment by Red-Portal** [comment]
There seems to be a problem because none of my installed packages are listed as 'installed'. It is listed as available though.
