### ISSUE TITLE
Must declare Main module for haskell-interactive-mode

### ISSUE THREAD

**Issue by acarrico** [haskell/haskell-mode#1492]
In haskell-interactive-mode, `C-c C-l` AKA `haskell-process-load-or-reload` seems to require a `module Main where` declaration at the head of the file.

In contrast, in a shell, `ghci Main.hs` puts you in an implicit Main module when the module was undeclared in the source.

I think this module declaration issue is why, as a beginner, haskell-mode sometimes seems to work, and other times doesn't. Haskell-mode isn't very beginner friendly to start with (requiring keybindings  in .emacs out-of-the-box), and this wrinkle steepens the learning curve.

**Comment by gracjan** [comment]
What keybindings are you talking about here:

> requiring keybindings in .emacs out-of-the-box

?

**Comment by acarrico** [comment]
The ones in the info documentation. Here they are in my init:

```
(require 'haskell-interactive-mode)
(require 'haskell-process)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)

(eval-after-load "interactive-haskell-mode"
  '(progn
     (define-key interactive-haskell-mode-map (kbd "M-.") 'haskell-mode-goto-loc)
     (define-key interactive-haskell-mode-map (kbd "C-c C-t") 'haskell-mode-show-type-at)))

(define-key haskell-mode-map (kbd "C-c C-l") 'haskell-process-load-or-reload)
(define-key haskell-mode-map (kbd "C-`") 'haskell-interactive-bring)
;;(define-key haskell-mode-map (kbd "C-c C-t") 'haskell-process-do-type)
(define-key haskell-mode-map (kbd "C-c C-i") 'haskell-process-do-info)
(define-key haskell-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
(define-key haskell-mode-map (kbd "C-c C-k") 'haskell-interactive-mode-clear)
(define-key haskell-mode-map (kbd "C-c c") 'haskell-process-cabal)

(define-key haskell-cabal-mode-map (kbd "C-`") 'haskell-interactive-bring)
(define-key haskell-cabal-mode-map (kbd "C-c C-k") 'haskell-interactive-mode-clear)
(define-key haskell-cabal-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
(define-key haskell-cabal-mode-map (kbd "C-c c") 'haskell-process-cabal)
```

**Comment by ivan-m** [comment]
I think this is because `haskell-process-load-or-reload` uses `:load`, which requires a module name to work.
