### ISSUE TITLE
Haskell process command errored with: (error "Unexpected response from haskell process.")

### ISSUE THREAD

**Issue by Abhiroop** [haskell/haskell-mode#1496]
A Haskell project which builds fine with `stack build` runs into this issue.
```
Unexpected response from haskell process.
Haskell process command errored with: (error "Unexpected response from haskell process.")
```
No helpful error messages to debug too.

**Comment by identicalsnowflake** [comment]
I just upgraded to GHC 8.2.1 and suddenly I'm getting this, too. My project builds fine (no stack involved), but emacs mode is broken - `C-c C-l` gives the error you posted.

**Comment by gracjan** [comment]
This is related: https://github.com/haskell/haskell-mode/pull/1168

**Comment by Abhiroop** [comment]
The issue was solved for me when I `:set -fobject-code` in GHCi. This issue can be closed now, if its solved for @identicalsnowflake

**Comment by identicalsnowflake** [comment]
Where are you setting this? I tried entering `:set -fobject-code` in ghci directly as well as putting it in my `.ghci` file in my home directory, but I still get the `unexpected response` error.

**Comment by Abhiroop** [comment]
This error message might be a common message for different class of errors(I am not sure about this).
For me I faced it while compiling https://github.com/typelead/eta
Setting object code in GHCi worked for me. And I was on GHC 7.10.

**Comment by identicalsnowflake** [comment]
Hmm. In my case I don't think it's a package: I get it even on the default "Hello world" file generated by `cabal init`.

**Comment by nrolland** [comment]
I am confronted to this message. How can we debug that to get more information on what's failing  ?

**Comment by Abhiroop** [comment]
@nrolland This seems like a common catch all error clause whose occurrence entirely depends on the code that you are trying to load. Like mentioned above my issue was solved by setting `:set -fobject-code`, but it is not necessary that the same will work with you.

I faced the same warning when I was trying to load a program with unlifted types. So you would have to produce a snippet of the program you are trying to load to debug it.

**Comment by nrolland** [comment]
@Abhiroop yeah, and since it's generic I imagined there was some "debug" facility to get more info to activate somewhere. 

There is an `haskell-process-log` emacs variable which creates a buffer but that seems to be OK, my module is loaded. 

How did you come up with your idea of setting `:set -fobject-code` ?

**Comment by nrolland** [comment]
For potential future references, there seems to be a bunch of heuristics in `haskell-load.el` in `haskell-process-load-complete` on how to interpret the response.

Replacing the function which does the matching to 

```
(defun haskell-process-consume (process regex)
  "Consume a regex from the response and move the cursor along if succeed."
  (progn
    (haskell-process-log (format "process: %S\n" (haskell-process-response process)))
    (haskell-process-log (format "regex: %s\n" regex))
  (when (string-match regex
                      (haskell-process-response process)
                      (haskell-process-response-cursor process))
    (haskell-process-set-response-cursor process (match-end 0))
    t)))
```

and `eval-defun` this, one can see 

> -> :load "/Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs"
> <- [1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
>    Ok, one module loaded.
>    Collecting type info for 1 module(s) ... 
>    
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: \[[ ]*\([0-9]+\) of \([0-9]+\)\] Compiling \([^ ]+\)[ ]+( \([^ ]+\), \([^ ]+\) )[^
> ]*[
> ]+
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: \[[ ]*\([0-9]+\) of \([0-9]+\)\] Compiling \([^ ]+\)[ ]+( \([^ ]+\), \([^ ]+\) )[^
> ]*[
> ]+
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: \[[ ]*\([0-9]+\) of \([0-9]+\)\] Compiling \[TH\] \([^ ]+\)[ ]+( \([^ ]+\), \([^ ]+\) )[^
> ]*[
> ]+
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Loading package \([^ ]+\) ... linking ... done.
> 
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: ^Preprocessing executables for \(.+?\)\.\.\.
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Linking \(.+?\) \.\.\.
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: 
> Building \(.+?\)\.\.\.
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Ok, \(?:[0-9]+\) modules? loaded\.$
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Failed, \(?:[0-9]+\) modules? loaded\.$
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Ok, modules loaded: \(.+\)\.$
> 
> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Failed, modules loaded: \(.+\)\.$
> 

This was probably intended to match

> process: "[1 of 1] Compiling Examples         ( /Users/nrolland/Sync/mactoastyClones/xquant2/content/notes/typerole/src/Examples.hs, interpreted )
> Ok, one module loaded.
> Collecting type info for 1 module(s) ... 
> "
> 
> regex: Ok, \(?:[0-9]+\) modules? loaded\.$
> 

Notice "one" in the response VS "1" in the match

**Comment by GeorgeCo** [comment]
I'm seeing this issue on ghc 8.4.3 with the latest version of haskell-mode, without stack. *haskell-process-log* shows:

> :set prompt2 "λ| "
> ...
> Some flags have not been recognized: prompt2

The issue seems to be that the code is using ":set prompt2" instead of  :set prompt-cont as adamse points out in 1569. This can be verified in ghci:

> :set prompt2 "λ| "
> Some flags have not been recognized: prompt2, λ| 
> λ>  :set prompt-cont  "λ| "
> λ> 
> 

Can somebody fix this in a new version of haskell-mode?
