### ISSUE TITLE
Fontification exception

### ISSUE THREAD

**Issue by ljli** [haskell/haskell-mode#1497]
I'm getting constantly this error: `error in process filter: Wrong type argument: number-or-marker-p, nil`.
A cursory look with the debugger suggests that the `match-data` set in the [`t` case in `haskell-lexeme-looking-at-qidsym`](https://github.com/haskell/haskell-mode/blob/master/haskell-lexeme.el#L127) isn't compatible with the `match-data` expected in [haskell-font-lock--select-face-on-type-or-constructor](https://github.com/haskell/haskell-mode/blob/master/haskell-font-lock.el#L323). The connecting piece is the [`haskell-lexeme-idsym-first-char`](https://github.com/haskell/haskell-mode/blob/master/haskell-font-lock.el#L484) keyword.
Specifically the second `match-group` is missing (or rather `'(nil nil)`, not sure how that is handled).

**Comment by gracjan** [comment]
Can you copy and paste what is in you haskell-interactive-mode buffer?

**Comment by ljli** [comment]
I think I'm not using haskell-interactive-mode or do you mean just the piece of code where this occurred? In that case I can't reproduce it unfortunately. I should have thought of that when I reported the issue. Luckily I reported the function call trace that lead to the issue. If the proposed explanation doesn't make sense to you, fell free to close the issue. I don't know what could have been the issue on my side, but then again I never had that problem before.

**Comment by gracjan** [comment]
Well, I need to write a unit test case for this problem.
