### ISSUE TITLE
Stop prompting to restart session

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#1498]
1. Enable `haskell-doc-mode`
2. Have working code with working session
3. Break code/session in some way (e.g. add something that doesn't type check, do a `stack build` after adding dependencies to Cabal file, reload buffer, agree to restarting session because Cabal file changed)
4. Try to fix the broken code
5. Put point somewhere in code on a function, etc.
6. Prompt comes up asking to restart session so it can provide type information, etc.
7. Hit `n` (as it of course won't actually load)
8. Start typing
9. Get interrupted by the prompt asking to restart session
10. Hit `n` again
11. Repeat steps 8-10 again and again until you scream.

**Comment by gracjan** [comment]
There is a `get-session` function that does much more that `get` :) As you see :)

**Comment by ivan-m** [comment]
This appears to be a duplicate of #1339.
