### ISSUE TITLE
Highlight URLs in Haddock comments

### ISSUE THREAD

**Issue by taktoa** [haskell/haskell-mode#1504]
It would be nice if URLs in Haddock comments were distinguished from the rest of the comment in some way (e.g.: boldface). Example code:
```haskell
-- | Examples:
-- Plain URL: <https://github.com/haskell/haskell-mode>
-- URL with label: <https://github.com/haskell/haskell-mode example>
-- Embedded image: <<https://i.imgur.com/foobar.png>>
-- Embedded image with title text: <<https://i.imgur.com/foobar.png example>>
-- Image with relative path: <<foobar.png>>
-- Image with relative path and title text: <<foobar.png example>>
foo :: a
foo = undefined
```
At the very least, it would be nice to avoid italicizing the text between the `/` characters, which currently happens with some URLs.

**Comment by gracjan** [comment]
`M-x goto-address-mode`: Activate URLs and e-mail addresses in the current buffer.

More info: http://www.gnu.org/software/emacs/manual/html_node/emacs/Goto-Address-mode.html
