### ISSUE TITLE
GHC case change for warning breaks haskell-mode check

### ISSUE THREAD

**Issue by slpopejoy** [haskell/haskell-mode#1513]
As of 8.0.2, GHC is now issuing warnings with a lower-case 'w':

```
src/Pact/Compile.hs:49:1-40: warning: [-Wunused-imports] …
    The import of ‘Hash’ from module ‘Pact.Types.Crypto’ is redundant
```

As a result, tools are not recognizing this and flagging things as errors or worse. Here's relevant results from a grep:

```
./haskell-interactive-mode.el:1032:             (not (string-match "^\n<interactive>:[-0-9]+:[-0-9]+:[\n ]+Warning:" response)))
./haskell-load.el:204:        ((string-match "Warning: orphan instance: " msg)
./haskell-load.el:398:    ((string-prefix-p "Warning:\n    " haskell-msg)
./haskell-load.el:521:             (type (cond ((string-match "^Warning:" error-msg)  'warning)
```

For `string-match`, using `[Ww]`fixes the issue and is presumably backward-compatible. Ie for line 521:
```
             (type (cond ((string-match "^[Ww]arning:" error-msg)  'warning)
```
works with my GHC 8.0.2 environment. `string-prefix-p` would need a better fix. I can't comment on the other places `string-match` is in use so I would request someone more familiar with this codebase make the fix.

NB: Why in [deity]'s name did they change the case in 8.0.2????? Do the haskell gods just enjoy breaking tools, because the GHC8 upgrade wasn't painful enough???

**Comment by ivan-m** [comment]
[This](https://github.com/ghc/ghc/commit/8a506104d5b5b71d5640afc69c992e0af40f2213) seems to be the commit they did it in (or at least some of their test-cases started to use the lower-case variant).

**Comment by gracjan** [comment]
Gods are whimsical and we were almost prepared: https://github.com/haskell/haskell-mode/pull/1168.

**Comment by slpopejoy** [comment]
Deeper research using a grep for "arning" in *.el files. Relevant finds:
1. [./haskell-compile.el:73](https://github.com/haskell/haskell-mode/blob/b0a5743f349e5e5b812291b5b06095aee1456656/haskell-compile.el#L73): `       ":\\(?6:\n?[ \t]+[Ww]arning:\\)?")` From #1477, which was aware of the case issue. not sure if it works with `[-Wfoo]` stuff that shows up though.
2. [./haskell-interactive-mode.el:1032](https://github.com/haskell/haskell-mode/blob/b0a5743f349e5e5b812291b5b06095aee1456656/haskell-interactive-mode.el#L1032): `             (not (string-match "^\n<interactive>:[-0-9]+:[-0-9]+:[\n ]+Warning:" response)))` This is a hard one to test as it's unclear why it's avoiding warnings; in my REPL errors are getting clobbered with weird types no matter what. Nonetheless, would seem to be safe to change to `[Ww]`.
3. [./haskell-load.el:204](https://github.com/haskell/haskell-mode/blob/b0a5743f349e5e5b812291b5b06095aee1456656/haskell-load.el#L204): `       ((string-match "Warning: orphan instance: " msg)` This is broken irrespective of case change.
4. [./haskell-load.el:398](https://github.com/haskell/haskell-mode/blob/b0a5743f349e5e5b812291b5b06095aee1456656/haskell-load.el#L398): `   ((string-prefix-p "Warning:\n    " haskell-msg)` Also broken irr. of case change
5. [./haskell-load.el:521](https://github.com/haskell/haskell-mode/blob/b0a5743f349e5e5b812291b5b06095aee1456656/haskell-load.el#L521): `            (type (cond ((string-match "^Warning:" error-msg)  'warning)` this is the main one for this issue, easily fixed with [Ww]
6. [./inf-haskell.el:84](https://github.com/haskell/haskell-mode/blob/b0a5743f349e5e5b812291b5b06095aee1456656/inf-haskell.el#L84): `   ("^\\(.+?\\):\\([0-9]+\\):\\(\\([0-9]+\\):\\)?\\( \\|\n *\\)\\([Ww]arning\\)?"`  case is fine, again not sure it handles `[-Wfoo]` stuff.

Proposal: I go ahead and introduce `[Ww]` for 2-5, but will only test the results for 5, and assume it doesn't break things further for the other cases. Please LMK if this is acceptable.

**Comment by gracjan** [comment]
Yes, good enough! Go ahead!
