### ISSUE TITLE
"Collecting Type Info for X modules ..." showing up, taking seconds to complete w/ GHC 8.0.2

### ISSUE THREAD

**Issue by slpopejoy** [haskell/haskell-mode#1514]
When I compare a 7.10.3 project with a GHC 8.0.2 project (just upgraded, so it's apples to apples), I notice that C-c C-l loading into the repl takes significantly longer with 8.0.2. Specifically, the message "Collecting type info for X module(s) ..." appears and stays around for many seconds (depending on the size of the load), which accounts for the additional delay.

I tried to understand what exactly is happening in the emacs code when this displays but I can't figure it out: https://github.com/haskell/haskell-mode/blob/master/haskell-load.el#L92

To troubleshoot, I compared loading in a `stack ghci` on the terminal (`:load Foo.Bar`), and GHC8 is faster than 7.10 (yay!).

**Comment by ivan-m** [comment]
I wonder whether this has anything to do with #1200 (specifically the completion support requiring all the modules being loaded).  I'm not sure if it's possible to disable this to test if it is indeed the cause of this.

**Comment by slpopejoy** [comment]
Yes, that's definitely it. If you issue `:unset +c`, the problem goes away, and returns if you issue `:set +c`.

**Comment by gracjan** [comment]
This report is definitelly a deplicate of #1436. Upvote there. Or better yet submit a PR.

**Comment by slpopejoy** [comment]
I added `:unset +c` as a workaround for that issue

**Comment by slpopejoy** [comment]
@gracjan what PR? to make `:set +c` optional via a defcustom?

**Comment by gracjan** [comment]
Yes, `defcustom` for `:set +c` plus a logic to tell people using `C-c C-t` that they are not getting type information because there is no `:set +c` available.
