### ISSUE TITLE
Why haskell-forward-sexp?

### ISSUE THREAD

**Issue by vasanthaganeshk** [haskell/haskell-mode#1517]
+ Haskell is not full of sexp like lisp, so why do we need this?
+ target file `haskell-mode.el`

**Comment by vasanthaganeshk** [comment]
As a follow up why do we need `haskell-collapse`? It depends on `haskell-collapse-sexp`.

**Comment by ivan-m** [comment]
They're in `haskell-collapse.el`, not `haskell-mode.el`.

As for what they are for: to provide the ability to collapse the definition of a function so it doesn't take up vertical space if you want to skim through a source file.

**Comment by gracjan** [comment]
Emacs has default keybindings for moving cursor by expressions, statements, definitions, etc:
 [Expressions](https://www.gnu.org/software/emacs/manual/html_node/emacs/Expressions.html)

Many more interesting functions are build on top of these primitives:: [Marking-Objects](https://www.gnu.org/software/emacs/manual/html_node/emacs/Marking-Objects.html).

**Comment by vasanthaganeshk** [comment]
@ivan-m This almost never works in Haskell. In lisp

```
(define x (y)
    (let (.
           .
           .
           .
           .)exp))
```

in this case it might make sense to collapse the let or the whole define part.

```
f ans (-1) y = ans
f ans x y
  | x == 0 && (null ans) = ans
  | otherwise = f ((i ++ " " ++ j):ans) (x-1) (y+1)
  where i = show x
             j = show y
```

In this case if we select the whole definition of `f` and collapse it, it won't work. That is because `haskell-collapse` is practically a while loop over `haskell-collapse-sexp`. This type of haskell code is not an s-expression.

In Haskell you cannot collapse expressions. I think this problem is just as hard as the indentation problem.

One exception is the collapse will work if there are braces, but most of the times we don't write haskell that way.

**Comment by ivan-m** [comment]
I'm not saying if it works correctly or not as I don't use it myself; but that I believe is what they're there for.

**Comment by ivan-m** [comment]
And you can treat Haskell code as containing sexp- like expressions; that's what structured Haskell mode does.

**Comment by vasanthaganeshk** [comment]
@gracjan Moving by expression won't work either (i.e. by sexp)

Take this example in lisp:

```
(define x (y)
    (let (.
           .
           .
           .
           .)exp))
```

In this example, if you place the cursor at the start you, if you invoke next-sexp command, it lands at the end of the expression. 

Take the haskell example:

```
foo ans (-1) y = ans
foo ans x y
  | x == 0 && (null ans) = ans
  | otherwise = foo ((i ++ " " ++ j):ans) (x-1) (y+1)
  where i = show x
             j = show y
```
Here the same move by sexp won't work. If you place the cursor at the start of the function definition `foo`, then it goes to the end of the `foo` i.e. it goes from `|foo` to `foo|`. That is not useful. (It can also go from start of a bracket to the end of a bracket...)

This is simply because Haskell is not [s-expression](https://en.wikipedia.org/wiki/S-expression).

I'm not sure how you can get to the end of an expression easily in haskell (I think it could be just as hard as indentation problem).

**Comment by vasanthaganeshk** [comment]
But if you bring [structured-haskell-mode](https://github.com/chrisdone/structured-haskell-mode) into picture like @ivan-m said, then this collapse thing, move by expression and all its cousins functions will make sense.

**Comment by gracjan** [comment]
Collapse for sure needs tree knowledge of source code. In lisp parentheses are there and it is simple.

Does SHM provide its own collapsing methods?

Can we in haskell-mode provide a sensible collapsing behavior despite lack of SHM support?

**Comment by vasanthaganeshk** [comment]
I'm not sure we can do that, but how about being able to collapse what ever is marked?

**Comment by vasanthaganeshk** [comment]
I think it has something similar to go to end of exp, we can model collapse around that (not without depending on SHM though).

**Comment by gracjan** [comment]
Collapse what is marked does not look like a useful functionality. This is not how people use collapse for.

**Comment by ivan-m** [comment]
Can this be closed since the intent behind these functions is now known (and let #1518 be for fixing them)?

**Comment by vasanthaganeshk** [comment]
@gracjan I agree that that is not the right way to do it. In SHM it is done with [haskell-src-exts](https://github.com/haskell-suite/haskell-src-exts). That is the code is parsed and the tree is identified and then operations are done on them (that is how it is done is SHM).

**Comment by vasanthaganeshk** [comment]
One more way that we can implement collapse is by using indentation. That is, the code is already split into trees and indented nicely, we can use that.

**Comment by gracjan** [comment]
Anyway, lets close this question.
