### ISSUE TITLE
make check-conventions fails

### ISSUE THREAD

**Issue by vasanthaganeshk** [haskell/haskell-mode#1520]
`haskell-code-conventions.el` uses a function  `el-search--search-pattern` from `el-search` module. `el-search--search-pattern` is not available in recent versions of `el-search`. Click [here](https://travis-ci.org/haskell/haskell-mode/jobs/243732195#L1198) to see travis complaining.

**Comment by gracjan** [comment]
This was a good idea but the value delivered wasn't as big as hoped. Basically check=conventions should be removed as it does not bring much to the table.

**Comment by vasanthaganeshk** [comment]
It checks for the lexical binding thing, no tabs for indentation, no spaces or tabs at the end of the line, it could be useful.

I thought it should work with the older version of `el-search` and I copied the definitions of the missing functions from the older version and `make` stops complaining (the code is under GPL-V3, I just put FSF's copyright). But it will need some refactoring later on.

**Comment by vasanthaganeshk** [comment]
Fixed in #1521
