### ISSUE TITLE
Jumping to definition is broken for qualified names

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1523]
I'm using `hasktags` to generate tags file. This works fine, but if name under point is qualified, `haskell-mode-jump-to-def-or-tag` is not clever enough to strip the prefix up to (and including) the last dot. For example, `T.strip` won't find `strip` even if it's in the tags file.

Maybe `haskell-ident-at-point` is the right place to drop the prefix, but I'm not sure.

**Comment by mrkkrp** [comment]
I can prepare a PR, but I need to know where is the best place to add the stripping code.

**Comment by mrkkrp** [comment]
@gracjan Ping. Any comment on this?

**Comment by gracjan** [comment]
Technically `ident` in haskell is qualified. I would say the correct place to drop qualifiecation is just before invoking tags functions.
