### ISSUE TITLE
haskell mode hangs on startup and on every edit

### ISSUE THREAD

**Issue by rubenmoor** [haskell/haskell-mode#1526]
When I open a `.hs` file in my project, e.g. `Main.hs`, the file never shows, only "Sorting declarations in Main.hs...done"

I can than hit `C-g` twice and I see the loaded file. Once I edit a few letters or add a new empty line, everything freezes again and I have to hit `C-g` twice again to even be able to exit emacs.

There is no problem editing the `.cabal` file. 

Also, it appears that I can edit without problems as long as the project compiles completely. But I have a major refactoring to do now and thus my current project won't compile for a while.

I can uninstall haskell-mode and editing works fine.

I am running haskell mode from "melpa" (same problem with "melpa-stable") on nixos with nix-shell (I am not using stack). I installed `haskell mode` via emacs prelude.

**Comment by ivan-m** [comment]
What is your haskell-mode configuration?

I wonder if it's because you've got one of the doc-modes enabled that keeps trying to query the running session, which you obviously don't want as the code won't compile at the moment.

**Comment by rubenmoor** [comment]
I tried to figure out further configuration options of haskell-mode (because of ivan-m's comment) and found this haskell-emacs wiki article:

https://github.com/serras/emacs-haskell-tutorial/blob/master/tutorial.md

I installed hasktags and happy (following the instructions in the wiki article).

`nix-env -iA nixos.haskellPackages.hasktags nixos.haskellPackages.happy`

and now everything works fine.

Could it be that the haskell-mode documentation isn't exactly explicit about required haskell packages and binaries on `PATH` or have I just overlooked it?

http://haskell.github.io/haskell-mode/manual/latest/Installation.html#Installation

**Comment by rubenmoor** [comment]
The configuration options seem a bit opaque to me.

I haven't touched any of the custom variables of the "Haskell Doc Group". 

That's my custom variables:

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(haskell-mode-hook
   (quote
    (capitalized-words-mode haskell-indent-mode interactive-haskell-mode
                            (lambda nil
                              (run-hooks
                               (quote prelude-haskell-mode-hook))))))
 '(haskell-process-log t)
 '(haskell-stylish-on-save t)
 '(package-selected-packages
   (quote
    (markdown-mode yaml-mode scss-mode geiser company-anaconda anaconda-mode zop-to-char zenburn-theme which-key volatile-highlights smex smartrep smartparens smart-mode-line rainbow-mode rainbow-delimiters ov operate-on-number move-text magit json-mode js2-mode imenu-anywhere ido-ubiquitous helm-projectile helm-descbinds helm-ag haskell-mode guru-mode grizzl god-mode gitignore-mode gitconfig-mode git-timemachine gist flycheck flx-ido expand-region evil-visualstar evil-surround evil-numbers elisp-slime-nav editorconfig easy-kill discover-my-major diminish diff-hl crux company-auctex cdlatex browse-kill-ring beacon anzu ace-window))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by gracjan** [comment]
What is `prelude-haskell-mode-hook`?

**Comment by rubenmoor** [comment]
The `prelude-haskell-mode-hook` was set by Emcas Prelude, cf. 

https://github.com/bbatsov/prelude

I installed Haskell mode via Emacs Prelude.

**Comment by rubenmoor** [comment]
For now it looks that I had `stack` installed as well and this seems to interfere with the nixos-based setup (that only uses cabal and the nix-shell for `cabal-configure`).

I have troubles setting the variables for haskell-mode, which again is more a problem of emacs-prelude and my lack of understanding of it.

**Comment by beauby** [comment]
Running into the same issue (also using `emacs-prelude` and the Haskell platform). Did you find a solution @rubenmoor?

**Comment by rubenmoor** [comment]
@beauby see comment above: I had stack in the mix, interfering with my ghc from nixos.

**Comment by omninonsense** [comment]
For anyone elese having this issue:

@rubenmoor I think the actual problem might've been that `haskell-mode` was downloading the latest GHC in the background via stack. I think running `stack build` (or something similar which will download) makes this go away.

However, depending on your OS, this might introduce different problems.
