### ISSUE TITLE
[Feature request] Truncate the amount of text being displayed in interpreter process's buffer.

### ISSUE THREAD

**Issue by vasanthaganeshk** [haskell/haskell-mode#1536]
In interpreter, displaying a lot of text (output of an expression) might make Emacs hang. So we could truncate what is being displayed (See [this](https://emacs.stackexchange.com/questions/32449/content-was-split-in-the-functions-of-comint-preoutput-filter-functions/32459)). We could hide the text being displayed using `hideshow.el` or by using the collapse functionality.

**Comment by ivan-m** [comment]
Isn't that what `C-c C-c` (killing the expression) is for?

**Comment by vasanthaganeshk** [comment]
Yes you are right. That should be enough. I'll close this issue.
