### ISSUE TITLE
Support tramp

### ISSUE THREAD

**Issue by k-bx** [haskell/haskell-mode#1559]
When you open project via tramp, if you launch `haskell-compile` you get something like:

```
cd /ssh:ubuntu@builder:/home/ubuntu/workspace/proj/ && stack build
/bin/sh: 2: cd: can't cd to /ssh:ubuntu@builder:/home/ubuntu/workspace/proj/

HsCompilation exited abnormally with code 2 at Tue Oct  3 13:13:07

```

Would be very handy if `haskell-compile` would work under tramp. Thank you!

**Comment by dredozubov** [comment]
I'm interested in this feature as well!

**Comment by dredozubov** [comment]
@k-bx Are you aware of any workarounds?

**Comment by k-bx** [comment]
No, I am not
