### ISSUE TITLE
Electric-pair-mode causes emacs to hang when writing comments in haskell-mode

### ISSUE THREAD

**Issue by ghost** [haskell/haskell-mode#1577]
Here's how to hang* emacs 10 out of 10 times in haskell mode:

1. Enter haskell-mode and electric-pair-mode

2. Enter a block comment

`{--}`

3. Try to insert hard brackets inside the comment, as such:

`{-[]-}` 

This will hang* emacs but wont produce a error in ~/.xsession-errors

This previously said crash, but hang is more accurate (sorry :c)

**Comment by purcell** [comment]
I can't reproduce this on a recent Emacs with the latest `haskell-mode`. Does it perhaps depend on the contents of the rest of the file?

**Comment by 4lph4-Ph4un** [comment]
I get exactly the same results! Disabling electric-pair-mode will prevent the crash.

**Comment by purcell** [comment]
> I get exactly the same results! Disabling electric-pair-mode will prevent the crash.

Could you provide reproduction instructions perhaps, including Emacs version?

**Comment by 4lph4-Ph4un** [comment]
Sure! :) 
GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)

**Comment by purcell** [comment]
Thanks. I can reproduce this in Emacs 25.1-25.3 inclusive, but not in 26.1 or later versions. So my feeling is that it's an Emacs bug. Unsure how much effort to put into working around this for that older version. There's a configurable inhibit function for electric pairing which could conceivably be used to short-cut this problem selectively in problematic Emacs versions.

**Comment by 4lph4-Ph4un** [comment]
Yes, this might be exactly how it is. I currently have that version on my WSL and I'm not sure if I can upgrade my Emacs there. If anyone has info on if it is possible to run newer versions there I think I'd give it a go. Otherwise, I'm fine by just solving it by configuring electric-pairing differently when Haskell-mode is on for now :) Thanks for the sanity-check, though!

**Comment by purcell** [comment]
A selective workaround is the following:
```el
(when (eq 25 emacs-major-version)
  (defun sanityinc/inhibit-bracket-inside-comment-or-default (ch)
    (or (nth 4 (syntax-ppss))
        (funcall #'electric-pair-default-inhibit ch)))
  (add-hook 'haskell-mode-hook
            (lambda ()
              (setq-local electric-pair-inhibit-predicate 'sanityinc/inhibit-bracket-inside-comment-or-default))))
```

**Comment by purcell** [comment]
I've included this workaround in `haskell-mode` directly now.
