### ISSUE TITLE
Binding in interactive-haskell-mode-map breaks Emacs conventions

### ISSUE THREAD

**Issue by pkkm** [haskell/haskell-mode#1583]
`interactive-haskell-mode-map` binds `C-c v c`, which breaks the [official Emacs key binding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html):

> Don't define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.

**Comment by purcell** [comment]
Thanks, fixed.
