### ISSUE TITLE
':' doesn't get recognized as a char

### ISSUE THREAD

**Issue by neongreen** [haskell/haskell-mode#1615]
![image](https://user-images.githubusercontent.com/1523306/45957821-3c670c80-c016-11e8-95e2-f7e71f778a04.png)

**Comment by ivan-m** [comment]
`':'` seems to have `haskell-constructor-face` (with the quotes being `default`) applied to it still, instead of `font-lock-string-face` as in `'a'`.

This isn't the case with `":"` though.

Wild guess: it's part of what allows you to use `':` in type-signatures causing it.

**Comment by alexpeits** [comment]
This issue was related: https://github.com/haskell/haskell-mode/issues/1508 and I think https://github.com/haskell/haskell-mode/pull/1578 causes the current issue
