### ISSUE TITLE
New release broke indentation with TAB key

### ISSUE THREAD

**Issue by vlatkoB** [haskell/haskell-mode#1644]
Just installed the latest version and it broke indenting lines with the TAB key.

1) Before, pressing TAB was circleing through all the `valid` indentation positions.
    Now, it just goes all the way.
2) Before, pressing TAB in the middle of the line would indent the line.
    Now, it inserts spaces at the cursor position (regardless if in the middle of the line or func/var name).

Anyone else seeing this behaviour?

**Comment by tshinohara** [comment]
Seeing the same behaviour too.

**Comment by fommil** [comment]
almost certainly https://github.com/haskell/haskell-mode/pull/1633

**Comment by purcell** [comment]
Reverted in #1646 - sorry, folks, I was trying to merge a few neglected PRs while I had some time free. :-)

**Comment by vlatkoB** [comment]
Thanks for quick reaction. :-)
Upgraded to latest and all seems to work perfectly.
