### ISSUE TITLE
Character decoding errors with haskell-mode-stylish-buffer

### ISSUE THREAD

**Issue by rvl** [haskell/haskell-mode#1654]
Hi! I was trying to run `haskell-mode-stylish-buffer` on a UTF-8 file with a © symbol in it.

It would fail and the `*haskell-mode*` buffer reported:
```
stylish-haskell: <stdin>: hGetContents: invalid argument (invalid byte sequence)
```

Outside of emacs, `stylish-haskell` works fine on that file.

When I debugged a bit by changing `haskell-mode-stylish-haskell-path`, I found that Emacs was converting my utf-8 haskell source file into the latin1 encoding!

If I set the emacs coding system variables before running `haskell-mode-stylish-buffer`, then it would work.

```emacs
(advice-add
 'haskell-mode-stylish-buffer
 :around (lambda (orig-fun &rest args)
           (let ((coding-system-for-read 'utf-8)
                 (coding-system-for-write 'no-conversion))
             (apply orig-fun args))))
```

I think `haskell-mode` should set these variables before running the process. `stylish-haskell` assumes all files are UTF-8 unless given the `--no-utf8` flag.

**Comment by purcell** [comment]
Thanks. Does b8f1b5d do the trick for you?

**Comment by rvl** [comment]
I just tested this fix (with advice removed), and it works. Thanks!

**Comment by purcell** [comment]
Nice, thanks for confirming.
