### ISSUE TITLE
How to troubleshoot `C-c C-l` making wrong choice of command?

### ISSUE THREAD

**Issue by capn-freako** [haskell/haskell-mode#1657]
I have a case where `C-c C-l` is making the wrong choice of command.
It's choosing `cabal repl` (or, maybe, just `ghci`; I'm not sure which.) even though my project meets the criteria for choosing `stack ghci`:

1. No `cabal.sandbox.config` files in current directory, or parents.
1. `stack.yaml` file present in parent directory.
1. `stack` executable available on the PATH.

How can I troubleshoot this?

**Comment by purcell** [comment]
Looking at the [code](https://github.com/haskell/haskell-mode/blob/0d5e4136668166c0edb259bb9accf09d257dcf68/haskell-customize.el#L433-L469), I think  the issue here must have been that Emacs could not find the "stack" executable on your path. Does that sound plausible?

**Comment by capn-freako** [comment]
Hi,

Thanks for your reply!

I suppose it is; despite my note 3, above, I suppose that _Emacs_ could've been working with a different definition of `PATH` than the one apropos to the shell I was in when I tested for `stack`'s presence on my path. I guess I'm really not sure and have no way of recreating the exact environment that was in force when I originally posted.

If I bump into this again, I'll test that and post what I find here.

Thanks!
-db

**Comment by purcell** [comment]
FWIW, [`exec-path-from-shell`](https://github.com/purcell/exec-path-from-shell/) can be useful for helping Emacs find executables in the way you expect.

**Comment by capn-freako** [comment]
Thanks, Steve!

Happy New Year!
-db

**Comment by purcell** [comment]
You too!
