### ISSUE TITLE
format error in .texi

### ISSUE THREAD

**Issue by forskning** [haskell/haskell-mode#1662]
/doc/haskell-mode.texi

you need a comma ',' after the closing brace '}' on the following line

`hook that will run and generate Emacs @xref{Tags,,,emacs} for the whole`

**Comment by forskning** [comment]
[patching haskell-mode](https://nurmi-labs.blogspot.com/2017/01/patching-haskell-mode.html) (blog Post)

also lists 4 unexpected results from running 'make check'

FAILED  haskell-guess-module-name
FAILED  haskell-process-wrapper-function-non-identity
FAILED  test-haskell-process--with-wrapper-compute-process-log-and-command-cabal-repl
FAILED  test-haskell-process--with-wrapper-compute-process-log-and-command-ghci

**Comment by forskning** [comment]
The linked to blog Post is over 2 years old.

@purcell

Have you any thoughts on the FAILED tests?

**Comment by purcell** [comment]
> Have you any thoughts on the FAILED tests?

Nope, and I don't have time to investigate at this point, but I'd be happy to accept a PR.

**Comment by forskning** [comment]
The blog Post (circa 2017) used emacs-24.3 running Windows XP.

Currently I'm running (on Linux) emacs-26.2.90 pretest; owing the below bug, which also affected Slackware Linux.

GNU bug report logs - #35739
[w32] Bad signature from GNU ELPA for archive-contents

Owing to the above, presently I'm not really in a position to do any testing.

The .texi file format error would seem however to be a simple correction for a single commit (by someone who has made previouls commits to the repository) and probably would not need a PR (with a concomitant review process).

NB: There might be other changes indicated (to support byte-compile) on recent emacs releases.

**Comment by purcell** [comment]
TeXinfo file fixed, and compilation issues resolved, at least for Emacs >= 26. Thanks!
