### ISSUE TITLE
C-a in interactive-mode should stop after prompt

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-mode#1666]
C-a should stop after prompt when on first line, but stop at BOL in following lines of a multiline-edit.

Ideally it should stop at second prompt then. But not leave that  line, (was bug #1611).

**Comment by purcell** [comment]
Okay, I've committed a fix: <kbd>C-a</kbd> now consistently moves point to the beginning of the line _unless_ the current prompt is on the line, in which case it moves point to just after the prompt.
