### ISSUE TITLE
Emacs 24.4 added subr-x

### ISSUE THREAD

**Issue by apparluk** [haskell/haskell-mode#1671]
Looks like the README.md file should be updated to reflect the implications of the following commit.

https://github.com/haskell/haskell-mode/commit/1717bffc2d3b555516cf439213bd4e50b1cacb6a
if-let is a thing
committed Oct 19, 2018

As the haskell-mode.texi file lists the version as 16.1-git I would suggest waiting for preparations to begin on a new haskell-mode release prior to updating that file's two relevant lines regarding the Emacs minimum version number.

@fommil

**Comment by purcell** [comment]
I've noted in the README that Emacs 24.4 is necessary. No new release is currently planned as there is no active maintainer.
