### ISSUE TITLE
haskell-process-load-file cannot load file

### ISSUE THREAD

**Issue by ccqpein** [haskell/haskell-mode#1676]
I recently change `haskell-process-type` to `'cabal-new-repl` because I need support cabal new build for my project. 

Today I write some demo (just one code file) code and use `C-c C-l` call `haskell-process-load-file` to load whole file to REPL, haskell-mode will show me error message about my code let me fix. However, when mini buffer says ok, all code error fixed, in REPL, I cannot run my function in my haskell code. It shows REPL cannot find symbol. 

When I change to `cabal-repl`, problem disappears.

**Comment by purcell** [comment]
Is this still an issue? More information would be needed, e.g. which versions of the various tools you have available on your executable path.

**Comment by ccqpein** [comment]
@purcell , thanks for your reply. I will test if issue still here this evening and put more informations here.

**Comment by ccqpein** [comment]
@purcell It looks fine, I make `haskell-process-type` to `auto`, and it works well.

+ when I in my cabal project, it can run `haskell-process-load-file` with any problem.
+ when I write a single file of haskell code. It also run well.

However: I have error messages of `Could not find module XXX` on `import` of my code. Even all repl and cabal work fine.

**Comment by purcell** [comment]
Ah. Flycheck is completely separate from `haskell-mode`, sorry. The default backend `flycheck` uses might not be picking up the configuration of your project. You might like to try [`dante`](https://github.com/jyp/dante) - it can be a little fiddly to configure but it is faster than the default `flycheck` backend and also offers functionality like jump-to-definition.
