### ISSUE TITLE
Crashes Emacs on writing "(" in a multiline comment

### ISSUE THREAD

**Issue by Serpial** [haskell/haskell-mode#1679]
E.g.
`{-  I am really sad : ( -}`

The emacs will crash when I enter the opening bracket. I don't know if this is just for me but it only does it in haskell-mode

**Comment by purcell** [comment]
Duplicate of https://github.com/haskell/haskell-mode/issues/1577 -- please see the solution posted there. This is specific to Emacs 25.x.
