### ISSUE TITLE
Getting error when installing electric-pair-inhibit-predicate

### ISSUE THREAD

**Issue by presci** [haskell/haskell-mode#1682]
I am getting error when I try to run make EMACS=/usr/bin/emacs. emacs version = 26.1
`
In toplevel form:
haskell-mode.el:857:50:Error: assignment to free variable `electric-pair-inhibit-predicate'
make: *** [Makefile:69: build-26.1/haskell-mode.elc] Error 1
The command '/bin/sh -c unzip master.zip && cd haskell-mode-master && make EMACS=/usr/bin/emacs' returned a non-zero code: 2`

Does anyone know how to resolve the issue?

**Comment by purcell** [comment]
Ugh, sorry, my bad: let me take a look at that.

**Comment by purcell** [comment]
Fixed now, thanks for reporting this.
