### ISSUE TITLE
Misleading documentation for Interactive Haskell keybindings

### ISSUE THREAD

**Issue by ajpaon** [haskell/haskell-mode#1685]
The documentation for haskell-mode says:

```
to enable ‘interactive-haskell-mode’, use the following:

    (add-hook ’haskell-mode-hook ’interactive-haskell-mode)
```

And the manual lists the following keybindings for Interactive haskell:

```
‘M-n’
     is bound to ‘haskell-goto-next-error’
‘M-p’
     is bound to ‘haskell-goto-prev-error’
‘C-c M-p’
     is bound to ‘haskell-goto-first-error’
```

But it seems like those keybindings were removed in #1380.

I needed to add the following to my init.el to get them back:

```
(eval-after-load "haskell"
  '(progn 
     (define-key interactive-haskell-mode-map (kbd "M-n") 'haskell-goto-next-error)
     (define-key interactive-haskell-mode-map (kbd "M-p") 'haskell-goto-prev-error)
     (define-key interactive-haskell-mode-map (kbd "C-c M-p") 'haskell-goto-prev-error)))
```

**Comment by poscat0x04** [comment]
The documentation shipped with the elpa package should be up to date.

**Comment by ajpaon** [comment]
I installed from melpa and I just upgraded to make sure. The same misleading documentation is still there.

**Comment by purcell** [comment]
Thanks, I've updated the docs.

**Comment by purcell** [comment]
Note also that `interactive-haskell-mode` sets `next-error-function`, so you should be able to use `next-error` (<kbd>C-x `</kbd> by default) to jump between errors, as you may be accustomed to doing with grep and compilation results.

**Comment by ajpaon** [comment]
Thanks for the fix! And the pointer to next-error.
