### ISSUE TITLE
Multiline GHCi prompt broken

### ISSUE THREAD

**Issue by Janfel** [haskell/haskell-mode#1689]
Hello,
it seems that `ghci` recently renamed the setting `prompt2` to `prompt-cont`. I am using `ghc 8.6.5` and the multiline prompt is broken for me.

The source of the issue is this line https://github.com/haskell/haskell-mode/blob/f63f315d538c3de6fbc05d872cd6fd733bbf19fc/haskell-commands.el#L122 where `prompt2` is set. Changing this to `prompt-cont` fixes the problem.

**Comment by purcell** [comment]
Thanks. I've pushed a commit which should resolve this.
