### ISSUE TITLE
please tag a new release

### ISSUE THREAD

**Issue by thkoch2001** [haskell/haskell-mode#1693]
Apparently people asked for regular releases before:

https://github.com/haskell/haskell-mode/issues/103 distro wants a stable tarball release
https://github.com/haskell/haskell-mode/issues/145 Make 13.6 release
https://github.com/haskell/haskell-mode/issues/842 Perhaps tag a release? Monthly releases?
https://github.com/haskell/haskell-mode/issues/1387 Release a new version

The latest release (16.1) is from 2016. Please release a new version so that I can update the debian package. Also your users from melpa-stable will thank you!

**Comment by purcell** [comment]
Thanks, done: 17.1.
