### ISSUE TITLE
Types that don't implement Show can be implicitly printed

### ISSUE THREAD

**Issue by FernandoBasso** [haskell/haskell-mode#1695]
I have noticed that things that don't have an instance of `Show` can be somehow printed, or displayed if I run the buffer with `C-c C-l`.

![image](https://user-images.githubusercontent.com/6560620/73876137-38b3de80-4835-11ea-9764-77391c87d3d7.png)

Why is that? Can it be disabled? In a normal REPL (on a terminal outside of Emacs), those would give an error because data constructors for types not deriving (or implementing) `Show` can't be printed, and functions don't implement `Show` either.

I am studying trough Haskell From First Principles, and was not getting the errors when trying to display things that don't implement `Show`, and was confused for a while until I tried in a normal REPL. Couldn't find this behavior in the docs either.

**Comment by purcell** [comment]
Well spotted. I hadn't noticed this myself. Turns out there's [special handling for this case](https://github.com/haskell/haskell-mode/tree/master/haskell-interactive-mode.el). You can `(setq haskell-interactive-types-for-show-ambiguous nil)` to disable this.
