### ISSUE TITLE
`comment-or-uncomment-region` should not accidentally create Haddock comments

### ISSUE THREAD

**Issue by Ptival** [haskell/haskell-mode#1700]
Consider a declaration:

```
data MyType
  = C1
  | C2
  | C3
  deriving ( Show )
```

Selecting the area of the last two constructors and commenting them out yields:

```
data MyType
  = C1
  -- | C2
  -- | C3
  deriving ( Show )
```

Sadly, those comments, because of the pipe, are interpreted as Haddock comments, which makes Haddock freak out and yell `parse error` on the `deriving` line.

**Comment by purcell** [comment]
Yeah, I get your point here, and I can see it being inconvient very occasionally, but I don't think it merits writing fiddly extra elisp code to handle this. Right now the commenting is handled by built-in Emacs mechanisms, and it would have to be customised to handle this and ensure it was reversible. So from my perspective, this is a "won't fix", sorry.

**Comment by Ptival** [comment]
Haha, I understand, it's also very easy to manually fix once you realize what happened. It was just surprising to have working, compiling code suddenly not parse at Haddock time, after having only commented out constructors! ^^

**Comment by purcell** [comment]
It's a spooky edge case, certainly!
