### ISSUE TITLE
Hoogle results missing URL

### ISSUE THREAD

**Issue by vlatkoB** [haskell/haskell-mode#1720]
Local `hoogle` query results were displaying URL, but that disappeared in one of last commits.

For example, before it was like this:
`Prelude class Eq a => Ord a -- https://hackage.haskell.org/package/base/docs/Prelude.html#t:Ord`

but now it is displayed as
`Prelude class Eq a => Ord a`

Url was very convenient to open a web page directly from `emacs`.

Was that removed on accident or is there some new setting that controls this behaviour or a new functionality that would allow opening `hoogle` result in browser?

**Comment by vlatkoB** [comment]
This is my `hoogle` command
`(haskell-hoogle-command                          "hoogle --color -l --numbers --count=10")`

**Comment by vlatkoB** [comment]
Looks like this [PR](https://github.com/haskell/haskell-mode/pull/1719) removed the functionality and made a breaking change.
If anyone else is missing it, copy "old" `haskell-hoogle` function from [here](https://github.com/haskell/haskell-mode/pull/1719/commits/33be58b8847db1e4d2f551ca03b8a383abf22ca3).

Can you make it somehow configurable, or maybe provide also the "old" function?

**Comment by purcell** [comment]
Pinging @galagora on this one. :-)

**Comment by galagora** [comment]
My previous commit stopped `haskell-hoogle` from using your custom `haskell-hoogle-command` (the `-l` flag is what makes the URL show). I opened a PR that restores the desired behaviour.

**Comment by vlatkoB** [comment]
Great, thanks for swift action. :-)
