### ISSUE TITLE
Disable scanning declarations / sorting declarations messages?

### ISSUE THREAD

**Issue by soupi** [haskell/haskell-mode#1726]
Hi!

When using something like imenu set to automatically refresh the menu [these](https://github.com/haskell/haskell-mode/blob/e72677668f5fc7cc148008e885a0f256e245dd43/haskell-decl-scan.el#L554) [messages](https://github.com/haskell/haskell-mode/blob/e72677668f5fc7cc148008e885a0f256e245dd43/haskell-decl-scan.el#L583) keep appearing at the line buffer whenever I move the cursor which can be fairly distracting.

Is it possible to disable them?

Thanks!

**Comment by purcell** [comment]
Yes, I think they could be deleted entirely. Want to submit a PR?

**Comment by soupi** [comment]
Will do. Thanks!
