### ISSUE TITLE
Better indentation rules

### ISSUE THREAD

**Issue by mcandre** [haskell/haskell-mode#173]
haskell-mode often indents code to weird positions; hit `(indent-region (point-min) (point-max))`, and you'll see imports indented an extra level inward, and case expressions indented multiple levels inward past where it makes any sense.

Does the new 13.7 version improve this behavior?

**Comment by gracjan** [comment]
Note: we just merged hi2 indentation mode as the new `haskell-indentation`. This should solve a lot of issues. I'm closing this particular issue report, but do not hessitate to report specific issues if you encounter further problems.
