### ISSUE TITLE
The package appears to be removed from ELPA and MELPA.

### ISSUE THREAD

**Issue by FrankDMartinez** [haskell/haskell-mode#1730]
As it says on the tin. Where does one get the package now?

**Comment by walseb** [comment]
It's there for me atleast https://melpa.org/#/haskell-mode

**Comment by FrankDMartinez** [comment]
Hmm, when I followed the "Quick Installation" instructions, "haskell-mode" is not in the list of packages. Does emacs need to be restarted after editing the configuration file?

**Comment by FrankDMartinez** [comment]
Some error messages which appeared when trying to refresh the package contents:

> Failed to download 'melpa-stable' archive. 
> Failed to download 'melpa' archive.

**Comment by Sofviic** [comment]
After following the instruction on the README.md, I closed all instances of emacs that were running, launched it again and was able to install it.
Check your list of installable packages, can you find it in "M-x package-list-packages"?

**Comment by FrankDMartinez** [comment]
@Sofviic It is in *that* list, yes, with versions "20180601.143" and "16.1". Are either of those current? I thought there was a more recent one. In any event, this does not explain the "Fail to download" messages.

**Comment by purcell** [comment]
What URL do you have for MELPA in `package-archives`?

**Comment by FrankDMartinez** [comment]
@purcell I have https://melpa.org/packages

**Comment by purcell** [comment]
That URL should have a trailing slash, as noted in the MELPA README.

**Comment by FrankDMartinez** [comment]
@purcell Tried that; no change.

**Comment by purcell** [comment]
Do you have SSL support in your Emacs? There really isn't much information here for me to go on...

**Comment by FrankDMartinez** [comment]
That's a great question, thanks. I will include a link to the current contents of my `init.el` file: https://pastebin.com/SdPHrCha

Note: lines 37 and 38 were not in the file originally when I opened this issue; I added them afterwards in a resolution attempt. The behavior is the same whether I include those lines or not.

**Comment by FrankDMartinez** [comment]
Also of note: I am not actually using SpacEmacs; that file is left over from when I tried it out before. I don't know if that matters.

**Comment by purcell** [comment]
No idea, sorry. Maybe try grabbing a 27.1 build from emacsformacosx.com and see if you get the same error, just in case the problem is related to aquamacs.

**Comment by FrankDMartinez** [comment]
@purcell While I don't get the errors with 27.1, the package still seems absent from the list of packages, even after `M-x package-refresh-contents`. The closest I can find are:

> haskell-emacs
> haskell-emacs-base
> haskell-emacs-text
> haskell-tab-indent

Is there a way to debug emacs on Mac?

**Comment by FrankDMartinez** [comment]
@purcell Update: I, to a certain extent, uninstalled Emacs in general (removing the configuration files, specifically) and then installed the command-line version of Emacs and the SpacEmacs configuration. I then opened Emacs from the command line and went thru the configuration wizard and then opened the 27.1 GUI. I can now see haskell-mode in the list of installable packages. So, it looks like it will be SpacEmacs for me for now. Thanks.

**Comment by purcell** [comment]
Great, glad you figured something out.
