### ISSUE TITLE
package-desc-from-define error

### ISSUE THREAD

**Issue by k-bx** [haskell/haskell-mode#1732]
Getting this error on fresh emacs under WSL2 when doing `package-list-packages` and pressing `install`:

```
Debugger entered--Lisp error: (wrong-type-argument stringp haskell-mode)
 intern(haskell-mode) 
 package-desc-from-define(haskell-mode "20201120.755" "A Haskell editing mode" (quote ((emacs "25.1"))) :commit "0d39c847fddddc5b76fe3c706e34ab45439760bc" :
...
```

[error.txt](https://github.com/haskell/haskell-mode/files/5740630/error.txt)

Would appreciate if someone with more experience could take a look.

**Comment by k-bx** [comment]
Doesn't seem to be related to haskell-mode directly

**Comment by purcell** [comment]
This is related to https://github.com/melpa/melpa/issues/7312, I believe, which is in the process of getting cleared ul.
