### ISSUE TITLE
Unicode symbols inside ghci prompt hang inferior-haskell-mode

### ISSUE THREAD

**Issue by adinapoli** [haskell/haskell-mode#176]
I've discovered this by chance, because my office's laptop has a .ghci file which sets the prompt to "ghci", but my home laptop set it to "λ> ".

With my surprise, this hang Emacs completely.

Any clue? Maybe it could be worthwhile to add a note in the README to avoid too much headaches :)

**Comment by unhammer** [comment]
Why the final `$`? I had to remove it to use the λ in ob-haskell.el, since org-babel expects to be able to split-string on comint-prompt-regexp.
