### ISSUE TITLE
Documentation of the variable (not function) `haskell-process-type` is faulty

### ISSUE THREAD

**Issue by dschrempf** [haskell/haskell-mode#1763]
Hello! Thank you very much for developing this package!

I found a small discrepancy in the documentation which led me to having a non-functioning cabal repl. I quote from the documentation of the variable (not function) `haskell-process-type`:
```
The inferior Haskell process type to use: ghci, stack, cabal, or auto.
...
```

However, the correct values are:
```
  :type '(choice (const auto)
                 (const ghci)
                 (const stack-ghci)
                 (const cabal-repl)
                 (const cabal-new-repl))
```

Thank you!

**Comment by dschrempf** [comment]
Thank you!

**Comment by purcell** [comment]
Thanks for flagging this! :)
