### ISSUE TITLE
Installation error: unable to connect to package archives

### ISSUE THREAD

**Issue by charrsky** [haskell/haskell-mode#1772]
When trying to list the packages in Emacs, I get this error:

Error retrieving: https://elpa.gnu.org/packages/archive-contents (error connection-failed "connect" :host "elpa.gnu.org" :service 443)

However, refreshing them seems to proceed with no errors.

Thus I cannot install the haskell-mode. Anyone came across this? Using macOS machine.

**Comment by purcell** [comment]
Hi, we don't host haskell-mode on GNU ELPA, so this bug report is invalid, sorry.
