### ISSUE TITLE
Four space indentation

### ISSUE THREAD

**Issue by bjourne** [haskell/haskell-mode#1788]
By default haskell-mode indents with two spaces:

    main = do
      opts <- execParser optsParser

I want the indentation step to be four spaces but there is no configuration for that:

    main = do
        opts <- execParser optsParser

**Comment by bernhard-herzog** [comment]
The `haskell-indentation.el` module has a few variables for this.
E.g. setting `haskell-indentation-left-offset` to 4 should achieve what
you want.

There are a few more variables like this that you might also want to
change.

**Comment by bjourne** [comment]
I tried to find information on how to customize indentation in [the manual](http://haskell.github.io/haskell-mode/manual/latest/Indentation.html#Indentation) but couldn't find anything.
