### ISSUE TITLE
auto-fill-mode is not working properly with literate-haskell-mode.

### ISSUE THREAD

**Issue by bremner** [haskell/haskell-mode#18]
in http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570236

Marco Túlio Gontijo e Silva writes:

If I have a big line, like:

If set to yes then the package management system will refuse to remove the package (upgrading and replacing it is still possible). The other possible value is no, which is the same as not having the field at all.$

And I press <SPACE> at the end of the line, I get:
```
If set to yes then the package management system will refuse to remove the $
package (upgrading and replacing it is still possible). The other possible value is no, which is the same as not having the field at all. $
```
Where I wanted:

```
If set to yes then the package management system will refuse to remove the
package (upgrading and replacing it is still possible). The other possible
value is no, which is the same as not having the field at all.
```
(I've added a $ in the end of the lines).

This is with turn-on-haskell-indentation in 2.8.0

**Comment by gracjan** [comment]
Just checked and it works. This bug reported originally iin 2010 seems to be no longer an issue.
