### ISSUE TITLE
Problem with multiline strings

### ISSUE THREAD

**Issue by qrilka** [haskell/haskell-mode#181]
Looks like haskell parsing is incorrect in dealing with escaping in multiline strings. I a quite simple (but a bit dummy) example:
```
x = "\
\"
y = 42
```
I get the third line colored like a string so a backslash used for the line continuation and a quote gets wrongly interpreted as an escaped quote.

**Comment by gracjan** [comment]
This issue report was last update in 2013. Is it still relevant to current code state?

**Comment by ivan-m** [comment]
I just tested the initial example, and it looks like it's still an issue.
