### ISSUE TITLE
string-trim-left redefinition vs quasi-quote tests in emacs 29.1

### ISSUE THREAD

**Issue by barak** [haskell/haskell-mode#1817]
There is a problem with test failures with emacs 29.1.

It would seem the redefinition in tests/haskell-indent-tests.el and tests/haskell-indentation-tests.el of string-trim-left is causing a failure in the eight quasi-quote tests in tests/haskell-lexeme-tests.el. If you remove those two "indent" files from the big emacs command invoked by `make check-ert` the quasi-quote tests work fine.

Can I suggest not redefining standard low-level functions in a non-backwards-compatible fashion (in this case, to not take an optional second argument)?

See https://bugs.debian.org/1042890

The test succeeds if the two redefinitions are simply removed; I'm adding a patch to the Debian package to do that.

**Comment by purcell** [comment]
Completely agree, that should never have been written like that, this is the first time I've seen it. Fixed now in `master`. This mistake will also have gone into the fresh release I tagged earlier today, though.

**Comment by barak** [comment]
Well, technically you did not actually **tag** the 17.4 release (as of my last `git fetch upstream --tags`) but I take your point. Anyway, I've just pushed a Debian package with your fix instead of my patch.

**Comment by purcell** [comment]
Perhaps I hadn't pushed the tag: I pushed it again now and it at least shows up in GitHub. Not the first time it's bitten me that tags get pushed separately from commits.
