### ISSUE TITLE
Should `haskell-cabal` mode derive from `prog-mode`?

### ISSUE THREAD

**Issue by cumber** [haskell/haskell-mode#1819]
Back in #86 `haskell-mode` was updated to derive from `prog-mode` rather than `fundamental-mode`. Should `haskell-cabal` mode follow suit?

At the moment basic configuration I want to apply to all programming modes (or even all programming and text modes, but not things like menus) has to additionally single out `haskell-cabal` mode.

**Comment by purcell** [comment]
> Should haskell-cabal mode follow suit?

Not really, sorry. If you look at other configuration and markup modes (`conf-toml-mode`, `yaml-mode`, `xml-mode`), you won't find `prog-mode` among the parent modes.

**Comment by purcell** [comment]
However, I noticed `haskell-cabal-mode` also wasn't derived from `text-mode`, which _would_ be typical, so I've just changed the mode so that it is. That should ease your configuration a bit.

**Comment by cumber** [comment]
Yeah, I wasn't sure which would be most appropriate. I ended up suggesting `prog-mode` since "Text mode is a major mode for editing human languages" according to https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html. I suppose **markup** languages are often used to mark-up content that is human-language text, but cabal file content really doesn't feel like "text" to me.

But I'm fine with a ruling that `text-mode` is more appropriate here. Thanks!
