### ISSUE TITLE
flymake-allowed-file-name-masks is void

### ISSUE THREAD

**Issue by magthe** [haskell/haskell-mode#1825]
I had to add this

```
(setq flymake-allowed-file-name-masks nil)
```

to make haskell-mode load on my latest build of 30.0.50.

I'm guessing it's this line that's failing when `flymake-allowed-file-name-masks` is void

```
(add-to-list 'flymake-allowed-file-name-masks '("\\.l?hs\\'" haskell-flymake-init))
```

**Comment by terlar** [comment]
Investigating a bit and the cause of this is the following commit:
https://github.com/emacs-mirror/emacs/commit/81c6569e654966c63f208013a4faf7ddb2a5d933

This variable is defined by `flymake-proc` which is not always required within `flymake` anymore. One solution is to require `flymake-proc` inside `haskell-mode.el`. However, given that proc is a legacy API, perhaps we should get of it anyways.

**Comment by Eason0210** [comment]
Have the same issue with Emacs 30.0.50

Please fix it.

**Comment by arjunkathuria** [comment]
ran into the same issue, seems @purcell fixed it. Thanks Steve!
