### ISSUE TITLE
Symbol's value as variable is void: flymake-allowed-file-name-masks

### ISSUE THREAD

**Issue by luisvgs** [haskell/haskell-mode#1831]
Hi everyone, first of all thanks for the effort you guys have putting into maintining this package. I'm trying to give haskell-mode a try, but the following error pops up when I try to open a project:

> Symbol's value as variable is void: flymake-allowed-file-name-masks

For context, I'm using `doom emacs`, with build version 29.1.50. I kindly ask for suggestions to solve this annoying problem. Thank you in advance!

**Comment by purcell** [comment]
Hi, this is a duplicate of #1825, but that's not in a stable release, only MELPA.

**Comment by luisvgs** [comment]
@purcell hello, is there any update regardings this bug? I wanted to ask: should I downgrade my emacs version to avoid it instead or pin haskell-mode to a specific commit as a workaround? It is unclear for me if this error is present in HEAD only. For context, I'm using doom emacs. Also, adding `(setq flymake-allowed-file-name-masks nil)` doesn't make the error go away neither. I'm getting out of ideas to make my haskell setup work. Thank you in advance.

**Comment by purcell** [comment]
Well yes, it's fixed, as mentioned above, and it's in the latest stable release too (v17.5) as of two weeks ago, so you should just be able to update your packages.

**Comment by purcell** [comment]
Maybe double-check and then close this if you can confirm the issue is indeed resolved for you

**Comment by luisvgs** [comment]
Hello @purcell, thanks for the response. I tried updating and pinning my package to the last commit `8d0f44bfe2a9ab6b0969c9bafb75089f315ff5ae` but it shows the following message: `Symbol’s value as variable is void: flymake-allowed-file-name-masks`. Is there any extra configuration that I should perform? Thank you in advance for your help.

**Comment by luisvgs** [comment]
Quick update here: the issue can be solved in `doom emacs` by pulling the latest version. Thanks for the kind help @purcell.
