### ISSUE TITLE
Type query from up to date file information

### ISSUE THREAD

**Issue by dudebout** [haskell/haskell-mode#185]
When I use the function `haskell-process-do-type` (`C-c C-t`) I often get the answer "Top level: Not in scope: `foo'". This is because the query made by `haskell-mode` uses the current content loaded in `ghci` and not the content of the file.

Is there a reason why the call to `haskell-process-do-type` does not reload the content of the file in ghci before querying it?

The same question applies to `haskell-process-do-info` (`C-c C-i`).

**Comment by gracjan** [comment]
This issue report was last update in 2013. Is it still relevant to current code state?

**Comment by chrisdone** [comment]
hvr commented on 17 Jul 2013 
> > Sub-expressions? When the file's invalid?
> @chrisdone are you sure ghc-mod type is able to work on invalid Haskell source files?

I meant the reverse. GHCi gives you (old) info when the file is invalid. I think ghc-mod does not because it requests type info on-demand.

gracjan commented an hour ago 
> This issue report was last update in 2013. Is it still relevant to current code state?

Yup.

**Comment by gracjan** [comment]
It seems that HIE will provide this functionality. I do not see this happening in haskell-mode due to lack of resources.
