### ISSUE TITLE
Clean up module dependency cycles introduced by `haskell-{process,session,interactive-mode}`

### ISSUE THREAD

**Issue by hvr** [haskell/haskell-mode#187]
The graph diagram below shows the current module inter-dependencies, and is generated by visualizing  `require` (black edges) and `declare-function` (red dashed edges) statements contained in the `*.el` files (i.e. the nodes):

![depgraph](https://f.cloud.github.com/assets/285533/830411/a79849b6-f14e-11e2-8826-da0305cda994.png)

As can be clearly seen the current integration of the `haskell-{process,session,interactive-mode}` cluster currently destroys an otherwise DAG-like dependency graph.

**Comment by gracjan** [comment]
@hvr @chrisdone: is this one done?

**Comment by gracjan** [comment]
I guess it is done. Reopen if you disagree.
