### ISSUE TITLE
Guess working directory from hs-source-dirs?

### ISSUE THREAD

**Issue by karljs** [haskell/haskell-mode#191]
I imagine the large majority of projects using Cabal tend to have a single directory under which all their source files are placed, such as `$PROJECT_ROOT/src`.  Given this, doesn't it make sense to try guessing the current directory based on the required cabal property `hs-source-dirs` when starting a new project?

Apologies if this is a bad suggestion as I'm not familiar with best practices when it comes to packaging Haskell code.

**Comment by gracjan** [comment]
In the somewhat related issue #180 it was hinted that `cabal repl` is the way to go. In general `cabal repl` is when you have .cabal file and ghci is only when you do not have it. Implementing more logic would be very fragile and user unfriendly.

I'm closing this issue, if I misunderstood something write a comment or reopen.

**Comment by svenpanne** [comment]
How is ``cabal repl`` related to editing Haskell source files?

**Comment by gracjan** [comment]
@svenpanne: I do not understand your question. Can you elaborate?
