### ISSUE TITLE
Multi-line -ferror-spans syntax not supported

### ISSUE THREAD

**Issue by hvr** [haskell/haskell-mode#192]
The feature implemented via #151 doesn't support the multi-line `-ferror-span` syntax, as in:

```
Server.hs:(231,5)-(247,119): Warning:
    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: Nothing
```

**Comment by gracjan** [comment]
This issue report was last update in 2013. Is it still relevant to current code state?
