### ISSUE TITLE
Introduce concept of "build target" in haskell-sessions/interactive-mode

### ISSUE THREAD

**Issue by hvr** [haskell/haskell-mode#193]
Thanks to haskell/cabal#1404 we will probably have a `cabal repl <build-target>` command in cabal-1.18, which provides a proper way to do what `cabal-dev` attempted to.

However, the new `cabal repl` command allows to select the build-target (i.e. library, executable, test suite or benchmark) the repl should use as environment. This however, is a concept missing in the current `haskell-session` framework.

In practice, a `.hs` buffer can be associated with multiple build targets, however when starting up GHCi, we need to decide which build-target the session shall use, as this affects which packages, modules and compile flags GHCi is started with.

**Comment by gracjan** [comment]
@hvr: is this one working for you?

**Comment by ivan-m** [comment]
I believe `haskell-session-change-target` solves this.
