### ISSUE TITLE
Ariadne binding?

### ISSUE THREAD

**Issue by qrilka** [haskell/haskell-mode#205]
Are there any plans to support https://github.com/feuerbach/ariadne in haskell-mode?
Unfortunately I don't know elisp good enough to provide you a pull request with this functionality.

**Comment by gracjan** [comment]
@qrilka, @chrisdone: as per Ariadne github:

    Ariadne is not maintained. If you want to take over, get in touch.

I guess binding to Ariadne is not going to happen in this case.

Can you close this issue?
