### ISSUE TITLE
How to set C-c C-k to check kind?

### ISSUE THREAD

**Issue by HaskellZhangSong** [haskell/haskell-mode#210]
I found there is a pieces of code to check the kind of a term in inf-haskell.el
(defun inferior-haskell-kind (type)
  "Query the haskell process for the kind of the given expression."
  (interactive

I bind the key as following
(define-key map (kbd "C-c C-k") 'inferior-haskell-kind)
and restart emacs but still cannot use it. 
I am a new user of haskell-mode. Could any explain to me a little bit.

**Comment by gracjan** [comment]
@HaskellZhangSong: did you manage to solve this problem? If not do not hessitate to write a note here and we will reopen this issue again.
