### ISSUE TITLE
Indenting Eat up all cpus and emacs die

### ISSUE THREAD

**Issue by m00nlight** [haskell/haskell-mode#212]
When using the set below:

(custom-set-variables
 '(haskell-mode-hook '(turn-on-haskell-simple-indent)))

the haskell mode of indenting will eat up all the cpus of one core, and emacs died there.
when using turn-on-haskell-indent, it is the same as simple-indent.

**Comment by gracjan** [comment]
@m00nlight: I've worked on haskell-simple-indent as lot recently. Can you confirm that this is no longer an issue?

**Comment by gracjan** [comment]
Or better yet: reopen the issue if it happens again to you.
