### ISSUE TITLE
Language pragma snippet corrupts undo history

### ISSUE THREAD

**Issue by brandonw** [haskell/haskell-mode#216]
If you do the initial expand of the lang snippet into ```{-# LANGUAGE  #-}``` but then cancel the expansion before choosing the extension, your undo history will not contain the insertion of ```{-# LANGUAGE  #-}```.

It looks as if the text outputted from the snippet before the macro is invoked is somehow not added to the undo history. I tried putting the entire content of the snippet inside of the macro instead of just the extension, but that somehow adds a line break that is not added to the undo history instead.

**Comment by gracjan** [comment]
Related #364, #305, #361.

**Comment by LukeHoersten** [comment]
This is still an issue and since this is my code I'll try to figure out what's going on.

**Comment by LukeHoersten** [comment]
I have no idea why this is happening. @capitaomorte can you provide any insight here?

**Comment by capitaomorte** [comment]
Undo support in yasnippet is finicky, but it should work. Can I see the snippet definition? Alternatively open related issue in yasnippet.

**Comment by LukeHoersten** [comment]
@capitaomorte https://github.com/haskell/haskell-snippets/blob/master/snippets/haskell-mode/lang-pragma

I'll wait to open a yasnippet issue until we've determined this isn't something I've caused.
