### ISSUE TITLE
Update marmalade

### ISSUE THREAD

**Issue by svenpanne** [haskell/haskell-mode#226]
http://marmalade-repo.org/packages/haskell-mode is quite a bit behind the code here on GitHub. It would be nice if marmalade was updated to something more recent, it is IMHO the most convenient way of installing haskell-mode.

**Comment by gracjan** [comment]
@chrisdone, @hvr, can you clarify release/tagging procedure?

MELPA has 20150120.1233 as current version at the time of this writing. Is this automatic?
I tried to find out about marmelade but failed to find out what is going on.

**Comment by bbatsov** [comment]
> MELPA has 20150120.1233 as current version at the time of this writing. Is this automatic?
> I tried to find out about marmelade but failed to find out what is going on.

It's automatic - MELPA builds the package from the master after each commit. MELPA Stable builds the package from the newest tag. Packages on Marmalade are updated manually.

**Comment by gracjan** [comment]
Duplicate of #394, as this is part of release procedure (or at least should be connected).

**Comment by purcell** [comment]
Yep, will close this and take care of updating Marmalade as part of #394.
