### ISSUE TITLE
haskell-indent-align-def, via haskell-indent-start-of-def, causes type of definition to align with '='

### ISSUE THREAD

**Issue by philipdexter** [haskell/haskell-mode#235]
Calling an align on

```haskell
test :: Int -> Int -> Int
test x y = x
test x y     = y
```

gives

```haskell
test     :: Int -> Int -> Int
test x y = x
test x y = y
```

I have looked briefly and I haven't found any Haskell code that uses this indentation style. I believe it should give

```haskell
test :: Int -> Int -> Int
test x y = x
test x y = y
```

I have created  a patch that changes
* `haskell-indent-start-of-def` to discard type lines (note: `start-of-def` is only called when P-ARG is nil)
* `haskell-indent-align-guards-and-rhs` to take a universal argument that switches on the P-ARG argument to `haskell-indent-align-def`

Result:
* to include type definitions in alignment prefix `C-u`

Thoughts?

There are other places in the alignment code that this could be changed. However I wanted to keep this fix simple and I didn't want to forbid aligning of code like

```haskell
test :: Int
testSecond :: Int
```

to

```haskell
test       :: Int
testSecond :: Int
```

**Comment by gracjan** [comment]
This issue has not seen activity for a very long time. Is this still something we should be concerned about?

**Comment by philipdexter** [comment]
It doesn't seem like it's a universal issue, closing
