### ISSUE TITLE
haskell-program-name "cabal repl" can't find .cabal

### ISSUE THREAD

**Issue by LukeHoersten** [haskell/haskell-mode#237]
Changing haskell-program-name to "cabal repl" (which supports cabal sanxboxes) can't find .cabal/root of the project and therefore fails:

    Package has never been configured. Configuring with default flags. If this
    fails, please run configure manually.
    cabal: No cabal file found.
    Please create a package description file <pkgname>.cabal

Someone recommended a [code change](https://gist.github.com/BJTerry/3693479) on IRC.

**Comment by gracjan** [comment]
@LukeHoersten: Is this still a problem?

**Comment by LukeHoersten** [comment]
This was resolved a long time ago. Sorry for not following up.
