### ISSUE TITLE
improve documentation for the haskell-process-type defcustom

### ISSUE THREAD

**Issue by nurpax** [haskell/haskell-mode#239]
It'd be great if the doc string for haskell-process-type would provide a bit more info on what the available choices mean.

The options are: ghci, cabal-repl, cabal-dev, cabal-ghci

I'm guessing that `cabal-repl` means to use the new cabal "cabal repl" feature.  But what is the difference between `cabal-repl` and `cabal-ghci`?

Ẁhat about `cabal-dev`?  Is that still needed?

I would send a pull request for this, but unfortunately I'm not 100% sure how one should use this.

Another documentation idea would be to explain what is the recommended way to setup haskell-interactive-mode for various workflows.  For example, how should one get set up for a workflow where all I want is just load a .cabal file, hit C-c C-c and build the project.    This would probably be better placed on http://github.com/haskell/haskell-mode/README.md (or in the manual?).  

While I've been able to use haskell-interactive-mode quite successfully this way, I'm not sure if I'm using this mode in the intended way.  Normally this doesn't matter so much, but when hitting bugs/problems, it's hard to know whether I'm seeing a bug in the haskell-mode or if I have just setup my Emacs configuration in some funny way.

**Comment by gracjan** [comment]
There are two options now only `ghci` and `cabal repl`. I hope they are obvious enough to not require extra documentation.

Meanwhile we are going to write some documentation anyway, but as part of general documentation process, so I'm closing this ticket.
