### ISSUE TITLE
No syntax sugar for multiple functions on single declaration

### ISSUE THREAD

**Issue by fxfactorial** [haskell/haskell-mode#246]
The following:  

check, checker :: Int -> Int

check x = x + 1
checker y = y + 2

does not give me the normal syntax highlighting that say:

check :: Int -> Int 

would. Is this something quick that could be fixed? If someone points me in the right direction, i'd like to try my hand at it.

**Comment by gracjan** [comment]
This was fixed by commit 7ca5e34ad6ff0f5c455c02ad2d80fcbe48fef59b.
