### ISSUE TITLE
haskell-mode-hook popup upon return

### ISSUE THREAD

**Issue by developernotes** [haskell/haskell-mode#248]
Hello,
I recently installed `haskell-mode`, version `20140309.342` via melpa on Emacs `24.3.50.1` on OS X.  I Created the a file, with the following content:

```
data MyMaybe t = Just t | Nothing
```

After typing `Nothing`, I pressed return which triggered my screen to split and showed the help for `haskell-mode-hook`.  It states that the current value is nil.  Note that I do not have any customizations to `haskell-mode`, nor do I have additional haskell emacs packages.  Is it correct that this is not the desired behavior?

**Comment by gwern** [comment]
Oh, so *this* is why haskell-mode has been so unbearable for the past year for me!

> Oh, wait, the pop-up actually explains all this:

The Debian package seems to include only the less informative popup. I had no idea that it had anything to do with adding an indent-mode.

Actually, I don't think the version you quote is a clear explanation either. I thought I understood Emacs reasonably well, but I don't get anything like "I need to add `(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)` to my `.emacs` to make this popup go away" from that documentation...

**Comment by adnelson** [comment]
I've added this line to my init.el:

```
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
```

And even though I've run `M-x eval-buffer`, I still get this popup every time I press enter telling me about haskell-mode-hook. This is *incredibly* obnoxious. What am I not doing to get rid of this?

**Comment by gracjan** [comment]
Use

(add-hook 'haskell-mode-hook 'haskell-indentation-mode)

Your version should also work but for some reason it does not. That is a bug.

**Comment by gracjan** [comment]
@adnelson: Hooks are run when things happen, the hook says to enable `haskell-indentation-mode` just after `haskell-mode` is turned on. It does not work retroactively on already open buffer, as you have noticed.
