### ISSUE TITLE
Integrate cmm-mode

### ISSUE THREAD

**Issue by tibbe** [haskell/haskell-mode#249]
We should consider integrating cmm-mode (https://github.com/tibbe/dot-emacs/blob/master/lib/cmm-mode.el). cmm-mode can be used on the output generated by `ghc -ddump-simpl -ddump-to-file`.

**Comment by gracjan** [comment]
@tibbe: Your code seems fine to me. `haskell-mode` seems overloaded so I think it is best if you package `cmm-mode` as a separate package. What do you think?

**Comment by tibbe** [comment]
Sounds good to me. I've handed over maintenance over cmm-mode I think it's separately package somewhere now.

**Comment by gracjan** [comment]
Thanks! Closing in this case.
