### ISSUE TITLE
Haskell-mode not respecting cabal sandboxes

### ISSUE THREAD

**Issue by dmjio** [haskell/haskell-mode#253]
After cabal-installing my project inside of a cabal sandbox (1.18.0.3) I am able to open a `cabal repl` and inspect the packages. When I open up emacs w/ haskell-mode and `C-c C-l` to send to ghci I get :
```haskell
Prelude> :cd /Users/dmj/Project/
Prelude> :load "Main.hs"

ST/Common/Types.hs:37:18:
    Could not find module `Web.Stripe.Customer'
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
Prelude>
```

How do I get `haskell-mode` to respect cabal sandboxes?

**Comment by gracjan** [comment]
@dmjio: Do you consider this fixed for your case? Can we close this issue or should there be a follow up pull request?

**Comment by DanielAtSamraksh** [comment]
To change the haskell-program-name variable, do:
    C-h v haskell-program-name RET

Change 'ghci' to 'cabal repl'.

**Comment by DanielAtSamraksh** [comment]
To change haskell-program-name from 'ghci' to 'cabal repl':

    C-h v haskell-program-name RET

Click 'customize'.
Change 'ghci' to 'cabal repl'.
Click 'Apply and Save'.

**Comment by gracjan** [comment]
Haskell-process-type is more relevant.
