### ISSUE TITLE
Implement support for Cabal CPP pragmas

### ISSUE THREAD

**Issue by lykahb** [haskell/haskell-mode#255]
When a file has a pragma with Cabal macros like

    #if MIN_VERSION_template_haskell(2, 7, 0)

it would not loaded by the inferior haskell process because of

    error: missing binary operator before token "("
    phase `C pre-processor' failed (exitcode = 1)

I suggest detecting this error message and issuing a command *:set -optP-include -optPdist/build/autogen/cabal_macros.h* as pointed out at http://stackoverflow.com/questions/12546757/how-do-i-use-cabals-min-version-and-other-macros-with-ghci

If the header file is absent, haskell-mode can run a cabal build.

**Comment by gracjan** [comment]
It has been over a ear since this issue was reported. It seems that todays `cabal repl` covers all use cases. Is this issue still relevant?

**Comment by gracjan** [comment]
I'll close this now. If you feel this is important just write below and we will reopen.
