### ISSUE TITLE
`haskell-stylish-on-save` with Yasnippet + ghc-mod sometimes removes import list

### ISSUE THREAD

**Issue by konn** [haskell/haskell-mode#256]
Using `haskell-stylish-on-save` with Yasnippet's import snippet sometimes erases import list. It seems that this occur when the import order will be changes.

Example:

```haskell
module Main where
import Prelude
imp
```

Then hit `[TAB]` on right after `imp` and import `Language.Haskell.TH` using ghc-mod's function symbol completion:

```haskell
module Main where
import Prelude
import Language.Haskell.TH
```

Push `[TAB]` to exit snippet, and don't move caret from right after `TH`.
Hit `C-xC-s`, then import list vanishes!:

```haskell
module Main where
import 
```

Environment
------------------
* GNU Emacs 24.3.4 (x86_64-apple-darwin11.4.2, Carbon Version 1.6.0 AppKit 1138.51)
* yasnippet-20140314
* haskell-mode-20140330
* ghc-20140331

**Comment by gracjan** [comment]
This issue has not seen activity for a very long time. Is this still something we should be concerned about?

**Comment by LukeHoersten** [comment]
Yes this is definitely still a problem. Until I saw this just now I didn't know it was related to YAS.

**Comment by gracjan** [comment]
@DanielG: Can you have a look at this if it has possibly any connection with ghc-mod?

**Comment by DanielG** [comment]
I don't see anything in the code that would trigger this sort of behavior immediately but I don't have enough time to try and reproduce this, I tried but I can't get haskell-mode to behave in a minimal environment for some reason :/. If we have a testcase I can give it a proper look.

**Comment by gracjan** [comment]
@LukeHoersten: have you actually reproduced the problem or not?

**Comment by LukeHoersten** [comment]
@gracjan I was able to reproduce, yes.

**Comment by gracjan** [comment]
What about this one?

**Comment by LukeHoersten** [comment]
Still happens though I have no idea why. Happens maybe 1 out of 10 times but it's pretty reproducible.
