### ISSUE TITLE
haskell-unicode-input-mode is slow as hell

### ISSUE THREAD

**Issue by spacekitteh** [haskell/haskell-mode#261]
When I'm writing, it takes about a second for the haskell unicode input method to process each character. It is rather frustrating. This has been the case ever since I started using it, present even in the latest commit :cactus:

**Comment by gracjan** [comment]
@spacekitteh: can you provide some more information? There were improvememnts all over the place since you reported this issue, maybe it just went away?

**Comment by gracjan** [comment]
I'll close this issue as it seems it went away. If you still experience this problem, write a comment here and we will reopen. Thanks for the report!
