### ISSUE TITLE
Regression: C-c C-l keeps asking for a new session for different files within the same project

### ISSUE THREAD

**Issue by ozataman** [haskell/haskell-mode#265]
Even after starting a session called `project` for `project/Foo.hs`, C-c C-l keeps asking whether we should start a new project named `project` for each newly introduced file under the same project.

This broke only recently (unless it was done by design, in which case I would ask that we create a flag to enable/disable it).

**Comment by gracjan** [comment]
If I understand correctly original issue is resolved. If not do not hessitate to leavea note here.

As for the other request to simplify `C-c C-l` behavior there was a pull request about it #409.
