### ISSUE TITLE
Haskell-interactive-mode and evil — return results in symbol put on the next line

### ISSUE THREAD

**Issue by EDmitry** [haskell/haskell-mode#273]
I am using haskell-interactive-mode with evil. I have the following bindings:

    (evil-define-key 'insert haskell-interactive-mode-map (kbd "RET") 'haskell-interactive-mode-return)
    (evil-define-key 'normal haskell-interactive-mode-map (kbd "RET") 'haskell-interactive-mode-return)

In insert mode when I hit "RET", everything works as expected. Unfortunately, in normal mode the last symbol of the statement is put on the next line:

    λ> verifySuspect 4 [4,4,4
    ]3

Here "]" was put on the next line. I suspect this is because in normal mode the cursor points /before/ the last symbol and it can't be moved to point after. Is there any particular reason it works like this?

**Comment by gracjan** [comment]
@EDmitry: can you check if referenced PR fixes your issue?

**Comment by EDmitry** [comment]
Works great, fixed an issue, thanks a lot! :-)
