### ISSUE TITLE
After the newline have to hit <tab> twice to start cycling

### ISSUE THREAD

**Issue by EDmitry** [haskell/haskell-mode#276]
I am trying to understand if this is an intended behavior. After I make a newline I am trying to use <TAB> to cycle through all possible indentations. But when I hit <TAB> the first time immediately after a newline nothing happens. Only when I hit it the second time the indentation level starts to cycle. If this is not an expected behavior I will add more information.

**Comment by EDmitry** [comment]
Found this old indentation bug/ feature request of mine. gracjan, could you please confirm this is indeed an intended behavior or a bug? Reproduces with hi2 too unfortunately.

**Comment by gracjan** [comment]
In this issue you are talking about `turn-on-haskell-indent` wherr in #500 you are talking about `haskell-indentation` in `hi2` branch. Those two have zero common code.

**Comment by gracjan** [comment]
If you have example of code that has two or more indentation points and single TAB does nothing but second one moves then I'd like to see it and put it in the test suite that we have.

**Comment by gracjan** [comment]
@EDmitry: I've read your comment more carefully :)

Can you paste your code that exhibits this behavior? I could not find any examples myself.

**Comment by EDmitry** [comment]
It reproduces for every line of code that has two indentation positions under it like:

```
main = (putStrLn . show) test
```

It could be related to evil-mode, so I am going to retest this without it to localize the problem. I just wasn't sure if that's a bug or an intended behavior, but now I am :-)

**Comment by gracjan** [comment]
I cannot reproduce with current wip/hi2. Can you make sure to do:

    make EMACS=$EMACS clean haskell-mode-autoloads.el

(the point is to make sure that there are no stale `*.elc` files getting in the way).

**Comment by gracjan** [comment]
Reopen if there is anything to add to this particular discussion.
