### ISSUE TITLE
haskell-process-cabal-build doesn't build under certain conditions

### ISSUE THREAD

**Issue by psibi** [haskell/haskell-mode#285]
In haskell-mode, when I do cabal build using `haskell-process-cabal-build`, I get this:

```
Complete: cabal build (0 compiler messages)
```

But in the `haskell-process-log`, I see this:

```
-> ":!cd /home/sibi/snapshot-analysis/ && cabal build
"
<- "/bin/sh: 1: cabal: not found
```

I don't get how it's not able to see my cabal path. In fact, I have these things in my emacs configuration, just to be sure:

```
(setq exec-path (cons "~/.cabal/bin" exec-path))

(setenv "PATH"
  (concat
   "~/.cabal/bin/" ":"
   (getenv "PATH")
  )
)
```

The cabal which I have is inside `~/.cabal/bin`. Let me know if you need any other details.

**Comment by gracjan** [comment]
@psibi: Is this PATH issues working for you?

**Comment by gracjan** [comment]
Do not hessitate to write a note here if this PATH issues is still bothering you.
