### ISSUE TITLE
Remove cabal-dev support

### ISSUE THREAD

**Issue by chrisdone** [haskell/haskell-mode#288]

**Comment by gracjan** [comment]
@chrisdone: are you sure about this?

Is there a legitimate reason to use cabal-dev these days?

**Comment by ivan-m** [comment]
@gracjan I believe cabal sandboxes have subsumed and replaced cabal-dev's functionality.

**Comment by gracjan** [comment]
@ivan-m, @chrisdone: with love for code removal: #480.
