### ISSUE TITLE
`indent-according-to-mode` opens the help buffer for `haskell-mode-hook`

### ISSUE THREAD

**Issue by gridaphobe** [haskell/haskell-mode#290]
This happens unless I turn on one of the indentation modes, but I want to use structured-haskell-mode, which recommends not turning any of them on.

Steps to reproduce:
1. `emacs -Q -L . -l haskell-mode-autoloads.el examples/indent.hs`
2. `M-x indent-according-to-mode` (or just hit `TAB`)

**Comment by EDmitry** [comment]
Why can't structured-haskell-mode implement `indent-according-to-mode` to indent the current position based on the context?

**Comment by gracjan** [comment]
Related:  #555.
