### ISSUE TITLE
Ask user whether to add missing package to test-suites

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell/haskell-mode#293]
When haskell-mode (?) detects that a symbol exists in a hidden package, it asks whether to add it to the cabal file.  However, it does not propose to add it to test-suites in the cabal file, only to libraries.

**Comment by gracjan** [comment]
@alexanderkjeldaas: seems like this one is fixed already while we weren't looking. Dependencies are added to source-bearing sections, that is:

    '("library" "executable" "test-suite" "benchmark"))

Can you check if this issue is solved for you and close it?

**Comment by ivan-m** [comment]
If you're importing a package's library into the test-suite, would you necessarily need to add other packages to the .cabal file?  Surely what should only happen is that haskell-mode detects a package is needed, it adds it to the dependency section of `(haskell-session-target)`.

**Comment by gracjan** [comment]
@alexanderkjeldaas: Is this working for you?

**Comment by alexanderkjeldaas** [comment]
I cannot check this, unfortunately.

**Comment by alexanderkjeldaas** [comment]
closing as this is probably fixed.
