### ISSUE TITLE
Can't get type info unless file compiles

### ISSUE THREAD

**Issue by vapniks** [haskell/haskell-mode#294]
I am using haskell-mode for editing a single file (not a whole cabal package). haskell-process-do-type and haskell-process-do-info only give me useful information if the file I am working on compiles without error. Otherwise the modules are not loaded into the REPL, and so it can't get the info. This is annoying since I most need to check types when the file doesn't compile, and so I have to manually load the modules into the REPL.
Is there any way around this?

**Comment by gracjan** [comment]
@vapniks, @chrisdone: this request seems valid but seems also very hard with GHCi. Can we agree to close this issue as not possible to solve in current setup?

**Comment by mgsloan** [comment]
`-fdefer-type-errors` might help here.  One of the intentions of that flag was to support IDE type info even when there are type errors.  Of course, there is no `-fdefer-scope-errors` or `-fdefer-syntax-errors` (haha) quite yet.

**Comment by vapniks** [comment]
@gracjan whats wrong with the solution/hack I suggested?

**Comment by gracjan** [comment]
@vapniks: there is of course nothing wrong with your hack! I was refering to previous comments in this thread that suggested that GHCi cannot be fixed and that is better to use ghc-mode.

Care to polish your hack into a pull request?

**Comment by gracjan** [comment]
@vapniks: Do you have your hack ready?

**Comment by gracjan** [comment]
Reopen when the hack is ready.
