### ISSUE TITLE
Implement REPL RET behaviour on previous prompts

### ISSUE THREAD

**Issue by chrisdone** [haskell/haskell-mode#30]
[Described here.](https://github.com/haskell/haskell-mode/issues/29#issuecomment-5233775)

I need to make the input grabbing code a bit smarter, as it currently supports multi-line input, so I will use some text-properties or markers to determine boundaries.

**Comment by geraldus** [comment]
This looks irrelevant, in current version I can't move point below prompt (getting "End of buffer" message), pressing <kbd>RET</kbd> on any line other than current prompt yields nothing.

@chrisdone shout it be finally closed?

**Comment by geraldus** [comment]
<kbd>RET</kbd> now copies line to prompt (#457)

I vote to close this
