### ISSUE TITLE
Non-standard UnicodeSyntax symbols and flycheck + process errors

### ISSUE THREAD

**Issue by jfeltz** [haskell/haskell-mode#308]
- haskell-mode-20140723.1211
- emacs 24.3.1
- applicable config (more or less):
https://github.com/jfeltz/emacs.d/blob/master/lang/haskell-mode.el
and with custom-set-variables:
```lisp
 '(haskell-font-lock-symbols (quote unicode))
 '(haskell-process-log t)
 '(haskell-process-type (quote cabal-repl))
 '(haskell-tags-on-save t)
 '(haskell-process-suggest-remove-import-lines t)

```

and elsewhere in project trigger:

```lisp
(turn-on-haskell-unicode-method) 
; note, when this is not done, I do get standard unicode, but the
; non-standard unicode (which I do like) is disabled
```
With regard to non-standard symbols from *haskell-unicode-input-method.el*:
* Are these symbols intended to be visually masking and not written by emacs? 
* These symbols are not in the UnicodeSyntax extension:
http://www.haskell.org/ghc/docs/7.8.2/html/users_guide/syntax-extns.html
So I'm assuming they are not actually supposed to be written to the buffer,
apparently Emacs is writing those symbols to the buffer/file, and this is
triggering errors in both flycheck with ghcmod, and in haskell-process-load-file.

I'm fairly new to emacs (going on a few weeks of use thus far) so if the problem looks obvious, it might be.

**Comment by gracjan** [comment]
@jfeltz: I see 2 mechanisms that are interfering here:

1. Haskell indeed supports Unicode symbols for identifiers and operators. Emacs can show it as Unicode.
2. Emacs can overlay Unicode 'looks' on top of a set of ASCII characters. So it can show '>>=' in a more beautiful way but that does not change the fact that >>= is still three characters long.

As far as I understand Emacs those better looking symbols should not be written to files, neither when saving normally nor when doing temporary save for flycheck/flymake.

Do you know where is the 'parse error on 'symbol' ' coming from? Is it GHC or flycheck or haskell-mode?

**Comment by gracjan** [comment]
@jfeltz: I saw now that you volunteered to describe what is going on. Such addition to documentation would be much appreciated. `haskell-mode.text` already has appriopriate sections, albeit empty.

A PR more than welcome.

I'm closing this particular issue and waiting for documentation.
