### ISSUE TITLE
symbol includes trailing @ sign in as-patterns

### ISSUE THREAD

**Issue by mattraibert** [haskell/haskell-mode#311]
Emacs 24.3.91.1 (built from src on ubuntu)
haskell-mode  20140726.1852 (from melpa)

When I use `find-tag` or `highlight-symbol-at-point` on an as-pattern, emacs incorrectly thinks the at-sign is part of the symbol.

For example, in the following code, if point is on the `xxs` on the left-hand side of line 3, and you type `M-.` to `find-tag`, the default symbol to search for will be `xxs@`

```
tails                   :: [a] -> [[a]]
tails []                =  [[]]
tails xxs@(_:xs)        =  xxs : tails xs
```

It's also observable in this screenshot of [this code](https://github.com/dbp/visualdb/blob/master/src/FileStore.hs) `store@` is highlighted but not `store` 

![store](https://cloud.githubusercontent.com/assets/279628/3722354/1bd3e2d2-1669-11e4-9098-f05bc72ed69c.png)

**Comment by gracjan** [comment]
@purcell: wait, this explanation does not sound right, please correct me if I'm wrong:

There is a 'w' category that is for words. '@' is never a part of 'w' category in Haskell.
There is a '_' category that is for symbols. '@' is either special symbol if alone or part of operator symbol if there is a longer sequence of symbols.

Am I wrong about either Haskell or Emacs interpretation of 'w' vs '_'?

**Comment by purcell** [comment]
@gracjan Hmm, yes, you're probably right that `@` should not have `symbol` syntax.

**Comment by gracjan** [comment]
@purcell, @mattraibert 

Currently '@' has class '_', each of 'store' has class 'w'.

In `haskell-mode` `highlight-symbol-at-point` highlights whole of 'store@', and whole of 'store+++' and whole of 'store+load'.

In `c-mode` characters like '+', '@' etc have class '.' (punctuation).

Do we lose any functionality if Haskell symbol characters get puntuaction class?

**Comment by purcell** [comment]
> Do we lose any functionality if Haskell symbol characters get puntuaction class?

Probably not, though I can't be 100% certain.
