### ISSUE TITLE
inf-haskell fails at identifying types for String literals

### ISSUE THREAD

**Issue by mcandre** [haskell/haskell-mode#322]
**Summary**

inf-haskell fails at identifying type information for String literals.

When the cursor is on either starting or ending double-quote (Trace 1: `["]FizzBuzz"`), the Emacs debugger triggers. When the cursor is on a character inside the String (Trace 2: `"[F]izzBuzz"`), the String content characters are mistakenly treated as a symbol.

**Source**

[Fizzy.hs](https://github.com/mcandre/mcandre/blob/6f41de873d08a9dabde3d1b8b07a8bde2384b581/haskell/fizzy/Fizzy.hs)

**Trace 1: ["]FizzBuzz"**

```
$ emacs -Q FizzBuzz.hs
M-x inf-haskell
C-c C-l
M-g g 13
M-g TAB 16
C-c C-t RET

Debugger entered--Lisp error: (error "No type info: Ok, modules loaded: Main.
*Main> :type 

<no location info>: not an expression: `'")
  signal(error ("No type info: Ok, modules loaded: Main.\n*Main> :type \n\n<no location info>: not an expression: `'"))
  error("No type info: %s" "Ok, modules loaded: Main.\n*Main> :type \n\n<no location info>: not an expression: `'")
  inferior-haskell-type("")
  #[nil "\300\301!\210\302\303 !\207" [inferior-haskell-load-file nil inferior-haskell-type haskell-ident-at-point] 2 nil nil]()
  call-interactively(#[nil "\300\301!\210\302\303 !\207" [inferior-haskell-load-file nil inferior-haskell-type haskell-ident-at-point] 2 nil nil] nil nil)
```

**Trace 2: "[F]izzBuzz"**

```
$ emacs -Q FizzBuzz.hs
M-x inf-haskell
C-c C-l
M-g g 13
M-g TAB 17
C-c C-t RET

*Main> :type FizzBuzz

<interactive>:1:1: Not in scope: data constructor `FizzBuzz'
```

**System**

* haskell-mode 20140815.1336
* Emacs 24.3.1
* GHC 7.6.3
* Haskell Platform 2013.2.0.0.debian3
* Ubuntu 14.04 Trusty Tahr

**Comment by gracjan** [comment]
@mcandre: `(haskell-ident-at-point)` looks at words and does not take strings and comments into account.

Note that comments never have type and strings always have type String. So the best thing to do is to ignore C-c C-t in strings and comments. Is this what you have in mind?

**Comment by mcandre** [comment]
@gracjan Almost.

Haskell has multiple string types, such as the basic Prelude String and ByteString for performance.

It would be nice if `C-c C-t` would report which one a string literal resolves to.

**Comment by gracjan** [comment]
`C-c C-t` find identifier at points or uses current region, wraps it in parentheses if necessary, and executes one of:

    :type %s
    :type (%s)

Meanwhile `ghc-mod` seems to have the functionality you are trying to get here:

    ghc-mod type <HaskellFile> <module> <line-no> <column-no>

See http://www.mew.org/~kazu/proj/ghc-mod/en/ghc-mod.html

Is this what you are looking for?

**Comment by mcandre** [comment]
Yes! I'd love for a Haskell minor mode to work like that.

On Tue, Mar 17, 2015 at 2:41 AM, gracjan <notifications@github.com> wrote:

> C-c C-t find identifier at points or uses current region, wraps it in
> parentheses if necessary, and executes one of:
>
> :type %s
> :type (%s)
>
> Meanwhile ghc-mod seems to have the functionality you are trying to get
> here:
>
> ghc-mod type <HaskellFile> <module> <line-no> <column-no>
>
> See http://www.mew.org/~kazu/proj/ghc-mod/en/ghc-mod.html
>
> Is this what you are looking for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haskell/haskell-mode/issues/322#issuecomment-82186458>
> .
>



-- 
Cheers,

Andrew Pennebaker
www.yellosoft.us

**Comment by ivan-m** [comment]
I think that it's unlikely for anything like this to be added to `inf-haskell`, as it seems to not be maintained (most of the work is done with the newer `haskell-process` setup instead).

`ghc-mod` also has Emacs integration; maybe you could use that?

**Comment by gracjan** [comment]
@mcandre: So `ghc-mod` is the way to go! There is a `ghc-mod` package for Emacs, so it should work for you

For now his functionality is out of scope for `haskell-mode`, at least until we get around to incorporating functionality of `ghc-mod` here. I'll close this specific issue, is that ok with you?
