### ISSUE TITLE
haskell-indentation mode sometimes can't parse multiline string literals

### ISSUE THREAD

**Issue by kini** [haskell/haskell-mode#324]
As title. The following code produces parse errors if you hit tab after the last line:

```haskell
main :: IO ()
main = do
  putStrLn "\
  \foo\
  \bar"
```

So does this code:

```haskell
main :: IO ()
main = do
  putStrLn "\
  \foo\
 \bar"
```

But this code doesn't produce a parse error (though the tab stop produced is a little odd)

```haskell
main :: IO ()
main = do
  putStrLn "\
  \foo\
   \bar"
```

Same with all of these code samples:

```haskell
main :: IO ()
main = do
  putStrLn "\
   \foo\
  \bar"
```

```haskell
main :: IO ()
main = do
  putStrLn "\
   \foo\
   \bar"
```

```haskell
main :: IO ()
main = do
  putStrLn "\
 \foo\
 \bar"
```

All the examples above are compiled by GHC without complaint.

**Comment by gracjan** [comment]
This one got slightly better due to #552, but not exactly right yet.

**Comment by gracjan** [comment]
This seems to be fixed properly by now. Leave a message here if you disagree.
