### ISSUE TITLE
getLine behaves not correctly in Interactive-Haskell-mode.

### ISSUE THREAD

**Issue by peterwang** [haskell/haskell-mode#333]
for example, the session:

λ> sequence [getLine, getLine]
a [hit enter]
b [hit enter]

raises an error buffer "*HS-Error*", which says:

-- Hit `q' to close this window.

["a","a"]
<interactive>:36:1: Not in scope: ‘b’

-- To disable popups, customize `haskell-interactive-popup-errors'.

Not sure this is a bug of the "interactive-haskell-mode" OR some kind of strange IO buffering problem?

**Comment by gracjan** [comment]
Can we reasonable expect that we can fix this particular issue?
