### ISSUE TITLE
haskell-ident-at-point returns empty identifier

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell/haskell-mode#334]
and haskell-ident-pos-at-point returns a tuple with the same number when no identifier is found

This is not according the the docstring and confuses for example 

```elisp
(let ((sym (haskell-ident-at-point)))
    (when sym
       ...))
```

**Comment by gracjan** [comment]
@alexanderkjeldaas, thanks for the report. Are you able/willing to create a patch for this one? Note that 'haskell-ident-at-point' has nice test suite in 'tests/haskell-mode-tests.el' and that should make it easy for you to get going. Just do:

    make EMACS=/path/to/your/emacs check-haskell-mode

**Comment by alexanderkjeldaas** [comment]
I had a patch somewhere, but I've changed my setup since.  I'll see if I can find it.

**Comment by gracjan** [comment]
@alexanderkjeldaas: were you able to find your patch?

**Comment by antalsz** [comment]
@gracjan: Given #603, should this be closed now?
