### ISSUE TITLE
"Double-buffering" GHCi sessions

### ISSUE THREAD

**Issue by hvr** [haskell/haskell-mode#346]
Here's just a crazy idea I wanted to write down before I forget about it again:

Currently there's the problem that if `:reload` fails (for instance because the last source-code edit introduced an error), GHCi is left in an empty state. While I hope we can teach GHCi at some point in the future to support a "safe" or "transactional" `:reload` it's not here yet...

So, why not simply spin up two GHCi sessions, und have switch back and forth between those two? That way, one can simulate a safe `:reload`, where you can rollback to the previous state if `:reload` fails...

**Comment by gracjan** [comment]
@hvr, @chrisdone: does any of you think that this is a good idea or what Chris said proper load handling should be outside of Emacs?

**Comment by gracjan** [comment]
In the light of `ide-backend` I guess it is better to put such optimizations in there than to emulate those in a problematic way in Emacs. So closing this issue.
