### ISSUE TITLE
Prompts to restart Haskell process after every character typed in an identifer

### ISSUE THREAD

**Issue by bmmoore** [haskell/haskell-mode#349]
After trying and failing to start a Haskell process, typing a character at the end of an identifer in the Haskell buffer prompts to restart again.

I have haskell-mode 13.10, GHC 7.8.3, cabal-install version 1.20.0.3 using version 1.20.0.2.

To reproduce, it's enough to make a trivial .cabal file for a Test.hs containing the line

    module Test where main

After something like C-c C-l that tries to start a haskell process, the process will die with the log showing the compiler error message. After that, adding letters to the end of "main" will prompt to restart the process after each character typed.

**Comment by ikirill** [comment]
Does #443 fix this? This may be due to the completion function starting after every character typed. If not, then maybe documentation function?

**Comment by gracjan** [comment]
@bmmoore: Seems like @ikirill fixed the issue. Can you check if this is really the case and write a note here if you still experience problems?
