### ISSUE TITLE
Support shallow indentation

### ISSUE THREAD

**Issue by mkscrg** [haskell/haskell-mode#366]
I find myself writing Haskell with mostly 4-space indents from the prior line. That applies in a lot of cases, e.g.
```haskell
foobar :: Foo -> Bar
foobar foo = doSomething $
    withALong subexpression (thatDoesnt fitOn) thePrevious $ line foo
```
 or
```haskell
data Foo = Foo
    { fooBar :: Bar
    , fooBaz :: Baz
    , fooQux :: Qux
    } deriving (Eq, Show, Ord)
```

In fact, I find myself  using 4-space indentation much more often than "align under start of this expression", which seems to be the `haskell-mode` approach.

Can I use `haskell-mode` with its indentation features disabled? 4-space indents are really easy to maintain by hand, and I find `haskell-mode`'s other features very useful!

**Comment by gracjan** [comment]
@mkscrg: Me too! This is a reallly good idea as one of possible options for `haskell-indentation`.

**Comment by gracjan** [comment]
So I worked a little on this and `haskell-indentation` is pretty close to supporting what we want here.
