### ISSUE TITLE
Not possible to set "interaction mode"?

### ISSUE THREAD

**Issue by cmyzie28** [haskell/haskell-mode#375]
I just installed haskell-mode from git, and when I try to run an interactive command, I get the error:

```
You tried to do an interaction command, but an interaction mode has not been enabled yet.

Run M-x describe-variable haskell-mode-hook for a list of such modes.
```

If I try to configure `haskell-mode-hook`, I can set things like indent mode but there is nothing about picking the interactive mode.  Does the error message need to be updated?

**Comment by k-bx** [comment]
+1 from me. Should we reopen this issue?

**Comment by gracjan** [comment]
Although @cmyzie28 got his problem resolved there should a better solution.

**Comment by gracjan** [comment]
Note: making `interactive-haskell` a default deserves a more prominent entry than a comment in other issue. Closing this one as fixed.

**Comment by codygman** [comment]
I had this problem recently and the error message was:


maybe adding a helpful message to the M-x describe-variable haskell-mode-hook help screen such as this:

Having problems using interactive mode? Try adding this to your .emacs:

(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
