### ISSUE TITLE
Tabs inserted into cabal file

### ISSUE THREAD

**Issue by leonbaum** [haskell/haskell-mode#376]
When I added an import to one of my modules, I was asked whether I wanted to add the package to my cabal file.  I said yes and it was added, but the formatting of the build-depends section was changed.  I like the formatting change, but it used tabs instead of spaces, which cabal chokes on.

Shouldn't haskell-mode always use spaces when modifying cabal files?

**Comment by gracjan** [comment]
`haskell-cabal-mode` explicitly does `(setq indent-tabs-mode nil)` so I guess a TAB in cabal file will happen never again.

Close?

**Comment by gracjan** [comment]
Hmm, or not, as this issue is talking about automatic additions not a buffer open in haskell-cabal-mode.

**Comment by purcell** [comment]
I would say so.
