### ISSUE TITLE
Del/Backspace do not delete text selection in literate mode outside bird lines 

### ISSUE THREAD

**Issue by kostya-sh** [haskell/haskell-mode#379]
My emacs configuration contains:

```el
(delete-selection-mode t)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
```

In `literate-haskell-mode` <kbd>DEL</kbd>/<kbd>BACKSPACE</kbd> keys do not delete selected text outside bird lines but work as expected for Haskell code.

I am quite new to Emacs but I think it can be fixed by changing `haskell-indentaton.el`: 

- `haskell-indentation-delete-backward-char` function to use `delete-backward-char` instead of `delete-char`
- `haskell-indentation-delete-char` function to use `delete-forward-char` instead of `delete-char`

**Comment by gracjan** [comment]
@kostya-sh: is this one solved for you?

Can this be related to #388?

**Comment by kostya-sh** [comment]
The issue still exists, it looks like it is related to #388 but the pull request from #388 doesn't solve the problem.

**Comment by gracjan** [comment]
So, grepping for offending functions:

    $ grep haskell-indentation-delete *.el

shows zero results. I guess we were taling about previous version of `haskell-indentation-mode`. Current one tries to bind neither <kbd>DEL</kbd> nor <kbd>BACKSPACE</kbd>.

**Comment by kostya-sh** [comment]
Yep, it works now. I haven't use haskell recently so I am not sure when it got fixed though.
