### ISSUE TITLE
haskell-mode does not work in emacs 24.4.1 in archlinux 

### ISSUE THREAD

**Issue by adrianor** [haskell/haskell-mode#380]
I have installed haskell mode for emacs in archlinux via:
sudo pacman -S emacs-haskell-mode
No problem so far. On my init.el file I have the load:
(load "/usr/share/emacs/site-lisp/haskell-mode/haskell-mode.el")
However, if I do "M-x haskell-mode" I get:
Symbol's value as variable is void: haskell-font-lock-choose-keywords
And also my haskell code is not highlighted as it is suppose to be.

**Comment by gracjan** [comment]
Is this one solved for you, @adrianor?

**Comment by gracjan** [comment]
@purcell? @adrianor? Can we close this?

**Comment by purcell** [comment]
I think so, thanks. @adrianor can re-open it if it's still a problem.

**Comment by adrianor** [comment]
no problem, can be closed

2015-02-17 10:06 GMT-06:00 Steve Purcell <notifications@github.com>:

**Comment by adamczykm** [comment]
I just got exactly the same issue, even archlinux and emacs version are the same. BUT I did install haskell-mode via cask (melpa). I guess this topic should be reopened.

**Comment by gracjan** [comment]
Reopened.

2015-03-23 2:05 GMT+01:00 Michał Adamczyk <notifications@github.com>:

**Comment by gracjan** [comment]
Michał, can you check what version is pacman installing for you?

**Comment by gracjan** [comment]
@adamczykm: Michał, can you check what version is pacman installing for you?

**Comment by adamczykm** [comment]
@gracjan You were too fast :). Melpa package didn't create autoload file, so I, going by usual convention required haskell-mode.el. Requiring haskell.el fixed all of the issues.
So maybe the thread didn't have to be reopened, it's strange though that the 'name-mode.el' isn't the root file. Thanks.

**Comment by gracjan** [comment]
@adamczykm: pacman package sure contains `haskell-mode-autoloads.el` (does not contain `haskell-mode-autoloads.elc`, not sure if that is the convention or what is the point).

pacman package also contains a lot of '*.elc' files which is arguably not a good thing as that depends on exact emacs version present.

@adamczykm: Can you report a bug to archlinux packager that did package `haskell-mode`?

**Comment by adamczykm** [comment]
I didn't use pacman. I used cask https://github.com/cask/cask

**Comment by gracjan** [comment]
Comfirmed, melpa package does not have autoloads inside.

Should melpa generate autoloads when installing? Should CASK generate autoloads when installing?

What is the convention here?

**Comment by purcell** [comment]
`package.el` generates autoloads at the point when the package is installed.

**Comment by gracjan** [comment]
Why does cask not do it? Should cask be doing it?

**Comment by purcell** [comment]
Not sure. I thought that `cask` just uses `package.el` and the `package-build.el` which provides the machinery for MELPA.

**Comment by gracjan** [comment]
Are autoload generated from `*.el` or there is a need for a special declaration file?

**Comment by purcell** [comment]
They're generated from the `;;;###autoload` comments in the `.el` files, via the standard `update-directory-autoloads` function.

**Comment by gracjan** [comment]
@adamczykm: I load `haskell-mode-autoloads.el` not `haskell-mode.el`, like this:

    (add-to-list 'load-path "~/Sources/haskell-mode")
    (require 'haskell-mode-autoloads)

and then everything works.
