### ISSUE TITLE
Delete-selection-mode is misused in haskell-indentation-delete-char

### ISSUE THREAD

**Issue by MrBones118** [haskell/haskell-mode#388]
In the function haskell-indentation-delete-char, delete-selection-mode is used to determine whether to delete the entire region if there is a mark set. 

Delete selection mode is for deciding whether to remove the region when a region exists and any character is inserted.

I believe that a check for delete-selection-mode should be removed in haskell-indentation-delete-char, meaning that <deletechar> will always delete a region if the mark is active.

**Comment by gracjan** [comment]
@MrBones118: Care to create a pull request for this one?

Bonus points if you add a test case.

**Comment by MrBones118** [comment]
https://github.com/haskell/haskell-mode/pull/482 - i'm not sure how a test case could be used here.

**Comment by gracjan** [comment]
@MrBones118: Thanks!

**Comment by gracjan** [comment]
New `haskell-indentation` does not use `delete-section-mode` at all so this issue seems not relevant anymore. Reopen it this is still a problem.
