### ISSUE TITLE
error with latest haskell mode

### ISSUE THREAD

**Issue by joe9** [haskell/haskell-mode#392]
Hello,

I just upgraded haskell-mode to the latest version and am seeing the below error when I press "SPC"

````
Debugger entered--Lisp error: (void-function haskell-mode-contextual-space)
  indirect-function(haskell-mode-contextual-space)
  command-execute(haskell-mode-contextual-space)
````
Please let me know if I can provide further details.

Thanks
Joe

**Comment by gracjan** [comment]
@joe9, @chrisdone, @purcell, this one is fixed, isn't it?

For reference for other lost souls: `haskell-mode-contextual-space` is not referenced fro anywhere and requires explicit key binding in your own mode-map. Look at `examples/init.el`, the line you are looking for is:

    (define-key haskell-mode-map (kbd "SPC") 'haskell-mode-contextual-space)
