### ISSUE TITLE
Tag a more recent version to melpa-stable

### ISSUE THREAD

**Issue by joe9** [haskell/haskell-mode#394]
Hello,

Just want to check if you could tag a more recent version to make it available to melpa-stable.

Thanks

**Comment by gracjan** [comment]
@chrisdone, @hvr, @purcell, can you clarify release/tagging procedure?

MELPA has 20150120.1233 as current version at the time of this writing. Is this automatic?
How is melpa-stable done? I tried to find out about marmelade but failed to find out what is going on.

**Comment by chrisdone** [comment]
We tend to release as dates, if ever: https://github.com/haskell/haskell-mode/releases Any other kind of versioning is meaningless.

**Comment by purcell** [comment]
So shall we just arbitrarily tag current head as v15.01?

**Comment by chrisdone** [comment]
Maybe once the code stops changing so much?

**Comment by gracjan** [comment]
Duplicate of #226, as this is part of release procedure (or at least should be connected).

**Comment by gracjan** [comment]
Melpa-stable has haskell-mode 13.10: http://stable.melpa.org/#/haskell-mode
Marmelade has 13.7: https://marmalade-repo.org/packages/haskell-mode

Was there a decision to stop updating marmelade?

**Comment by gracjan** [comment]
Note also that haskell-mode-pkg.el needs update:

    (define-package "haskell-mode" "13.10" "A Haskell editing mode" 'nil)

**Comment by gracjan** [comment]
This is a release workflow issue and we are working on release procedure that will also cover releasing to melpa.
