### ISSUE TITLE
after save hook

### ISSUE THREAD

**Issue by acowley** [haskell/haskell-mode#395]
I started getting "run-hooks: Symbol's function definition is void: haskell-mode-after-save-handler" when saving a file. If I `(require 'haskell)`, then I don't get the error, so perhaps a little bit of wiring is missing somewhere.

**Comment by thornjad** [comment]
I'm still getting this error if I don't `(require 'haskell)`, though I don't see this in the installation documentation.

**Comment by purcell** [comment]
@thornjad Then I think you must not be loading the autoloads file as directed in the README.

**Comment by thornjad** [comment]
@purcell the only mention of the autoloads file I see in the README is under the "Installation from git repository" section; I installed from MELPA, so I didn't pay close attention to that section. Is `(require 'haskell-mode-autoloads)` always needed in that case too?

**Comment by purcell** [comment]
If you installed from MELPA, then a `haskell-mode-autoloads.el` file should have been generated into the package installation directory, and `package.el` will load that for you at package initialization time (generally startup time). So with that set up you should not be hitting this issue at all: I'm confused!

**Comment by thornjad** [comment]
I do see `haskell-mode-autoloads.el` in my installation directory, though it doesn't `provide` anything so I can't seem to `require` it anyway. I am using `use-package` rather than `package.el` directly, so I wonder if there's something extra I need to do that `package-install` would do automatically?

**Comment by purcell** [comment]
If it's been installed with `package.el`'s `package-install` via `use-package`, then as long as `package-initialize` gets called, the autoloads file should be loaded. Not sure whether `use-package` calls that for you. It's called implicitly by Emacs at an arbitrary point, so many of us call it explicitly near the beginning of our configs.

**Comment by thornjad** [comment]
Well, I don't like this sort of resolution, but I was playing around with the order in which I call `package-initialize`, `require 'use-package` and some other stuff, and suddenly this error stopped showing up and I can't get it to come back, without needing to `require 'haskell` or anything. I don't know what happened or what changed, but I guess it's good that the error is gone!
