### ISSUE TITLE
haskell-indent-mode keymap interferes with haskell-mode keymap C-c C-.

### ISSUE THREAD

**Issue by ryantm** [haskell/haskell-mode#396]
I am using MELPA version 20141212.1131.

The minor mode, haskell-indent-mode, sets `C-c C-.` to be `haskell-indent-align-guards-and-rhs` shadowing the major mode's binding of that chord to `haskell-mode-format-imports`.

**Comment by gracjan** [comment]
Hmm, with some smart logic C-c C-. could do both depending where you are in the buffer.
