### ISSUE TITLE
haskell-indentation-mode parse error on indenting import declaration

### ISSUE THREAD

**Issue by ryantm** [haskell/haskell-mode#397]
When I use MELPA version 20141212.1131 of the haskell-mode, and a file containing:

```{haskell}
module A where

import Control.Concurrent
  ( forkIO
, killThread)
```
and I put the point at the "k" in killThread and type tab, it prints "Parse error" in the minibuffer and it does not change the indentation.

**Comment by gracjan** [comment]
Unit test case in #562.
