### ISSUE TITLE
Prevent stylish-haskell errors

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#401]
With `haskell-stylish-on-save` set to `t` and something that `stylish-haskell` can't parse (via `haskell-src-exts`) in a buffer, e.g.

```
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}

class Foo c a where

  bar :: (c a) => a -> a
```

every time the buffer is saved the `*Warnings*` buffer pops up (typically overriding another buffer I had open, thus forcing me to change it back) with a parse error from stylish-haskell.

Is there a way to prevent this?  It seems that this is because of the explicit call to `display-warnings` in https://github.com/haskell/haskell-mode/blob/a165795af8ab0347bdde8a877a88fc5ff34385db/haskell-commands.el#L760

**Comment by gracjan** [comment]
@ivan-m, @purcell, @rietmann: can you check if referenced commit fixes your issue?
