### ISSUE TITLE
⧺(U+29FA) not highlighted as operator

### ISSUE THREAD

**Issue by eigengrau** [haskell/haskell-mode#410]
I’m using `⧺ (double plus, U+29FA)` as an alias to `++`, but I’ve noticed that this glyph is not highlighted like the other operators, despite U+29FA being a non-alphanumeric character as per the Unicode character data.

This is with Haskell-mode v. 20141213.848.

Thanks for making Haskell-mode!

**Comment by eigengrau** [comment]
Hello! Thank you kindly for the fix!

I presume the most general approach would be to use property values defined in the official Unicode character database. I would have expected that Emacs could query these, but I could only find [functions](http://www.gnu.org/software/emacs/manual/html_node/elisp/Character-Properties.html) which can query the Unicode «general category» of a character, not the individual properties.

It might be that this is enough, since the category will say whether a character is a letter or a number (cf. [here](http://www.wikiwand.com/en/Unicode_character_property#/General_Category)). I guess you could either pull a list based on such a category, or define it programmatically based on the category.

Maybe one could just use a regexp character class (`[^[:alpha:][:digit:]]`?), but I previously noticed quirks in the way Emacs handles character classes (e.g., the whitespace class only matches ASCII whitespace).

**Comment by eigengrau** [comment]
Ah, I just noticed you already added some block ranges. I guess that should work. I’m not sure whether the blocks not explicitly mentioned include some operators, though, or vice versa, whether some of these ranges include characters classified as alphanumeric by the Unicode data specs.

**Comment by eigengrau** [comment]
E.g., the «enclosed alphanumerics» block includes characters officially classified as numeric characters. I’m not sure how Haskell syntax is supposed to handle these, though.

**Comment by purcell** [comment]
@eigengrau See the comments in #412 -- specifically:

> I added enclosed alphanumeric characters, they are not alphanumeric (http://www.fileformat.info/info/unicode/char/2460/index.htm)

**Comment by eigengrau** [comment]
Thanks! Some of the chars from the enclosed numbers block are numeric (general category `other number`), but at least with these, the GHC lexer doesn’t like them at all, so it shouldn’t be a problem to define them as operators for the time being. This seems to be a bug in GHC, though, since other `other number` characters, e.g. superscript 2 `²`, are currently valid in identifiers, and the GHC source says `other number` characters are generally okay.

**Comment by ikirill** [comment]
@purcell There is some imprecision in doing this per-block (ghc uses general category to determine if a character is Letter-lower/upper/other/titlecase or Number-digit/other) because some non-alphanum characters are missed in skipped blocks. I went by a regular expression applied to a block's name, and it catches all the common mathematical operators. 

Actually, for Enclosed alphanumerics I think I shouldn't have done that: I went by isLetterOrDigit (http://www.fileformat.info/info/unicode/char/2460/index.htm), but its category is really Number-Other, so that was wrong.

**Comment by purcell** [comment]
Ah, okay. Well, I feel like we're still basically making things better rather than worse! If there are any follow-up corrections you'd like to make, I can merge them promptly.

**Comment by ikirill** [comment]
Should this be done only for symbol constituents, or for identifiers too?

**Comment by purcell** [comment]
@ikirill I'm not really sure what's allowed where. For instance, I noticed that Haskell parses `foo⧺bar` as `foo ⧺ bar`, so `⧺` presumably shouldn't be considered an identifier character.

**Comment by ikirill** [comment]
No, I mean for haskell-mode? I made a huge non-contiguous list of symbol characters and identifier characters. Should I set all identifier characters to word syntax?

**Comment by purcell** [comment]
I guess so, but IIRC they're matched by a `varid` regexp, so I don't know how much the syntax table comes into play.

**Comment by purcell** [comment]
Perhaps give it a try locally and see how things work out.

**Comment by ikirill** [comment]
@purcell See #413
