### ISSUE TITLE
Pick one indentation mode as preferred in the documentation/customize.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell/haskell-mode#414]
Configuring haskell-mode is a bit hard on the user still.  Even by knowing how to use customize, every user is required to visit the wiki or read detailed documentation just to configure what &lt;TAB&gt; is supposed to do.

If one indentation mode was marked as suggested in the customize UI, then this would be much less of an issue.

**Comment by purcell** [comment]
Agreed. There should be one reasonable option enabled by default.

**Comment by gracjan** [comment]
Fixed by #555.

**Comment by ivan-m** [comment]
Actually, I think `simple` should be the default as a more basic solution.

**Comment by gracjan** [comment]
Recently merged `hi2` (new `haskell-indentation`) has a very high quality. If you think there is something to be fixed about `haskell-indentation` please file an issue report.

**Comment by ivan-m** [comment]
Nothing to do with quality.  Just that if someone unused to any such mode installs haskell-mode, then the simple indentation mode should be the easiest to get started with.

**Comment by gracjan** [comment]
`haskell-indentation` is the easiest to start with for people used to other programming modes for Emacs.

**Comment by ivan-m** [comment]
Which, of course, assumes that everyone installing haskell-mode is used to other programming modes for Emacs.

(And I don't recall any other mode having a similar indentation cycle...)

**Comment by purcell** [comment]
> Which, of course, assumes that everyone installing haskell-mode is used to other programming modes for Emacs.
> 
> (And I don't recall any other mode having a similar indentation cycle...)

Python indents similarly, and is one of the few other languages where indentation is semantically meaningful.

Why do you think `simple` would be any easier?

**Comment by ivan-m** [comment]
No indentation cycle.  Hitting tab just indents to the next position and that's it.

Especially since whilst the hi2 branch might have existed for a while for testing purposes, it has only just now been installed as part of the haskell-mode installed through MELPA/distro packages/etc. and it would probably be better to have a transition or something for it (I admittedly haven't tried it out as I use shm nowadays, but I used to use `haskell-indentation` when it was still referred to as Kuribas' indentation mode).

**Comment by purcell** [comment]
I don't personally feel strongly about which indentation mode should be the default, but `simple` sounds reasonable, and still better than none.

**Comment by gracjan** [comment]
`haskell-indentation` is the most used mode according to last survey. It received most engeneering hours spend polishing it. Code created by kuribas and nilcons is actually hackable and that will enable us to react to bug reports and possible feature requests. I do not see why we should impose subpar experience on newcomers.

If somebody feels strongly for using hsi then it is just one `turn-on-haskell-simple-indent` away.

**Comment by purcell** [comment]
That also sounds very reasonable. I suggest we stick with this new arrangement for now and see how things go.

**Comment by kuribas** [comment]
I am biased of course, but I'd like to give the following reasons for making indentation-mode the default:

 * It's not intrusive for a new user.  The only thing they have to know is _tab_ indent to the right, and _shift-tab_ indent to the left.  In contrast to for example _structured haskell mode_, which takes some time to get used to.
* It is fairly correct in finding place to indent, in contrast with haskell-indent
* emacs has always been an editor for people who want something extra at the cost of a steeper learning curve.  A plain indentation mode may give the user the mistaken impression that haskell doesn't have auto-indentation.

**Comment by geraldus** [comment]
@gracjan is it still relevant?

**Comment by gracjan** [comment]
Yes. haskell-indentation-mode is still not good enough to be a good default.

**Comment by gracjan** [comment]
New attempt: #922.
