### ISSUE TITLE
Assertion failure in haskell-indent-in-comment

### ISSUE THREAD

**Issue by ikirill** [haskell/haskell-mode#415]
With the following file:

```hs
{-# OPTIONS -w
    #-}

module Test where

-- {{{ A header
-- !

import Data.List

-- }}}
```

place point right after the exclamation mark and press enter with electric-indent-mode turned on. (With electric indent turned off, press enter, then indent with tab.)

I get:
```
Debugger entered--Lisp error: (cl-assertion-failed (<= start end))
  signal(cl-assertion-failed ((<= start end)))
  (or (<= start end) (signal (quote cl-assertion-failed) (list (quote (<= start end)))))
  haskell-indent-in-comment(60 37)
  haskell-indent-indentation-info(60)
  haskell-indent-virtual-indentation(60)
  haskell-indent-after-keyword-column(("where" 0 0) 60)
  haskell-indent-indentation-info()
  haskell-indent-cycle()
  indent-for-tab-command(nil)
  funcall-interactively(indent-for-tab-command nil)
  call-interactively(indent-for-tab-command nil nil)
  command-execute(indent-for-tab-command)
```

Maybe it should just return nil instead of raising an error?

**Comment by gracjan** [comment]
That was easy to confirm and reproduce. I've added a test that should be a nice jump start for a solution.

**Comment by gracjan** [comment]
We have just merged new and improved `haskell-indentation` that should solve issues like this and more.

I'm closing this particular issue. Do not hessitate to report similar issues related to `haskell-indentation`.
