### ISSUE TITLE
Can't find module in completely trivial case

### ISSUE THREAD

**Issue by karljs** [haskell/haskell-mode#423]
Suppose I create two files (One.hs and Two.hs) in a directory as follows:
One.hs:
```haskell
module One where

data One = One
```
Two.hs
```haskell
module Two where
import One

data Two = Two One
```
If I load `Two.hs` and run `haskell-process-load-or-reload` it fails to find module One.  When prompted, I give the directory containing the two files as both the cabal directory and the current directory.

I generally set `haskell-process-type` to auto, but this occurs even when commenting out all Haskell-related code in my .emacs file or when setting it to ghci manually.

If I run GHCi manually as a sanity check, it works fine.  I'm using the version from Melpa (and have tried removing and reinstalling).

**Comment by chrisdone** [comment]
What's going on in the log? https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-REPL#Troubleshooting

**Comment by karljs** [comment]
Here is a copy of what's in the log.  As best I can tell, it's not entering the "test" directory even when I set that as the current directory, but I'm not 100% sure on the expected behavior.

```
Starting inferior GHCi process ghci ...
-> :set prompt "\4"
-> Prelude.putStrLn ""
-> :set -v1
<- GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
   
<- Loading package ghc-prim ... 
<- linking ... done.
   Loading package integer-gmp ... linking ... done.
   Loading package base ... linking ... done.
   Prelude> 
-> :cd /Users/karl/workspace/
<- 
   
-> :load "/Users/karl/workspace/test/Two.hs"
<- 
   /Users/karl/workspace/test/Two.hs:3:8-10:
       Could not find module ‘One’
       Use -v to see a list of the files searched for.
   Failed, modules loaded: none.
```

**Comment by karljs** [comment]
Ah, I've found the problem.  There seems to be a conflict with Helm.  If I disable Helm completely, this works as expected.  I suppose the bug is on their end then.

Feel free to close as you see fit.
