### ISSUE TITLE
Identifiers within backticks not highlighted when prefixed with module name

### ISSUE THREAD

**Issue by eigengrau** [haskell/haskell-mode#438]
While functions enclosed within backticks are normally highlighted using the operator face by default, I have noticed that this doesn’t happen when the function has a module prefix in front. Is this intended?

E. g., in the following program, `Module.function` will have `haskell-default-face`, wheras it has `haskell-operator-face` when the module prefix is left out.

```
x = y `Module.function` z
```

This is with Melpa ver. 20150101.1151.

Best regards!

**Comment by gracjan** [comment]
Confirmed. Font lock rules seems to be overly complicated...

**Comment by gracjan** [comment]
Here you go!

**Comment by eigengrau** [comment]
Working just fine! Thank you kindly!

**Comment by gracjan** [comment]
@purcell, @chrisdone, This one is fixed and can be closed.
