### ISSUE TITLE
haskell-definition-face not used when as-pattern precedes infix function definition

### ISSUE THREAD

**Issue by eigengrau** [haskell/haskell-mode#450]
When a function is defined in infix syntax, haskell-definition-face applies to the function name. So in the following, `op` will bear the definition face.

```
foo `op` bar = undefined
```

However, haskell-definition-face will fail to be assigned when an as-pattern precedes the function name. So, `op` below receives haskell-operator-face.

```
foo@Nothing `op` bar = undefined
```

**Comment by gracjan** [comment]
Ugh, this one is real tough, if we complicate a little:

    foo@RadomRecord { withFields = (_,Just assignAVar) } `op` bar

going over the part after @ needs more than a regexp. I'm guessing it is doable in Emacs, but current haskell-font-lock.el does not allow for easy way of doing it.

**Comment by gracjan** [comment]
Not only tokenizer, full parser is needed. The one from haskell-indentation could be retroffieted to do what we need.

**Comment by gracjan** [comment]
See also #1122.

**Comment by gracjan** [comment]
No semantic therefore no fix for this one.
