### ISSUE TITLE
always pops open a help buffer when hitting return

### ISSUE THREAD

**Issue by anarcat** [haskell/haskell-mode#454]
Hi

I am using the `haskell-mode` package from debian (version `13.10-3`). When I edit a haskell source file and hit the `ENTER` key pretty much anywhere in the buffer, i get popped a buffer:

```
haskell-mode-hook is a variable defined in `haskell-mode.el'.
Its value is nil

  This variable may be risky if used as a file-local variable.

Documentation:
Hook run after entering Haskell mode.
No problems result if this variable is not bound.
`add-hook' automatically binds it.  (This is true for all hook variables.)

You can customize this variable.

[back]
```

That is so strange! :) I can't quite figure out where this is coming from on my own, and I don't believe I have any special customization for this module. Anyways it happens with only `emacs -q` in Emacs 24:

```
This is GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)
 of 2014-12-09 on gaia, modified by Debian
```

**Comment by cocreature** [comment]
Read https://github.com/haskell/haskell-mode/wiki/Indentation You need to set an indentation hook.

**Comment by chrisdone** [comment]
I suspect your haskell-mode is older than The Beatles.

**Comment by anarcat** [comment]
i am using the debian package:

```
ii  haskell-mode                                          13.10-3                         all                             major mode for editing Haskell in Emacs
```

**Comment by anarcat** [comment]
@cocreature, it seems that:

```
(add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
```

... fixes the problem here. shouldn't there be a more obvious way to find this? i've been using emacs for years, and i was utterly confused by this behaviour. it seems to me saner defaults should be implemented here...

**Comment by chrisdone** [comment]
There is a better behaviour which tells you that you need to do this. But your haskell-mode version is probably too old. Debian isn't exactly the most up to date of distributions.

**Comment by anarcat** [comment]
Beyond the stereotypes, i already pasted here the version i am using, and it's 13.10, which is the latest version available here. It is a year old. Unless the beatles made a special comeback (from the dead) that I wasn't aware of or that time travel was finally figured out, i think i have the right version of haskell-mode.

If the "better behavior" that "tells me that i need to do this" is the window popup i described in this bug, then it was clearly not obvious to me that i "needed to do anything".

But then again, i'm just an old beatles fan, so what do i know.

**Comment by chrisdone** [comment]
Git is the latest version. Nobody has made a "release" since 13.10. Yes, in two years things have changed.

**Comment by anarcat** [comment]
well maybe a release should be made before complaining that people are running "old code".

unless there should be no more releases and we should just all use git forever? who needs release engineering anyways.

**Comment by ivan-m** [comment]
Most people now tend to install Emacs packages via package.el, and there are newer versions of haskell-mode in both the marmalade and melpa repositories.

**Comment by anarcat** [comment]
from what i can tell, Marmalade has [13.7](https://marmalade-repo.org/packages/haskell-mode). only MELPA has a "newer version" of haskell-mode, which is not a release, but a [snapshot](http://melpa.org/#/haskell-mode).

anyways, i guess "please keep on making regular releases" is a different issues. if the usability issue has been fixed in later versions (even if unreleased), it seems fair to close this issue.

**Comment by ivan-m** [comment]
See #394

**Comment by gracjan** [comment]
@purcell, @chrisdone: I guess this issue is closable in the sense that git version has the functionality. For releasing newer version there is #394.
