### ISSUE TITLE
Interactive-mode fails on multiple executables

### ISSUE THREAD

**Issue by LukeHoersten** [haskell/haskell-mode#458]
I have multiple executable sections and a library section in my cabal file. Interactive mode gets confused in two ways:

1. My modules that are in the src sections of the executable sections aren't found.
2. Dependencies that only the executables have but that are not dependencies of library are not found.

**Comment by ivan-m** [comment]
Is this using cabal-repl?  If so, you need to use `haskell-session-change-target` (unfortunately you need to manually set it, it can't find out what all the possible targets are).

**Comment by LukeHoersten** [comment]
Yeah that fixes it. Thanks.

**Comment by ivan-m** [comment]
For those stumbling across this: #1551 will fix this.
