### ISSUE TITLE
Document how to get :complete support

### ISSUE THREAD

**Issue by unhammer** [haskell/haskell-mode#460]
Perhaps `(error "GHCi lacks ':complete' support")` in haskell-process.el:268 could be changed to say `"GHCi lacks ':complete' support (try installing 7.8 or ghci-ng)"` – when I searched for "ghc complete support" I got no hits, only found out by accident that I could just `cabal install ghci-ng` to get it

**Comment by gracjan** [comment]
@unhammer: So true!

Sound like a good task. Are you able and willing to get it done and submit a pull request?
