### ISSUE TITLE
Customizable module template

### ISSUE THREAD

**Issue by MichaelXavier** [haskell/haskell-mode#462]
I wanted to see if you'd take a PR to change `haskell-auto-insert-module-template` to use a customizeable var. At my work we use a different indentation for module headings so while I use this feature, I always have to manually reformat. I was thinking the var could be in `format` style: "--|\nimport %s where\n". Here's the relevant code.

https://github.com/haskell/haskell-mode/blob/af34d4e5afe11061bd98d2757d9d2bb93006faec/haskell-mode.el#L1036

If you would take a PR, should I keep the same function name, or make it `haskell-apply-auto-insert-template`, or if not, what would you like the var named?

**Comment by ivan-m** [comment]
As an alternate way of doing things, I instead use `skeleton-mode` rather than `haskell-auto-insert-module-template` (I actually didn't even know the latter existed):

```
(require 'skeleton)
(require 'autoinsert)

;; Skeletons
(define-skeleton haskell-module-skeleton
  "Haskell hs file header"
  "Brief description: "
  "{- \|\n"
  '(setq module-name (haskell-guess-module-name))
  "   Module      : " module-name "\n"
  "   Description : " str | (concat "The \"" module-name "\" module") "\n"
  "   Copyright   : (c) Ivan Lazar Miljenovic\n"
  "   License     : 3-Clause BSD-style\n"
  "   Maintainer  : Ivan.Miljenovic@gmail.com\n"
  "\n"
  "   " _ "\n"
  "\n"
  " -}\n"
  "module " module-name " where\n\n")

(add-to-list 'auto-insert-alist '("\\.hs\\'" . haskell-module-skeleton))
```

**Comment by chrisdone** [comment]
Making it customizable by a format string seems fine. The PR should preserve the existing behaviour with a default customization which matches what it already does.
