### ISSUE TITLE
Errors in interactive buffer to code

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#467]
It used to be that if an error appeared in the interactive buffer, I could hit Enter and be taken to where in the source code that error was found.

Now, it seems that this no longer works.  Even for something as simple as this:
```
bar :: Int
bar = 3.0
```

I have enter/return bound to the default `(haskell-interactive-mode-return)`.

I couldn't find anything obvious in the source or its history as to when this behaviour changed.  Any ideas?

**Comment by chrisdone** [comment]
It should work. Moar data.

**Comment by ivan-m** [comment]
I worked out what happened: somehow `flycheck` was being enabled on interactive buffers, which causes problems with `next-error-internal` *facepalm*

This seems to be because I have flycheck enabled globally.  I guess I should change that then ;-)
