### ISSUE TITLE
haskell-cabal-add-dependency messes up cabal file if tabs are not turned off.

### ISSUE THREAD

**Issue by rabipelais** [haskell/haskell-mode#474]
I am attempting to add a dependency automatically to a cabal file. However, after the insertion, the cabal file is completely broken. This happens if `indent-tabs-mode` is set to true, *even* if it is set to false for haskell-cabal mode.

# Steps to reproduce
Start with default auto-generated minimal cabal file.
With that file in the current buffer run:
`(setq-default indent-tabs-mode t)`
`(haskell-cabal-add-dependency "foo" "3" nil nil)`
Answer `yes` to prompts

# Expected result
```
name:                test
version:             0.1.0.0
license-file:        LICENSE
build-type:          Simple
cabal-version:       >=1.10

executable test
  main-is:             Main.hs
  build-depends:  foo >= 3
                 , base >=4.7 && <4.8
  default-language:    Haskell2010
```

# Actual result
```
name:                test
version:             0.1.0.0
license-file:        LICENSE
build-type:          Simple
cabal-version:       >=1.10

executable test
  main-is:             Main.hs
  build-depends:       					   foo >= 3
					 , 4.8
  default-language:    Haskell2010
```
Note that the weird indentation and lack of `base` is verbatim copied from my editor. The whitespace between `build-depends:` and `foo` is tabs, not spaces.

# Notes
As mentioned above, this happens if tabs are turned on, even if they are turned off for all haskell related modes. Adding more dependencies after this only makes the file wonkier. 
If I undo the `(haskell-cabal-add-dependency "foo" "3" nil nil)` command, set `indent-tabs-mode` to `nil`, and re-add the dependency, it is inserted correctly this time.

**Comment by gracjan** [comment]
@rabipelais: Is this the same as #376?

**Comment by rabipelais** [comment]
@gracjan 
> haskell-cabal-mode explicitly does (setq indent-tabs-mode nil) so I guess a TAB in cabal file will 
> happen never again.

That solution doesn't work for me in this case, because that `(setq indent-tabs-mode nil)` applies only to `haskell-cabal-mode`. 
In the use-case where a *global* `indent-tabs-mode` is not `nil` (for example for me, as I use tabs for C/C++ dev), the problem arises when `haskell-cabal-add-dependency` calls `haskell-cabal-with-subsection`, which in turn uses the `with-temp-buffer` macro to temporarily format the new entries. The buffer that `with-temp-buffer` opens starts in the default `major-mode`, which is `fundamental-mode` in the default case. 
Here the `indent-tabs-mode` from the `haskell-cabal-mode` has no effect, hence the tabs, which are copied verbatim to the cabal file.

I will test if changing `indent-tabs-mode` inside the `with-temp-buffer` macro solves the issue.

**Comment by rabipelais** [comment]
Yes, apparently setting `indent-tabs-mode` to nil inside `with-temp-buffer` (and recompiling) solves the issue, with no side-effects.

```
--- #<buffer haskell-cabal.el>
***************
*** 464,469 ****
--- 464,470 ----
         (save-excursion
           (prog1
               (with-temp-buffer
+ 			     (setq indent-tabs-mode nil)
                 (indent-to ,start-col)
                 (insert ,section-data)
                 (goto-char (point-min))
```

**Comment by gracjan** [comment]
@rabipelais: Change looks good to me and was already discussed in #376.

A pull request would be greatly appreciated.

**Comment by gracjan** [comment]
@rabipelais: Is this working for you now? Can we close?

**Comment by rabipelais** [comment]
Yes, working. It can be closed, thank you.

**Comment by gracjan** [comment]
@rabipelais: You can close this issue yourself as you are the one reporting it!
