### ISSUE TITLE
haskell-mode Version header

### ISSUE THREAD

**Issue by holomorph** [haskell/haskell-mode#475]
Quoting the elisp manual, emphasis my own:
> ‘Version’
>      If you wish to record version numbers for the individual Lisp
>      program, put them in this line.  Lisp files distributed with Emacs
>      generally do not have a ‘Version’ header, since the version number
>      of Emacs itself serves the same purpose.  _If you are distributing a
>      collection of multiple files, we recommend not writing the version
>      in every file, but only the main one._

haskell-indent.el seems to be the only file in the project with a Version header. This should instead be haskell-mode.el, because I imagine that is the "main" one.

This became apparent when I used the shiny `package-install-file`[0] in development Emacs, and I ended up with haskell-indent in my package list. Otherwise the install was flawless. Neat!

Anyways, fixing the headers is a small change and I can make a PR if you want.

[0] http://endlessparentheses.com/new-in-emacs-25-1-easily-install-multifile-package-from-a-directory.html

**Comment by gracjan** [comment]
@holomorph: Great! PR would be appreciated!
