### ISSUE TITLE
haskell-indendation and guards 

### ISSUE THREAD

**Issue by EDmitry** [haskell/haskell-mode#481]
Consider the following code:

```
resolve (amount, max) number 
  | number > max = (1, number)
  | number == max = (amount + 1, number)
```

If I put the cursor in the end of the last line and hit <enter> and then try to use <tab> to cycle through all indentation possibilities it would never align with the previous guard. Is this expected or a bug? How does haskell-indentation mode format guards?

**Comment by ivan-m** [comment]
Does `C-c C-|` (or it might be `C-c |`; I forget; I haven't used haskell-indentation for quite a while) work for auto-insertion of guards?  What is `haskell-indent-spaces` set to?  (It appears that you have the guards indented by two spaces here.)

**Comment by EDmitry** [comment]
I have this set:
```
(setq c-default-style "bsd"
      c-basic-offset 4)
(setq-default indent-tabs-mode nil)
```
but nothing specific to haskell-mode. But shouldn't it indent based on previous guard automatically?

**Comment by ivan-m** [comment]
`C-h v haskell-indent-spaces`

**Comment by EDmitry** [comment]
New indentation from wip/hi2 doesn't fix this issue unfortunately:

![screen shot 2015-03-09 at 1 40 46 pm](https://cloud.githubusercontent.com/assets/141007/6563901/fe011a96-c661-11e4-9b84-9c0b487a1ae4.png)

I am still not sure how this is supposed to be working — I am not convinced guards have to be inserted by a hotkey. In theory it should be pretty easy to detect a guard on the previous line and add an indentation stop right under it.

**Comment by gracjan** [comment]
Do I understand that the pink rectangle position is offered as indentation point when it should not be?

Or do you want `haskell-indentation` to insert guards for you? (Auto-inserting was done by `haskell-indent`).

**Comment by EDmitry** [comment]
Sorry, the pink rectangle is just my cursor, I should have moved it before taking the screenshot. I was expecting the indentation position (one of) to be right under `|`.

**Comment by gracjan** [comment]
I think I now understand. So if you place the cursor *at a line with a guard* then it offers proper indentation position. But if you place the cursor *on empty line below a line with a guard* then it does not offer guard position as an option.

There are a couple of ways to intepret this situation. As far as I understand most of emacs modes for other languages use 'electric' behvior, that is as soon as you insert '|' (guard) it gets indented properly. This could work in this case as there is exactly one available indentation position.

**Comment by gracjan** [comment]
If you consider code:

```
resolve (amount, max) number 
  | number > max = (1, number)
  | number == max = (amount + 1, number)
  |
```

and now press TAB on line with the singe `|` in it, then `haskell-indentation` is properly able to recognize that you have started new guard.

I'll close this specific issue about guards as similar problem appears when continuing lists or records or curly braced constructs. Someday we will be able to tackle this together.

**Comment by PierreR** [comment]
:+1: to tackle this as soon as it can be ;-)
