### ISSUE TITLE
Remove cabal-ghci support

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#486]
cabal-ghci was like cabal-dev. After proper support for 'cabal repl' those are not needed anymore.

**Comment by gracjan** [comment]
Longer discussion in comments below the issue #198.

**Comment by gracjan** [comment]
Fixed by #480.

**Comment by gracjan** [comment]
This was not fully done after all.

**Comment by gracjan** [comment]
@johnwalker: And if you could finish removing `cabal-ghci` that would be awesome!

**Comment by johnwalker** [comment]
sure!
