### ISSUE TITLE
Boolean OR (||) highlighting as guard

### ISSUE THREAD

**Issue by mcandre** [haskell/haskell-mode#489]
In the latest haskell-mode, boolean OR (`||`) is being hightlighted as as guard (`|`) followed by plain text; instead of highlighting both pipes as a single token.

**Comment by ivan-m** [comment]
It isn't for me; it looks like it's `haskell-definition-face`.

**Comment by gracjan** [comment]
Confirmed. The issues seems to be with more operators, particularly `==` is also affected.
