### ISSUE TITLE
Read only of REPL prompt in Inf-Haskell

### ISSUE THREAD

**Issue by m00nlight** [haskell/haskell-mode#493]
It should be nice to make the repl prompt in Inf-haskell buffer not deletable like in the *eshell* mode.

**Comment by gracjan** [comment]
@m00nlight: you see to know what you want and know how to copy paste relevant fragment from eshell. How about a pull request?

**Comment by m00nlight** [comment]
@gracjan  OK. I will try to patch a pull request.

**Comment by gracjan** [comment]
@m00nlight: great!

**Comment by m00nlight** [comment]
@gracjan After some investigation, I found that `inf-haskell-mode` is depreciated. It is replaced by `interactive-haskell-mode` which can configured with the following link:

https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-Setup

And the prompt of `interactive-haskell-mode` is read-only by default. So do we still need to patch
the depreciated `inf-haskell-mode`? Or should we just to update the configure tutorial on haskell wiki
and make more clear document in the repository?

[1] https://wiki.haskell.org/Emacs/Inferior_Haskell_processes

**Comment by gracjan** [comment]
@m00nlight: updates to instructions are way more important than fixing old code. Can you do that?

**Comment by m00nlight** [comment]
@gracjan  OK. No problem. I will update the configuration tutorial.
