### ISSUE TITLE
Link to latest HTML Manual in README.md is broken

### ISSUE THREAD

**Issue by tekul** [haskell/haskell-mode#494]
The link in the "Basic Configuration" section (to http://haskell.github.io/haskell-mode/manual/latest/) doesn't exist.

**Comment by gracjan** [comment]
Hmm, haskel.github.io does not exist because somebody removed github.com/haskell/haskell-mode.github.io repo. 

@chrisdone or @purcell, do you know when and why it happened?

**Comment by purcell** [comment]
No idea, sorry.

**Comment by gracjan** [comment]
Hmm, people actually want to read the documentation.

@purcell, @chrisdone: do you have opinion where to put the documentation?
