### ISSUE TITLE
Multiline string literal not terminated by syntax highlighter

### ISSUE THREAD

**Issue by eallik** [haskell/haskell-mode#497]
Going through the RWH book, I ended up having the following 2 definitions:

```haskell
raw = "\
      \#define X_FOOBAR   /* a foobar */\n\
      \#define X_QUUX     /* a quux */\n\
      \#define Y_BLAH     /* a blah */\n\
      \#define X_BLAH     /* a blah */\n\
      \"

defs = map sndWord . (lines >>> filter ("#define X_" `isPrefixOf`))
  where sndWord = (!! 1) . words
```

(coincidentally, GitHub's markdown has the same bug :))

![screen shot 2015-03-08 at 11 51 13](https://cloud.githubusercontent.com/assets/17533/6545314/919a0486-c589-11e4-9651-941e4ecf7a9f.png)

Inserting a space between the `\` and `"` results in correct behavior (but obviously also a different string value stored in `raw`):

![screen shot 2015-03-08 at 11 52 47](https://cloud.githubusercontent.com/assets/17533/6545319/c1833514-c589-11e4-8492-35232cbdb308.png)

Note that _both_ snippets compile, i.e. `\"` as the last line of a multiline string is perfectly legal and not the same as ending a single-line string with a backslach.

**Comment by gracjan** [comment]
@eallik: After a quick test program:

   str = "\"

gives error in compilation:

    T2.hs:3:10:
       lexical error in string/character literal at character '\n'

Where this program compiles as it should:

   str = "\""

So if you backslash-escape last doublequote you get unterminated string constant and lexical error.

Having said that I like the idea of treating unescaped newline as string terminating for the purpose of font-lock. I'm not sure though how hard it is to get in emacs as currently define dquote to be pair to another dquote and backslash as escape character and we just let emacs do the font locking.

**Comment by gracjan** [comment]
Note that other emacs modes highlight the same, for example c-mode:

    char *str = "unterimanted\"
    void main()
    {
    }

will font-lock as string till the end of file.

**Comment by gracjan** [comment]
@eallik: I would love to see unterminated strings in error face font.

Are you into emacs lisp enough to have a go at this problem?

**Comment by ivan-m** [comment]
@gracjan

**Comment by ivan-m** [comment]
@gracjan except that that's the correct syntax for multiline strings:

```haskell
test :: String
test = "hello\n\
       \"
```

This is a valid definition of a `String`, and is equivalent to just `test="hello\n"`.

**Comment by gracjan** [comment]
Oh, that is suprising! For the record, this is legal:

    str = "\"\
           \"

This is not legal:

    str = "\"\
           "

Relevant quote for [Haskell Report](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-200002.6):

> A string may include a “gap”—two backslants enclosing white characters—which is ignored. This allows one to write long strings on more than one line by writing a backslant at the end of one line and at the start of the next. For example,

    "Here is a backslant \\ as well as \137, \  
        \a numeric escape character, and \^X, a control character."

**Comment by eallik** [comment]
@gracjan exactly; that's why the title said "multiline"; obviously `"\"` is not legal. In other words, I knew the snippet I include was 100% compilable.
