### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by frankcash** [haskell/haskell-mode#505]
>Alternatively, you can also direct your browser to the [latest online HTML version](http://haskell.github.io/haskell-mode/manual/latest/).

http://haskell.github.io/haskell-mode/manual/latest/ 404's.

**Comment by gracjan** [comment]
@frankcash: good catch. @tekul already reported this one in #494.

**Comment by frankcash** [comment]
No problem, sorry for over looking that.
