### ISSUE TITLE
Backspace character in haskell-interactive-mode

### ISSUE THREAD

**Issue by cmears** [haskell/haskell-mode#51]
QuickCheck uses backspace characters to make nice output while it is running tests. This does not work in haskell-interactive-mode:

```
λ> import Test.QuickCheck

λ> quickCheck (\xs -> reverse (reverse xs) == xs)
(0 tests)^H^H^H^H^H^H^H^H^H         ^H^H^H^H^H^H^H^H^H(1 test) [etc.]
```

I think the old inferior-haskell mode handles this properly, but I'm not sure how to fix it in the new interactive mode.

**Comment by ShaneDrury** [comment]
I don't mean to dredge up a 4 year old issue, but it can be fixed by adding 
```lisp
(add-hook 'haskell-mode-hook
       '(lambda ()
          (setq process-connection-type nil)))
```
to your `.emacs` file. From https://sites.google.com/site/haskell/notes/ghci610emacsmadness

**Comment by ivan-m** [comment]
@ShaneDrury are you sure it's relevant? That page says it doesn't apply as of 6.10.3.
