### ISSUE TITLE
Can't load tests

### ISSUE THREAD

**Issue by cocreature** [haskell/haskell-mode#515]
When loading tests `cabal repl` and so ofc also haskell-mode complains about missing dependencies. For tests haskell-mode should launch a separate repl with `cabal repl tests`. Not quite sure how to detect when a file is a test.

**Comment by ivan-m** [comment]
Use `haskell-session-change-target` to change to the test target.

**Comment by cocreature** [comment]
Thanks for your answer. On a quick look that doesn't seem to work. It tries to switch to that directory which breaks my nix setup because the .nix file is only in the main directory. However I don't see why changing the target should cause a directory switch. I'll try to look into this a bit more tomorrow.

**Comment by ivan-m** [comment]
Wait, you said you were using cabal-repl; what does that have to do with a .nix file?

**Comment by cocreature** [comment]
I am using `haskell-process-wrapper-function` to wrap every command inside nix-shell.

**Comment by ivan-m** [comment]
OK, don't know anything about using that.

But using `haskell-session-change-target` will let you switch to a test target in the .cabal file, so that you can then make sure any additional dependencies are in scope.

**Comment by cocreature** [comment]
Ah I think there is something wrong with how haskell-session-change-target is passed. It is not wrapped but passed as an extra argument (which causes it to be passed to the wrapped command). I'll investigate and try to fix it. Closing this issue as it is really about applying the wrapper correctly.
