### ISSUE TITLE
C-c C-l gives uneasy suggestion

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#522]
`C-c C-l` says:

    You tried to do an interaction command, but an interaction mode has not been enabled yet.
    Run M-x describe-variable haskell-mode-hook for a list of such modes.

(this does not fit in minibuffer because it is two lines long, but disregarding that)

`M-x describe-variable haskell-mode-hook` tell the usual Emacs blurb and this:

    Documentation:
    Hook run after entering Haskell mode.

`M-x customize-option RET haskell-mode-hook` suggests a lot but neither `interactive-haskell-mode` nor `inf-haskell-mode` is in the list.

Then there is a link to "See also haskell-mode and (haskell-mode)haskell-mode-hook." and that leads to:

    @vindex haskell-mode-hook
    One of the important setting you should customize is the @code{haskell-mode-hook} variable  
    (@pxref{Hooks,,,emacs}) which gets run right after the @code{haskell-mode} major mode is
    initialized for a buffer. You can customize @code{haskell-mode-hook} by 
    @kbd{M-x customize-variable @key{RET} haskell-mode-hook}. It's highly recommended you
    set up indentation to match your preferences; @xref{Indentation}, for more details about
    the indentation modes included with Haskell Mode.

So still nothing about `interactive-haskell-mode`. 

There is wiki: https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-Setup , where we read:

    Run C-` to make a REPL open, this will create a session, start GHCi, and open the REPL.

Meanwhile `C-backtick` (`haskell-interactive-bring`) is not bound at all.

**Comment by gracjan** [comment]
Note that more documentation for `haskell-mode-hook` is there, just it is not shown via `describe-variable`.

**Comment by gracjan** [comment]
Seems Emacs just does not show documentation for hook beyond the generic `Hook run after entering XXX mode.`. So helpful!

**Comment by unhammer** [comment]
Odd, when I do `C-h v haskell-mode-hook RET`, I get the full documentation (same as when looking at the elisp).

(By the way, what's the use of `haskell-interactive-bring` instead of `haskell-interactive-switch`? The only difference I can see is that -bring switches to the interactive buffer if and only if it's not visible; I find that a bit inconsistent.)

**Comment by gracjan** [comment]
Interesting, I use Aquamacs, that might be the reason.

No idea about -bring and -switch. Is it sensibly fixable?

**Comment by unhammer** [comment]
gracjan <notifications@github.com> writes:

> No idea about -bring and -switch. Is it sensibly fixable?

I would do 

    (defalias #'haskell-interactive-bring #'haskell-interactive-switch)

but perhaps there are people who prefer the -bring behaviour.

**Comment by PinkMushroom** [comment]
@unhammer interesting if i use C-h v haskell-mode-hook RET i do NOT get the full documentation.

**Comment by unhammer** [comment]
what do you get?

**Comment by geraldus** [comment]
This is what I see:
> haskell-mode-hook is a variable defined in `haskell-mode.el'.
> Its value is
> (structured-haskell-mode hindent-mode interactive-haskell-mode turn-on-font-lock)
> 
> 
>   This variable may be risky if used as a file-local variable.
> 
> Documentation:
> Hook run after entering Haskell mode.
> No problems result if this variable is not bound.
> `add-hook' automatically binds it.  (This is true for all hook variables.)
> 
> [back]

**Comment by unhammer** [comment]
Oh maybe I was doing h f haskell-mode instead of haskell-mode-hook, because when I try again now I get what @geraldus gets. Anyway, perhaps the docs for C-c C-l should point at `C-h f haskell-mode'

**Comment by gracjan** [comment]
True, docs should point to `haskell-mode` as a hub for all documentation
and links to specifics.

Can you create a pull request?

BTW: C-c C-l suggestion could fit on one line. That would be MUCH better!

**Comment by geraldus** [comment]
@gracjan is it still relevant?

**Comment by gracjan** [comment]
Yes. It is still strange to find out how to enable haskell-interaction-mode
and it is a stumbling block for many.

**Comment by wwat** [comment]
How did you manage to fuck up a piece of software which did work 5+ years ago to the point that I am now also seeing this message?

**Comment by geraldus** [comment]
@wwat I think if you wish you can use 5+ years old release in this case.
https://github.com/haskell/haskell-mode/releases/tag/2_8_0

**Comment by mukeshtiwari** [comment]
I am using prelude [1]  and when I am trying to open a file and run it (C-c C-l), it throws me couple of question.
Start a new project named "haskell" ? (y or n) (I press y)
Then it asks for cabal directory ( /home/mukeshtiwari/.cabal/bin) and it ask set current director and finally it displays the message "no such file or directory, ghci" 
I have already installed the ghci and cabal, running M-x eshell 
Welcome to the Emacs shell

~/Programming/code/haskell $ echo $PATH
/home/mukeshtiwari/.cabal/bin:/home/mukeshtiwari/Programming/haskell/bin:/home/mukeshtiwari/.opam/4.02.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
~/Programming/code/haskell $ ghci
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
Prelude> 1+2
Could some one please tell me how to configure this. 

[1]  https://github.com/bbatsov/prelude

**Comment by gracjan** [comment]
This is no longer an issue.
