### ISSUE TITLE
Indentation wrong after destructured tuple with underscore

### ISSUE THREAD

**Issue by rietmann** [haskell/haskell-mode#526]
I'm having indentation problems with haskell-indentation-mode `(turn-on-haskell-indentation)`. The following code does not seem to indent correctly:

    let (a_b) = 1
                |

(Note: Vertical bar/pipe is where cursor is and will not move if I `<tab>` or `<delete>`)
If I remove the parenthesis, it works. If I remove the `_` it also works. It's really quite frustrating as I like to use underscore for variables and camelCase for functions. I just update via melpa (`20150317.204 installed`)

**Comment by gracjan** [comment]
@rietmann: Can you check if you have same problem with code on branch `wip/hi2`? That branch contains improved version of `haskell-indentation`.

**Comment by gracjan** [comment]
Next generation `haskell-indentation` mode has been merged and it is expected that this issue is fixed. Please check if your issue is resolved by that. If it is not please write a comment here or just open new request. Thanks!
