### ISSUE TITLE
`haskell-session-change-target` should list available targets

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#534]
There's already a few functions that deal with finding sections, but none to find *all* sections and return them in a list (e.g. for use with ido).

**Comment by vlatkoB** [comment]
Isn't this already solved?

**Comment by ivan-m** [comment]
Yes, though it's not as nice a representation as the one presented by `ebal` (not to mention that it currently seems to be providing lots of extraneous values such as the description, etc.).

**Comment by vlatkoB** [comment]
`haskell-session-change-target` calls `haskell-cabal-enum-targets` to get the list of targets and displays them in `ido`. `haskell-cabal-enum-targets` returns target names only. As in 
```elisp
("target1" "test")
```
Have I understood you correctly, you want the target list to have descriptions as `ebal`?

**Comment by ivan-m** [comment]
I do like having the `lib:`, `exe:`, etc. prefixes.

And `haskell-cabal-enum-targets` doesn't seem to work very well; for example, the is the result of running it on my [graphviz](https://github.com/ivan-m/graphviz) project:

```
("library provides bindings for the Dot language used by the" "(<http://graphviz.org/>) suite of programs for visualising" ", as well as functions to call those programs." "features of the graphviz library include:" "head" "test-parsing" "{" "graphviz-testsuite {" "graphviz-printparse {" "graphviz-testparsing {")
```

Or [fgl](https://github.com/haskell/fgl):

```
("inductive representation of manipulating graph data structures." "website can be found at <http://web.engr.oregonstate.edu/~erwig/fgl/haskell>." "head" "{" "fgl-tests {")
```

Included in here seems to be portions of the `description` field, and also the `source-repository` labels (not to mention all the `{`).

**Comment by vlatkoB** [comment]
Must say this is the first time I see curly braces in `.cabal`. :-)
I removed the braces, indented `Description:`'s description, and now I got this:

    ("head" "test-parsing" "" "graphviz-testsuite" "graphviz-printparse" "graphviz-testparsing")

Seems `.cabal` parser doesn't honour braces but is indentation dependent.
It also doesn't filter targets only, but I made a PR to correct that.

**Comment by vlatkoB** [comment]
Should somewhere be a note that `haskell-mode` does not support curly braces in `.cabal` file?

**Comment by ivan-m** [comment]
Well, then that behaviour is wrong: it is perfectly acceptable to use braces to denote blocks in `.cabal` files.

**Comment by vlatkoB** [comment]
Looks like `.cabal` parser simply ignores curly braces, which means that enumerating targets works with or without them, so I fixed `haskell-cabal-enum-targets` function.

Indentation inside braces is another thing.
Hope this helps.

**Comment by gracjan** [comment]
Reopening due to curly braces.

**Comment by ivan-m** [comment]
@vlatkoB it seems your patch doesn't work, as if you try and change to the library you get an error of:

```
cabal: Unknown build target 'library'. There is no component 'library' or module 'library'.
```

As a workaround, hitting `C-j` in the ido list seems to work.

**Comment by vlatkoB** [comment]
Yes, I became aware of that when I realized I tested it on a non-library project, but had no time to fix it before.
Please try this on your projects and let me know.

**Comment by gracjan** [comment]
Please create a test that covers this new knowledge.
