### ISSUE TITLE
haskell-process-load stops working after a while

### ISSUE THREAD

**Issue by LukeHoersten** [haskell/haskell-mode#536]
Sporadically when I try to trigger a `haskell-process-load-or-reload` with `(C-c C-l)` it doesn't work and instead just says `(No changes need to be saved)` in the `*Message*` buffer. The `*haskell-process-log*` says nothing. This problem continues until I `haskell-process-reload`. This makes `haskell-flycheck` stop working as well and doesn't seem to have a way to be restarted after the haskell-process is restarted. Ping @chrisdone

**Comment by gracjan** [comment]
Are you using Windows by chance?

ping @chrisdone

**Comment by LukeHoersten** [comment]
This is on OS X.

Also confirmed `(haskell-interactive-mode-clear)` does not fix the issue. Only restart does.

**Comment by LukeHoersten** [comment]
@chrisdone informed me that '(haskell-process-clear)' not '(haskell-interactive-mode-clear)' is the correct command to clear out the process queue and that did indeed fix things. Still, shouldn't be getting jammed in the first place.

**Comment by ivan-m** [comment]
I've had similar issues (but keep forgetting to report a bug for it) when I use a sandbox and on initial load there's an error; in that case I have to kill the buffer and re-create the session.

**Comment by sritchie** [comment]
Same here - I'm on OS X, and every so often (I think prompted by my saves, which trigger hasktags) the haskell process stops processing commands. `(haskell-process-clear)` works.

**Comment by LukeHoersten** [comment]
Looks like a duplicate of #447 - thanks for pointing that out @sritchie.
