### ISSUE TITLE
Commenting a {-# ... #-} pragma

### ISSUE THREAD

**Issue by asr** [haskell/haskell-mode#544]
I'm not sure if this is an Emacs or a haskell-mode issue.

For example, after marking the line

    {-# LANGUAGE CPP #-}

`M-;` incorrectly produces

    # LANGUAGE CPP #

instead of

    -- {-# LANGUAGE CPP #-}

Emacs version: 24.4.1
Haskell-mode version: 20150321.21

**Comment by gracjan** [comment]
Nice catch!

2015-03-22 19:41 GMT+01:00 Andrés Sicard-Ramírez <notifications@github.com>:

**Comment by gracjan** [comment]
I've checked what is going on. I think you hit this part of functionality
of `M-;`:

> If the region is active and `transient-mark-mode' is on, call
`comment-region' (*unless it only consists of comments, in which case it
calls `uncomment-region'*).

Note that {-# ... #-] pragmas are technically comments too. And you seem to
have one marked and it gets converted to non-comment.

**Comment by asr** [comment]
> Note that {-# ... #-] pragmas are technically comments too.

You are right. Should I close the issue?

**Comment by gracjan** [comment]
Close the issue if your problem is clarified or solved.

2015-03-23 2:09 GMT+01:00 Andrés Sicard-Ramírez <notifications@github.com>:
