### ISSUE TITLE
haskell-indentation seems to have problems with underscore

### ISSUE THREAD

**Issue by bmktuwien** [haskell/haskell-mode#547]
I have currently a strange problem with haskell-indentation-mode if one of the function argument identifiers contains the `_` character:
```haskell
foo (Foo _) = []
foo x = go x
```
With the code above, if I press `<tab>`  in the second line, then I get the message `Parse error`.
The problem disappears if I write `(Foo foo)` instead of `(Foo _)`, but this is not a solution for me, since the compiler will generate a warning if I don't use the variable.

I am using the version: `20150323.559`
(Maybe this issue is related to the issue #526)

**Comment by ivan-m** [comment]
For linkification purposes: #526 (putting it in backticks stops GitHubs automagic linkification).

**Comment by bmktuwien** [comment]
@ivan-m Thanks, my bad. I have updated my post...

**Comment by gracjan** [comment]
@bmktuwien: can you check if work on branch wip/hi2 also exposes this problem?

**Comment by bmktuwien** [comment]
@gracjan I have just checked it with `hi2 ver. 20141005`, and the issue is the same...

**Comment by gracjan** [comment]
Can you check if patch in #548 fixes your issue?

**Comment by bmktuwien** [comment]
@gracjan Yes! The patch solves the problem! Thank you so much!

**Comment by gracjan** [comment]
Good to hear!

Note that this patch might have side effects. If you spot anything else
unusual please report back, okay?

**Comment by bmktuwien** [comment]
Ok, will do!

**Comment by gracjan** [comment]
@bmktuwien: are you sure wip/hi2 does not solve the issue as is? On that branch there is this commit 74154cf4ef877f052810116612abdcefcd76e901 that should basically do what you need that is treat underscore as part of identifier.

**Comment by bmktuwien** [comment]
As I mentioned in the post, I've installed the `hi2` package via Melpa package manager version 20141005. I didn't install it directly from the wip/hi2 branch... I will check it again later when I get back home from work.

**Comment by gracjan** [comment]
I see. I would ask you to specifically test out wip/hi2 branch as it has
fixes on top of what is available via hi2 package from melpa.

**Comment by gracjan** [comment]
Next generation `haskell-indentation` mode has been merged and it is expected that this issue is fixed. Please check if your issue is resolved by that. If it is not please write a comment here or just open new request. Thanks!

**Comment by bmktuwien** [comment]
I've just updated haskell-mode via Melpa and so far so good! Everything works! Thx again and good job!
