### ISSUE TITLE
[Discussion] Character class for apostrophe

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#549]
Apostrophe is seriously overloaded character in Haskell. Here it goes:

- `'x'`, `'X'` - a char constant
- `'xf'` - Template Haskell Name for `xf'`
- `''XF'` - Template Haskell Type for `XF'`
- `'\1231'` - a char constant
- `'\SOH'` - a char constant
- `''` - illegal, somewhat char
- '1x' - illegal
- `'''XF` - illegal

So apostrophe is a:
- symbol constituent (`xf'`)
- string quote (`'x'`)
- expression prefix (`'xf` `''XF`)
- illegal

Most of the above can be fixed by `syntax-propertize`. There are two questions though:
- what should be the default syntax class for apostrophe?
- what should be the syntax class for apostrophe in illegal cases?
- should apostrophe that is part of identifiers have syntax class `_` or `w`?

**Comment by ivan-m** [comment]
Don't forget also that `x'f` is also a valid variable/function name (so `'` isn't just a symbol constituent at the end).

**Comment by gracjan** [comment]
Proposition is:
- default for apostrophe is punctuation
- illegal apostrophe is punctuation
- apostrophe in identifiers is same class as underscore, that is 'w'

**Comment by gracjan** [comment]
Some more testing:

    Prelude> (,) 'x''y'
    ('x','y')
    Prelude> (,) 12'y'
    (12,'y')
    Prelude> (,) 0x12'y'
    (18,'y')
    Prelude> (,) x12'y'
    <interactive>:6:5: Not in scope: ‘x12'y'’
    Prelude> (,) 'x''y''
    <interactive>:7:12:
        lexical error in string/character literal at end of input
    Prelude> let y = 45
    Prelude> (,) 'x'y
    ('x',45)
    Prelude> (,) 'x''y
    ('x',y_1627393257)
    Prelude> (,) "x"'y'
    ("x",'y')
    Prelude> (,) 'y'"x"
    ('y',"x")
    Prelude> (,) '"'"'"
    ('"',"'")
    Prelude> (,) 12e-34'r'
    (1.2e-33,'r')
    Prelude> (,) 12.34'r'
    (12.34,'r')

**Comment by gracjan** [comment]
And apostrophe for DataKinds and TemplateHaskell is prefix operator class.

**Comment by gracjan** [comment]
This is more or less fixed in the new `syntax-propertize0-function`.
