### ISSUE TITLE
Indentation doesn't work correctly if a multiline string is present

### ISSUE THREAD

**Issue by bmktuwien** [haskell/haskell-mode#556]
First I am using the newest version 20150327.

It seems currently that the haskell-indentation mode doesn't work correctly if a multine string is present.
For example:
```
foobar = "foo \
         \bar"
          barfoo = "barfoo"
```

The line with `barfoo` just won't indent correctly when I cycle through indentations pressing `<Tab>` repeatedly. Is this a known issue and is there a known workaround?

**Comment by gracjan** [comment]
Issue is know and noted in #324. Fix should not be that hard but not easy either.

You may look inside `haskell-indentation-skip-token` and do something about this part `(looking-at "\"\\([^\\\"]\\|\\\\.\\)*\"")`.

i'm closing as duplicate.
