### ISSUE TITLE
Reverse of haskell-mode-jump-to-def-or-tag?

### ISSUE THREAD

**Issue by sritchie** [haskell/haskell-mode#563]
Is there some way to come back to one's starting point after jumping to a tag? If the function's defined in a different buffer I can just kill the new window, but if I jump to a function defined in the same file it's pretty tough to get back.

Thanks!

**Comment by gracjan** [comment]
There is `(pop-tag-mark)` bound for me as `Alt-*`.

**Comment by sritchie** [comment]
Nice, thanks!

**Comment by Yuhta** [comment]
`(pop-tag-mark)` has a bug in haskell-mode when the tag is in a different file, it does not jump back to the first file.
