### ISSUE TITLE
"File mode specification error: (void-function haskell-indentation)"

### ISSUE THREAD

**Issue by joehillen** [haskell/haskell-mode#569]
I saw the announcement for the March release about the new indentation and I wanted to try it out: https://github.com/haskell/haskell-mode/wiki/Month-in-haskell-mode-March-2015

On the announcement it says to try it out add:
```
(add-hook 'haskell-mode-hook 'haskell-indentation)
```

If I do that, I get the above error. However, this works (found in the guide):
```
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
```

Is this a bug in the announcement?

**Comment by gracjan** [comment]
Proper is:

    (add-hook 'haskell-mode-hook 'haskell-indentation)

thanks for noticing!

**Comment by joehillen** [comment]
@gracjan I'm confused. `'haskell-indentation` gives me the error; `'turn-on-haskell-indentation` does not.

**Comment by gracjan** [comment]
I can't spell at this hour. Proper is with -mode at the end:

    (add-hook 'haskell-mode-hook 'haskell-indentation-mode)

**Comment by joehillen** [comment]
Got it. Thanks!
