### ISSUE TITLE
fill-paragraph does not fill first line with Haddock marked-up comments

### ISSUE THREAD

**Issue by massysett** [haskell/haskell-mode#570]
There is a problem with fill-paragraph; it does not work with some comments with Haddock markup, especially if you are running fill-paragraph with point in the first line of the comment.  This is fully described in the Haskell source file at

https://gist.github.com/massysett/ac42073f92f098b55dfe

I verified this by running emacs as `emacs -Q -L . -l haskell-mode-autoloads.el`.

**Comment by gracjan** [comment]
Confirmed. Thanks for report!

@massysett: Are you able to create a (failing) test case? We have a testsuite and a good place is in file `tests/haskell-mode-tests.el`.
