### ISSUE TITLE
Presentation mode configuration does not make any changes

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#574]
If I set `haskell-process-use-presentation-mode` to `t` this make no difference if it is set to `nil`. E.g. no matter what value is used, when I run `haskell-mode-show-type-at` it shows me colourful type information in echo area, and also prints to __* Messages *__ buffer.

I'm not sure what **Presentation mode** actually is, but I expected that Emacs will create some kind of popup instead of echoing type information when mentioned variable is set to `t`. Currently I have `haskell-doc-mode` enabled, which almost instantly replaces nice colourful type information from interactive haskell mode with plain colourless text; I hoped that presentation mode will help with this.

**Comment by gracjan** [comment]
@chrisdone: Chris, can you comment on this issue?

**Comment by chrisdone** [comment]
Presentation mode currently just applies to `haskell-process-do-info` (i.e. `C-c C-i`). I don't think doc-mode interacts well with `C-c C-t` presently.

**Comment by geraldus** [comment]
Oh, well, now I see what presentation mode is. I've opened it because description of this var states:
> Use presentation mode to show things like type info instead of printing to the message area.

Thanks for clarification, I will wait for updates.

**Comment by geraldus** [comment]
I can't promise anything for sure, I'll take a look of how `haskell-process-do-info` written and maybe try to make `haskell-mode-show-type-at` become aware of presentation mode too.

**Comment by chrisdone** [comment]
If so make it optional; I originally had types using presentation mode, but in the end I found it too heavy-weight to just see the type.
