### ISSUE TITLE
Font lock for bind operator

### ISSUE THREAD

**Issue by hmgibson23** [haskell/haskell-mode#581]
Would be nice to avoid the >= of >>=  being turned into &#x2265; so you get >&#x2265;

**Comment by ivan-m** [comment]
I assume you're using some kind of prettyfication mode for this?

**Comment by hmgibson23** [comment]
Yes exactly. In emacs24 prettify-symbols-mode is enable by default.

**Comment by gracjan** [comment]
There you go!

Thanks for the report.

**Comment by ivan-m** [comment]
I have Emacs 24.4.1 and don't seem to have prettify-symbols-mode enabled...

**Comment by hmgibson23** [comment]
I'm rocking 24.4 (9.0) and it's on by default. 

As an addition Arrow operator ```&&&``` will also be affected by this. 

Thanks for the fix!
