### ISSUE TITLE
haskell-mode doesn't work when which-function-mode enabled

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#584]
After a recent update `haskell-mode` has lost its ability to function. When I open any Haskell file, I see message "scanning declarations in filename.hs (27%)" or something like this in the minibuffer. Emacs hangs, it's clear that gets in some kind of infinite loop (according to processor usage statistic).

My investigation has shown that it happens only when `which-function-mode` is enabled. To reproduce: `emacs -Q`, then `(package-initialize)` to initialize `haskell-mode`, then `(which-function-mode 1)` to enable `which-function`, then open any `*.hs` file.

Note that I'm using Emacs 25.0.50.1. As far as I know `which-function` is built-in functionality that should work OK. So, I guess the problem is in `haskell-mode`.

**Comment by gracjan** [comment]
I've reverted in e5afe82. Still, there must be some twisted logic going on if that commit broke scanning.

**Comment by mrkkrp** [comment]
@gracjan, thank you. Now that problem has gone.

**Comment by mrkkrp** [comment]
@gracjan, please note that last commit fixed indentation too (it was really strange, but that was a minor problem).
