### ISSUE TITLE
Declarations scanning gets stalled

### ISSUE THREAD

**Issue by k0ral** [haskell/haskell-mode#585]
The issue was noticed under OS-X and linux, at least.
When opening a haskell file, emacs freezes on the `Scanning declarations in file.hs` phase.
Reverting PR #580 fixes the issue.

Thank you !

**Comment by deviant-logic** [comment]
If I read the docs right, `looking-at-p` differs from `looking-at` in that it doesn't mutate the match data.  Presumably, some of the uses of `looking-at` in the declaration scanning code actually depended on the side-effect?

**Comment by gracjan** [comment]
I've reverted in e5afe82bc878183397a49ab150244bf4391c20c0. Still, there must be some twisted logic going on if that commit broke scanning.
