### ISSUE TITLE
Prettify symbol troubles with dot operator

### ISSUE THREAD

**Issue by hmgibson23** [haskell/haskell-mode#589]
Great fix for the issues with ```>>=```. Thanks for the super fast response. The fix however has unfortunately introduced another bug. Now in imports ```.``` is transformed into &#8728; so you get the fairly unpleasant import Data&#8728;ByteString&#8728;Char8 instead of ```Data.ByteString.Char8```.

Sorry I feel like the scrooge of prettify-symbols-mode!

**Comment by gracjan** [comment]
@hmgibson23: If you look through the code you will see that "." requires special handling.

Are you able to look at this yourself and create a pull request?

**Comment by hmgibson23** [comment]
Yes will have a look

**Comment by gracjan** [comment]
@hmgibson23: should be pretty easy: just check if a dot has space before and space after.

**Comment by hmgibson23** [comment]
Yeah good call.

**Comment by ivan-m** [comment]
@gracjan it can't just be a matter of requiring a space before/after: that means that `(.)` wouldn't be pretty-fied.

Then again, how do you tell if `Foo.Bar` is subsequently applying two constructors or just applying one qualified constructor?

**Comment by gracjan** [comment]
See here:

https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-180002.4

specifically this table:

This 	Lexes as this

    f.g 	f . g (three tokens)
    F.g 	F.g (qualified ‘g’)
    f.. 	f .. (two tokens)
    F.. 	F.. (qualified ‘.’)
    F. 		F . (two tokens)

**Comment by hmgibson23** [comment]
I'm not that familiar with Elisp, so would something like 

```
    (or (re-search-backward "\\<forall\\>[^.\"]*\\="
                            (line-beginning-position) t)
        (re-search-backward "[^ ]\.[^ ]"
                            (line-beginning-position) t))))
```

work?

Which makes me think the ```forall``` regex is actually redundant.

**Comment by gracjan** [comment]
Close, but no cigar. I guess using `char-before` and `char-after` would be better idea. You can read about those here:

http://www.gnu.org/software/emacs/manual/html_node/elisp/Near-Point.html
