### ISSUE TITLE
Haskell-mode crashing and buffer erased (not sure exactly where problem is)

### ISSUE THREAD

**Issue by rietmann** [haskell/haskell-mode#594]
In the last days, I've had some very strange behavior when working on my latest haskell project. I'm editing along normally, I *think* I hit save, or maybe switch buffers and suddenly the buffer I was editing is blank and has been saved to disk! (no text at all, 0 bytes in filesystem). Additionally it seems that haskell-mode has crashed (it doesn't show in status bar). It's only happened twice, and I can never quite remember which keys I just hit; I was just in the flow, if you know what I mean. I don't know if there is a log of keystrokes or commands in emacs.

I'm running Haskell-mode, with stylish-haskell, Helm, and company mode, mostly installed via the Prelude emacs setup, with a few vanilla customizations, and flycheck.

Luckily I'm running Dropbox, so when it happens I can quickly go to their web interface and get the version just before the file is wiped out.

Now, I'm mostly looking for help to debug the issue. I'm reasonably proficient with Emacs, but I'm at a total loss here.

I'm running the newest stable emacs (24.5.1) and haskell-mode version 13.12 (elpa/haskell-mode-20150420.2132). Stylish-haskell (stylish-haskell-0.5.11.0).

My only idea is that somehow something goes wrong in the stylish-haskell update, that it crashes while updating the text?

How can I debug this, or what might be the problem? It's a little scary because sometimes Dropbox crashes on my Linux machine and could lose quite a bit of work.

**Comment by geraldus** [comment]
@rietmann, you can hit `C-h l` to see last 300 input keystrokes.

**Comment by rietmann** [comment]
@geraldus Thanks for the tip. If it happens again, I'll make sure to try that and post back.

**Comment by gracjan** [comment]
Reopen if you have experienced this issue again. Thanks.
