### ISSUE TITLE
Incompatibility with htmlize 1.47

### ISSUE THREAD

**Issue by pyr** [haskell/haskell-mode#596]
Hi there!

`htmlize` (at version 1.47) recently stopped working with haskell. This is because of extra quoting when defining faces I had to change the lines:

```elisp
(defface haskell-keyword-face
  '((t :inherit 'font-lock-keyword-face))
  "Face used to highlight Haskell keywords."
  :group 'haskell)
```

And remove the extraneous quoting:

```elisp
(defface haskell-keyword-face
  '((t :inherit font-lock-keyword-face))
  "Face used to highlight Haskell keywords."
  :group 'haskell)
```

The same goes for every face declaration (https://github.com/haskell/haskell-mode/blob/master/haskell-font-lock.el#L91-L131). If this change does not introduce problems with earlier emacs/htmlize builds, I can provide a PR to fix this.

**Comment by gracjan** [comment]
For those oblivious what htmlize is: http://fly.srk.fer.hr/~hniksic/emacs/htmlize.el.cgi

@pyr: Note that font-lock documentation states:

> Note that in new code, in the vast majority of cases there is no need to
> create variables that specify face names.  Simply using faces directly
> is enough.  Font-lock is not a template to be followed in this area.

That is why it got changed.

@pyr, please provide PR, we will check and see what to do with this.

**Comment by pyr** [comment]
Hi @gracjan thanks for the comments. I attached a PR with the fix that resolve the situation for now.
Using standard face names seems like a really good idea for the future indeed.
