### ISSUE TITLE
Debugger triggered on "match c of", a typo for "case c of"

### ISSUE THREAD

**Issue by mcandre** [haskell/haskell-mode#599]
As a Haskell newbie, I want haskell-mode to behave more gracefully when I make a typo, like `match c of` instead of `case c of`. Currently, the debugger triggers on such parse errors.

**Comment by ivan-m** [comment]
Is this for indentation? Or when you load it into ghci?

**Comment by mcandre** [comment]
Indentation, no GHCi used.

**Comment by ivan-m** [comment]
Which indentation mode are you using?  Can you provide the complete error for it?

**Comment by mcandre** [comment]
Here is my .emacs configuration:

https://github.com/mcandre/dotfiles/blob/master/.emacs

**Comment by ivan-m** [comment]
Pinging @gracjan and @kuribas (especially since the new indentation mode was merged in recently).

@mcandre are you installing haskell-mode via package.el or a distro package? Do you know what version it is?

**Comment by mcandre** [comment]
I load haskell-mode via use-package, install haskell-mode via Emacs Cask, source haskell-mode from MELPA, and I'm using the latest version, 20150423.710.

**Comment by ivan-m** [comment]
Yeah, so it is to do with the new version of haskell-indentation (and thus I can't really help you with it :p)

**Comment by mcandre** [comment]
Thanks for the tip.

In some programming languages, package metadata can specify an upper limit on dependencies and sandbox them so that your package is guaranteed to use a safe version. Is this possible with Emacs packages?

**Comment by gracjan** [comment]
@mcandre: `haskell-indentation` uses usual elisp `throw`/`catch` mechanism to do deep unwinding. This is normal, what is not normal is that it should not trigger debugger, even if `(debug-on-error t)` is set.

Since you are the kind of person that has `(debug-on-error t)` you seem to have skill and knowledge to find out why catch/throw is triggering debugger. It should not.

Also note that MELPA comes in two variants, melpa and melpa-stable. The second one is supposed to be less bleeding edge than the first one. Instructions for both are in our https://github.com/haskell/haskell-mode/blob/master/README.md file.

**Comment by gracjan** [comment]
Here is the place:

https://github.com/haskell/haskell-mode/blob/master/haskell-indentation.el#L561

**Comment by kuribas** [comment]
hm, this is the same bug as in #483  I have a fix in my own haskell-indentation.el, but it is quite
out of sync with master.  I should have a fix when I can get myself out the github mess...

**Comment by gracjan** [comment]
Which repo?

I see nothing here: https://github.com/kuribas/haskell-mode
And nothing here: https://github.com/kuribas/hi2

@kuribas, I tried to send you an email but no result. Which inbox do you
respond to?

**Comment by kuribas** [comment]
In my local repo, sorry...  You can send mail to my resonata inbox.

**Comment by gracjan** [comment]
I've tried resonata, can you look into your INBOX there?

**Comment by kuribas** [comment]
I got only a github message...

**Comment by gracjan** [comment]
I've used this:

http://www.resonata.be/contact

so `info` at the address. Is this wrong? Is this correct?

**Comment by kuribas** [comment]
hm, that may be broken... try kristof at resonata.be

**Comment by gracjan** [comment]
Check INBOX now.

**Comment by mcandre** [comment]
@kuribas A fix you say? Please merge :)

I'm actually new to Emacs Lisp; The only reason I turned on debug-on-error is to produce better bug reports, lol!

**Comment by gracjan** [comment]
Haha, well, we need to built some mechanism for bug reporting tailored for
haskell-mode. debug-on-error sure isn't one of those :)

**Comment by gracjan** [comment]
Thinking about this more I come to reason that haskell indentation should have a much more permissive parser. It should care only about `of` being a keyword, `case` can be treated as ordinary identifier, so it will not bail out when it see `match`. It won't care.

**Comment by gracjan** [comment]
This is no longer bailing out with parse error.
