### ISSUE TITLE
Internalize haskell-decl-scan-mode

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#623]
`haskell-decl-scan-mode` consist of:
- recognizing top level declaration
- navigation via `C-M-a`, `C-M-e` and marking `C-M-h`
- `which-func-mode` relies on this
- `imenu` is populated by it

Note that `which-func-mode` relies on `haskell-decl-scan-mode` even if the mode is not enabled. `font-lock` also recognizes top-level declarations, sadly it has its own ideas how to find those.

`haskell-decl-scan-mode` should just become part of default `haskell-mode`. Decl scan should be officially enabled always (not sneakily as it is now). `imenu` integration should be official, enabled when `imenu` is enabled. `font-lock` should use same mechanisms to find top-level declarations so that those two agree.

**Comment by bergey** [comment]
We should remember to update [the manual](http://haskell.github.io/haskell-mode/manual/latest/Declaration-scanning.html#Declaration-scanning) when this happens.

**Comment by gracjan** [comment]
Related #1122.

**Comment by gracjan** [comment]
I do not think we can move here due to lack of semantic parser.
