### ISSUE TITLE
Remove all mentions of Marmelade

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#626]
Marmelade is as good as dead now, see here: https://github.com/nicferrier/elmarmalade/issues/92.

Remove all mentions of Marmelade from:

- [x] README.md
- [x] Makefile (package generation part)
- [x] [haskell-mode/wiki](https://github.com/haskell/haskell-mode/wiki)

Find out also about haskell-mode on marmelade mentions in external wikis or tutorials, contact respective authors, tell them to update.

**Comment by jhenahan** [comment]
Non-historical references to Marmalade have been purged from the wiki.

**Comment by gracjan** [comment]
@jhenahan: Great! Thanks!

Can you also prepare a pull request that removes Marmelade from README and Makefile?

**Comment by jhenahan** [comment]
Done, with #627.
