### ISSUE TITLE
Make haskell process' log always scroll to bottom

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#633]
I opened this as reminder for future work and also to discuss issue subject. Usually I use log to see compilation progress, and it annoys me because I always have to scroll it manually. There are some rare cases when log is scrolled to bottom automatically.
So the plan is to find all print to log relating stuff and add scrolling to bottom action after that. Maybe we should have a special function for that? This will make possible to have some customisation like `Scroll Log To Bottom` in case if user do not want log to autoscroll.

**Comment by gracjan** [comment]
Please use the trick from Microsoft VisualStudio output buffer:

1. If the `point` is at the end of the buffer, then append and move the point to the end of the buffer again (effectively inserting before). Otherwise just append.
2. If the window scroll position is at the end, then scroll to the new end after inserting, otherwise do not scroll.

No settings needed.

**Comment by gracjan** [comment]
Check out `auto-revert-tail-mode`:

http://www.gnu.org/software/emacs/manual/html_node/emacs/Reverting.html

**Comment by geraldus** [comment]
> Check out auto-revert-tail-mode

Auto-revert works only for file based buffers.

> 1. If the point is at the end of the buffer, then append and move the point to the end of the buffer again (effectively inserting before). Otherwise just append.
> 2. If the window scroll position is at the end, then scroll to the new end after inserting, otherwise do not scroll.

So

    remember does scroll is at end
    effective append
    scroll according to remembered val

Right?

I hope that `haskell-process-log` is the only one way used to log stuff. I can update it. Also I think that we should have an option to truncate log to some fixed number of lines (like `eshell` does via custom var).
