### ISSUE TITLE
Interactive mode recognizes some lines as compiler errors incorrectly

### ISSUE THREAD

**Issue by ikirill** [haskell/haskell-mode#635]
In this error message, `haskell-interactive-next-error-function` incorrectly picks up the line 

         program :: IO () ....

 as a "FILE:LINE:COL-COL: ", and then fails to find the corresponding file, causing it to fail when the filename ends up being nil.

Here's an example:

    src/EnvelopesGLFW.hs:144:3-18: Couldn't match expected type ‘Program’ with actual type ‘IO ()’ …
        In the pattern: program :: IO ()
        In a stmt of a 'do' block:
          program :: IO () <- makeProgram (ProgramSpec {..})
        In the expression:
          do { program :: IO () <- makeProgram (ProgramSpec {..});
               vao :: VertexArrayObject <- genObjectName;
               programCoords <- uniformCoords program "coords";
               bufPos <- setupBuffer vao ArrayBuffer
                         $ do { locPos <- attribLocation' program "position" FloatVec2;
                                vertexAttribArray locPos $= Enabled;
                                .... };
               .... }

**Comment by gracjan** [comment]
For reference `haskell-flycheck` uses this specification:

```el
  :error-patterns
  ((warning line-start (file-name) ":" line ":" column ":"
            (or " " "\n    ") "Warning:" (optional "\n")
            (message
             (one-or-more " ") (one-or-more not-newline)
             (zero-or-more "\n"
                           (one-or-more " ")
                           (one-or-more not-newline)))
            line-end)
   (error line-start (file-name) ":" line ":" column ":"
          (or (message (one-or-more not-newline))
              (and "\n"
                   (message
                    (one-or-more " ") (one-or-more not-newline)
                    (zero-or-more "\n"
                                  (one-or-more " ")
                                  (one-or-more not-newline)))))
          line-end))
 ```

Here: https://github.com/flycheck/flycheck/blob/master/flycheck.el#L6237
