### ISSUE TITLE
Why is the syntax of "." punctuation?

### ISSUE THREAD

**Issue by ikirill** [haskell/haskell-mode#639]
"." is a valid constituent of qualified identifiers, e.g., `Data.List.map`, so shouldn't it have symbol-constituent syntax?

This has the side effect that `(thing-at-point 'symbol)` (which is emacs-standard) doesn't quite work correctly: when placed on a qualified identifier, it selects only the unqualified identifier or a part of the module name (e.g., `map` or `Data` or `List`).

Is this intentional, or a bug?

**Comment by gracjan** [comment]
"." has many functions in Haskell. Example:

    forall a . a -> a
    f . g
    Data.List.map
    Control.Category..  (note two dots at the end)

It is best to treat "." default as punctuation.
