### ISSUE TITLE
Better doc strings in `haskell-commands.el`

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#642]
`haskell-process-restart` and `haskell-process-start` both refer to **inferior** process, however this functions also used to re/start interactive-mode process. I think we should generalise doc strings somehow because this is a bit confusing:
https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L36-L37
https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L43-L44
Update: this could be related https://github.com/haskell/haskell-mode/blob/master/haskell-process.el#L82

`haskell-process-hayoo-ident` doc string looks obsolete:
https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L168-L169

Here is some updates already done https://github.com/geraldus/haskell-mode/commit/f216375dbd74731db2879405408d109dbdf088e9

**Comment by geraldus** [comment]
@gracjan please review https://github.com/geraldus/haskell-mode/compare/master...geraldus:better-doc-strings-haskell-commands

There are 3 warnings left, and I have no strong opinion about them, I marked issues with `FIXME`s.

**Comment by gracjan** [comment]
I do not seem to be able to comment inline until you create a pull request.

In case of arguments where I do not know to wrtie I usually refer to function that can produce such an argument. For example where you describe SESSION you can refer to `haskell-session-make`. And that is good enough.

**Comment by geraldus** [comment]
Ok, I'll close it, here is a PR https://github.com/haskell/haskell-mode/pull/644. Let's move discussion there.
