### ISSUE TITLE
Move recently introduced `hs-utils/…` functions into haskell-utils.el

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#643]
It turns that there is a module for utility functions already, so we can move `hs-utils/…` functions (which was introduced by me recently) there. We can change their prefix according to other two functions in that module `hs-utils/` ➞ `haskell-utils-`, or vice versa.

**Comment by gracjan** [comment]
I vote for `haskell-utils-`. I forgot about this module. Nice catch!

**Comment by geraldus** [comment]
Hmm… If I move this stuff to `haskell-utils` I need to import these functions: `haskell-spanable-pos-at-point`, `haskell-ident-pos-at-point`, `haskell-process-session`, `haskell-interactive-process`, `haskell-present`. So it will bring circular imports. Let's just rename mine functions and leave them in place?

**Comment by gracjan** [comment]
OK.

**Comment by geraldus** [comment]
https://github.com/haskell/haskell-mode/pull/646
