### ISSUE TITLE
haskell-font-lock-symbols: Two dots display as two function compositions symbols

### ISSUE THREAD

**Issue by mhwombat** [haskell/haskell-mode#645]
I'm using `haskell-font-lock-symbols`. If I type:

    import Somepkg (Something(..))

the dots (`..`) are converted to the function composition symbol:

    import Somepkg (Something(°°))

This didn't happen in earlier versions (I recently upgraded my copy of haskell-mode). I was using a different font (solarized theme) before, and now I'm using the default theme... but I don't see why that would make a difference.

**Comment by mhwombat** [comment]
Also, >>= is displayed as >≥

**Comment by gracjan** [comment]
@mhwombat: thanks for the report.

This one seems to be a duplicate of #589 and fixed in #591.

Is github version of haskell-mode working for you correctly?

**Comment by mhwombat** [comment]
I installed the github version of haskell-mode, and it is working fine.
