### ISSUE TITLE
haskell-doc-mode is not asynchronous wrt ghci process, unlike eldoc-mode

### ISSUE THREAD

**Issue by ikirill** [haskell/haskell-mode#649]
haskell-mode's support for eldoc-mode is asynchronous, so placing point on top of an expression while a ghci computation is already running does not hang emacs. On the contrary, haskell-doc-mode runs the `:type` command synchronously, possibly hanging emacs when point is moved until the corresponding ghci command is executed.

https://github.com/haskell/haskell-mode/blob/master/haskell-doc.el#L1570

https://github.com/haskell/haskell-mode/blob/master/haskell-doc.el#L1517

**Comment by gracjan** [comment]
Good catch. There were recent changes that solved similar issue in #607.

**Comment by ikirill** [comment]
One thing about it is that haskell-doc-mode is quite old, IIUC, and seems to be duplicating what the standard eldoc-mode is doing anyway. Since eldoc-mode is included with emacs, would it be reasonable to deprecate haskell-doc-mode and move to only using eldoc-mode? In my configuration I turned it off when it started giving me this problem.

**Comment by gracjan** [comment]
@ikirill: Can you research this topic?

If there is a standard way to provide a functionality then it is usually better to use it. On the other hand we would like to avoid upsetting our users by breaking something they liked.

**Comment by gracjan** [comment]
We will not be fixing `haskell-doc-mode`, we will work on `eldoc-mode` support instead.
