### ISSUE TITLE
haskell-mode-jump-to-def-or-tag<f> Requires a running session

### ISSUE THREAD

**Issue by bezirg** [haskell/haskell-mode#650]
This is just a Feature Request. Can we make this interactive function to fallback on TAGS when there is no session running?

Right now when I run this command, the minibuffer output is:

> haskell-interactive-session: No session associated with this buffer. Try M-x haskell-session-change or report this as a bug.

**Comment by gracjan** [comment]
Resonable request.

@bezirg: Are you able to create a pull request fixing this issue?

**Comment by gracjan** [comment]
Closing in favor of #1180, there is more information there.
