### ISSUE TITLE
stylish-haskell integration no longer reports errors

### ISSUE THREAD

**Issue by MichaelXavier** [haskell/haskell-mode#651]
Often in haskell development, the buffer I'm working on will be invalid for stylish haskell: missing MultiParamTypeClasses, syntax error, etc. If I recall, stylish-haskell used to drop the error it was getting into the minbuffer. Recently, is just says: "Error: stylish-haskell ended with errors, leaving buffer alone". In order to fix the error, I have to leave my editor and manually run `stylish-haskell file.hs | head` to get the error. Seems like the formatter should capture the stderr of the process and leave it somewhere.

**Comment by gracjan** [comment]
This change was motivated by #557 and done in #557.

As we do not know if buffer is or is not valid Haskell it is an expected condition that stylish-haskell fails. if you wish it reported then we need to find a better way of handling the error.

@MichaelXavier: do you have a more concrete proposal?

**Comment by LukeHoersten** [comment]
I would recommend using something like flycheck-haskell to check for errors on the fly since it is purpose built for that. Stylish-haskell is only reporting why it couldn't format your code and isn't intended for on-the-fly debugging like flycheck is.

**Comment by MichaelXavier** [comment]
@LukeHoersten I'm not really trying to use stylish-haskell for debugging. There are cases if I recall  where the program will compile but stylish-haskell will refuse to parse it (I think to do with missing extensions like MultiParamTypeClasses). Sometimes you're concerned with formatting independently of errors in the code.

@gracjan Thanks for the heads up. That works for me! One thing I'd recommend though is maybe to recommend setting `warning-minimum-log-level` to debug rather than `warning-minimum-level`. That seems like it would satisfy more people because it won't pop up in your face but it won't suppress the actionable information from your warnings buffer either.
