### ISSUE TITLE
Can't compile unicode symbols

### ISSUE THREAD

**Issue by 4lex1v** [haskell/haskell-mode#652]
When i type something with haskell-mode, it replaces std symbols with prettier unicode alternatives, e.g:

`function :: Ord c => c -> (c, c)`
with
`function :: Ord c ⇒ c → (c, c)`

But when i hit `haskell-process-cabal-build` i throws me these errors:

```
Not in scope: type constructor or class ‘⇒’
Not in scope: type constructor or class ‘→’
```

I've added an extension to .cabal file : `extensions: UnicodeSyntax`, but it didn't help. I like unicode symbols, but can't compile files.

**Comment by gracjan** [comment]
Hi @4lex1v,

Try the following: Add this line at the top of Haskell source file:

    {-# LANGUAGE UnicodeSyntax #-}

and report back. Also can you upload your source file somewhere, for example http://lpaste.net/ is a good place for Haskell code.

**Comment by geraldus** [comment]
> extensions: UnicodeSyntax
should it be `default extensions:`?

**Comment by 4lex1v** [comment]
@geraldus Thank you, correct, it should be `default-extensions` and it should be placed under the `library ` section.
