### ISSUE TITLE
Turn-on-haskell-indentation hook won't enable haskell-indentation

### ISSUE THREAD

**Issue by dredozubov** [haskell/haskell-mode#654]
After recent updates(at least i think it's related to them) i experience following error when emacs tries to indent a haskell source:

```
You tried to do an indentation command, but an indentation mode has not been enabled yet.

Run M-x describe-variable haskell-mode-hook for a list of such modes.
```

Inspecting `haskell-mode-hook` shows:
```
haskell-mode-hook is a variable defined in `haskell-mode.el'.
Its value is
(company-mode haskell-auto-insert-module-template flymake-hlint-load
              (lambda nil
                (ghc-init))
              interactive-haskell-mode turn-on-haskell-indentation)


  This variable may be risky if used as a file-local variable.

Documentation:
Hook run after entering Haskell mode.
No problems result if this variable is not bound.
`add-hook' automatically binds it.  (This is true for all hook variables.)
```

I have a `(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)` line in my `~/.emacs` and it worked until recently. Running `M-x haskell-indentation-mode` manually helps with this issue(and then it repeats with other buffers).

**Comment by geraldus** [comment]
I'm faced same issue, but I thought it was my fault.

**Comment by geraldus** [comment]
I'm not sure is this related to issue subject,  but in past when interactive-mode always asked me to start a new session or select existing one when I open haskell source file from new location (i.e. project). And now if I open `.hs` file interactive-mode will be activated silently, and will ask nothing.

**Comment by dredozubov** [comment]
@gracjan thanks for clarification on the matter.

It should be enabled as `(add-hook 'haskell-mode-hook 'haskell-indentation-mode)`, not `(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)`.

 Docs are not up to date with this and i was thinking of fixing it and opening a PR quickly, but it seems that it is a bigger issue. Isn't `turn-on-` counterparts supposed to go if they're not working anymore? It seems unintentional that these functions do not work automatically as hooks, maybe it should be fixed w/o updating docs?

**Comment by gracjan** [comment]
You are right on both points:

1. Documentation should be updated.
2. Old functions should still work (marked as deprecated).

I'm not sure why they stopped working.

**Comment by geraldus** [comment]
In ny case `turn-on-haskell-indentation` work, but does it silently.

**Comment by geraldus** [comment]
@dredozubov is it still relevant (sorry I've missid Gitter notifications)?

**Comment by biboudis** [comment]
And order matters.
```
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
```

Not the other way around.

**Comment by gracjan** [comment]
Nice catch. Minor modes should not interfere.

Can you debug this so that we know why does it need the order as you
described?

**Comment by biboudis** [comment]
Thx. I will investigate this with my colleague who is a more advanced emacs user than me. I will post findings here /cc @gbalats.
