### ISSUE TITLE
Typed characters do not appear at the cursor.

### ISSUE THREAD

**Issue by mhwombat** [haskell/haskell-mode#658]
I'm using the github version of haskell-mode, as of 10 minutes ago, and I'm seeing weird behaviour where the cursor does not show where characters that I type will appear.

![snapshot](https://cloud.githubusercontent.com/assets/1899200/7725061/14342b8a-feef-11e4-8910-2b852e472b2f.png)

**Comment by gracjan** [comment]
What version of Emacs are you using?

The composition mechanism that is used for unicode prettyfication is quite buggy.
Can you disable `haskell-font-lock-symbols` and restart whole Emacs?

**Comment by mhwombat** [comment]
I'm using: "GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on lamiak, modified by Debian"

I disabled haskell-font-lock-symbols, but the problem persists. 

I suspect the problem is related to those underscores that magically appear on the line containing the cursor. The underscores seem to be a new feature; the version of haskell-mode in melpa doesn't have them. I suspect their purpose is to show the various indentation levels, but I find them kind of distracting. Is there a way to turn them off?

**Comment by gracjan** [comment]
`M-x customize-option RET haskell-indentation-dyn-show-indentations`.

**Comment by mhwombat** [comment]
OK, I turned off the indentation markers (underscores), and the problem went away. Thank you.

**Comment by geraldus** [comment]
@gracjan I think we need a patch for this (:

**Comment by gracjan** [comment]
I think we need a lot of patches for haskell-indentation.

Artur, can you meanwhile do a patch that turns this showing off by default?
It is basically debug information for haskell-indentation developers and it
is getting in the way too much (note that it also interferes with full like
marking modes, for example bm.el).

**Comment by geraldus** [comment]
Yep, but I will be able to do it tommorow.

Despite of this is also interferes with `fill-column-indicator` I like this indicators and it's sad that it is not working properly. I also dream about vertical lines indicating indentation (like in FPco web IDE).

**Comment by geraldus** [comment]
@gracjan btw, If I disable `haskell-indentaion-show-indentations-after-eol` it works fine with `fill-column-indicator`, but I think many people will find these overlays distractive. If we disable them by default I think we need to mention about it doc string (and possibly in wiki). I'm a bit short in time currently.

**Comment by geraldus** [comment]
I think this can be closed now.
