### ISSUE TITLE
Syntax highlighting remarks 

### ISSUE THREAD

**Issue by DanielG** [haskell/haskell-mode#659]
Here the `::` is being highlited lilke a constructor. Everywere else it's highlighted as haskell-definition-face:

<img src="http://i.imgur.com/ckpQPQp.png"></img>

Here additionally the `,` is  haskell-definition-face even though it's haskell-operator-face everywhere else.

<img src="http://i.imgur.com/18yl8VW.png"></img>

I would also argue that `,` being haskell-operator-face everywhere (including declarations and import lists) is wrong and in `haskell-mode-20150108.346` it didn't used to be. Also `::` being haskell-definition-face also seems weird.

**Comment by gracjan** [comment]
True on both. Thank for the report.
