### ISSUE TITLE
File mode specification error: (wrong-number-of-arguments ...

### ISSUE THREAD

**Issue by sacundim** [haskell/haskell-mode#662]
Fresh MELPA install of version 13.12, when attempting to load a `.hs` file in the same directory that has a `.cabal` file:

    File mode specification error: (wrong-number-of-arguments #[(other-window) "\203$\303\304!!\211\203
    \203\305	!\202\"\306	!\202\"\307\310\")\207\307\311!\207" [buffer-file-name cabal-file other-window haskell-cabal-find-file file-name-directory find-file-other-window find-file error "Could not locate \".cabal\" file for %S" "Cannot locate \".cabal\" file for buffers not visiting any file"] 4 ("/Users/sacundim/.emacs.d/elpa/haskell-mode-13.12/haskell-cabal.elc" . 9453) "P"] 0)

Emacs version:

    GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

Haskell mode configuration:

    (add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
    
    (eval-after-load "haskell-mode"
      '(progn
         (define-key haskell-mode-map (kbd "C-x C-d") nil)
         (define-key haskell-mode-map (kbd "C-c C-z") 'haskell-interactive-switch)
         (define-key haskell-mode-map (kbd "C-c C-l") 'haskell-process-load-file)
         (define-key haskell-mode-map (kbd "C-c C-b") 'haskell-interactive-switch)
         (define-key haskell-mode-map (kbd "C-c C-t") 'haskell-process-do-type)
         (define-key haskell-mode-map (kbd "C-c C-i") 'haskell-process-do-info)
         (define-key haskell-mode-map (kbd "C-c M-.") nil)
         (define-key haskell-mode-map (kbd "C-c C-d") nil)))
    
    (eval-after-load "haskell-mode"
      (define-key haskell-mode-map (kbd "C-c v c") 'haskell-cabal-visit-file))

**Comment by sacundim** [comment]
Removing this bit from the Emacs init file resolves the issue:

    (eval-after-load "haskell-mode"
      (define-key haskell-mode-map (kbd "C-c v c") 'haskell-cabal-visit-file))

But I got those lines from the `haskell-cabal-mode` chapter in the info file that comes with the mode.

**Comment by syohex** [comment]
@sacundim You miss `quote` at  2nd `eval-after-load`.

```lisp
(eval-after-load "haskell-mode"
  '(define-key haskell-mode-map (kbd "C-c v c") 'haskell-cabal-visit-file))
```

**Comment by sacundim** [comment]
@syohex Good catch!  I copypasted the code from the `*info*` buffer, but it turns out that the docs were wrong and were only recently fixed:

https://github.com/haskell/haskell-mode/commit/03d3c7c1b6bfd51de252bbe6b9b439d1c3222bcd

I'm closing this issue.
