### ISSUE TITLE
Use easy-mmode-defmap to define all keymaps

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#669]
`haskell-mode` code mostly predates Emacs 23. Since then (or even earlier) there is `easy-mmode` available and it seems to be standard method to declare keymaps, like this:

    (easy-mmode-defmap xxx-map
      `(("n" . xxx-next)
        ("p" . xxx-prev))
       "The base keymap for `xxx-mode'.")

Use this metod everywhere keymaps are defined.

**Comment by fice-t** [comment]
I don't know, is it the standard? I `zrgrep`'d `/usr/share/emacs/24.5/lisp/` and got 47 results for `let ((map (make-keymap)))` and 17 results for `easy-mmode-defmap`. 3rd party packages seem to use the `let` method as well.

It does look a bit nicer though.

**Comment by gracjan** [comment]
Hmm, I'm not sure at this point. Can you just look at the keymaps and do some cleanup there so that all keymaps are defined in the same way?

**Comment by gracjan** [comment]
Okay, lets just close this as I'm no longer sure this is a good idea.

**Comment by gracjan** [comment]
@fice-t: I've closed this easymenu, wasn't clear if it was a good idea. But there is a good idea to make eldoc-mode subsume haskell-doc-mode: https://github.com/haskell/haskell-mode/issues/1138. Do you think you could take care of it?

**Comment by fice-t** [comment]
Hmm, sorry, I don't think I'll be able to man that. I expect to be busy in the next few months (I put off some stuff I shouldn't have...), so I probably won't have much time for anything bigger.
Maybe if I see something really small myself I might try it, but no requests. :-)
