### ISSUE TITLE
"haskell-mode-enable-process-minor-mode: You tried to do an interaction command, but an interaction mode has not been enabled yet."  error.

### ISSUE THREAD

**Issue by sidhu1f** [haskell/haskell-mode#674]
Error in title occurs with haskell-mode 13.12-3, emacs 24.4.1, debian testing.
Workaround: Downgrading to 13.10-3 eliminates error.

Couple of suggestions re error message second line "Run M-x describe-variable haskell-mode-hook for a list of such modes.":
Reword to "C-h v haskell-mode-hook". Also remove blank line in-between the two error message lines.

**Comment by gracjan** [comment]
Already done in https://github.com/haskell/haskell-mode/commit/27545106.

Thanks for the report btw. That motivates us to release a stable version.
