### ISSUE TITLE
Check if function at point fuses

### ISSUE THREAD

**Issue by codygman** [haskell/haskell-mode#676]
I was thinking maybe there was a way to take advantage of [this](http://www.joachim-breitner.de/blog/649-Does_list_fusion_work_) to make a function that runs the function your cursor is in (assuming it is pure) and checks to see if it fuses.

**Comment by gracjan** [comment]
Thanks for the heads up about this functionality, very cool stuff!

And very specialized at the same time. I could imagine a package called `haskell-mode-extras` where this would fit, in general `haskell-mode` we ar eswamped supporting what is already there.

I have to close this issue as out of scope for `haskell-mode`. Having said that do not hessitate to publish other package that does what you have in mind!

**Comment by codygman** [comment]
Thanks for your hard work on haskell-mode. I understand if it's already too
much to support. I've been trying to figure out elisp and looking through
the source of haskell-mode, so hopefully I'll be able to help and maybe
even create the haskell-mode-extras you've suggested.

**Comment by gracjan** [comment]
Great if you can help! It is actually plenty fun to do! Start with something well defined, like one of the tasks with the 'well-defined-task' label:

https://github.com/haskell/haskell-mode/issues?q=is%3Aopen+is%3Aissue+label%3Awell-defined-task

Step by step instructions how to get going without too much trouble are here:

https://github.com/haskell/haskell-mode/wiki/Contributing

Our current focus is to get as many people hacking on haskell-mode as we can, as you haven't contributed yet you get priority treatment!

(Note that research what the code actually does and documenting it in haskell-mode.texi is also badly needed).
