### ISSUE TITLE
haskell-process-completions-at-point is likely broken for OPTIONS completions

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#679]
I'm still trying to make some improvements on `haskell-process-completions-at-point` function.

I've spent some time trying to figure out how [this part][1] of code works. Finally, I realized that it's likely broken, for example this returns `""` empty string when I place anywhere in following line:

```
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
```

Can someone confirm or refute this?

[1]:https://github.com/haskell/haskell-mode/blob/master/haskell.el#L88-L95

**Comment by gracjan** [comment]
For me this function always returns `nil`...

**Comment by geraldus** [comment]
@gracjan `C-c C-l` first

**Comment by gracjan** [comment]
Oh boy, that is sneaky... `OPTIONS` and `LANGUAGE` should go without `C-c C-l`! Those should work even without ghc being installed!

**Comment by geraldus** [comment]
I agree (: I hope I will improve this, I just need confirmation that this is now work for every one.

**Comment by geraldus** [comment]
Fixed in #733
