### ISSUE TITLE
Issue using type-at in spacemacs

### ISSUE THREAD

**Issue by fatlazycat** [haskell/haskell-mode#689]
Hi, not sure where the issue lies, within spacemacs or haskell-mode hence this issue.

Have raised https://github.com/syl20bnr/spacemacs/issues/1472

It appears something is sending the wrong columns to the type-at command.

Any ideas ? Could you help point me in the direction to debug this ?

Thanks

**Comment by geraldus** [comment]
@fatlazycat can you `M-x toggle-debug-on-error` to enable debugging, then run type-at command and post here debugger output?

**Comment by fatlazycat** [comment]
Would that goto the haskell-process-log ?

Is any different from the output 

    λ> :type-at /Users/graham/Development/GitHub/fatlazycat/NICTA-course/src/Course/ListZipper.hs 240    29 240 31 xs

    *Course.ListZipper| *Course.ListZipper| *Course.ListZipper| xs :: a -> List a -> List a
    λ> :type-at /Users/graham/Development/GitHub/fatlazycat/NICTA-course/src/Course/ListZipper.hs 240 31 240 32 xs

    *Course.ListZipper| *Course.ListZipper| *Course.ListZipper| <interactive>:1:1-2: Not in scope: ‘xs’

**Comment by geraldus** [comment]
@fatlazycat do you have some error message when invoking type-at command or you just have unexpected result? In first case debugger output would be really helpful.

Also, please clarify output you posed: which command you run manually or both of them? I see different column numbers (29 -> 31, 31 -> 32) in above commands, can you also show me line 240?

**Comment by fatlazycat** [comment]
Hmm, apologies seem to be getting myself confused. 

They changed the default emacs binding but their standard binding <spc> m h t now works showing the output in the haskell-process-log.

It just doesn't appear anywhere else such as the gutter, which I assume is a spacemacs / my config issue.

**Comment by geraldus** [comment]
@fatlazycat if it works it's good. I've made some improvements on `haskell-process-show-type-at` recently, so if it is not works I want to know. Anyway, if you're facing any issues with `haskell-mode` please feel free to report them!

**Comment by wedens** [comment]
I have the same issue with result printed only in haskell-process-log. Nothing is printed at the bottom of emacs (whatever it's called).

**Comment by fatlazycat** [comment]
@wedens In a non-spacemacs emacs ?

**Comment by wedens** [comment]
@fatlazycat  yeah. non-spacemacs

**Comment by fatlazycat** [comment]
@geraldus hmm, how do you see the results ?

I'll try a get the most minimal config for emacs sorted to try and narrow it down.

**Comment by geraldus** [comment]
Hey guys, sorry I also does not see results. Please excuse me I didn't made proper checks of echo area, I have presentation mode enabled and I can confirm that at least it works _(and echo area stuff worked fine just not long ago)_! Let me see what's happening and why it's become broken.

**Comment by geraldus** [comment]
Well, likely `haskell-utils-echo-or-present`<sup>[1]</sup> is a culprit, but it is so simple that I have no idea what's going wrong!

[1]:https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L963-L971

**Comment by geraldus** [comment]
Cool! I have a hotfix! There was missing parenthesis, I'll make a PR right now.

**Comment by fatlazycat** [comment]
😀 great thanks!

**Comment by geraldus** [comment]
@fatlazycat @wedens thanks for reporting, and excuse me for confusion! Let's wait Travis build

**Comment by geraldus** [comment]
Merged! @fatlazycat can you upgrade haskell-mode and check everything is working now?

**Comment by fatlazycat** [comment]
Not sure when it makes it to melpa-stable but copying your change into my system fixes it :) 

Thanks ! :)

Another point, not sure it it's my config or haskell-mode but when I do haskell-process-show-type-at it moves the point / cursor to a place after the thing you are asking it's type of. Obviously not major.

**Comment by geraldus** [comment]
Yeah, I know that, I believe this was so from very beginning.  Can you open an issue as a reminder?

**Comment by fatlazycat** [comment]
Sure #700

**Comment by gracjan** [comment]
Starting last stable release we actually have a workflow for cherry-picks of small fixes from master to stable branches.

Let me find out how this works.

(If it doesn't then you will need to wait for next stable release, this does not have a date forecast yet)

**Comment by fatlazycat** [comment]
Actually spacemacs picked up the nightly for haskell-mode so all good, thanks.
