### ISSUE TITLE
ghc-mod: unknown command: `legacy-interactive'

### ISSUE THREAD

**Issue by pmiddend** [haskell/haskell-mode#697]
I'm using the latest ghc-mod version from hackage (5.2.1.2) and the latest versions of "ghc" and "haskell-mode" from melpa. ghc-mod doesn't work because:

    ghc-mod: unknown command: `legacy-interactive'

Apparently it needs either an older or newer version of ghc-mod. So I went and used the elisp sources from my ghc-mod version, not the ones from melpa. With those, ghc-mod works, but pressing M-? to display an error in the source files gives:

    function definition is void: turn-off-haskell-font-lock

I suspect that the haskell-mode package from melpa depends on the ghc package from melpa. So what do I do here? Install some older version of the haskell-mode package? If so, which one? How do I know which version of haskell-mode plays along with the ghc emacs package and ghc-mod?

**Comment by gracjan** [comment]
This was fixed by the commit: https://github.com/kazu-yamamoto/ghc-mod/commit/51f9d716b84fa18770347bbca556fc3118b0b5fa
