### ISSUE TITLE
Improve manual (and README)

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#702]
I think we need to improve current documentation. User should have prominently displayed comprehensive brief overview of all major features of haskell mode somewhere , there should be covered following issues:

+ [ ] Minimal setup: how to get  and what features it gives
+ [ ] __Interactive__ and __Inferior__ modes should be mentioned right after that, there should be short description (explaining what is the difference between them?) followed by further instructions links for both.
+ [ ] Auto-completions and how to improve them
+ [ ] Each section should mention all optional external tools that could improve user experience (e.g. `hasktags`, `stylish-haskell`, `hoogle`)
    I think we need to mention `(add-hook 'haskell-mode-hook …) at least.
+ [x] Replace link `the online haskell-mode manual` to [HTML manual] page in README's **Advanced configuration** section.

What else?

It would be great to have a native English volunteer for documentation updates.

[HTML manual]:http://haskell.github.io/haskell-mode/manual/latest/

**Comment by geraldus** [comment]
I have updates this list a bit

**Comment by gracjan** [comment]
I'd direct people from README to the manual, or actually even better to the (not yet existing) web page here http://haskell.github.io/haskell-mode/.

**Comment by gracjan** [comment]
We know that we need to do documentation, I do not see how this issue improves our knowledge.
