### ISSUE TITLE
Can't install by following README instructions

### ISSUE THREAD

**Issue by tibbe** [haskell/haskell-mode#704]
I'm unable to find the haskell-mode package when using package-install. I have this in my init:

```
;; Packages
(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "http://stable.melpa.org/packages/"))

(defvar my-packages '(git-commit-mode markdown-mode protobuf-mode
				      better-defaults magit ido-ubiquitous
                                      yasnippet haskell-mode ghc smex
                                      exec-path-from-shell haskell-mode))
(package-initialize)
(dolist (p my-packages)
  (when (not (package-installed-p p))
    (package-install p)))
```

A manual package content refresh and package-install doesn't list the package either.

**Comment by tibbe** [comment]
Could it be because it's already installed?

**Comment by tibbe** [comment]
That seems to be it. Confusingly package-install claims a package doesn't exist if it's installed.

**Comment by geraldus** [comment]
Packages that already installed are listed at the bottom, the default order is available packages, installed packages and finally built-in packages.  Can you find `haskell-mode` there?

I've faced some issues with package list, finally I've got it to work properly having following config

``` elisp
(require 'package)
(add-to-list 'package-archives
  '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)

;; custom load-path locations goes here
```
Note, I'm not using MELPA stable.

**Comment by geraldus** [comment]
Oh, and I believe you need to invoke `package-refresh-contents` when checking installed pacakges:

``` elisp
(unless (g/packages-installed-p)
  (message "%s" "Refreshing packages database…")
  (package-refresh-contents)
  (dolist (pkg g/packages)
    (when (not (package-installed-p pkg))
      (package-install pkg))))
```
