### ISSUE TITLE
haskell-process-log doesn't exist

### ISSUE THREAD

**Issue by tibbe** [haskell/haskell-mode#705]
The interactive-haskell-mode output tells me to use haskell-process-log to debug, but that symbol is not defined (but some other haskell-process- ones are).

**Comment by geraldus** [comment]
Run `M-x customize-option RET haskell-process-log` and enable it via Customize.

**Comment by nrolland** [comment]
This option should be more prominent, but where can it be described : the GitHub repo, the haskell wiki, the Haskell-mode manual ?
