### ISSUE TITLE
parse-error with illegal token in instance declaration

### ISSUE THREAD

**Issue by haucheefa** [haskell/haskell-mode#707]
```
instance (Monoid a) => Applicative (Either2 a) where
  pure = Right2
  Right2 f <*> Right2 a = Right2 (f a)
  Left2  e <*> Right2 _ = Left2 e
  Right2 _ <*> Left2 e  = Left2 e
  Left2 e1 <*> Left2 e2 = Left2 (mappend e1 e2)
```
I get the following error message
> Illegal token: =>
> haskell-indentation-parse-error: No catch for tag: parse-error, "Illegal token: =>"

I am using current head of master branch (commit 4291cb94af1e928bf533624a2e60f2dcaedc7f46).

**Comment by gracjan** [comment]
Thanks for noticing this!
