### ISSUE TITLE
split-string(nil) in haskell-flymake-init

### ISSUE THREAD

**Issue by bremner** [haskell/haskell-mode#71]
A Debian user writes

> With this .emacs.el:

> (require 'flymake)
> (add-hook 'find-file-hook 'flymake-find-file-hook)

> If I try to open any (new or existing) haskell file, for instance with
> C-x C-x a.hs <ENTER>, it will give an error and not open the file.

> The error logged in *Messages* is:

> split-string: Wrong type argument: stringp, nil

I could reproduce this in emacs 23.4.1, and I got the following backtrace:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("[ \f	\n
]+" nil 0)
  split-string(nil)
  haskell-flymake-init()
  flymake-start-syntax-check()
  flymake-mode()
  flymake-find-file-hook()
  run-hooks(find-file-hook)
  after-find-file(t t)
  find-file-noselect-1(#<buffer b.hs> "~/b.hs" nil nil "~/b.hs" nil)
  find-file-noselect("~/b.hs" nil nil t)
  find-file("~/b.hs" t)
  call-interactively(find-file nil nil)

**Comment by gracjan** [comment]
@chrisdone: this one seems to be fixed already, as the code says:

    (let ((checker-elts (and haskell-saved-check-command
                           (split-string haskell-saved-check-command))))

so `split-string` is never called with `nil`. Close issue?
