### ISSUE TITLE
Why does `haskell-interactive-bring' call `delete-other-windows'?

### ISSUE THREAD

**Issue by the-kenny** [haskell/haskell-mode#710]
I find it rather annoying that running ```haskell-interactive-bring``` deletes all my windows (via ```delete-other-windows``` when starting a new session. Why doesn't it just use ```switch-to-buffer``` or similar?

(If there's a sense in the current behavior, please make it at least customizable)

**Comment by gracjan** [comment]
I do not think current behavior is the final form of what `haskell-interactive-bring` was supposed to be doing.

@the-kenny: if you could hack `haskell-interactive-bring` the way you would like it to be and submit a pull request we'd love to review it and improve the functionality for everybody.

**Comment by geraldus** [comment]
Yeah, very unpleasant stuff!  @the-kenny can you try to fix this?

**Comment by the-kenny** [comment]
I'm not sure when I'll find time but it's on my todo-list now. Likely some time next week.

**Comment by geraldus** [comment]
> it's on my todo-list

Cool! Let's wait for you then.

**Comment by the-kenny** [comment]
Please check the PR above. It's a simple fix, and we might want to make the function used configurable so users can stick to the old behavior if they want to.

**Comment by gracjan** [comment]
Configurability is a costly mechanism so we should try to avoid complexity as much as we can.

Pull request looks good to me. Lets wait a little so that other people get a chance to test it before merging.

**Comment by geraldus** [comment]
@gracjan I'm not certain, but will try to find a time and test this stuff this evening.
