### ISSUE TITLE
haskell-indentation-mode layout tops braces

### ISSUE THREAD

**Issue by arybczak** [haskell/haskell-mode#712]
Consider the following code:

```haskell
module Main where

data Foo = Foo {
  bar :: Int
, baz :: Int
} deriving Show

main :: IO ()
main = do
  let foo = Foo {
        bar = 0
      , baz = 0
      }
  putStrLn $ show foo
```

After you go to the line with "baz = 0" and press Enter, Emacs displays "Illegal token: layout-item" in statusbar and indentation no longer works after this point.

**Comment by gracjan** [comment]
Hmm, github version seems to be working. Likewise melpa version should also work. I haven't checked melpa-stable.

**Comment by arybczak** [comment]
Hmm, this is weird, I get this with master.

**Comment by arybczak** [comment]
I have emacs 24.5, it happens with .emacs.d/init.el containing only

```elisp
;; enable haskell-mode
(defconst haskell-mode-directory "~/.emacs.d/haskell-mode/")
(add-to-list 'load-path haskell-mode-directory)
(require 'haskell-mode-autoloads)
(add-to-list 'Info-default-directory-list haskell-mode-directory)

(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
```

and ..emacs.d/haskell-mode having haskell-mode from master.

**Comment by gracjan** [comment]
How about `rm *.elc` ?

**Comment by arybczak** [comment]
This is with clean, just cloned and compiled repository :(

**Comment by arybczak** [comment]
Added tests do not replicate the issue I posted.

Here's the patch to correctly reflect it:
```
diff --git a/tests/haskell-indentation-tests.el b/tests/haskell-indentation-tests.el
index 85e1150..aa36fdb 100644
--- a/tests/haskell-indentation-tests.el
+++ b/tests/haskell-indentation-tests.el
@@ -410,8 +410,9 @@ Example of lines:
    "main = do"
    "let foo = Foo {"
    "      bar = 0"
-   "      , baz = 0"
-   "      ^"))
+   "    , baz = 0"
+   "    }"
+   "    ^"))
 
 (ert-deftest haskell-indentation-check-instance-21a-unicode ()
   "layout versus comma in braces (unicode)"
@@ -420,5 +421,6 @@ Example of lines:
    "main = do"
    "let foo = Foo {"
    "      bar = 0"
-   "      , baz = 0"
-   "      ^"))
+   "    , baz = 0"
+   "    }"
+   "    ^"))
```

and it indeed fails with "Illegal token: layout-item".

**Comment by gracjan** [comment]
Confirmed.

Braces and commas should take priority over `layout-item`, `haskell-indentation` does it opposite to what Haskell Report says.
