### ISSUE TITLE
haskell-indentation breaks with UnicodeSyntax

### ISSUE THREAD

**Issue by eigengrau** [haskell/haskell-mode#715]
Trying to use haskell-indentation-mode in haskell-mode 20150512.2319 using the following example will fail with `Illegal token: ←`.

```
{-# LANGUAGE UnicodeSyntax #-}

fun = do
  x ← "abc"
```

**Comment by gracjan** [comment]
Note that we have a very nice testsuite in `tests/haskell-indentation-tests.el` where you can add a test for this case.

**Comment by gracjan** [comment]
This one is working correctly now. Thanks for the report!

**Comment by eigengrau** [comment]
Thank you!
