### ISSUE TITLE
haskell-indentation-mode does not bind DEL

### ISSUE THREAD

**Issue by drvink** [haskell/haskell-mode#721]
Sorry for the noise, but I've looked over the commit log and I can't tell if I'm losing my mind or if something's changed with the default behavior of DEL under haskell-indentation-mode. It doesn't seem to be getting rebound for me anymore (when I `C-h k DEL`, it's bound to `delete-backward-char`), and furthermore, the cursor gets placed differently from where I expect it used to be.

The info pages seem to indicate that DEL should be getting rebound:

```
‘haskell-indentation-mode’

     Improved variation of ‘haskell-indent-mode’ indentation mode.
     Rebinds <RET> and <DEL>, so that indentations can be set and
     deleted as if they were real tabs.
```

Looking through the history, the behavior I'm used to from DEL was supplied by `haskell-indentation-delete-backward-char`, but the only relevant commit I see is c91c6b205310d15f9d115e86e3fcc822e48c086c, which was in March.

I update haskell-mode from master pretty often, so I don't know why I'm only seeing this now, but it's driving me crazy. Can we please have the old stuff back as an alternative, or can you tell me what functions I can use (if any) that will give similar behavior to the way DEL and the indentation algorithm for a new line used to work?

**Comment by drvink** [comment]
The stuff controlled by this was what I was referring to:

```elisp
(defcustom haskell-indentation-delete-backward-jump-line nil
  "Delete backward jumps to the previous line when removing last indentation."
  :type 'boolean
  :group 'haskell-indentation)
 
(defcustom haskell-indentation-delete-indentation t
  "Delete removes indentation."
  :type 'boolean
  :group 'haskell-indentation)
```

...and I preferred the previous indent placement algorithm by far.

**Comment by gracjan** [comment]
Hi, thanks for the report.

`S-TAB` is bound to `haskell-indentation-indent-backwards`, is that the functionality you are looking for?

If you have specific case where indentation is subpar please report it! Current code is hackable and has a test suite so that gives good prospects for future of `haskell-indentation`.

**Comment by drvink** [comment]
`haskell-indentation-indent-line` and `haskell-indentation-indent-backwards` achieve part of it, but they're not quite the same as what `haskell-indentation-delete-backward-indentation`, `haskell-indentation-delete-indentation`, or `haskell-indentation-delete-backward-jump-line` did, since they only handle indent and don't combine indenting with deletion. I need to test more for the indent placement problem--I can't reproduce the strange behavior I was previously having, so I may have been mistaken.

I [updated](https://gist.github.com/drvink/dbb533fcc87e4e7fdec2) the old deletion code to work on current haskell-mode, but it seems to delete two characters instead of just one, and I can't figure out why.

**Comment by gracjan** [comment]
Is this the same request as in #866? If so I'd like to understand how this is supposed really work, I've tried to use it and it was horrible.

**Comment by drvink** [comment]
That was part of it, but not all, if I recall. I filed this issue a while ago. :)

**Comment by gracjan** [comment]
The consensus so far is that binding <kbd>DEL</kbd> is not the best usability option and should not be done. <kbd>S-TAB</kbd> works more predictably.
