### ISSUE TITLE
Move haskell-utils-* from haskell-commands.el to utils package if possible, rename otherwise

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#728]
There are several utility functions defined in `haskell-commands.el`.  I think it's better to move them into `haskell-utils.el` if possible, and rename prefix to `haskell-commands-`.  I think we can move those functions which does not depends on other `haskell-mode` functionality, for example `haskell-utils-capture-expr-bounds` uses `haskell-spanable-pos-at-point` internally and likely it is first candidate to rename rather than move.

Here is a list of this functions:

+ [x] `haskell-utils-async-post-command-flag`<sup>[1](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L37-L39)</sup>
+ [x] `haskell-utils-capture-expr-bounds`<sup>[2](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L916-L927)</sup>
+ [x] `haskell-utils-compose-type-at-command`<sup>[3](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L929-L962)</sup>
+ [x] `haskell-utils-insert-type-signature`<sup>[4](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L965-L979)</sup>
+ [x] `haskell-utils-echo-or-present`<sup>[5](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L981-L989)</sup>
+ [x] `haskell-utils-async-update-post-command-flag`<sup>[6](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L991-L997)</sup>
+ [x] `haskell-utils-async-watch-changes`<sup>[7](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L999-L1007)</sup>
+ [x] `haskell-utils-async-stop-watching-changes`<sup>[8](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L1009-L1019)</sup>
+ [x] `haskell-utils-reduce-string`<sup>[9](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L1021-L1026)</sup>
+ [x] `haskell-utils-parse-repl-response`<sup>[10](https://github.com/haskell/haskell-mode/blob/master/haskell-commands.el#L1028-L1031)</sup>

**Comment by gracjan** [comment]
There is also `haskell.el` containing a lot of questionable content that could be moved somewhere else.

`haskell-mode` does not use this double-dash conventions, so lets not introduce yet another way of doing things. Same against against `/` as a separator that seems to be yet another convention for private methods or variables.

**Comment by geraldus** [comment]
Is this task is well defined, btw? :D

**Comment by gracjan** [comment]
I have removed all confusing statements. Now it is well-defined :)

**Comment by geraldus** [comment]
Nice! #752 covered all stuff, can be closed now.  Good job, @ankhers !
