### ISSUE TITLE
Turn haskell-ghc-supported-extensions and haskell-ghc-supported-options customization options to variables

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#730]
I can't be certain, but `haskell-ghc-supported-extensions`<sup>[1][exts]</sup> and `haskell-ghc-supported-options`<sup>[2][opts]</sup> are likely useless, when you try unfold them it brings a huge list.  I can't imagine the case when it needed to extend these lists, or remove/modify items.  In both cases values are fetched by invoking shell commands (`ghc --show-options` and `ghc --supported-extensions`).  I think it's better to modify these options to variables.

[opts]:https://github.com/haskell/haskell-mode/blob/master/haskell-customize.el#L337
[exts]:https://github.com/haskell/haskell-mode/blob/master/haskell-customize.el#L331

**Comment by ivan-m** [comment]
I know that shm uses `ghc --supported-languages` (which is a alias for `ghc --supported-extensions`) to complete `LANGUAGE` pragmas; possibly something similar could be done in haskell-mode itself?

(`haskell-ghc-supported-options` could then be used to help auto-complete fields in .cabal files...)

**Comment by geraldus** [comment]
It's very strange to me, that we have following code<sup>[1][lang-exts]</sup> in `haskell-customize.el`:
```el
(defcustom haskell-language-extensions
  '()
  "Language extensions in use. Should be in format: -XFoo, -XNoFoo etc."
  :group 'shm
  :type '(repeat 'string))
```
Should it be move to **SHM** itself? @ivan-m are you talking about this? In my Emacs installation it's empty (as default value).

Looks like SHM get extensions from `Language.Haskell.Extensions`<sup>[2][hask-exts]</sup> using its binary<sup>[3][shm-src]</sup>.

@chrisdone can you clarify a bit? 

[lang-exts]:https://github.com/haskell/haskell-mode/blob/master/haskell-customize.el#L325-L329
[hask-exts]:http://hackage.haskell.org/package/Cabal-1.22.4.0/docs/Language-Haskell-Extension.html#
[shm-src]:https://github.com/chrisdone/structured-haskell-mode/blob/2f41350bc320d364fe8ebb1c41030cb3da516ae8/src/Main.hs#L256-L293

**Comment by ivan-m** [comment]
Looks like something that wasn't moved over to shm properly.

Though I was referring to [this usage](https://github.com/chrisdone/structured-haskell-mode/blob/2f41350bc320d364fe8ebb1c41030cb3da516ae8/elisp/shm-insert-del.el#L229) by shm (which doesn't use its own binary, nor get them from Cabal); what you linked to I believe is for parsing purposes.

**Comment by chrisdone** [comment]
Oh, this variable has the wrong group, that's all. The idea is that various tools written with HSE that don't know what extensions to use can use this variable. Examples: hlint, hindent, structured-haskell-mode, tool-de-jour, …

**Comment by geraldus** [comment]
@chrisdone, I guess in this case the group should be `haskell`.

BTW, you can use mentioned `haskell-ghc-supported-extensions` variable [here][1].  Also I will introduce similar variable for pragma names in `haskell-mode` in my next PR related to completions stuff, so you will be able to use it and remove [this variable][2] from SHM. I can ping you when it will be done or provide a PR.

[1]:https://github.com/chrisdone/structured-haskell-mode/blob/2f41350bc320d364fe8ebb1c41030cb3da516ae8/elisp/shm-insert-del.el#L244
[2]:https://github.com/chrisdone/structured-haskell-mode/blob/2f41350bc320d364fe8ebb1c41030cb3da516ae8/elisp/shm-customizations.el#L166

**Comment by chrisdone** [comment]
> BTW, you can use mentioned haskell-ghc-supported-extensions 

No! I think that is different. We have the two cases: 

* haskell-ghc-supported-extensions: here are all extensions that GHC ***supports***
* haskell-language-extensions: here are the extensions that are **enabled*** in this buffer(s)

**Comment by geraldus** [comment]
@chrisdone hmm, why not?

`haskell-ghc-supported-extensions` value is set by<sup>[1][ghc-sup-exts]</sup>

```el
(split-string (shell-command-to-string "ghc --supported-extensions"))
```

SHM uses<sup>[2][shm-sup-exts]</sup>:

```el
(split-string (shell-command-to-string "ghc --supported-languages")
```

And `ghc --supported-languages` is an alias for `ghc --supported-extensions` and gives same results, so the result should be the same in both cases. Am I missing something?

[ghc-sup-exts]:https://github.com/haskell/haskell-mode/blob/master/haskell-customize.el#L332
[shm-sup-exts]:https://github.com/chrisdone/structured-haskell-mode/blob/2f41350bc320d364fe8ebb1c41030cb3da516ae8/elisp/shm-insert-del.el#L244

**Comment by chrisdone** [comment]
Yes, those two are the same. As long as you're leaving `haskell-language-extensions` alone, your plan seems good. :+1:

**Comment by gracjan** [comment]
Such submarine dependencies are very fragile invisible constructs. Other Emacs packages tend to depend on obscure functions and variables. Recently we had such a problem with `ghc-mod`.

`haskell-language-extensions` is never mentioned anywhere else in `haskell-mode`. This is questionable and fragile engineering that puts unnecessary ambush surprises on future coming new contributors.

**Comment by chrisdone** [comment]
It's the same kind of variable as `haskell-indent-spaces`. 

If you have anything cogent to contribute, please do so. Name-calling things "questionable" and "fragile" is zilch.

**Comment by gracjan** [comment]
@chrisdone: Please follow https://help.github.com/articles/using-pull-requests/ even you have commit bit. We try to get all changes through TravisCI before they are merged.

Your added comment forgets to explain if `nil` as value means no extensions or all available extensions.

**Comment by chrisdone** [comment]
"Forgets" is the wrong word, it implies there was ever any intention to write about this strange notion of "all available extensions", as if they're all mutually compatible, to begin with, which there neither was nor is.

**Comment by gracjan** [comment]
So I had to go to the place where this variable is **used** to find out what is the meaning of it.

Here is what happens:

```haskell
-- | Default extensions.
defaultExtensions :: [Extension]
defaultExtensions =
  [e | e@EnableExtension{} <- knownExtensions] \\
  map EnableExtension badExtensions

-- | Extensions which steal too much syntax.
badExtensions :: [KnownExtension]
badExtensions =
    [Arrows -- steals proc
    ,TransformListComp -- steals the group keyword
    ,XmlSyntax, RegularPatterns -- steals a-b
    ,UnboxedTuples -- breaks (#) lens operator
    -- ,QuasiQuotes -- breaks [x| ...], making whitespace free list comps break
    ]
```

https://github.com/chrisdone/structured-haskell-mode/blob/master/src/Main.hs#L280

So shm enables **all available extensions** (in haskell-src-exts) minus some deemed bad.

@chrisdone: Please write some ERT tests for this variable instead of arguing.

**Comment by chrisdone** [comment]
The particular behaviour of SHM, one consumer of this variable, is irrelevant, what it does with the list may change at any time. The variable's purpose has been documented.

> @chrisdone: Please write some ERT tests for this variable instead of arguing.

![](http://www.sharegif.com/wp-content/uploads/2013/09/21/lol-gif-36.gif)

Stop pinging me by name on this issue. I'm done here.

**Comment by ivan-m** [comment]
@gracjan except that bit of code is not what was being talked about; @geraldus was asking about the elisp variables in haskell-mode and I said that one of them could be used for similar functionality to something that SHM has in *elisp*.

**Comment by gracjan** [comment]
@ivan-m: I agree with your comments.

For reference `haskell-language-extenstions` is used in exactly two places in shm:

```el
(defcustom shm-language-extensions
  (if (boundp 'haskell-language-extensions)
      haskell-language-extensions
    '())
  "Language extensions in use. Should be in format: -XFoo, -XNoFoo etc."
  :group 'shm
  :type '(repeat 'string))

(defun shm-language-extensions ()
  "Get the number of spaces to indent."
  (if (boundp 'haskell-language-extensions)
      haskell-language-extensions
    shm-language-extensions))
```

I'm still bothered by unused variables, I'm still bothered by submarine dependencies, I'm still bothered by new contributors hitting such obstacles.

**Comment by gracjan** [comment]
@geraldus: Can you restate exactly what was your intention in the beginning with certain terms in a new PR request? I would like to mark it as well-defined-task, for that it has to sound as a simple description what should be done.

**Comment by geraldus** [comment]
@gracjan surely

**Comment by ivan-m** [comment]
@gracjan what do you mean by submarine dependencies?

Note that `haskell-language-extensions` is not what @geraldus was referring to originally; IIUC this variable is equivalent to having language extensions specified in the .cabal file (and using ghci rather than cabal-repl) rather than using LANGUAGE pragmas.
