### ISSUE TITLE
haskell-process-do-info no longer displays exports (doesn't invoke :browse <module> )

### ISSUE THREAD

**Issue by dmjio** [haskell/haskell-mode#737]
Prior to `13.14` I was able to hover over a module import and call `haskell-process-do-info` (mapped to `C-c C-i` by default) and all top level functions / data types would display in the haskell interactive repl. Now nothing shows up. Has this functionality been moved? It appears to show a preview of the exports in a mini-buffer and in `*Messages*`, but not the repl. 
Example: `-- imported via Vertigo.Types.Follow [ data Follo .. ]  ` is all I get, in a mini-buffer. Am I missing something trivial?

**Comment by geraldus** [comment]
@dmjio I've already tried to reply you on IRC, have you tried presentation mode?  You can enable it customizing `haskell-process-use-presentation-mode` option.  The functionality changed a bit recently.

**Comment by dmjio** [comment]
@geraldus, ah thanks, typing `haskell-customize` and toggling the `Haskell Process Use Presentation Mode` under the `Haskell interactive group`
