### ISSUE TITLE
Support company-mode docs and source with haskell-mode backend

### ISSUE THREAD

**Issue by LukeHoersten** [haskell/haskell-mode#738]
From the [`company-mode` docs](http://company-mode.github.io):
> When the completion candidates are shown, press <f1> to display the documentation for the selected candidate, or C-w to see its source. Not all back-ends support this.

**Comment by LukeHoersten** [comment]
Ping @geraldus

**Comment by creichert** [comment]
`company-ghc` uses `hoogle search --info <ident>` to populate the doc buffer: https://github.com/iquiw/company-ghc/blob/master/company-ghc.el#L193.

`auto-complete` does support this feature with the F1 key as well. Different auto-complete sources utilize it in different ways but I like the haddock.

I pasted a screenshot in #215 and it would be nice to allow some options for what kind of docs are shown. I can help test auto-complete if needed.

**Comment by LukeHoersten** [comment]
I was under the impression `company-ghc` depended on `ghc-mod` which I don't use. I use `haskell-process` etc instead. Perhaps we need to rethink how all this ties together?

**Comment by LukeHoersten** [comment]
Looks like this is redundant with #215 - thank's @creichert

**Comment by creichert** [comment]
The doc buffer uses `hoogle` (although the rest of `company-ghc` does use `ghc-mod`).

My only point was this is something we could most likely support relatively easily in both auto-complete and company-ghc. I definitely want this feature too.

**Comment by LukeHoersten** [comment]
Understood. Good point.
