### ISSUE TITLE
haskell-ident-pos-at-point does not work for operators

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#739]
Function `haskell-ident-pos-at-point` returns `nil` when point is at operator.   Fixing this will potentially fix many other things (show type, show info, completions).  I have no strong opinion right now what should be returned when operator is wrapped in parentheses in following cases (`*` means point is at following char)
+ `(>>*=)`, point at `=`
+ `(>>=*)`, point at `)`
+ `(>>=)*`, point stands after `)`.

By the way, I've decided to test will REPL complete operator partially wrapped, e.g. `:complete repl "(>>`, and I've found that REPL returns unexpected results for operators: no matter is there an opening parenthesis or not, REPL returns all imported names, that is a functions, operators, and even data type and value constructors.  You can try it yourself, give REPL following commands:
`:complete repl ">>"`
`:complete repl "+"`
`:complete repl "(>"`
`:complete repl "(+"`
This will list a lot of useless results! @gracjan do you know where can I open issue ticket for this stuff?

Related to #735

**Comment by gracjan** [comment]
This seems the way to go:

https://ghc.haskell.org/trac/ghc/wiki/ReportABug

It is really sad news that ghci can't :complete operator symbols. Is there
a way to work around this limitation somehow?

-- 
Gracjan

**Comment by geraldus** [comment]
@gracjan likely it is not, I thought maybe prefixing module name will help, but it does not:
```
:complete repl "Prelude.map"
7 7 ""
"Prelude.map"
"Prelude.mapM"
"Prelude.mapM_"
```
but `:complete repl "Prelude.>" gives back everything again.

**Comment by geraldus** [comment]
I've created a ticket https://ghc.haskell.org/trac/ghc/ticket/10576#ticket

**Comment by gracjan** [comment]
@geraldus: Can we do something about this or must we wait?

Can we somehow detect that haskell-mode has faulty GHCi running and warn the user that asking for operators is not going to work?

**Comment by geraldus** [comment]
@gracjan I've already provided a patch for this, but it needs some polishing.  I think we can implement a workaround based on your recent lexeme stuff though.  But some research is needed, I was extremely short in time past weeks, and my current point of interest is still completions stuff (and I did write some code for this, will provide few PRs soon), so I can't take this myself right now.

**Comment by geraldus** [comment]
This is still relevant.  @gracjan are lexemes allow us now to easily grab operator bounds for both infix and bracketed forms?

**Comment by gracjan** [comment]
Closing because #1227 describes what should be done.
