### ISSUE TITLE
On opening a file, haskell-doc opens several files defined in import section

### ISSUE THREAD

**Issue by vlatkoB** [haskell/haskell-mode#742]
Hi,
In a `Yesod` project, on opening `Application.hs` file, `haskell-doc` automatically opens `Import.hs` and `Foundation.hs` (which is imported from `Import.hs`). So, instead of having just one intended buffer (`Application.hs`), there are two more unwanted buffers opened.
If `haskell-doc` is not turned on, it doesn't happen.

Is this a bug or a feature? :-)
Possible to turn off?

br,
vlatko

**Comment by gracjan** [comment]
This seems to be a function of `projectile` no `haskell-doc`. Can you confirm that `haskell-doc` has nothing to do with this?

**Comment by vlatkoB** [comment]
@gracjan When I do not `turn-on-haskell-doc`, only one file is opened. I tried turning off everything but `haskell-mode`, so I think it is `haskell-doc`. I noticed it on a plain `Yesod` app. This might be specific because all three files, `Application.hs`, `Foundation.hs` and `Import.hs` are in the project root, not in `src` dir.

**Comment by gracjan** [comment]
This is super strange. Do we know what mixture of functionalities cause this interaction?

**Comment by vlatkoB** [comment]
Just discovered what's blocking answering the `haskell-process-suggest-*` questions so I have to C-g 3 times to unblock/unfreeze, and than it leaves the answered letter ('y','n') at point in buffer. It is 'haskell-doc'.
I turned all other packages off, left just `haskell-mode`, and turned `haskell-doc` on/off.
Emacs is 24.5.1 on Arch, and all emacs packages updated. Not using ghc-mod.
Anyone else have such problems?

**Comment by vlatkoB** [comment]
And another discovery. If `haskell-doc` is not loaded, emacs freezes with message "Scanning declarations...". And never ends. Again, 3 x C-g allows to continue.

**Comment by vlatkoB** [comment]
Found the culprit for opening other files. It is `haskell-doc-show-global-types`. When set to `t`, it opens files. Setting it to `nil`, other files are not open.
Closing this issue.

**Comment by gracjan** [comment]
vlatkoB: Can you add some documentation in haskell-mode.texi about this?

**Comment by vlatkoB** [comment]
I'm rather busy right now, but I do not think there is a need for that. Customize for `Haskell Doc Show Global Type` says clearly:
```
Haskell Doc Show Global Types 
   If non-nil, search for the types of global functions by loading the files.
   This variable is buffer-local.
```
Another question is should this be done in another way?

**Comment by gracjan** [comment]
It is good enough in this case. Thanks.
