### ISSUE TITLE
Add Stack ghc feature

### ISSUE THREAD

**Issue by johnwalker** [haskell/haskell-mode#744]
I'd really like to be able to use `stack ghc` instead of `cabal repl`. To do this, we just need to work inside haskell-process.el, right?

**Comment by gracjan** [comment]
There is a thing called `process-type` and it currently supports `cabal-repl` and `ghci`. It should be pretty easy to add `stack ghc` to the list of supported methods.

**Comment by johnwalker** [comment]
OK, I'll put in a PR today.
