### ISSUE TITLE
[Discussion] haskell-indentation, reset indentation after newline

### ISSUE THREAD

**Issue by meditans** [haskell/haskell-mode#747]
It would be a feature if there was a option to reset indentation to the first column after an empty line in `haskell-indentation`, similarly to what is done in `haskell-indent`.

**Comment by gracjan** [comment]
Note that `haskell-indent-mode` does not reset to first line after second `newline`.

**Comment by gracjan** [comment]
It seems it never did. I'm not sure what is asked in this issue in this case. There is always <kbd>C-a</kbd> available when needed.

**Comment by meditans** [comment]
Sorry @gracjan, I somehow missed your responses on this issue. Let's do an example to understand the problem. I have the code:

    bar :: Int -> Int
    bar i = i + 2|

when I hit newline, the position of my cursor will be (quite correctly):

    bar :: Int -> Int
    bar i = i + 2
      |

However, if I hit newline again, the position of the cursor will be:

    bar :: Int -> Int
    bar i = i + 2
    
      |

what I'm saying here is that this way of indenting _after the first blank line_ feels strange to me: I usually want to start a new definition. A most ergonomic solution, in my opinion, is to reset the indentation after a blank line.

Here's how I set my local config to do that:

    (defun haskell-indentation-advice ()
      (when (and (< 1 (line-number-at-pos))
                 (save-excursion
                   (forward-line -1)
                   (string= "" (s-trim (buffer-substring (line-beginning-position) (line-end-position))))))
        (delete-region (line-beginning-position) (point))))
  
    (advice-add 'haskell-indentation-newline-and-indent
                :after 'haskell-indentation-advice)

I still believe, though, that this should be the default behaviour. What do you think?

**Comment by geraldus** [comment]
@meditans such behaviour looks right to me.
