### ISSUE TITLE
How can I specify where build artifacts are stored?

### ISSUE THREAD

**Issue by codygman** [haskell/haskell-mode#749]
For instance I have a Yesod project which looks like this after using haskell-process-load-or-reload in my project:

```shell
~/programming/haskell/yesod/my-project $  ls
Application.hs  Handler    Model.hi   Settings     app                    my-project.sqlite3-shm  static
Foundation.hi   Import     Model.hs   Settings.hi  config                 my-project.sqlite3-wal  templates
Foundation.hs   Import.hs  Model.o    Settings.hs  my-project.cabal    dist                       test
Foundation.o    LICENSE    README.md  Settings.o   my-project.sqlite3  stack.yaml                 
```

Is there a way to put all of these *.(hi|o) files into a custom directory?

**Comment by geraldus** [comment]
Not an answer, just want to clarify, that I didn't faced this issue in near past, all that files were stored in `dist/build` directory.  I have no ability to check it right now (I've changed GHC from 7.8.4 to version 7.10.1 recently and need to rebuild/reconfigure my tools), but I think I'll be able to do it later this day.

**Comment by ivan-m** [comment]
If you use a `.cabal` file then they'll be stored in the `dist/` directory when using `cabal` to build the project.

Otherwise, see `-hidir` and `-odir` for ghc.

**Comment by gracjan** [comment]
This issue seems to be ghc/ghci/cabal related and there is little we can do in haskell-mode about it.

I close this issue report, write a comment here if you want it reopened.

**Comment by ivan-m** [comment]
In particular, unless you are using object code in ghci, haskell-mode wouldn't be producing the `.o` and `.hi` files.
