### ISSUE TITLE
haskell-process-suggest-pragma hangs emacs

### ISSUE THREAD

**Issue by drewr** [haskell/haskell-mode#754]
Using `haskell-mode-20150707.57` with `interactive-haskell-mode`, whenever `haskell-process-suggest-pragma` is triggered, it sometimes works, and sometimes hangs emacs. After that a C-g will suspend the process and try to dump core.

**Comment by johnwalker** [comment]
Is this specific to stack-ghci?

**Comment by drewr** [comment]
I think so. I can't quite tell because I've been switching back and forth quite a bit. I'll switch back to cabal for a bit and see if it's triggered.

**Comment by drewr** [comment]
I switched back to `cabal-repl` and the first time I responded `n` it hung.

**Comment by vlatkoB** [comment]
It is happening to me with `cabal-repl` as well. I found out that it is because of `haskell-doc` being active during suggestions. And I have to C-g 3 times to get out of it. :-)

I made a workaround until this gets fixed:
```elisp
(defun haskell-process-trigger-suggestions-ad (orig-fun &rest args)
  (turn-off-haskell-doc)
  (apply orig-fun args)
  (turn-on-haskell-doc))

(advice-add 'haskell-process-trigger-suggestions
   :around #'haskell-process-trigger-suggestions-ad)
```

**Comment by gracjan** [comment]
Closing in favor of #820, there is more information there.
