### ISSUE TITLE
C-c C-l  returns "No current directory"

### ISSUE THREAD

**Issue by wwat** [haskell/haskell-mode#763]
As a user I don't want to see this whining from a program. Especially, if all this stuff did work 5 years ago. Usually, software becomes *better* over time.

**Comment by gracjan** [comment]
Can you help us to debug this issue? How did you get this message?

**Comment by wwat** [comment]
No, sorry. You should design your software, such that it is easy to debug in the first place, like all the grown ups do. If you do that, your failure rate would also go down. 

If you don't know how to do this, then please just stop with all your software development activities, because one day, I might have to work on code you have written.

**Comment by gracjan** [comment]
My role in this project is to facilitate others to contribute. Do you plan
to contribute?

**Comment by mrkkrp** [comment]
@wwat, this is a wrong window, you wanted <kbd>M-x doctor</kbd>.

@gracjan, behavior of this user is rather destructive, obviously some sort of trolling takes place. Please consider reporting abuse if this continues. To report abuse go to personal page of offending account and click on a button with little exclamation point. In this menu you can either block the user or report abuse.

**Comment by wwat** [comment]
@mrkkrp I am not the one who fucked up haskell-mode.  It's not trolling if it's the truth. Also, if your IQ is not above 150, I'd prefer it if you would not talk to me.

**Comment by geraldus** [comment]
@wwat I'd prefer to action rather than speak, if you don't like something you may cry forever, or just put your hands on it and make something at least.  If you have huge bad of money (someone paid you), pay someone else who will write the software you need exactly.  What a problem?

**Comment by wwat** [comment]
@geraldus Please construct valid English or better: stop talking to me for three years.

**Comment by geraldus** [comment]
@wwat I think no one will talk to you soon.

**Comment by gracjan** [comment]
Closing as we have other issue tracking behavior of `C-c C-l` in #522.
