### ISSUE TITLE
REPL does not work properly until load or reload file second time

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#765]
I had very limited interaction with REPL in past, but getting to use it more now.  Usually loading file with `haskell-process-load-or-reload` works correctly only first time, if I'll modify source and reload it REPL does not work.  For example, loaded modules are unavailable (`<interactive>:1:1: Not in scope: …`), or `main` action could not be run:

```
λ> main
Too late for parseStaticFlags: call it before runGhc or runGhcT
*** Exception: ExitFailure 1
```

To resolve this I have to simply reload file once again without any modifications, after that everything work.  I don't know is it some recent breakage or old bug.  I've faced this issue with single haskell files and with cabal projects too.

Any thoughts?

**Comment by geraldus** [comment]
One thing I should mention, I'm currently using GHC version **7.10.1**.

**Comment by ivan-m** [comment]
Is this with just plain ghci or with cabal?  I haven't seen anything like this when using cabal + sandboxes before.

(btw, you probably want to use `:main` rather than `main`: the former acts more like you're running it on the command line, which makes a difference if you want to test parsing in command-line arguments, etc.)

**Comment by geraldus** [comment]
> Is this with just plain ghci or with cabal?
 
> I've faced this issue with single haskell files and with cabal projects too.

So, this behaviour was spotted both with `ghci` and `cabal-repl` process types.

Thank you for notice about `main`!

**Comment by geraldus** [comment]
I think this is not relevant now.
