### ISSUE TITLE
Rename turn-on-haskell-* functions

### ISSUE THREAD

**Issue by ankhers** [haskell/haskell-mode#771]
I noticed that `turn-on-haskell-indentation` has been marked obsolete in favour of `haskell-indentation-mode`. Are there plans to obsolete all `turn-on-haskell-*` in favour of `haskell-*-mode`?

I think it would ultimately be better to stick to a single naming convention.

**Comment by gracjan** [comment]
Yes. Consistency is important.

If you do a pull request marking other functions as obsolete then we will
be very grateful. Remember to change the documentation also.
