### ISSUE TITLE
No indentation suggested for case clauses

### ISSUE THREAD

**Issue by dzhus** [haskell/haskell-mode#786]
I'm experiencing broken indentation for `case` keyword clauses with haskell-mode version 13.15-git (/home/dzhus/.emacs.d/elpa/haskell-mode-20150729.316/)

Minimal example:

```
f x =
  case x of
    Just 5 -> return ()
```

When I hit TAB on the line with `Just`, it suggests to line it up with `case`:

```
f x =
  case x of
  Just 5 -> return ()
```

Here's an illustration of the problem with «Show indentations» option switched on:

![2015-07-30-001022_1280x800_scrot](https://cloud.githubusercontent.com/assets/102053/8970044/f609f124-364f-11e5-8f24-91cdd1d8e7be.png)

The rest of the options in `haskell-indentation` group are set to standard.

**Comment by gracjan** [comment]
Hmm, technically this is correct in current implementation of `haskell-indentation`. The point is that clause after `of` may be empty and `Just` may start a new statement. `haskell-indentation` does not look past the first token on the line you are indenting.

I see how this might be confusing though... just not sure how to improve given current indentation design.

**Comment by dzhus** [comment]
Thanks for the explanation. However, a there's an equal possibility that there *is* a clause after the `case` line (and this is usually the case in the wild with actual Haskell code). It should be possible to cycle through indentation options with TAB.

> haskell-indentation does not look past the first token on the line you are indenting.

I believe in this case we should look at the line *before* the current line? And how is this different from `case` line being indented after `f x`?

**Comment by gracjan** [comment]
Hmm, I think I misunderstood your comment.

To clarify: I get BOTH indentation points proposed. Do you get something else?

**Comment by dzhus** [comment]
Yes, I am only suggested to have my `Just 5` aligned on the same column as `case`. I cannot cycle with TAB to actually  indent the `Just 5` line.

**Comment by gracjan** [comment]
That is interesting. Are you using `haskell-indentation` or something else?
The latest github version or other version?

**Comment by gracjan** [comment]
To my best knowledge this is working ocrrectly. Reopen if you check against latest github version of haskell-indentation mode and it does not work.
