### ISSUE TITLE
Can't compile from within emacs if $EMACS is not set.

### ISSUE THREAD

**Issue by wkunkel** [haskell/haskell-mode#791]
The makefile uses the `$EMACS` environment variable to find emacs if it is present, or falls back to `emacs` if it is not. However, emacs seems to set the `$EMACS` environment variable to `t` for all of its subshells if it does not already exist. The result is that running make from an emacs shell or with M-x compile fails with `/bin/sh: t: command not found`.

**Comment by gracjan** [comment]
Is there a way to find out the real path to currently running Emacs?

**Comment by wkunkel** [comment]
Good question! I can get the parent PID from a shell with bash's $PPID

**Comment by wkunkel** [comment]
Sorry about closing/reopening, my browser did something weird.

**Comment by gracjan** [comment]
@wkunkel: I see that your fix actually fixes the issue, so merged. Thanks.
