### ISSUE TITLE
Haskell mode is asking too many questions before it starts a repl.

### ISSUE THREAD

**Issue by jaseemabid** [haskell/haskell-mode#793]
The project does have a .cabal file. I'm using the `haskell-process-load-file` function bound to C-c C-l to start the repl.

1. It asks for project name
2. Cabal directory
3. Build target
4. Current directory

How do I configure Haskell mode to ask no questions at all? I think the experience can be improved and I'm willing to help. 

Versions: 

    GNU Emacs 25.0.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2015-05-19 on lcy01-07
    haskell-mode version 13.15-git (/home/j/.emacs.d/elpa/haskell-mode-20150729.316/)

PS: I know its been asked elsewhere and someone tried to troll the bug list a few days back. Please don't relate to that :)

**Comment by gracjan** [comment]
Current answer is: just upgrade haskell-mode. It should not ask any
questions anymore as the new default is to not ask anything. There is a new
setting that enables previous behavior.

**Comment by jaseemabid** [comment]
I got the latest available on melpa (Version: 20150729.316).

**Comment by gracjan** [comment]
This is the commit:

https://github.com/haskell/haskell-mode/commit/477c7b5e40515af1e98c977b1878921e97d5d23b

**Comment by jaseemabid** [comment]
@gracjan Great! Works as expected. When will this be on melpa?

**Comment by gracjan** [comment]
Should be there on MELPA, it will end up on MELPA-STABLE with the release.
