### ISSUE TITLE
`session` and `process` are the same thing, but aren't, and this causes pain

### ISSUE THREAD

**Issue by deepfire** [haskell/haskell-mode#799]
Witness `haskell-process-start`:

```
    (haskell-session-set-process session process)
    (haskell-process-set-session process session)
```
..this says everything.  The objects are the same thing, and the question is what to do about it.

I propose we cease this schizophrenia, recognize this fact and merge them into one single entity -- let's provisionally call it `proc`, for the lack of a better name.

@gracjan, what do you think?

**Comment by geraldus** [comment]
I think it is good idea.

**Comment by gracjan** [comment]
Good idea. Note that historically there were supposed to be two processes
per session one used while the other was reloading.

I think we should be conceptually open to the idea that we have a foreground
interactive process and a background process that is ghc-mod or ide-backend
based. Someday.

Right now it is good to unify session and process.

**Comment by gracjan** [comment]
@deepfire: Do you have a good plan how to unify session and process? That is a lot of code. Can you list tasks that would lead to the unification?

**Comment by deepfire** [comment]
I don't except one vague idea that -- since `session` has a longer lifetime than `process`, the latter should be merged into the former.

This can be done in two steps:
1. Trivial substitution -- maximum mechanical text transformation, so as not to break anything
2. Perform sweeping simplifications

**Comment by deepfire** [comment]
Progress made in #808.

**Comment by gracjan** [comment]
In the light of intero I think we should skip all major overhauls in interactive mode. Intero itself is such an overhaul.
