### ISSUE TITLE
ghc-mod / stack / dist dir

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-mode#801]
I use `inf-haskell-mode` with GHC 7.10.2 and `ghc-mod` compiled from https://github.com/alanz/ghc-mod/tree/HaRe (basically ghc-mod master but exposing some more internals)

haskell-mode is set up out of the box from spacemacs

I have found that the on the fly checking goes into a continuous cabal configure reload loop as I type unless I make sure that the `./dist` directory exists, either by doing `cabal configure` separately from stack, or by symlinking the output of `stack path --dist-dir` to  `./dist`.

**Comment by gracjan** [comment]
@danielg, @kazu-yamamoto: pinging so that you know there is a potential issue.

**Comment by DanielG** [comment]
I'm not familiar with inf-haskell-mode does that even invoke `cabal configure` somehow?

**Comment by alanz** [comment]
I think it is the ghc-mod using cabal-helper to read its cache, not finding
a dist-dir and doing a configure, which configures in the
.stack-work directory and so is not seen. And then this just repeats.

**Comment by DanielG** [comment]
Oh well that makes sense. But ghc-mod shouldn't go into a loop by itself. Something needs to be invoking it over and over.

**Comment by alanz** [comment]
That is the haskell-mode tie-in. The "loop" is triggered every time the
file is saved, when ghc-mod check is invoked on it.

**Comment by DanielG** [comment]
So what happens when you do it on the command line?

**Comment by gracjan** [comment]
As I understand `ghc-mod` supports `.stack` these days, doesn't it?

If there is something to do on `haskell-mode` then write here and we will reopen this issue.
