### ISSUE TITLE
haskell-interactive-mode-tab not very helpful

### ISSUE THREAD

**Issue by bitemyapp** [haskell/haskell-mode#805]
![screen shot 2015-08-07 at 12 52 01 pm](https://cloud.githubusercontent.com/assets/320177/9142102/2dca0310-3d03-11e5-93f9-13cee9136187.png)

`<TAB>`

![screen shot 2015-08-07 at 12 52 05 pm](https://cloud.githubusercontent.com/assets/320177/9142101/2dc8281a-3d03-11e5-8fa6-3273ab58e758.png)

(that doesn't exist, it's actually `CreativeDS`)

`return`

![screen shot 2015-08-07 at 12 52 09 pm](https://cloud.githubusercontent.com/assets/320177/9142100/2dc7ee5e-3d03-11e5-92f4-d18e47b29ced.png)

It doesn't add the missing bits to the string or replace it in place, just tacks on it. Naturally, that doesn't exist.

**Comment by gracjan** [comment]
@geraldus: This seems to be a completion issue, does it not? There was another report of similar problem happening.

**Comment by geraldus** [comment]
@gracjan yeah, it looks like something was broken at some point, I have some troubles (and time-troubles also), but I'll try to go into details next week.

**Comment by gracjan** [comment]
I wonder if you could write unit tests that catch this sort of problem.

**Comment by vwyu** [comment]
This issue is related to #787.

**Comment by bitemyapp** [comment]
Changed title, it's `interactive`, not `indentation` dang it.

**Comment by gracjan** [comment]
@bitemyapp, might be, can you check if it works now for you?

**Comment by gracjan** [comment]
Looks like fixed.
