### ISSUE TITLE
Refactor load-or-reload

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#807]
User interface around load or reload needs a bit of work:

- [ ] Bind `C-c C-l` directly to `haskell-process-load-file`
- [ ] Rename `haskell-process-reload-file` to `haskell-process-reload`
- [ ] Bind `C-c C-r` directly to `haskell-process-reload`
- [ ] Make sure that in case of a lacking session error message are helpful
- [ ] Mark `haskell-process-load-or-reload` as obsolete
- [ ] Mark `haskell-reload-p` as obsolete

**Comment by deepfire** [comment]
What about it the case when the user doesn't want to think whether he wants to load or reload -- and just wants to "get the latest version into GHC"?

**Comment by gracjan** [comment]
For your viewing pleasure full source of current `haskell-process-load-or-reload` function:

```el
(defun haskell-process-load-or-reload (&optional toggle)
  "Load or reload. Universal argument toggles which."
  (interactive "P")
  (if toggle
      (progn (setq haskell-reload-p (not haskell-reload-p))
             (message "%s (No action taken this time)"
                      (if haskell-reload-p
                          "Now running :reload."
                        "Now running :load <buffer-filename>.")))
    (if haskell-reload-p (haskell-process-reload-file) (haskell-process-load-file))))
```

I do not think this does what you thought it does.

To answer more directly: just use `haskell-process-load` and you will be fine.

**Comment by deepfire** [comment]
Oh my god..
