### ISSUE TITLE
[Discussion] REPL vs IDE

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#809]
We feel that there are two important use cases for a running Haskell interpreter process:

1. REPL-based: load/reload only on command, any interactive command allowed, interpreter window interacts with the user
2. IDE-based: load-on-save/visit, -Wall by default for warning overlays, interacts with user only with predefined set of commands, results are parsed and presented

The discussion was spawned by @deepfire comment: https://github.com/haskell/haskell-mode/pull/795#issuecomment-128534943.

Lets discuss this avenue here.

**Comment by gracjan** [comment]
We have a bit more information:

https://github.com/kazu-yamamoto/ghc-mod/issues/544

In this case we should settle for the following:

1. ghc-mod serves the IDE-mode workflow
2. ghci serves the REPL-mode workflow

**Comment by deepfire** [comment]
Does this mean we will have two haskell processes running?

**Comment by gracjan** [comment]
ghc-mod should be running to get error highlights, navigate to definition,
show types, etc. Repl should be running if you actually want to run the
program.

You are free to skip either of those. Or both.

Those two use cases do not go well together, in my opinion. There are
rumors that ghc-mod should also be able to 'run' things, but I do not know
the details of it.

**Comment by DanielG** [comment]
I'm planning to add interactive code evaluation support to ghc-mod so then both of these would happen at the same time. In ghc-mod we first need to add server-client RPC support though as this would have to run as a separate process probably.

**Comment by gracjan** [comment]
Great to hear!

Would situation like infinite loops, garbage collection, Ctrl-C, terminal
handling not get in the way of the IDE functions of ghc-mod? I would hate
to hang Emacs just because my Haskell program hangs.

**Comment by alanz** [comment]
I think if the right/separate comms channels are established between the ide and ghc-mod this shouldn't be a problem, even if it is one physical channel with streams multiplexed onto it.

**Comment by gracjan** [comment]
I have had bad experiences with such setups. Just look at Chrome and
each-tab-is-a-process-so-we-can-kill-it-separatelly as a very successful
paradigm.

**Comment by DanielG** [comment]
The problem is that the memory consumption of a single ghci process is already insane in the right project and running ghc-mod and ghci at the same time is just a huge waste.

**Comment by gracjan** [comment]
Can't deny that. Well, I just like the feeling of safety when I can kill
this or the other should it go berserk.

**Comment by acowley** [comment]
I'd definitely like it to be one process, but it should of course be a top priority to avoid hanging the editor.

@DanielG is there are branch where you are working on the design of adding interactive evaluation to ghc-mod?

**Comment by gracjan** [comment]
Looks like HIE is better forum to discuss this.
