### ISSUE TITLE
Unicode function symbol and data types

### ISSUE THREAD

**Issue by asr** [haskell/haskell-mode#811]
Let's suppose I want to create a data type `Foo` with two constructors `C1` and `C2`, so I start to type

```haskell
{-# LANGUAGE UnicodeSyntax #-}

data Foo = C1 (Int → Int)
````
then when I press the enter key after `)` I get the error

````
Illegal token : →
````

Haskell-mode version: 20150809.2327

**Comment by gracjan** [comment]
There you go. Thanks for reporting this issue.

**Comment by asr** [comment]
Great! Thanks for fixing the issue.
