### ISSUE TITLE
Use lexical-binding in all source files

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell/haskell-mode#815]
Lexical binding is available since Emacs 24 but can be used in way that is compatible with Emacs 23. Tasks to make this happen:

1. Add `;;; -*- lexical-binding: t -*-` to every `*.el` file.
2. Fix all warnings about unused lexical variables (be removing a variable or prepending underscore to its name).
3. Fix all errors about undefined lexical variables (if any).

Example of current output:

```
In toplevel form:
haskell-modules.el:51:1:Warning: Unused lexical argument `dontcreate'
haskell-modules.el:51:1:Warning: Unused lexical argument `session'
Wrote /Users/kazu/tmp/haskell-mode/haskell-modules.elc
```

**Comment by kazu-yamamoto** [comment]
Or put the prefix of "_". For instance, `foo` to `_foo`.

**Comment by gracjan** [comment]
How did you get this output?

Can you add this mechanism to Makefile so that TravisCI fails if there are
unused variables?

**Comment by kazu-yamamoto** [comment]
The magical command is like this:

```
% emacs -batch -eval "(setq hack-local-variables-hook (lambda () (setq lexical-binding t)))" -eval '(byte-compile-file "x.el")'
```

I put it to Makefile to detect unused variables. It would be nice to add the "detect" target or something to Makefile so that we can find them by "make detect".

**Comment by gracjan** [comment]
Hmm, in this case we could just put `lexical-binding: t` on top of the file in question and have the current Makefile machinery catch this. So we do not need additional target in Makefile.

**Comment by kazu-yamamoto** [comment]
That's one way. But I have not enough experience of `lexical-binding` in Elisp. So, I cannot tell which is better at this moment.

**Comment by kazu-yamamoto** [comment]
BTW. I used to use XEmacs to detect unused variables. But I cannot byte-compile haskell-mode with XEmacs anymore. So, I found the way to detect unused variables with Emacs.

**Comment by deepfire** [comment]
What might look like unused lexical binding can actually be a used dynamic binding..

**Comment by gracjan** [comment]
If this is the case then unused lexical binding should be converted into a
declared and used dynamic binding.
