### ISSUE TITLE
Use prettify-symbol-mode

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#823]
Emacs has its own `prettify-symbol-mode`. Starting with Emacs 25 that mode has `prettify-symbols-compose-predicate` that enables us to conditionally prettify dot depending on context.

Task list:

- [ ] configure `haskel-mode` to use `prettify-symbols-alist` and `prettify-symbols-compose-predicate`
- [ ] enable only in Emacs that has `prettify-symbols-compose-predicate`
- [ ] remove custom machinery that did the composition ourselves

Shedding this code will be very good improvement to general code quality. There are very strange things in there.

**Comment by cpitclaudel** [comment]
By the way, I already set up my .emacs.d code for this here: https://github.com/cpitclaudel/.emacs.d/blob/master/lisp/prettify-alists/haskell-prettify.el

**Comment by gracjan** [comment]
Further research shows that using `prettify-symbols-mode` with `haskell-mode` requires significant hacks to make it aware of all the lexical conventions for Haskell:

1. Know when `.` is an operator and not `forall` separator or module separator.
2. Know when operator starts and where it ends.

This is doable in Emacs 25 thanks to [`prettify-symbols-compose-predicate`](https://lists.gnu.org/archive/html/emacs-devel/2015-08/msg00727.html), but then the truth is that when doing font-lock we have all this information and could do the composition ourselves. It should be more robust that way.

**Comment by cpitclaudel** [comment]
One significant advantage of moving to prettify-symbols-mode is that you'll automatically benefit from the extensions that it will get in the future. A simple example is the new `prettify-symbols-unprettify-at-point` variable:

```
If non-nil, show the non-prettified version of a symbol when point is on it.
If set to the symbol ‘right-edge’, also unprettify if point
is immediately after the symbol.  The prettification will be
reapplied as soon as point moves away from the symbol.  If
set to nil, the prettification persists even when point is
on the symbol.

You can customize this variable.

This variable was introduced, or its default value was changed, in
version 25.1 of Emacs.
```

**Comment by geraldus** [comment]
Oh, great!  @cpitclaudel can I use this (with your code snippet) in Emacs 25.0.91.1?  Also, does it visually breaks layout?

**Comment by gracjan** [comment]
@cpitclaudel: true. I wonder how to make it work. Basically at every symbol haskell-mode would need to check if it really should be composed, that can be achieved in at least two ways:

1. Move back to preceding whitespace, beginning of line or other safe character that will never be part of symbol and to do lexical analysis again. This means a bit of double work.
2. Make haskell-font-lock put additional properties on text marking beginning and end of a lexical token. Then prettify-symbols-compose-predicate could use that information. This means a bit more memory used.

And in any case we will support all of this only if `prettify-symbols-compose-predicate` is supported and that means Emacs 25.

**Comment by geraldus** [comment]
I think extra memory is OK at present days (:

**Comment by gracjan** [comment]
It might me both slower AND extra memory at the same time. Reparsing a line is a no brainer really.

**Comment by gracjan** [comment]
We would have to drop support for Emacs 24, we are not ready to do this yet and won't for years.

**Comment by cpitclaudel** [comment]
No, I don't think you would have to drop support. Assuming you implement this, you would just need to load it conditionally, instead of haskell-mode's custom support, on Emacs 25 only.

**Comment by gracjan** [comment]
It would mean there is no symbol prettyfication on Emacs 24.

**Comment by cpitclaudel** [comment]
No; you can keep the old support, add the new one, and chose which to run dynamically based on Emacs' version.

**Comment by gracjan** [comment]
This is exactly what I'd like to avoid. Pretty symbols aren't worth double implementation and a switching logic (and tests for all of that).
