### ISSUE TITLE
Pull in ghc-mod's ghc-make-indent-shallower/deeper into haskell-mode

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#826]
Do:

- [ ] pull code from https://github.com/kazu-yamamoto/ghc-mod/blob/master/elisp/ghc-indent.el
- [ ] connect to `haskell-mode-map` under keys `C-c <` and `C-c >`
- [ ] use `haskell-indentation-layout-offset` for calculations
- [ ] create a pull request against `ghc-mod` that removes this functionality from there
- [ ] describe new functionality in `doc/haskell-mode.texi`

Mentioning @kazu-yamamoto, so that he knows what we are up to.

**Comment by kazu-yamamoto** [comment]
Assign this job to me. I will send a pull request.

**Comment by gracjan** [comment]
@kazu-yamamoto: Actually I'd like to spare this task for somebody that is a less experienced lisp hacker. What you can do though is to try to find and describe more bite-sized tasks so that other people can jump in and help easily.

**Comment by kazu-yamamoto** [comment]
OK.

**Comment by gracjan** [comment]
@kazu-yamamoto: I see that nobody volunteered. Can you do this one yourself?

**Comment by gracjan** [comment]
Interestingly `haskell-indentation-mode` does indent-rigidly when pressed TAB or S-TAB while a region is active. Is this the same functionality or does ghc-mod add functionality on top of that?

**Comment by gracjan** [comment]
Closing in favor of #949.
