### ISSUE TITLE
haskell-decl-scan-mode fails while updating imenu

### ISSUE THREAD

**Issue by patrickt** [haskell/haskell-mode#832]
As of haskell-mode 20150823.2218, attempting to turn on `haskell-decl-scan-mode` fails with the following message: 

`Error in menu-bar-update-hook (imenu-update-menubar): (void-variable index-imp-alist)`

I'm running emacs 24.5.1 on OS X.

**Comment by ivan-m** [comment]
I've just noticed this as well.

**Comment by gracjan** [comment]
Do you have stack trace?

**Comment by gracjan** [comment]
This:

```
(symbol-value SYMBOL)

Return SYMBOL's value.  Error if that is void.
Note that if `lexical-binding' is in effect, this returns the
global value outside of any lexical scope.
```

And it is used here:
https://github.com/haskell/haskell-mode/blob/master/haskell-decl-scan.el#L502

Any takers to fix this one?

**Comment by vlatkoB** [comment]
Not sure what that `sym` does (doesn't seem to be used anywhere), but I've tried with
```elisp
 (if (boundp sym)
		(set sym (cons (cons name start-pos) (symbol-value sym)))))))
```
and at first glance seems fine. 

I wouldn't like to make a PR as I do not know what that is and are there any hidden consequences.

**Comment by gracjan** [comment]
We need to change this into cond or case.

**Comment by patrickt** [comment]
Thanks so much :heart:
