### ISSUE TITLE
indentation-mode wrong with tuples

### ISSUE THREAD

**Issue by rietmann** [haskell/haskell-mode#835]
The following test example doesn't indent correctly with indentation-mode with the newest version

    main = do
      let (a,b) = (1,2) :: (Int, Int)
          test = 4
                 (c,d) = (4,3)
          ^
          |
          desired indent

I understand that haskell-indentation is undergoing quite some work, but I thought I would add another issue to fix and add to the test suite. Thanks!

**Comment by vwyu** [comment]
It seems that the problem may be related to the type annotiation ending with ")". 

The following test case has the same issue: 

```haskell
main = do
  let a = "1" :: (String)
      b = 2
          c = 3
```

**Comment by vwyu** [comment]
Another test case that fails:

```haskell
main = do
  let a = (putStrLn "1") :: IO ()
      b = 2
          c = 3
```

**Comment by geraldus** [comment]
Nice catch.  @vwyu can you give a try to make a PR fixing this?

**Comment by gracjan** [comment]
Even a pr with just a failing test case would be great. The file to edit is
tests/haskell-indentation-mode-tests.el.
