### ISSUE TITLE
[Discussion] Perhaps tag a release? Monthly releases?

### ISSUE THREAD

**Issue by mdorman** [haskell/haskell-mode#842]
I know there's a temptation to want to work towards being able to declare "stability", but as the monthly activity reports @gracjan puts together highlight so well, the pace of development seems to be picking up---so maybe it's time to just make monthly tags so melpa-stable can allow people to follow along at a slightly slower pace than melpa?

I mean, the monthly report seems like it would be a perfect accompanyment to a tag---here's your new version, here's what's in it.

**Comment by gracjan** [comment]
Good idea!

We could follow similar date-driven releases as rust project does (they have 6 week releases). They opted to have it purely time driven.

I've described how to make a release in [Release Procedure](https://github.com/haskell/haskell-mode/wiki/Release-procedure).

**Comment by gracjan** [comment]
I would not mind somebody taking Release Manager responsibility. Until that happens we need to do releases when it feels safer than usual and that means irregular releases.
