### ISSUE TITLE
Invalid token: = 

### ISSUE THREAD

**Issue by YoEight** [haskell/haskell-mode#844]
Hi,

I updated my haskell-mode with MELPA and I keep having 

```
Invalid token: = 
```

here a snippet

```
loadPhases :: M.Map String (Phase g l) -> [String] -> Maybe [Phase g l]
loadPhases ps = traverse go
```

The syntax looks good to me. That prevents me from editing my buffer. Is it possible to disable such behavior ?  

Thanks for your time.

**Comment by ivan-m** [comment]
Which indentation mode are you using (as that's probably what's causing it)?  Are you doing any other customisations?

**Comment by YoEight** [comment]
I use that one 

`(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)`

I also run 

`(add-hook 'haskell-mode-hook 'haskell-style)`

**Comment by YoEight** [comment]
Thanks !

When that patch would be available on MELPA please ?

**Comment by gracjan** [comment]
Should be already there.
