### ISSUE TITLE
Drop Emacs 23 support

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#847]
We have introduced lexical binding, currently we use it in backward compatible manner. This requires us to jump through some hops to keep the appearances. An example can be found here:

https://github.com/gracjan/haskell-mode/blob/9a6fa5073ac505c41f085d492f39e8ff415a7d13/haskell-indentation.el#L899-L904

```el
  (haskell-indentation-with-starter
   `(lambda ()
      (let ((implicit-layout-active nil))
        (haskell-indentation-separated
         #',parser ,sep ,stmt-sep)))
   end))
```

On top of this Emacs 23 lacks build in `cl-lib` and does not support `package.el` out of the box. Emacs 23 is old: 23.1 was released 2009-07-29, 23.4 was released 2012-01-29.

Emacs 24 and coming Emacs 25 are much better and are easy to install on every supported platform.

Steps to take:
- [x] make sure we do not alienate anybody by dropping Emacs 23
- [x] make last release supporting Emacs 23
- [x] remove TravisCI build for Emacs 23
- [x] make haskell-mode fail if enabled under Emacs less than 24
- [x] add a note in documentation that release 13.18 was the last one to support Emacs 23
- [x] remove other mentions of Emacs 23 from the documentation
- [x] remove Emacs 23 from README
- [x] remove Emacs 23 from wiki

Comments?

**Comment by mrkkrp** [comment]
Of course, let's drop it. I can't image any devoted Emacs user still uses Emacs 23.

**Comment by gracjan** [comment]
There might be people stuck on not-their-own machines without a possibility to upgrade.

But then those would be more of Emacs 22 kind and that is already as good as dead.

**Comment by geraldus** [comment]
There was some activity recently from people using Emacs 23, so let's wait a bit for feedback.

**Comment by gracjan** [comment]
I was thinking about dropping emacs 23 in the beginning of year 2016.

**Comment by gracjan** [comment]
What about XEmacs? Is it active and used?

**Comment by purcell** [comment]
FWIW, `cl-lib` from ELPA works fine with Emacs 23, and plenty of people use `package.el` with Emacs 23. So those shouldn't be relevant factors here. Lexical binding *may* be sufficient justification, but I don't personally find it a compelling argument.

**Comment by gracjan** [comment]
I know it works. It just isn't there by default.

**Comment by gracjan** [comment]
One more reason to use Emacs 24 is `syntax-propertize-function` that is not available in Emacs 23 but is mandatory to properly support Haskell's token lexing for font-lock.
