### ISSUE TITLE
Filling of Haddock comments is broken

### ISSUE THREAD

**Issue by khumba** [haskell/haskell-mode#851]
Set `fill-column` to 80 and try filling the following comment with `M-q`:

    -- | asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf 1234 5678
    -- 90ab
    main :: IO ()

Despite the first line being longer than 80 characters, it won't move `5678` to the next line.  If you remove the leading `|`, or remove the whole `90ab` line, it will wrap, but if the comment already has multiple lines, it won't.

`(haskell-version)` reports `haskell-mode 13.15-git (/home/khumba/.emacs.d/elpa/haskell-mode-20150904.1344/)`, and this is on NixOS 14.12.  The only thing for haskell-mode in my ~/.emacs is:

    (add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)

**Comment by gracjan** [comment]
Thanks for the report.

Can you add this as a test case in tests directory?

**Comment by khumba** [comment]
On Sat, 05 Sep 2015 23:46:07 -0700
Gracjan Polak <notifications@github.com> wrote:

> Thanks for the report.
> 
> Can you add this as a test case in tests directory?

Sure.  Not sure if you wanted a pull request (of course, the test
failed), but see https://github.com/haskell/haskell-mode/pull/852.

**Comment by gracjan** [comment]
@khumba: since there is a nice test case now how about you help us fixing this issue? We have something wrong with the definitions of `paragraph-separate`, `paragraph-start` or `fill-prefix`. More documentation here:

http://www.gnu.org/software/emacs/manual/html_node/emacs/Fill-Prefix.html
http://www.gnu.org/software/emacs/manual/html_node/emacs/Paragraphs.html

**Comment by khumba** [comment]
I'll take a look when I get a minute.  One observation, `-- ^` doesn't trigger the problem.

**Comment by khumba** [comment]
`a3173e9d` is where the problem starts (pull #387).

**Comment by khumba** [comment]
Okay, I think the problem is that paragraph-separate should only match
lines between paragraphs, and not the first line in each paragraph as
well.  When I remove the " *-- |" case from paragraph-separate, my
test case is fixed.  Does this sound sensible?

I'll test this more thoroughly and send another PR.  " *-- \\^" also
needs to be added to paragraph-start.

**Comment by khumba** [comment]
I have no idea why Github decided that there is quoted text in my
previous comment, but it's not...  On the subject of parsing bugs :).

**Comment by ivan-m** [comment]
I normally only see that quoted text in GitHub issues when someone replies via email rather than using the web interface.

**Comment by khumba** [comment]
On Sun, 06 Sep 2015 17:02:50 -0700
Ivan Lazar Miljenovic <notifications@github.com> wrote:

> I normally only see that quoted text in GitHub issues when someone replies via email rather than using the web interface.

But then, there's usually text quoted with a greater than symbol or
the like, but there wasn't in the email I sent.  Guessing it had
something to do with the " *-- \\^"...

...and not the second paragraph...

**Comment by gracjan** [comment]
Please have a look at font-lock. There are four symbols that can start
haddock comment.

**Comment by gracjan** [comment]
The precise definition of a paragraph boundary is controlled by the variables paragraph-separate and paragraph-start. The value of paragraph-start is a regular expression that should match lines that either start or separate paragraphs (see Regexps). The value of paragraph-separate is another regular expression that should match lines that separate paragraphs without being part of any paragraph (for example, blank lines). Lines that start a new paragraph and are contained in it must match only paragraph-start, not paragraph-separate. For example, in Fundamental mode, paragraph-start is "\f\\|[ \t]*$", and paragraph-separate is "[ \t\f]*$".

**Comment by gracjan** [comment]
Fixed by #1037.
