### ISSUE TITLE
Don't override M-n without permission/configuration

### ISSUE THREAD

**Issue by bitemyapp** [haskell/haskell-mode#856]
Making M-n something other than `next-error` is annoying and breaks everything else.
![screenshot from 2015-09-08 15 53 28](https://cloud.githubusercontent.com/assets/320177/9747176/c1971572-5641-11e5-9b95-0635cc9636cb.png)

**Comment by gracjan** [comment]
@deepfire: Serge, can you look at this? I think we have a keybinding conflict here.

**Comment by deepfire** [comment]
@gracjan, there are two questions at play:
1. why `ghc-mod` people get away with that, and `haskell-mode` cant? I think I sort of understand the question
2. what would be the alternative keybinding?

**Comment by deepfire** [comment]
Also:  `M-n` and `M-p` were picked /exactly/ because they simulate `next-error`/`previous-error`.

@bitemyapp, what is the clash with?

**Comment by bitemyapp** [comment]
@deepfire flycheck, which I use for hlint / type errors.

>why ghc-mod people get away with that, and haskell-mode cant? I think I sort of understand the question

They shouldn't be doing it either, but I stopped using ghc-mod because how fragile it was already.

**Comment by gracjan** [comment]
Flycheck uses `C-c ! n` and `C-c ! p`.

http://www.flycheck.org/manual/0.23/Navigating-errors.html

**Comment by bitemyapp** [comment]
@gracjan right but it works if you invoke next-error which is what M-n should be assigned to by default. Flycheck uses those shortcuts in part so it _doesn't_ clobber the default.

**Comment by gracjan** [comment]
I see nothing about next-error  in flycheck documentation.

Make-mode rebinds M-n for its own purpose, ghc-mod does the same. Why is it
okay for them and at the same time not okay for Haskell-mode?

**Comment by deepfire** [comment]
@bitemyapp, do I understand it right, that flycheck somehow integrates into `next-error`?

**Comment by ivan-m** [comment]
From what I understood from bytemyapp, flycheck does *not* integrate next-error, and specifically uses keybindings that don't override the ones used by next-error.

Indeed, if I try and use flycheck I can't get `M-n` to do anything.

When I look do a `describe-function next-error`, I'm told that the keybindings are ```C-x `, M-g n, M-g M-n```.

Furthermore, I know at least magit re-uses `M-n`.

According to the [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation-Mode.html), `M-n` is used for `compilation-next-error`, and seems to be only enabled in the `compilation-mode` (including `grep-mode`).

**Comment by gracjan** [comment]
Issue #821 should get this usability part fixed as a side effect.

**Comment by purcell** [comment]
Yep, I use M-n and M-p for other things, so I don't like that they're overridden. I can (and have) worked around that in my own config but in fact, since I use `flycheck` for compiler warnings, I'd actually like to be able to disable all the special overlay and fringe handling which is currently unconditionally triggered by loading the current file. But that may be a separate issue.

**Comment by purcell** [comment]
I can imagine a `haskell-after-load-hook`, such that functions added to this hook would be passed a list of errors/warnings etc. The default hook list would include a function which marks up the current buffer with overlays/fringe annotations etc. Then I could disable that hook, or add my own handlers as desired.

**Comment by geraldus** [comment]
> imagine a haskell-after-load-hook

Sounds good.

**Comment by bitemyapp** [comment]
@gracjan @deepfire where's this at?
