### ISSUE TITLE
There is no option package-archives

### ISSUE THREAD

**Issue by k-bx** [haskell/haskell-mode#857]
I installed fresh emacs24-nox, ran it, wanted to install haskell-mode, due to instructions:

> To install haskell-mode you need to add a package archive repository that distributes haskell-mode. Execute

> M-x customize-option RET package-archives

But there is not option `package-archives`. Maybe correct would be to advice to `customize-variable RET package-archives`?

**Comment by syohex** [comment]
Please add `(require 'package)` to your configuration file(`~/.emacs.d/init.el`) and retry.

See also
- http://ergoemacs.org/emacs/emacs_package_system.html
- http://emacswiki.org/emacs/ELPA

**Comment by k-bx** [comment]
@syohex Should we update README with this info? These instructions are the very first thing you see at https://github.com/haskell/haskell-mode

// btw, using `customize-variable` worked for me.

**Comment by syohex** [comment]
> Should we update README with this info?

Yes. It is good for Emacs newbies.

**Comment by gracjan** [comment]
README.md should be as newbie friendly as possible. By all means please
improve as much as you can and send a pull request.

Note that our users are programmers so we should give them a hint that we
very eagerly accept contributions.

**Comment by gracjan** [comment]
Per Emacs documentation: customize-variable is an alias for
`customize-option' in `cus-edit.el'.

**Comment by k-bx** [comment]
@gracjan thank you, it is indeed weird then. I confirm they do seem equal, probably something happened during restart, and this variable occurred.

Removing `~/.emacs` and `~/.emacs.d` removes this variable from options again (from both commands). I'll try to observe further.

**Comment by k-bx** [comment]
Adding `(require 'package)` helps (adds this variable to `customize-option/customize-variable` list), so maybe it should be added to instructions.

**Comment by gracjan** [comment]
If this is so complicated we should just point people to official MELPA
documentation that says to to make use of melpa or melpa-stable.
