### ISSUE TITLE
haskell-simple-indent-mode non-responsive

### ISSUE THREAD

**Issue by ghost** [haskell/haskell-mode#867]
When I enable haskell-simple-indent-mode, and attempt to do anything other than indent in haskell mode, emacs becomes non responsive.  Hitting C-g will cause it to interrupt, and throw an error regarding undo and the undo size, when I finally get my input in the buffer, it appears backwards.  `print` will appear as `tnirp`.

The *Warnings* buffer shows the following:

    Warning (undo): Buffer `*Org Src honors-cs108.org[ haskell ]*' undo info was 15968301 bytes long.
    The undo info was discarded because it exceeded `undo-outer-limit'.

    This is normal if you executed a command that made a huge change
    to the buffer.  In that case, to prevent similar problems in the
    future, set `undo-outer-limit' to a value that is large enough to
    cover the maximum size of normal changes you expect a single
    command to make, but not so large that it might exceed the
    maximum memory allotted to Emacs.

    If you did not execute any such command, the situation is
    probably due to a bug and you should report it.

    You can disable the popping up of this buffer by adding the entry
    (undo discard-info) to the user option `warning-suppress-types',
    which is defined in the `warnings' library.

Any suggestions/recommendations?

**Comment by gracjan** [comment]
Does this happen in source code directly or only in org mode embedded
source?

**Comment by e3home** [comment]
Only in the embedded source.  Indentation doesn't seem to work at all for me however (I can't just have an expression at the start of the line, it's always insistent on having it indented to some level (generally 2)).  I'm not entirely sure why this is.

**Comment by ivan-m** [comment]
Probably an interaction between org-mode's tabbing and haskell-mode.  What does `C-h k <tab>` say?

**Comment by e3home** [comment]
Currently, `yas-expand`.  After disabling yasnippet, it shows as `indent-for-tab-command`.  The use of `haskell-simple-indent-mode` bogs down the emacs process, I've switched to `haskell-indent-mode`, but still have the issue of incorrect indentation.

And to the org-mode tabbing issue, I enter the code block using `C-c ;`, and edit it directly in haskell-mode.

**Comment by gracjan** [comment]
We had some reports about yas causing issues. You may want to search archives. AFAIK we weren't able to find what is going on.

Having said that can you try `haskell-indentation-mode`?

**Comment by e3home** [comment]
Sure.  It doesn't lock things up,  but I still get weird indentation.  I.E.:

    print ""
      print ""

Even though I'd rather have something like

    print ""
    print ""

And actually, for every character I type, it indents a little bit more.

**Comment by gracjan** [comment]
Can you try again with 'haskell-indentation-mode'?

**Comment by e3home** [comment]
I did.  That's when I the get wonky indentation.  No idea why, no messages printed about it.  I disable yas-minor-mode in haskell-mode, so that shouldn't be causing a problem.

**Comment by gracjan** [comment]
Staircase used to be due to electric-indent-mode, but that one should be
disabled by default.

Can you check if you have electric-indent-mode enabled by chance?

**Comment by e3home** [comment]
I do have it enabled (well, did).  I went ahead and disabled it in Haskell mode, and it works as expected.  Thanks.

**Comment by gracjan** [comment]
It should not be enabled as we take steps to disable it. Do you know why
did you have had it enabled?

**Comment by e3home** [comment]
It's enabled globally.  Adding a hook function to purposely disable it and `aggressive-indent-mode` fixed it.

**Comment by gracjan** [comment]
What is aggressive-indent-mode?

**Comment by e3home** [comment]
An add-on to electric-indent-mode.  It indents stuff even more automatically than aggressive indent mode.  I use it when writing lisp (which I do a lot).

**Comment by gracjan** [comment]
If you write a lot of lisp then feel invited to helping us with
haskell-mode. We could use an experienced lisper.

**Comment by e3home** [comment]
Wrong kind of lisp.  I do a lot of DB and web stuff, emacs lisp is not my forte.

**Comment by gracjan** [comment]
Emacs lisp is tiny compared to any other lisp. Also Emacs as an execution
environment has only tiny amount of functions to use and quirks to learn.
It all fits nicely in the head at once.

**Comment by e3home** [comment]
Might as well try, but as it is, I'm learning haskell, so having someone who doesn't know the language working on its major mode doesn't seem like a good idea...

**Comment by gracjan** [comment]
We have quite many obvious tasks and bugs. Just look at the
well-defined-task label:

https://github.com/haskell/haskell-mode/issues?q=is%3Aopen+is%3Aissue+label%3Awell-defined-task

**Comment by e3home** [comment]
I'll think about it, but I need to take care of other things (school) first.  And I'd like to get access to my primary GH account first anyways.
