### ISSUE TITLE
Invalid Token :|

### ISSUE THREAD

**Issue by YoEight** [haskell/haskell-mode#878]
Hi, 

I'm not sure if I should have put that one on the previous ticket I made. Frankly, I have a lot of those in various situations, so please tell me how would be the best way to report those.

In this case, here's the code snippet:

```haskell
data Request r
    = forall a. New (Operation 'Init a) (Either OperationError a -> r)
      -- ^ Register a new 'Operation'.
    | Pkg Package
```

The error disappears when I get rid of the comment.

Thanks for your time.

**Comment by gracjan** [comment]
Really good report. Keep those coming.

Are you able to turn this into a unit test case in the tests directory?
