### ISSUE TITLE
Standard Keybindings not available

### ISSUE THREAD

**Issue by e3home** [haskell/haskell-mode#879]
The standard keybindings as shown on the haskell-wiki page are not available.  When using `C-c C-|`, I get the following error: `C-c C-| is undefined`.

Any help would be appreciated.

**Comment by gracjan** [comment]
This is for haskell-indent-mode not haskell-indentation-mode.

**Comment by swflint** [comment]
OK.  Thanks.  You might want to make that clear on the wiki page.

**Comment by gracjan** [comment]
Wiki page content should be moved to documentation proper and all such discrepancies should be killed in the process.

I'll close this issue.
