### ISSUE TITLE
parse-error "Expecting then" "Expecting else" DoAndIfThenElse in indentation

### ISSUE THREAD

**Issue by k-bx** [haskell/haskell-mode#884]
For this code:

```haskell
main :: IO ()
main = do
    if True
    then putStrLn "True"
```

when you press enter after "True" – you get an error:

let: No catch for tag: parse-error, "Expecting then"

**Comment by k-bx** [comment]
Added a PR with a failing test

**Comment by gracjan** [comment]
This seems to be an instance of [DoAndIfThenElse](https://ghc.haskell.org/trac/haskell-prime/wiki/DoAndIfThenElse).

**Comment by k-bx** [comment]
@gracjan yeah, seems like it. All compilers support it now with no flags needed, so would be nice for haskell-mode to support it, since it feels not right when code compiles, while indentation fails to work.

**Comment by gracjan** [comment]
The way this extension is defined with this semicolons out of nowhere is
super strange. How to make indentation use this syntax will require some
ingenuity.

**Comment by gracjan** [comment]
Actually we have this reported already as #321.
