### ISSUE TITLE
Is it possible to use ghci-ng with "stack-ghci" haskell-process-type?

### ISSUE THREAD

**Issue by rrnewton** [haskell/haskell-mode#889]
I'm trying to get the `:type-at` based `haskell-process-do-type` working with stack based projects.

**Comment by geraldus** [comment]
I'm missing this feature too!

**Comment by gracjan** [comment]
I do not see a fundamental problem why this should not work. What does `*haskell-process-log*` say?

**Comment by rrnewton** [comment]
Well, I can see that `*haskell-process-log*` says haskell-mode is calling `stack ghci`.

But, based on `stack ghci --help`, I don't see any way to change the ghci implementation to use `ghci-ng`.  It *does* have a `--with-ghc` option, but `stack ghci --with-ghc=ghci-ng` is bogus because ghci-ng isn't a full command line replacement for `ghc`.

**Comment by gracjan** [comment]
Sounds like an issue report for stack.

When you report it there can you post a link here so we know when it is
ready?

**Comment by chrisdone** [comment]
`with-ghc` is the proper flag, it's just poorly named. I copied this name from `cabal-repl`. See comment here: https://github.com/commercialhaskell/stack/issues/1024#issuecomment-142208475

I noticed recently that `stack-ghci` was added as a supported REPL type, so probably there can be a variable for specifying extra args like in the GHCi case, or otherwise use the wrapper. E.g.

``` lisp
(setq haskell-process-wrapper-function
                    (lambda (args)
                       (append args (list "--with-ghc" "ghci-ng"))))
```

**Comment by rrnewton** [comment]
Wow, great, that works.  

In this case I had to modify `haskell-process-args-stack-ghci` to include the `--with-ghc` option, but now I'm in Haskell IDE paradise being able to use both *stack* and errors right in my editor buffer...

**Comment by da-x** [comment]
The version of `ghci-ng`  needs to match the version of GHC, and when you have both 7.10.3 and 7.10.2 as compilers under `.stack`, then `ghci-ng` can't just sit in the `~/local/.bin`, it needs to sit as two different compiled versions, under `~/.stack/programs/x86_64-linux/ghc-7.10.2/bin` and `~/.stack/programs/x86_64-linux/ghc-7.10.3/bin`.

My question is, would it our work out of the box for `haskell-mode`, or do we need to do something else? Where's the best place to put the `ghci-ng` exe therefore?
