### ISSUE TITLE
Indentation is broken

### ISSUE THREAD

**Issue by Tekkkz** [haskell/haskell-mode#890]
I have following code:
```haskell
sumtorial :: Integer -> Integer
sumtorial 0 = 0
sumtorial n = n + sumtorial (n-1)

hailstone :: Integer -> Integer
hailstone n
  | mod n 2 == 0 = div n 2
  | otherwise    = 3*n + 1

sumPair :: (Int,Int) -> Int
sumPair (x,y) = x + y
```
I have in my `~/.emacs` following line:
`(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)`

And now, when I use tab at line 7, the indentation of 2 spaces gets f*cked up to 4 spaces. When i press return at the end of line 8, im indented at the new line by 19 characters.

But now the funny thing is, when I start emacs with `-q` and do `M x turn-on-haskell-indentation` then, at least the problem in line 7, is away.

So how to fix my settings?

**Comment by gracjan** [comment]
Nice catch. This should work as you have it here. Can you debug this
further?

**Comment by Tekkkz** [comment]
Oh. There was a bug. I reinstalled `haskell-mode` now it works. Thanks :D
