### ISSUE TITLE
Illegal tokens and QuasiQuotes

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#894]
It seems that `haskell-indentation` also searches QuasiQuotes for keywords:

```haskell
{-# LANGUAGE QuasiQuotes #-}

test = [randomQQ| This is a quasiquote with the word in |]
```
Hitting Enter at the end of the line gives `Illegal token: in`.

(It seems that GitHub's highlighter also doesn't understand QuasiQuotes :p)

**Comment by mgsloan** [comment]
I've run into this too.  IMHO such exceptions shouldn't cause enter to fail - there should be a fallback behavior.  It's very frustrating when bugs prevent me from typing something.

**Comment by gracjan** [comment]
Can you create a pull request with a failing test case?

**Comment by ivan-m** [comment]
I'll try to do so tomorrow when I'm back at work (as that's where I've got the actual code that this has a problem with).

**Comment by vagifverdi** [comment]
Looks like it is fixed. I just git pull today and now enter after quasiquotes works fine.
