### ISSUE TITLE
Haskell Interactive Shell Stuck in Insert Mode (spacemacs)

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#895]
`haskell-interactive-mode` somehow interacts badly with spacemacs:

https://github.com/syl20bnr/spacemacs/issues/445

**Comment by PierreR** [comment]
I would close this. I am personally OK with the workaround as described here:
https://github.com/syl20bnr/spacemacs/issues/3271

As I see it,  the link issue is not really a `haskell-mode` issue
