### ISSUE TITLE
Syntax highlighting: no difference between data constructor and type ?

### ISSUE THREAD

**Issue by PierreR** [haskell/haskell-mode#898]
I am using emacs (spacemacs). I cannot see a difference between type and data constructor.
For instance in the following snippet I would expect `Foo` to be displayed differently than `Int`.
```
data Query = 
  Foo Int
  | ...
```
Am I missing a setting? Is this a problem with the theme I am using (I have tried a couple) ?

**Comment by gracjan** [comment]
This functionality does not exists... yet. Plan how to implement it is described in #899.

**Comment by gracjan** [comment]
Closing in favor of #899.
