### ISSUE TITLE
Disable Indentation

### ISSUE THREAD

**Issue by jbsiddall** [haskell/haskell-mode#90]
Hi,
Is there anyway you can disable the haskell-mode indentation, so why you hit TAB it inserts a tab characters, no spaces, no aligning with previous line?

**Comment by rightfold** [comment]
@ivan-m haskell-simple-indent does more than just inserting tabs.

**Comment by mx4492** [comment]
The fix mentioned in https://github.com/haskell/haskell-mode/issues/90#issuecomment-15070662 did not work for Emacs 24.5.1 and haskell-mode 20160117.1345. The default hook does not have `turn-on-haskell-indent` in there anymore. Instead, when haskell-mode is loaded it calls `(haskell-indentation-mode)` by default (expecting it to be overridden by items in the hook). 

The following alternative worked for me -- it explicitly disables the `haskell-indentation-mode` minor mode.
```
(add-hook 'haskell-mode-hook (lambda ()
            (make-local-variable 'tab-stop-list)
            (setq tab-stop-list (number-sequence 4 80 4))
            (setq indent-line-function 'indent-relative)
            (haskell-indentation-mode 0)))
```

**Comment by jarmitage** [comment]
Hi, I've tried everything listed here but cannot get haskell-indentation-mode to turn off by default. Any other ideas?

**Comment by gracjan** [comment]
`(haskell-indentation-mode -1)`

**Comment by jarmitage** [comment]
@gracjan I'm afraid that doesn't work

**Comment by listx** [comment]
Too bad that the fix I mentioned does not work any more; I have since moved on to my own minor mode called "kakapo-mode" (it's on MELPA) that handles indentation for me, so I cannot really comment how/why my fix from 3 years ago (yikes!) doesn't work any more.
