### ISSUE TITLE
haskell-session-installed-modules and out-of-date caches

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-mode#901]
When the cache to a pkgdb is out of date, then `ghc-pkg dump` will report:

```
WARNING: cache is out of date: /usr/local/Cellar/ghc/7.10.2/lib/ghc-7.10.2/package.conf.d/package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
```
(I think to stderr, but I forgot to check this whilst this was still the case.)

`haskell-session-installed-modules` will blindly try and split this string and thus each word in this error message will be returned as being a "module".

**Comment by gracjan** [comment]
Emacs merges stderr and stdout. To ignore stderr we either need a wrapper or there is a flag in emacs to put stderr in a file. Later we could ignore and delete the file. Or show a message buffer.

**Comment by gracjan** [comment]
Didn't mean to close this.
