### ISSUE TITLE
Mac OS X El Capitan: no such file or directory, ghci

### ISSUE THREAD

**Issue by r3ticuli** [haskell/haskell-mode#908]
After installing OS X El Capitan, the ghci command in my terminal no longer worked. I added symlinks ghci and ghc into /usr/local/bin and can now use it in my terminal like I used to, but haskell-mode is not picking up the links. Is there a way to redefine the path to ghci/ghc for haskell-mode?

**Comment by ivan-m** [comment]
Is `/usr/local` in your `$PATH`? Also have a look at https://github.com/haskell/haskell-mode/wiki/PATH

**Comment by tinoheth** [comment]
I came across here because of a complete unrelated issue, but I guess if you have a script calling a script, there are some sandbox-issues... :-(

**Comment by ivan-m** [comment]
@tinoheth maybe you want to use `cabal exec` or `cabal run`.

**Comment by tonyday567** [comment]
try the exec-path-from-shell module.  Or edit `exec-path` directly.  This variable is emacs own path for subprocesses.

**Comment by gracjan** [comment]
If this happens again please report here and we will reopen the issue.
