### ISSUE TITLE
GHCi multiline prompt (`:set prompt2`) support

### ISSUE THREAD

**Issue by konn** [haskell/haskell-mode#915]
GHCi has multiline input mode which can enabled by `:set +m` or `:{` and `:}`.
For example:

```haskell
ghci> :set +m
ghci> let a = 12
ghci|     b = 42
ghci| 
ghci>
```

`:{` version:
```haskell
ghci> :{
ghci> let a = 12
ghci|     b = 42
ghci| :}
ghci>
```

Prompt for multiline input (here, `ghci| `) can be set by `:set prompt2 "ghci| "`, but we don't have any configuration item to set `prompt2` in `haskell-mode`.
This results in the following not-so-useful-for-indenting looking:

```haskell
λ> let a = 12
ghci|     b = 42
ghci| 
λ> :{
λ> let a = 12
ghci|     b = 42
ghci| :}
λ> 
```

So we need the way to `:set prompt2`.

**Comment by gracjan** [comment]
Note that lambda is special and is detected by `interactive-haskell-mode` as command separator.

**Comment by issue-dispenser** [comment]
Doesn't `interactive-haskell-mode` use a defcustom for the prompt? What makes it special? I noticed that it's hardcoded into `inferior-haskell-mode` though.

What's stopping `haskell-mode` from using a new defcustom for `prompt2`?

**Comment by gracjan** [comment]
What has prompt to do with spaces?

**Comment by issue-dispenser** [comment]
Different issue.

**Comment by fice-t** [comment]
@konn You can now change it using the variable `haskell-interactive-prompt2`. The default is `λ| `.
