### ISSUE TITLE
"Expecting else" error message

### ISSUE THREAD

**Issue by cjauvin** [haskell/haskell-mode#917]
I'm running `haskell-mode` version `20151003.0` with Emacs 24.5 on OSX, and I'm new to Haskell (so please bear with me as this might well be a non-issue, caused by my ignorance). I noticed a weird behavior with nested `do` blocks inside an `if` expression, which this simple function demonstrates:
```haskell
test :: Bool -> IO ()
test b = do
  if b then do
    putStr "hello "
    putStrLn "world"
  else do
    -- Starting from this line I get an "Expecting else" message in
    -- tbe minibuffer when I try to insert a newline by pressing
    -- <enter> (except inside the comments)
    putStr "bye "
    putStrLn "world"
```

**Comment by gracjan** [comment]
This is a known extension to Haskell language that needs to be implemented in `haskell-indentation`. Thanks for reporting this, we have already #884 so it is tracked.
