### ISSUE TITLE
Support commas in first indentation column

### ISSUE THREAD

**Issue by arybczak** [haskell/haskell-mode#918]
Consider the following code:
```haskell
data T = T {
  foo :: String
, bar :: String
}
```

After putting the closing bracket you get the error message from the title.

**Comment by gracjan** [comment]
`haskell-indentation` finds first line that starts at column zero above the line you are trying to indent. So it sees only this fragment:

```haskell
, bar :: String
}
```

and of course gets confused. What is the idea of putting commas in the first column? For now use one of the following styles:

```haskell
data T = T {
    foo :: String
  , bar :: String
  }
```

or

```haskell
data T = T
  { foo :: String
  , bar :: String
  }
```

or

```haskell
data T = T {
  foo :: String,
  bar :: String
  }
```

**Comment by arybczak** [comment]
for new code sure, but the problem is that it breaks if such code is already there. This is valid Haskell and indentation mode should work with it.

**Comment by mgsloan** [comment]
Agreed, to me it's crazy that an indentation mode would throw an error and not have a fallback behavior.  Like syntax highlighting, this stuff should be a "best effort" thing, and not a syntax parser that that attempts to validate your Haskell (particularly if it doesn't accept valid Haskell...).

**Comment by gracjan** [comment]
I agree that `haskell-indentation` should never throw a parser error. I do not agree that `haskell-indentation` should throw and swallow exceptions. `haskell-indentation` should do something sensible with any stream of characters, original authors stood on the position that only valid Haskell should be supported. We need to backtrack that decision.

**Comment by mgsloan** [comment]
As a temporary solution, how about catching exceptions and printing them, and then falling back on some simple indentation strategy like "same column as start of current line".
