### ISSUE TITLE
haskell-process changes the directory which causes loaded modules to be unloaded

### ISSUE THREAD

**Issue by 11Kilobytes** [haskell/haskell-mode#923]
When you use stack-ghci as your haskell-process-type, I think that haskell-process ought not to change directories after loading the repl, since all modules of the project are loaded correctly. 

There is no advantage to changing directories for stack-ghci and cabal-repl.

**Comment by 11Kilobytes** [comment]
There is no advantage to changing directories for stack-ghci and cabal-repl.

**Comment by gracjan** [comment]
I think you are right. Can you provide a pull request?

**Comment by 11Kilobytes** [comment]
Sure, I'll do that right now.
