### ISSUE TITLE
haskell-process.el binds `C-c c` but should not

### ISSUE THREAD

**Issue by jwiegley** [haskell/haskell-mode#926]
According to Emacs developer guidelines, modes should not bind the lowercase alphabetic space within the `C-c` keymap.  This space is reserved for users (I have it bound to `compile`, for example, so that it works in all buffers).  `haskell-process.el` binds this to `haskell-process-cabal`.  This should be changed to some other binding, such as `C-u C-c C-c`.

**Comment by gracjan** [comment]
Agreed.

Do you have a better suggestion what to bind this functionality to?

**Comment by jwiegley** [comment]
If `C-c C-c` is the "quick" version, meant to build, then `C-u C-c C-c` would be the "long" version, meant to refine interaction with Cabal.  This would follow typical Emacs behavior based on several other packages.

Other than that, `C-c C-X`, where X is any letter not yet spoken for.

**Comment by gracjan** [comment]
Can you submit a pull requests that fixes this problem?

**Comment by jwiegley** [comment]
@gracjan I don't use the current version of `haskell-mode`, and I'm absolutely buried under my todo list.  I'm afraid the only contribution I can offer to make the problem and a potential solution known.

**Comment by gracjan** [comment]
Thanks for your help. It counts.

The proper solution needs to wait on a volunteer.

**Comment by vwyu** [comment]
I fail to see any binding in haskell-process.el. 

It seems that haskell.el binds C-c C-c to haskell-process-cabal-build.

**Comment by ivan-m** [comment]
I think haskell-mode used to make that binding (and it was recommended), but it now seems to be `C-c C-x`.

**Comment by jwiegley** [comment]
Ah!  Excellent.  Yes, it is due to my using an older version to work around the current haskell-indentation bug:

``` elisp
    (define-key map (kbd "C-c c") 'haskell-process-cabal)
```
