### ISSUE TITLE
Simple indent vs haskell-indentation when using autofill on comments

### ISSUE THREAD

**Issue by joe9** [haskell/haskell-mode#932]
Hello,

I use autofill on comments. When a comment is more than 70 characters long, autofill wraps the line into a different line and adds the "--" to the beginning of the new line.

For example
-- This is a comment line in haskell code and it is longer than 70 characters. After the 70th character, the line becomes 

is converted to 

-- This is a comment line in haskell code and it is longer than 70 characters.
-- After the 70th character, the line becomes 

This is the code that does the above:
(defun haskell-init::comment-auto-fill ()
  (setq-local comment-auto-fill-only-comments t)
  (auto-fill-mode 1))
(add-hook 'haskell-mode-hook 'haskell-init::comment-auto-fill)

For some reason, the above indentation works fine with simple-indent but not with haskell-indentation.

With haskell-indentation, the above converted line is:
-- This is a comment line in haskell code and it is longer than 70 characters.
After the 70th character, the line becomes 

Thanks

**Comment by gracjan** [comment]
Thanks for the report.

Auto fill functionality should be part of haskell-mode. Why is it in any
indentation, indent or simple indent is beyond me. Are you able to look at
this yourself and report back what is going on here?

**Comment by vwyu** [comment]
I seem to have the same problem also with simple indent. 

When I turn on haskell-simple-indent-mode and auto-fill-mode, I get:

-- This is a comment line in haskell code and it is longer than 70 characters.
After the 70th character, the line becomes

**Comment by joe9** [comment]
@vwyu are you sure about that behaviour when using haskell-simple-indent? That happens when I am using haskell-indentation to me.

**Comment by gracjan** [comment]
To me it happens all the time, in every indentation mode and when indentation modes are disabled. I never got the proper functionality running,

**Comment by gracjan** [comment]
Okay, I see it now. If haskell-indentation was enabled once for buffer then it breaks the auto-fill functionality forever.

**Comment by gracjan** [comment]
Note that for some reason it does not work for multiline comments `{- ... -}` as it breaks them this way:

```
{- sdfg sdfgsdfgsdfg sdg sdfg sdfg sd gfser twer twer twedfs gsd
{- sdfg wer twr twert wert fbdfh  bfgbdfg ert hrt rt ertgdg dfghdf g
```

Not good. Do we have proper `comment-start` and friends?

**Comment by vwyu** [comment]
@joe9 I think the reason I had the same issue with haskell-simple-indent was because I enabled it after starting with haskell-indentation-mode (as @gracjan explained). 

@gracjan's change in #945 solves the issue for me.

**Comment by gracjan** [comment]
Note that the part `(setq-local comment-auto-fill-only-comments t)` will be default in `haskell-mode` and therefore no need to set it. See #945 for details.

**Comment by joe9** [comment]
@gracjan Thanks, now the comments are automatically getting filled.

I had to comment out the line: (define-key haskell-mode-map (kbd "<return>") 'haskell-simple-indent-newline-same-col) to get the <return> after the comments to work without error. Is that expected?

Another issue that I noticed is that though I have auto-fill-mode enabled, I had to enable auto-fill-mode again after opening the haskell file. Not sure if haskell-mode resets auto-fill-mode to disabled.

**Comment by gracjan** [comment]
Hmm, I do not see where you get that keybinding. Where did you comment out
it from?

Note that auto-fill is per buffer that is disabled by default. You can use
`add-hook` on `haskell-mode-hook` to enable it whever haskell-mode is
enabled, I do not think there is a globa switch to enable auto-fill
everywhere.

**Comment by joe9** [comment]
@gracjan Thanks. I am not sure where I got that snippet from.

As an fyi, below is my haskell config. If you find anything weird or missing, Could you please let me know?

Thanks again

```
;; haskell-init.el --- Haskell editing configuratio -*- mode:emacs-lisp; lexical-binding:t -*-

;; Keywords: lisp, convenience

;;; Commentary:

;; Configuration for editing haskell files

;;; Code:

;; Ignore compiled Haskell files in filename completions
(add-to-list 'completion-ignored-extensions ".hi")

(require 'package-init)
(package-init:load
 '(
   s ;; required by f
   epl ;; required by pkg-info
   pkg-info ;; required by projectile and flycheck
   dash ; required by flycheck-haskell
   f ; required by flycheck-haskell
   let-alist ; required by flycheck-haskell
   flycheck
   flycheck-haskell

   haskell-mode
   ))

(require 'flycheck)
(require 'flycheck-haskell)
(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup)

(require 'haskell-mode)
(require 'haskell-interactive-mode)
(require 'haskell-process)

;; TODO company-ghc usage for autocompletion

;; haskell-mode setup
(setq haskell-stylish-on-save t
      haskell-tags-on-save t
      ;;       haskell-notify-p t
      haskell-process-suggest-remove-import-lines t
      haskell-process-auto-import-loaded-modules t
      haskell-process-log t)

;; got the below from haskell-mode/examples/init.el
;; https://github.com/haskell/haskell-mode/blob/master/examples/init.el
(add-hook 'haskell-mode-hook 'haskell-hook)
(add-hook 'haskell-cabal-mode-hook 'haskell-cabal-hook)

;; Haskell main editing mode key bindings.
(defun haskell-hook ()
  (imenu-add-menubar-index)
  (turn-on-haskell-decl-scan)
  (turn-on-eldoc-mode)
  (turn-on-haskell-doc)
  ;; (turn-on-haskell-unicode-input-method)
  ;; (capitalized-words-mode)
  (auto-fill-mode 1)
  (interactive-haskell-mode)

  ;; haskell-indentation does not work with autofill on comments
  ;;   https://github.com/haskell/haskell-mode/issues/932
  (turn-on-haskell-indentation)

  ;; from https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-Setup
  (define-key haskell-mode-map (kbd "C-c C-l") 'haskell-process-load-or-reload)
  (define-key haskell-mode-map (kbd "C-`") 'haskell-interactive-bring)
  (define-key haskell-mode-map (kbd "C-c C-t") 'haskell-process-do-type)
  (define-key haskell-mode-map (kbd "C-c C-i") 'haskell-process-do-info)
  (define-key haskell-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
  (define-key haskell-mode-map (kbd "C-c C-k") 'haskell-interactive-mode-clear)
  (define-key haskell-mode-map (kbd "C-c c") 'haskell-process-cabal)
  (define-key haskell-mode-map (kbd "SPC") 'haskell-mode-contextual-space)

  )

;; Useful to have these keybindings for .cabal files, too.
(defun haskell-cabal-hook ()
  (define-key haskell-cabal-mode-map (kbd "C-`") 'haskell-interactive-bring)
  (define-key haskell-cabal-mode-map (kbd "C-c C-k") 'haskell-interactive-mode-clear)
  (define-key haskell-cabal-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
  (define-key haskell-cabal-mode-map (kbd "C-c c") 'haskell-process-cabal))


(provide 'haskell-init)
;;; haskell-init.el ends here

```
