### ISSUE TITLE
haskell-process-load-or-reload and haskell-interactive-switch-back

### ISSUE THREAD

**Issue by d12frosted** [haskell/haskell-mode#955]
Hey,

I like to use `haskell-process-load-or-reload` function because it switches to REPL and loads buffer into it. The only thing I don't like about it - it doesn't play well with `haskell-interactive-switch-back` function. What do you think about reusing `haskell-interactive-switch` in `haskell-process-load-or-reload`?

**Comment by gracjan** [comment]
Note also #807.

**Comment by d12frosted** [comment]
Oh nice! Probably I would give it a try! :smile:

**Comment by gracjan** [comment]
@bergey, can you take a look at this one? I'm not sure what is missing here really...
