### ISSUE TITLE
Wiki documentation out of sync ?

### ISSUE THREAD

**Issue by PierreR** [haskell/haskell-mode#968]
I was willing to contribute to some documentation but [the online wiki](https://github.com/haskell/haskell-mode/wiki/Indentation) looks out of sync with [its source](https://github.com/PierreR/haskell-mode/blob/master/doc/haskell-mode.texi).

To illustrate, `haskell-indentation-show-indentations` for instance still appears in the wiki doc but does not seem to be anywhere in the source file

**Comment by gracjan** [comment]
Manual is here:

http://haskell.github.io/haskell-mode/manual/latest/

Material from the wiki should be moved to official manual in
haskell-mode.texi.


2015-10-28 9:58 GMT+01:00 Pi3r <notifications@github.com>:

**Comment by PierreR** [comment]
Ah right. Can I at least update the link from the README page for the real manual if this can help.

**Comment by gracjan** [comment]
Can you help with moving more content from the wiki to official manual
first?

**Comment by PierreR** [comment]
Ok. I guess the source for the wiki is on the gh-pages branch ? Could you point me to the sections that hasn't been integrated yet ?

**Comment by gracjan** [comment]
Soirce is in doc/Haskell-mode.texi. Web page updates itself when merged.

**Comment by PierreR** [comment]
Then I don't get it. I thought `doc/Haskell-mode.texi` was the source for http://haskell.github.io/haskell-mode/manual/latest/  not the wiki.

**Comment by gracjan** [comment]
Please edit `doc/haskell-mode.texi`. This is the official documentation. Wiki needs to gradually be displaced.

**Comment by PierreR** [comment]
Yes I know. You suggest I displaced content from the wiki into `doc/haskell-mode.texi`. I can copy paste from the web interface but it might be more convenient to copy from the actual source. So my question was what is the source file for the **wiki**. The stuff I want to copy **from**. Sure I will copy to  `doc/haskell-mode.texi`.

**Comment by gracjan** [comment]
Oh, I see. Wiki is edited inplace on github. The wiki is the source for itself, although it can be accessed via git (github has info how to do this somewhere).

**Comment by PierreR** [comment]
Ok thanks ;-)

**Comment by gracjan** [comment]
So I close this one.
