### ISSUE TITLE
Can't edit a buffer while resolving merge conflict because `Invalid Token` error. 

### ISSUE THREAD

**Issue by YoEight** [haskell/haskell-mode#969]
Hi,

Indentation-mode can't handle a file with git conflict marks in it.

Regards

**Comment by gracjan** [comment]
Good use case. Can you provide a unit test case documenting this?

**Comment by YoEight** [comment]
This time I'll try to not forget doing it !

**Comment by gracjan** [comment]
If you forget 'illegal token' will haunt you in your dreams.

**Comment by gracjan** [comment]
@YoEight: How does this go?

**Comment by YoEight** [comment]
@gracjan Sorry for the delay,

I did find out in the wiki how to come up with a test case and run it. I have zero emacs-lisp knowledge, I browse the tests directory but it didn't help me figuring out a test. Could you give some help ?

**Comment by bergey** [comment]
@YoEight If you can post a small snippet of Haskell that triggers the bug, I can turn it into a test case.  I'll write [something like this](https://github.com/haskell/haskell-mode/blob/master/tests/haskell-indentation-tests.el#L755), using the Haskell string you provide, and telling emacs where the indentation should be.
