### ISSUE TITLE
C pragma and `Illegal token: else`

### ISSUE THREAD

**Issue by YoEight** [haskell/haskell-mode#970]
Hi,

```haskell
{-# LANGUAGE CPP #-}
module Test where

foo :: Int -> Int
#ifdef FOO
foo = succ
#else
foo = pred
#endif
```
gets me `Illegal token: else` message when I hit ENTER.

Thanks for your time,
Regards

**Comment by gracjan** [comment]
Good use case. Can you provide unit test case for this in
`tests/haskell-indentation-tests.el`?

**Comment by Shimuuar** [comment]
There's one already AFAIR

**Comment by gracjan** [comment]
Might be. We might need a couple more. CPP has a couple of features, like line continuations and stuff.
