### ISSUE TITLE
Makefile doesn't work in a shell under emacs

### ISSUE THREAD

**Issue by ilitzroth** [haskell/haskell-mode#972]
The makefile contains this line:

```sh
EMACS := $(shell echo "$${EMACS:-emacs}")
```

in an emacs shell buffer `EMACS=t`.

**Comment by gracjan** [comment]
The full `Makefile` fragment goes like this:

```
EMACS := $(shell echo "$${EMACS:-emacs}")

# Emacs itself sets the $EMACS environment variable to t if it is not
# present, so we should ignore the variable if this is its value.
ifeq ($(EMACS),t)
EMACS := emacs
endif
```
It seems to me we are doing the correct thing here. Am I wrong?

**Comment by bergey** [comment]
The Makefile works for me in shell-mode or eshell.  It does not work in term-mode, where `EMACS=24.5.1 (term:0.96)`.  I don't know that we need to care about this last, I'm just trying to be complete.
