### ISSUE TITLE
Please do not make haskell-mode non-useful without ghc-mod

### ISSUE THREAD

**Issue by gleber** [haskell/haskell-mode#974]
Due to ghc-mod licensing, some people are not able to use it at work. Details are here:
https://github.com/kazu-yamamoto/ghc-mod/issues/638

Based on this month's haskell-mode news there seem to be more integration/cooperation between these two. If this goes too far, e.g. I won't be able to use newer releases of haskell-mode due to it's use of AGPL and corporate policies.

**Comment by gracjan** [comment]
We hear you laud a clear.

haskell-mode itself is released under GPL license and it is going to stay that way. We understand that stability of license is important for our users.

We have limited influence on other tools and their licensing ideas. But we will take into account what is going on and, given our limited resources, do our best to keep the project going forward avoiding this whole licensing mess.

**Comment by gracjan** [comment]
I'll close this as there is nothing to fix here. We have heard and will act accordingly.
