### ISSUE TITLE
`haskell-process-load-file`: cabal `test-suite` wants to inject deps into `library`

### ISSUE THREAD

**Issue by fosskers** [haskell/haskell-mode#979]
Hi, I have these two sections in my `.cabal`:

```
library
  exposed-modules:     Data.Versions   
  other-extensions:    OverloadedStrings
  build-depends:       base >=4.8 && <4.9
                     , parsec >=3.1 && <3.2
                     , semigroups >= 0.16.2.2
                     , text >=1.2 && <1.3
                     , text-show >= 2 
  default-language:    Haskell2010

test-suite versions-test
  type:                exitcode-stdio-1.0
  other-extensions:    OverloadedStrings

  build-depends:       base >=4.8 && <4.9
                     , either >= 4.4.1
                     , extra >= 1.4.1
                     , semigroups >= 0.16.2.2
                     , tasty >= 0.10.1.2
                     , tasty-hunit >= 0.9.2
                     , text >=1.2 && <1.3
                     , text-show >= 2
                     , versions

  hs-source-dirs:      test
  main-is:             Test.hs
  default-language:    Haskell2010
```

And I have `C-c C-l` bound to `haskell-process-load-or-reload`.

When I use `C-c C-l` on my library source code, it compiles fine. However, when I attempt the same in my `test-suite` code (which has different deps than the library. `tasty` for instance), `haskell-mode` wants to inject `tasty` etc into the deps of the `library` section. If I don't, the test suite won't compile, and I can't run my tests in the `haskell-mode` REPL.

Am I doing something wrong?

**Comment by ivan-m** [comment]
Use `haskell-session-change-target`.  This is because `cabal repl` loads up a specific target in the .cabal file.

**Comment by fosskers** [comment]
That did it, thanks.
