### ISSUE TITLE
Emacs hangs when typing behind whitespace

### ISSUE THREAD

**Issue by Wysaard** [haskell/haskell-mode#980]
When in haskell-mode I experience the following problem:
If I use my `enter` key to go to a new line, indentation is already there for me (this is the case with all indentation modes). But that's not a problem of course. The problem comes when I use `C-a` to jump to the start of the line. If I type now, all my actions will have some delay; sometimes a little, other times a lot.

This looks like a bug to me, but I'm not very experienced with this (month or two) so maybe it's just a fuckup of mine.

**Comment by gracjan** [comment]
Interesting. I do not observe this behavour. Do you have other modes
enabled?

**Comment by Wysaard** [comment]
Not that I'm aware. I'll try a few things and see if I can find out under what circumstances it happens.

**Comment by Wysaard** [comment]
Here's an easy way to reproduce the problem:
Open a new `.hs` file. Fill one line with a lot of spaces, like a hundred. Now start typing at the start of the line.

It seems that the more spaces, the worse. I also experienced this when working in a very big file with jus a few spaces, but never when I have no spaces in front of my cursor at all.

So basically the delay gets worse when there are spaces in front of your cursor. The more spaces, the worse. The more text in the file, the worse.

I have tested this with `haskell-simple-indent` and `haskell-indent`. It appears to not be a problem with emacs itself, as I don't experience any problems whatsoever when I do the same thing in the scratch buffer.

**Comment by Wysaard** [comment]
In other news, it also happens if I use a completely clean .emacs file. No indentation enabled whatsoever.

There's also this weird thing where if you start typing at the second character of the line there is no issue. Thereafter using arrows to navigate to the first character allows me to start typing in the normal way sometimes (not sure when it does and when it doesn't). However, just typing a lot of spaces and then using `C-a` to skip to the first character and then start typing always ruins my day.

To summarize the info so far:

- The issue is that emacs freezes on every keypress
- It happens after skipping to the start of the line with `C-a`, when the rest of the line consists of spaces, and in some other ways (of going to the start), but I couldn't see a real pattern there.
- It happens in at least two of the indentation modes, and also when all indentation modes are disabled.
- It only (as far as I know) happens in `haskell-mode`. At least a quick check in some other files revealed no problems to me (I've never had this problem in other files/modes, and at least the scratch buffer can take quite a few spaces without breaking)
- It feels (can't really judge objectively on this) that the problem is worse when the file is large.
- It is the case (definitely true) that the problem is worse when there are more spaces.

**Comment by gracjan** [comment]
I tried to reproduce this but everything seems perfectly fine. Can anybody else try to help with this problem?

**Comment by gracjan** [comment]
I cannot reproduce the problem. If anybody can do it please write a message here and we will reopen the issue.

**Comment by Wysaard** [comment]
After updating emacs just now, the problem is no longer there. As I was seemingly the only one with this issue, it can be regarded as solved.

**Comment by gracjan** [comment]
Great, thanks.
