### ISSUE TITLE
Parsing failure with type-level lists

### ISSUE THREAD

**Issue by KaneTW** [haskell/haskell-mode#982]
The following valid Haskell code
```
{-# LANGUAGE DataKinds, TypeOperators, PolyKinds #-}
module Bug where

data A (a :: [*]) 
data B 
data a :> b
data a :<|> b

type Fail = A '[] :> ( A '[] :<|> B)
```

fails to parse with haskell-mode. When using haskell-indentation-mode, pressing TAB fails with `No catch for tag: parse-error, "Illegal token: )"`

**Comment by gracjan** [comment]
Can you add a test case in `tests/haskell-indentation-tests.el`?

**Comment by KaneTW** [comment]
Just tested with HEAD. Seems to be fixed.
