### ISSUE TITLE
Issues trying to use local version of a package in a layer

### ISSUE THREAD

**Issue by codygman** [haskell/haskell-mode#993]
I had a bug I patched in haskell-mode and wanted to try it out, so I checked out the documentation on [layers](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#packagesel)

After quite a bit of reading I did the following:

```shell
# clone haskell-mode
git clone git@github.com:haskell/haskell-mode.git ~/.emacs.d/private/local/haskell-mode

# reset to specific revision so this repro works for everyone
cd ~/.emacs.d/private/local/haskell-mode
git reset --hard a8e924b5138e2ebc767ad60e78d26f5fba219017

# create copy of haskell layer, then modify haskell-mode to use local package
cd ~/.emacs.d/private
cp -R ~/.emacs.d/layers/+lang/haskell/ ~/.emacs.d/private/

# modify haskell layer's packages.el to use local package of haskell-mode
cd ~/.emacs.d/private/haskell/
sed -i '22s/haskell-mode/(haskell :location local)/' packages.el

# fix bug, then recompile haskell-mode
cd ~/.emacs.d/private/local/haskell-mode/
make EMACS=$(which emacs)
```

restart spacemacs & open eshell

```
~ λ echo "main = putStrLn \"hello\"" > /tmp/hello.hs
~ λ find-file /tmp/hello.hs 
#<buffer hello.hs>
```

within hello.hs buffer, `SPC h d m`, search for haskell mode, click (haskell-mode.el). When it opens haskell-mode.el, press `SPC f f`

This shows me I'm opening the haskell-mode.el in:

`~/.emacs.d/elpa/haskell-mode-20151113.1304/haskell-mode.el`

rather than the desired:

`~/.emacs.d/private/local/haskell-mode/haskell-mode.el`

What is the issue? How can I debug the issue?

Thanks!

**Comment by codygman** [comment]
Just followed my reproduction instructions again to make sure the steps worked, they do.

**Comment by codygman** [comment]
I then tried `SPC f e h` and searched for `package: haskell` and saw this:

![1447996388](https://cloud.githubusercontent.com/assets/225847/11292415/313f7194-8f13-11e5-9a0a-71aaae48a5bb.png)

**Comment by ivan-m** [comment]
This to me sounds more like a spacemacs issue than a haskell-mode one.

**Comment by codygman** [comment]
@ivan-m I think it's an issue of me not using local packages correctly, failing that I think it's a spacemacs issue. It could not be a haskell-mode issue.

**Comment by ivan-m** [comment]
If it isn't a haskell-mode issue, why file it as an issue on haskell-mode?

**Comment by codygman** [comment]
Whoops, please close... Or I can in the morning.
